### PR TITLE
bugfix/9088-pie-tooltip-errors

### LINKED ISSUE #9088: Point update fails in Pie chart, because tooltip series doen't have xAxis and yAxis
#### Expected behaviour
image

#### Actual behaviour
image

#### Live demo with steps to reproduce
https://jsfiddle.net/jameswhf/spz8r6wd/6/ 
after pie charts show up, hover on chart, wait for few seconds(5s), you can see error happens in console

#### Product version
Highstock 6.1.4

#### Affected browser(s)
All

### PR DESCRIPTION
**Pull request by pawelfus**
Fixed #9088, updating a point in a pie chart threw errors when another slice was hovered.

### CODE REVIEW

File: samples/unit-tests/series-pie/mouseover/demo.js [hunk 1]
```diff
@@ -254,4 +254,32 @@ QUnit.test('Halo sliced point (#3016)', function (assert) {
 
     });
 
+});
+
+QUnit.test('Update point hwen hovering slice (#9088)', function (assert) {
```
Comment (KacperMadej) [inline samples/unit-tests/series-pie/mouseover/demo.js]: @pawelfus 

> hwen
