### PR TITLE
bugfix/23527-rotated-axis-labels-margin

### LINKED ISSUE #23527: Too much space to left of yAxis label for non-zero rotation
#### Expected behaviour

Consistent (minimal) spacing around yAxis label regardless of `yAxis.labels.rotation`.

#### Actual behaviour

It is not consistent.  There is too much spacing when using e.g. -45 for `yAxis.labels.rotation`... the following shows a comparison, where the blue box has the same width in both:

Image

There is too much space opened up when rotating the labels.  This is OK in some situations but not when laying out a chart in a very space-constrained context.

#### Live demo with steps to reproduce
https://jsfiddle.net/8dw34gvm/

#### Product version
Highcharts Core v12.4.0

#### Affected browser(s)
Chrome

### PR DESCRIPTION
**Pull request by kamil-musialowski**
Fixed #23527, chart margin was too big for rotated axis labels.

### CODE REVIEW

**Comment by kamil-musialowski** [comment]
_Internal note:_ When reviewing, please think if you can figure out a better solution instead of taking `Math.min` from rotated and unrotated label. Like it's stated in the comment, narrow label may produce a smaller width when unrotated, long label may produce a smaller width when rotated. Pixel differences are not that big, yet still noticable.

File: ts/Core/Axis/Tick.ts [hunk 1]
```diff
@@ -658,15 +658,27 @@ class Tick {
...
-        return this.label ?
-            this.label.getBBox()[this.axis.horiz ? 'height' : 'width'] :
-            0;
+        const { label, axis } = this;
+        // Short labels: the rotated box is often wider than non-rotated, so we
+        // use the non-rotated width.
+        // Long labels: the rotated box is often narrower, so we use the rotated
+        // width.
+        if (!axis.horiz && isNumber(label?.rotation) && label.rotation !== 0) {
+            const unrotated = label.getBBox(false, 0),
```
Comment (pawelfus) [inline ts/Core/Axis/Tick.ts]: If you plan to use unrotated width, then try using `label.textPxLength`. So something like this?
```
return Math.min(label.textPxLength, label.getBBox().width);
```

**Review by pawelfus — CHANGES_REQUESTED** [review]
I'm not convinced to the solution - why exactly should we use lower value of width and rotated_width? Checked the math - it seems the returned width is correct for the given sample (tested label=200, width returned by `getRotatedBox()` was correct). Could you elaborate? Thanks!

File: ts/Core/Axis/Tick.ts (hunk 1 above)
Comment (kamil-musialowski) [reply ts/Core/Axis/Tick.ts]: Ohh, that is a very good idea!

**Comment by kamil-musialowski** [comment]
@pawelfus 

Original solution was based on `this.label.getBBox()`. And to put it simple, narrow labels produced GREATER rotated width, long labels produces NARROWER rotated width. That's why we couldn't use `getBBox()` reliably or all labels lenghts.

After you mentioned `textPxLength` this comparison gets even easier.
Please have a look here: https://jsfiddle.net/BlackLabel/x7dwb4cr/

File: ts/Core/Axis/Tick.ts (hunk 1 above)
Comment (kamil-musialowski) [reply ts/Core/Axis/Tick.ts]: I have improved it even further, should be faster, shorter and more readable now.

**Review by jedrzejruta — APPROVED** [review]
Smart solution, looks good to me!

**Review by pawelfus — CHANGES_REQUESTED** [review]
Two cases where it returns wrong results:
- https://jsfiddle.net/BlackLabel/x7dwb4cr/11/ - labels are now too close to the title (master is no better)
- https://jsfiddle.net/BlackLabel/qsr0z8fu/3/ - labels are too far away

**Review by DJTechnoo — APPROVED** [review]
LGTM! 🎉

**Review by pawelfus — APPROVED** [review]
Looks solid! Thanks

**Review by PaulDalek — APPROVED** [review]
Good work!

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks! It seems to work very well for rotations ranging from -75 to 0, but there are some problems with other ranges.

See https://jsfiddle.net/highcharts/pbu8xvwt/1/, where I added a helper line 10px from the title
* For rotations > 0, there is still too much space between the labels and the helper line. It seems like little or no change from the prod behaviour.
* For rotations of -75 and lower, the labels are now too close to the axis title. This is a regression - in v12.5.0 it [fits nicely to the helper line](https://jsfiddle.net/highcharts/pbu8xvwt/2/).

**Comment by kamil-musialowski** [comment]
@TorsteinHonsi Thanks for checking, and thanks for the cool demo!

I tweaked the current logic a bit to make it work with both negative and positive rotations. Should be good enough now imo!

**Review by TorsteinHonsi — APPROVED** [review]
