### PR TITLE
bugfix/19750-update-with-highcontrast

### LINKED ISSUE #19750: Some HighContrastTheme settings are lost on chart update
#### Expected behaviour

Rendering the chart ( .chart(container, A) ) and updating the chart ( .update(A) ) with the same configuration should result in the same chart rendering in High Contrast Mode when A has specific settings for highContrastTheme.

#### Actual behaviour

Rendering the chart ( .chart(container, A) ) renders the correct result according to A's highContrastTheme settings, but  updating the chart with the same configuration ( .update(A) ) results in some high contrast colors being lost. Instead, the chart is renderer with some elements coloured with non-high contrast mode colors, even when the user is using high contrast mode.

#### Live demo with steps to reproduce
https://jsfiddle.net/mauro1855/L3ck8hgw/

1. Open the JS Fiddle above -- in the fiddle you have a chart that is updated 2 seconds after the initial rendering (via setTimeout) with the exact same configuration that was used to render it in the first place.
2. Notice that the data series and the horizontal plot line at value 125 are both blue, as that is the defined color for both in the chart settings. They remain both blue forever.
3. Enable High Contrast Mode in your Windows machine, or use Chrome's emulation of forced colors.
4. Rerun the chart.
5. Pay special attention to the plot line at value 125. In High Contrast Mode, it starts out as red, but once the chart updates 2 seconds later it reverts to blue (the non-high contrast mode color) even though the user is still in high contrast mode. Also note that the color of the series remains correct for the full time.

#### Product version
Latest

#### Affected browser(s)
All? Tested in Chrome.

### PR DESCRIPTION
**Pull request by MarkusBarstad**
Fixed #19750, `highContrastTheme` settings were partially lost after `chart.update`.

Right when it initially renders you can see blue quickly swap to red, should that be fixed by this branch?

Test: https://jsfiddle.net/mkb93/4qphj3fu/3/
Switch to forced-colors to simulate windows high contrast in chrome

### CODE REVIEW

**Review by goransle — APPROVED** [review]
Looks good to me 👍 

I was not able to catch the red swap with my own eyes, but if its an existing issue I think it should possibly be fixed in a separate PR

File: ts/Accessibility/HighContrastMode.ts [hunk 1]
```diff
@@ -38,6 +38,7 @@ const {
 
 declare module '../Core/Chart/ChartBase'{
     interface ChartBase {
+        applyingHighContrastTheme?: boolean;
         highContrastModeActive?: boolean;
```
Comment (TorsteinHonsi) [inline ts/Accessibility/HighContrastMode.ts]: To avoid polluting the Chart object (which we have done a lot in the past), can we gather these two into one combined object? Something like this:

```ts
interface HighContrastState {
    active?: boolean
    applying?: boolean
}

declare module '../Core/Chart/ChartBase'{
    interface ChartBase {
        highContrastState?: HighContrastState;
    }
}
```

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks! Just a comment on structure.

**Comment by MarkusBarstad** [comment]
Good idea @TorsteinHonsi , tried to refactor it now, we now have an object on chartBase instead which contains a couple of properties, as you suggested

**Review by TorsteinHonsi — APPROVED** [review]
Looks great, thanks!
