### PR TITLE
bugfix/23815-area-series-negative-values

### LINKED ISSUE #23815: Logarithmic Y-axis with area series behaves unexpectedly
We’ve found several issues when using logarithmic Y-axes with area series.

1. **Area disappears with non-positive values**
  If a single data point is zero or negative, the entire area is no longer displayed.
    - Expected: only non-positive points should be skipped; the rest of the area should render normally.
    - Actual: the whole series renders like a line series.
    - Workaround: replace non-positive values with null — but this leads to the next issue.
    - https://jsfiddle.net/brani114/15g87scp/

2. **Incorrect interpolation in stacked areas**
  With stacked area series, the interpolation between points is incorrect.
    - In this example, the blue “Series 1” drops to 0.75 (the Y-axis min) and then suddenly jumps to 0.1 or 1.1, depending on whether the stack sum or the individual value is evaluated.
    - Changing the chart type to "line" removes the issue, but we would like to display areas.
    - https://jsfiddle.net/brani114/fecxr0th/
  

Stacked area charts with logarithmic axes should behave like in this Plotly example.

Image

Image

We tried to reproduce this behavior with Highcharts here, but the two issues mentioned stand in our way:
https://jsfiddle.net/brani114/Lsqrd586/

### PR DESCRIPTION
**Pull request by kamil-musialowski**
Fixed #23815, area chart with negative values was not rendered when the y-axis was logarithmic

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1211926560843546

### CODE REVIEW

File: ts/Series/Area/AreaSeries.ts [hunk 1]
```diff
@@ -466,9 +475,13 @@ class AreaSeries extends LineSeries {
                         i += upOrDown;
                     }
                     y = pick(y, 0);
-                    y = yAxis.translate(// #6272
-                        y, 0 as any, 1 as any, 0 as any, 1 as any
-                    );
+                    if (yAxis.logarithmic && y <= 0) {
+                        y = yAxis.getThreshold(0);
```
Comment (pawelfus) [inline ts/Series/Area/AreaSeries.ts]: Q: Why `0`? Why not `options.threshold`?

Comment (kamil-musialowski) [reply ts/Series/Area/AreaSeries.ts]: No you're right, it should use the threshold from options 😄

**Comment by kamil-musialowski** [comment]
@pawelfus To get the same behaviour as the line series you need to use `connectNulls`on area series. https://jsfiddle.net/BlackLabel/qema61u8/

File: ts/Series/Area/AreaSeries.ts [hunk 2]
```diff
@@ -466,9 +475,13 @@ class AreaSeries extends LineSeries {
...
                     }
                     y = pick(y, 0);
-                    y = yAxis.translate(// #6272
-                        y, 0 as any, 1 as any, 0 as any, 1 as any
-                    );
+                    if (yAxis.logarithmic && y <= 0) {
+                        y = yAxis.getThreshold(series.options.threshold ?? 0);
+                    } else {
+                        y = yAxis.translate(// #6272
+                            y, 0 as any, 1 as any, 0 as any, 1 as any
```
Comment (PaulDalek) [inline ts/Series/Area/AreaSeries.ts]: I know this was already in the code before, but it's really weird and definitely looks worse than just:

```
y = yAxis.translate(// #6272
    y, false, true, false, true
);
```

There are two such `translate` occurances in this file, so I would correct them both.

**Review by PaulDalek — APPROVED** [review]
Great, thanks!

File: ts/Series/Area/AreaSeries.ts [hunk 3]
```diff
@@ -230,7 +231,13 @@ class AreaSeries extends LineSeries {
                     bottom = stackedValues[0] + cliffVal;
                     isNull = !!nullVal;
 
-                } else if (!stacking && points[otherI]?.isNull) {
+                } else if (
+                    !stacking &&
+                    otherI >= 0 &&
+                    otherI < points.length &&
```
Comment (TorsteinHonsi) [inline ts/Series/Area/AreaSeries.ts]: Could this be shortened to just check for the array item? Or even shorter, create a constant `otherPoint = points[otherI]`, then use that in the condition.

```suggestion
                    points[otherI] &&
```

File: ts/Series/Area/AreaSeries.ts [hunk 4]
```diff
@@ -466,13 +475,17 @@ class AreaSeries extends LineSeries {
...
-                    y = yAxis.translate(// #6272
-                        y, 0 as any, 1 as any, 0 as any, 1 as any
-                    );
+                    if (yAxis.logarithmic && y <= 0) {
+                        y = yAxis.getThreshold(series.options.threshold ?? 0);
+                    } else {
+                        y = yAxis.translate(// #6272
+                            y, false, true, false, true
+                        );
+                    }
```
Comment (TorsteinHonsi) [inline ts/Series/Area/AreaSeries.ts]: This is also not really new to this PR, but it is confusing that `y` first is used for the value, then repurposed to mean plotY. I would prefer a little refactor here:

Line 477, `pick` is not necessary. If y is already 0, we're fine.
`y ||= 0;`

Move the rest down. Note that I use `positiveValuesOnly` instead of `yAxis.logarithimic`. First compute threshold in the top of the function, to avoid doing it over and over in the point loop.

`translatedThreshold = yAxis.getThreshold(series.options.threshold || 0)`

```ts
segment.push({
    // other props
    plotY: yAxis.positiveValuesOnly && y <= 0 ?
        translatedThreshold :
        yAxis.translate(y, false, true, false, true)
    // other props
});
```
