### PR TITLE
bugfix/24096-tooltip-missing-when-hovered-from-bottom

### LINKED ISSUE #24096: Cannot trigger tooltip when mousing into scatter plot series marker on x-axis from bottom
#### Expected behaviour

- This occurs specifically on data points that appear along the x-axis (at `y=0`), with the series type being `scatter`
- The expected behaviour is that if you mouse into such data points from the bottom, the tooltip should appear and persist just as it would if you mouse into it from any direction

This was working for our team on an older Highcharts version - version 9.0.0. Example:

https://github.com/user-attachments/assets/6d43b7fc-7f33-4d18-95b8-444fbb3e2345

#### Actual behaviour
On Highcharts version 12.5.0 we get the 'buggy' behaviour.
- Mousing into data points at `y=0` on a _scatter plot_ does not trigger a tooltip to appear when you mouse in from underneath the data point. You have to mouse in from the top.
- The data point is also not clickable when you mouse in from the bottom.

Example:

https://github.com/user-attachments/assets/abc7c5db-6be0-4338-aad7-39a82b97f503

#### Live demo with steps to reproduce

https://jsfiddle.net/jz8xhfc7/19/

#### Product version

Highcharts 12.5.0

#### Affected browser(s)
The videos above are from Chrome, but I was able to replicate the issue on Safari and Firefox as well.

### PR DESCRIPTION
**Pull request by AndrzejBuleczka**
Fixed #24096, missing point events for scatter points on the edge of the plot area.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1213007363344605

### CODE REVIEW

File: ts/Series/Column/ColumnSeries.ts [hunk 1]
```diff
@@ -874,6 +874,14 @@ class ColumnSeries extends Series {
                                 visiblePlotOnly: true
                             }
                         ) ||
+                        // Added condtion for scatter points on the edge, #24096
```
Comment (KacperMadej) [inline ts/Series/Column/ColumnSeries.ts]: "condition"

Comment (AndrzejBuleczka) [reply ts/Series/Column/ColumnSeries.ts]: fixed

File: samples/unit-tests/series-scatter/general/demo.js [hunk 2]
```diff
@@ -53,4 +53,30 @@ QUnit.test('Scatter series general tests.', function (assert) {
...
+    const columnSeries = chart.addSeries({
+        type: 'column',
+        data: [1, 2]
+    });
+
+    assert.strictEqual(
+        columnSeries.allowOutsidePlotInteraction(mockEvent),
+        false,
+        'Default series (Column) should NOT allow interaction outside ' +
+        'he plot area (#24096).'
```
Comment (KacperMadej) [inline samples/unit-tests/series-scatter/general/demo.js]: he --> the

File: ts/Series/Scatter/ScatterSeries.ts [hunk 3]
```diff
@@ -143,6 +144,21 @@ class ScatterSeries extends LineSeries {
         }
     }
 
+    /**
+     * Allow scatter points on the edge to be interacted with outside the plot
+     * area, #24096.
+     * * @private
```
Comment (KacperMadej) [inline ts/Series/Scatter/ScatterSeries.ts]: `* * @private` --> `* @internal`

File: ts/Series/Column/ColumnSeries.ts [hunk 4]
```diff
@@ -874,6 +874,15 @@ class ColumnSeries extends Series {
...
                         ) ||
+                        // Allow specific series types to extend interaction
+                        // outside the plot area, #24096
+                        (
+                            series.allowOutsidePlotInteraction(e) ||
+                            pointer?.inClass(
+                                e.target as any,
+                                'highcharts-point'
+                            )
+                        ) ||
```
Comment (KacperMadej) [inline ts/Series/Column/ColumnSeries.ts]: Is the inClass check with `'highcharts-point'` still needed? Also: how about using `series?.allowOutsidePlotInteraction(e)` and then Series doesn't need to have `allowOutsidePlotInteraction`. Typing then should be resolved in ScatterSeries.ts with addition of code like:
```
declare module '../../Core/Series/SeriesBase' {
    interface SeriesBase {
        allowOutsidePlotInteraction?(e: PointerEvent): boolean;
    }
}
```

File: samples/unit-tests/series-scatter/general/demo.js (hunk 2 above)
Comment (AndrzejBuleczka) [reply samples/unit-tests/series-scatter/general/demo.js]: fixed, thanks

File: ts/Series/Column/ColumnSeries.ts (hunk 4 above)
Comment (AndrzejBuleczka) [reply ts/Series/Column/ColumnSeries.ts]: great idea, really thanks!

File: ts/Series/Scatter/ScatterSeries.ts (hunk 3 above)
Comment (AndrzejBuleczka) [reply ts/Series/Scatter/ScatterSeries.ts]: sure
