### PR TITLE
bugfix/23517-datalabels-zindex

### LINKED ISSUE #23517: timeline graph marker's zIndex doesn't work well with the latest highcharts (v12.3.0)
#### Expected behaviour

Image

#### Actual behaviour

Image

#### Live demo with steps to reproduce
Working one with 11.4.8: https://jsfiddle.net/qx412z03/4/
Not working with the latest Highcharts (12.3.0): https://jsfiddle.net/e4pcbmhr/1/

### PR DESCRIPTION
**Pull request by hubertkozik**
Fixed #23517, `dataLabels.zIndex` was ignored, so labels could render above series regardless of the setting.

______

I was investigating leaving the `dataLabelsGroup` on the `chart`, but because of the paint order, data-labels per series should not be in one group. 

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1211223721280589

### CODE REVIEW

File: ts/Extensions/NonCartesianSeriesZoom/NonCartesianSeriesZoom.ts [hunk 1]
```diff
@@ -20,6 +20,7 @@ import type Chart from '../../Core/Chart/Chart';
 import type Series from '../../Core/Series/Series';
 import type Point from '../../Core/Series/Point';
 import type Tooltip from '../../Core/Tooltip';
+import SVGElement from '../../Core/Renderer/SVG/SVGElement';
```
Comment (KacperMadej) [inline ts/Extensions/NonCartesianSeriesZoom/NonCartesianSeriesZoom.ts]: `import type` is all that is needed, right?

**Comment by hubertkozik** [comment]
@KacperMadej, the unit test based on SVG paint-order or z-indicies of each data labels group won't work in that case. The problem wasn’t the `z-index` values – those were already correct and still are – but the actual paint order in the SVG. Unit tests only let us check attributes, not whether one element really renders above or below another, so there’s nothing new we can assert here.

File: ts/Extensions/NonCartesianSeriesZoom/NonCartesianSeriesZoom.ts [hunk 2]
```diff
@@ -399,6 +407,21 @@ function onAfterSetChartSize(
...
+ * Create data labels parent group for clipping purposes after zoom-in
+ * @private
+ */
+function onDrawDataLabels(
+    this: Series
+): void {
+    if (this.hasDataLabels?.()) {
+        this.dataLabelsGroupParent ||=
+            this.chart.renderer.g()
+                .attr({ zIndex: (this.options.dataLabels as any).zIndex || 6 })
```
Comment (KacperMadej) [inline ts/Extensions/NonCartesianSeriesZoom/NonCartesianSeriesZoom.ts]: This casting hides a problem of no support for dataLabels as an array I mention in the top review comment.

**Review by KacperMadej — COMMENTED** [review]
I might be missing something so please correct me if I'm wrong with anything.

Order in the DOM decides the rendering order for SVG, so checking the the sequence should be enough to ensure rendering order. There might be a fancier way, but checking innerHTML gets the job done. `childNodes` are listed in the placement order for the chart's `svg` Node, so maybe could be used. If all of this fails to work as a unit test - I don't imagine why would it, but regardless - we have visual tests.

`zIndex` values are not correct nor were correct, but in a different way.

`dataLabelsGroup` had hard-coded `zIndex` of `6` and was ignoring [dataLabel.zIndex](https://api.highcharts.com/highcharts/series.column.dataLabels.zIndex). dataLabel's `zIndex` was applied inside of the `dataLabelsGroup` group, so was not affecting top layers of the SVG - only order within that group. In result, it was impossible to have dataLabels under the series as docs describe.

With the changes, it works for dataLabels set as object. When setting as an array it doesn't work - both land in the same group that has hard-coded `zIndex` of `6` because it attempts to read it from array, but it's not showing as anything incorrect because of the `as any` casting.

**Comment by KacperMadej** [comment]
_Visible here but a general note:_
Linter is too generous with it's ignore pattern that includes ``` ` ```.
Just the usage of template literals is no excuse to exceed the max-len limit.

_Side note:_
.eslintrc in ts dir has ignorePattern that could be edited to try to catch this

**Comment by KacperMadej** [comment]
Failing visuals clue: inactive is set twice - parent and target group. Visible locally with karma emulated, or with the non-cartesian-zoom added because it is causing the unwanted change.

File: ts/Core/Series/Series.ts [hunk 3]
```diff
@@ -4283,6 +4289,18 @@ class Series {
...
+            ...Object.keys(series).filter((k): boolean => (
+                k.startsWith('dataLabelsGroup')
+            ))
+        );
+
+        groups.push(
+            ...Object.keys(series).filter((k): boolean => (
+                k.startsWith('dataLabelsGroupParent')
+            ))
+        );
```
Comment (KacperMadej) [inline ts/Core/Series/Series.ts]: dataLabelsGroupParent starts with dataLabelsGroup

**Comment by KacperMadej** [comment]
Organization series has useHTML: true by default making it buggy on zoom, but that is a separate issue: https://github.com/highcharts/highcharts/issues/23438

**Comment by KacperMadej** [comment]
Summary:
Originally, this was a regression, but even before the break `zIndex` for multiple `dataLabels` was not working - this is the reason for the quite heavy Core change.

The code could be optimized to make it lighter (e.g. store collections in arrays to reduce the usage of keys filtering), but this seems like a good point to check if this is going into the right direction @TorsteinHonsi ?

File: ts/Core/Series/DataLabel.ts [hunk 4]
```diff
@@ -492,14 +507,35 @@ namespace DataLabel {
...
-        return this.plotGroup(
+    function initDataLabelsGroup(
+        this: Series,
+        index: number,
+        dataLabelsOptions?: DataLabelOptions
+    ): SVGElement {
+        fireEvent(
+            this,
+            'initDataLabelsGroup',
+            { index, zIndex: dataLabelsOptions?.zIndex || 6 }
```
Comment (TorsteinHonsi) [inline ts/Core/Series/DataLabel.ts]: Sooner or later someone will try to set `zIndex: 0` and wonder why it is not working
```suggestion
            { index, zIndex: dataLabelsOptions?.zIndex ?? 6 }
```

File: ts/Core/Series/DataLabel.ts [hunk 5]
```diff
@@ -492,14 +507,35 @@ namespace DataLabel {
...
+        // Existing group or first time
+        this.dataLabelsGroup = this.dataLabelsGroups?.[index];
+
+        const group = this.plotGroup(
             'dataLabelsGroup',
             'data-labels',
             this.hasRendered ? 'inherit' : 'hidden', // #5133, #10220
-            (this.options.dataLabels as any).zIndex || 6,
-            this.chart.dataLabelsGroup
+            dataLabelsOptions?.zIndex || 6,
```
Comment (TorsteinHonsi) [inline ts/Core/Series/DataLabel.ts]:
```suggestion
            dataLabelsOptions?.zIndex ?? 6,
```

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks! In addition to the inline comment, I'm wondering how zIndex on individual point label configs should work. See https://jsfiddle.net/highcharts/d8t0zjew/, where the point config actually takes over the z-index of the whole series. I don't we should take this too far, we could for example just disable the zIndex property on point configs. But then it needs to match the typing and [the API](https://api.highcharts.com/highcharts/series.line.data.dataLabels.zIndex).

**Review by TorsteinHonsi — APPROVED** [review]
