### PR TITLE
bugfix/23058-rangeselector-wrong-plotheight

### LINKED ISSUE #23058: Overlapping legends with plot area
#### Actual behaviour

Observe that legends are overlapping with plot area:
Image

#### Expected behaviour
I tried adjusting [inputPosition.y](https://api.highcharts.com/highstock/rangeSelector.inputPosition.y) of range selector but a constant value will not work for varying legend widths / number of legends. I wanted to understand if there exists a dynamic solution that intelligently places everything properly.

#### Live demo with steps to reproduce
https://jsfiddle.net/txqsg4ce/

#### Product version
Latest

#### Affected browser(s)
Chrome

### PR DESCRIPTION
**Pull request by jedrzejruta**
Fixed #23058, invalid `chart.plotHeight` set with `rangeSelector` on shorter charts.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1210273148874182

### CODE REVIEW

**Review by kamil-musialowski — APPROVED** [review]
LGTM!

File: ts/Stock/RangeSelector/RangeSelectorComposition.ts [hunk 1]
```diff
@@ -299,14 +303,26 @@ function onChartDestroy(
...
     if (rangeSelector?.options?.enabled) {
+
+        // Rerender rangeSelector in order to return correct plotHeight, #23058
+        const { min, max } = this.xAxis[0].getExtremes();
+        if (
+            isNumber(min) &&
+            rangeSelector?.inputGroup &&
+            rangeSelector.inputGroup?.getBBox().width < 20
+        ) {
+            rangeSelector.render(min, max);
```
Comment (pawelfus) [inline ts/Stock/RangeSelector/RangeSelectorComposition.ts:323]: If we have `RS.render()` in `chartGetMargins()` callback, then shouldn't we remove the one in `chartRedraw()`? And keep only alignment part on redraw?

Comment (jedrzejruta) [reply ts/Stock/RangeSelector/RangeSelectorComposition.ts:323]: I thought about it, but removing it results in one test failing regarding centering of the buttons, I'm not exactly sure how it could affect other samples (or cause some unwanted layout shifts). 
centered
With removed `RS.render()` on `chartRedraw`:
uncentered

Comment (pawelfus) [reply ts/Stock/RangeSelector/RangeSelectorComposition.ts:323]: All clear, thanks for checking!

File: ts/Stock/RangeSelector/RangeSelectorComposition.ts [hunk 2]
```diff
@@ -299,14 +303,26 @@ function onChartDestroy(
...
 ): void {
     const rangeSelector = this.rangeSelector;
 
     if (rangeSelector?.options?.enabled) {
+
+        // Rerender rangeSelector in order to return correct plotHeight, #23058
+        const { min, max } = this.xAxis[0].getExtremes();
+        if (
+            isNumber(min) &&
+            rangeSelector?.inputGroup &&
```
Comment (pawelfus) [inline ts/Stock/RangeSelector/RangeSelectorComposition.ts]:
```suggestion
            rangeSelector.inputGroup &&
```

File: ts/Stock/RangeSelector/RangeSelectorComposition.ts [hunk 3]
```diff
@@ -299,14 +303,26 @@ function onChartDestroy(
...
+            rangeSelector.inputGroup?.getBBox().width < 20
```
Comment (pawelfus) [inline ts/Stock/RangeSelector/RangeSelectorComposition.ts]:
```suggestion
            rangeSelector.inputGroup.getBBox().width < 20
```

**Review by pawelfus — APPROVED** [review]
Unless we decide to implement a box-based space reservation solution (as discussed some time ago with Torstein), I think we're good to proceed with this approach - redrawing the Range Selector twice. I haven’t observed any performance degradation in the benchmarks.
