### PR TITLE
bugfix/22657-annotation-resize-with-flags-series

### LINKED ISSUE #22657: Annotation resizes while dragging onto flags series
-- Expected behavior
when you user drags annotation it should not resize or change the size

-- Actual behavior
after adding annotation from stock tools GUI --> dragging it changes its size

-- Live demo with steps to reproduce
https://jsfiddle.net/83s09r1h/1/

-- Steps:
add any annotation and drag it to blank area.. it will resize and will not maintain its original size.. Flag series (scatter) is causing this issue.. if you comment out that part of code.. then things will work fine.

video to demo the issue
https://vimeo.com/1056522276

Product version
12.0.0 onwards latest

Affected browser(s)
all browsers

### PR DESCRIPTION
**Pull request by kamil-musialowski**
Fixed #22657, annotation dragging and resizing over flags series was incorrect.

- [x] add test

### CODE REVIEW

File: samples/unit-tests/stock-tools/stock-annotation-dragging/demo.js [hunk 1]
```diff
@@ -55,6 +55,15 @@ QUnit.test('Dragging annotation', assert => {
...
                 }
+            }, {
+                type: 'flags',
+                data: [{
+                    x: data[50][0]
+                }, {
+                    x: data[52][0]
+                }, {
+                    x: data[55][0]
+                }]
```
Comment (pawelfus) [inline samples/unit-tests/stock-tools/stock-annotation-dragging/demo.js:66]: Please add this series after existing tests. We don't know if adding this series prior to the test won't make the test redundant (and not testing what it should test).

**Review by pawelfus — CHANGES_REQUESTED** [review]
Minor thing, the solution looks good!

**Review by pawelfus — APPROVED** [review]
Thanks!

**Review by jedrzejruta — APPROVED** [review]
Great job! :tada:

**Review by bm64 — APPROVED** [review]
LGTM!

**Review by DJTechnoo — APPROVED** [review]
Nice! This also seems to fix [#22887](https://github.com/highcharts/highcharts/issues/22887)

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
