### PR TITLE
bugfix/11389-inactive-styledmode-nodes

### LINKED ISSUE #11389: Dependency wheel styles are missing from the styled mode version
#### Expected behaviour

Using dependency wheel with styled mode on an off results in exactly the same behaviour on hover.

#### Actual behaviour

If styled mode is enabled, the chords are not dimmed and are rendered on top of each other at the same opacity. Upon opening the Dev Tools, and hovering on each of them, we can see that the classes `highcharts-point-hover` and `highcharts-point-inactive` are applied, but to no effect.

Since I use other charts with styled mode enabled in the same page, disabling it for just the wheel results in broken behaviour.

#### Live demo with steps to reproduce
These codepens demo the issue: [styled mode off](https://codepen.io/anon/pen/WqWYOZ), [styled mode on](https://codepen.io/anon/pen/jjRQzz), and [styled mode off but with the css loaded](https://codepen.io/anon/pen/JQVeZP).

In the codepen for the styled mode, I added four CSS classes to demo a possible fix.

#### Product version

Highcharts 7.1.2

#### Affected browser(s)

Tested in Firefox 70.0a1 and Vivaldi 2.6.1566.44 (Chrome/75.0.3770.102).

### PR DESCRIPTION
**Pull request by pawelfus**
Fixed #11389, inactive styles for dependency wheel series in styled mode were missing.
___
Refactored a bit + added dependency wheel to karma-files config. Let's hope tests will pass in CircleCI..

### CODE REVIEW

**Comment by pawelfus** [comment]
Ok, no tests then, I'll remove them in the next commit.

File: ts/parts/Pointer.ts [hunk 1]
```diff
@@ -854,6 +843,39 @@ Highcharts.Pointer.prototype = {
...
+     *
+     * @private
+     *
+     * @param {Array<Highcharts.Point>} points
+     *        Currently hovered points
+     *
+     */
+    setInactiveSeries: function (
+        this: Highcharts.Pointer,
+        points: Array<Highcharts.Point>
```
Comment (bre1470) [inline ts/parts/Pointer.ts]: As indicated in the corresponding description, this should also support Series beside Point. It is a bit strange to have a function `setInactiveSeries` that takes points only.

**Comment by bre1470** [comment]
> We should rename the `setInactiveSeries` function or allow array of series as the argument.

That is my humbled opinion.

File: ts/parts/Interaction.ts [hunk 2]
```diff
@@ -1525,14 +1526,31 @@ extend(Series.prototype, /** @lends Highcharts.Series.prototype */ {
...
+     * Set the state for all points in the series.
+     *
+     * @function Highcharts.Series#setAllPointsState
+     *
+     * @private
+     *
+     * @param {string} [state]
+     *        Can be either `hover` or undefined to set to normal state.
+     */
+    setAllPointsState: function (
```
Comment (jon-a-nygaard) [inline ts/parts/Interaction.ts]: Do we really need to add this function to the series prototype? I feel that it is already quite bloated with utility functions.
Since this is used only in one place, at least for now, it could be an internal utility function in the same file.

File: ts/parts/Pointer.ts [hunk 3]
```diff
@@ -854,6 +843,39 @@ Highcharts.Pointer.prototype = {
...
+     *
+     * @function Highcharts.Pointer#setInactiveSeries
+     *
+     * @private
+     *
+     * @param {Array<Highcharts.Point>} points
+     *        Currently hovered points
+     *
+     */
+    setInactiveSeries: function (
```
Comment (jon-a-nygaard) [inline ts/parts/Pointer.ts]: Same concern with prototype as for `Highcharts.Series#setAllPointsState`

File: ts/parts/Pointer.ts (hunk 1 above)
Comment (pawelfus) [reply ts/parts/Pointer.ts]: There's no need for `Series` array. From currently hovered points, retrieve all inactive series and set them inactive. You are right, we could use a better name - what do you suggest? `setInactiveSeriesFromPoints` is just too long. Description of the function is:
>     * Set inactive state to all series that are not currently hovered,
>     * or, if `inactiveOtherPoints` is set to true, set inactive state to
>     * all points within that series.

File: ts/parts/Interaction.ts (hunk 2 above)
Comment (jon-a-nygaard) [inline ts/parts/Interaction.ts]: Maybe a bit verbose, but I would prefer it to be named `setAllPointsToState`.

File: ts/parts/Pointer.ts (hunk 1 above)
Comment (bre1470) [reply ts/parts/Pointer.ts]: How about `applyInactiveState`?

**Comment by jon-a-nygaard** [comment]
> Ok, no tests then, I'll remove them in the next commit.

Btw, do you @pawelfus know what is causing the test to fail on CircleCI? It looks good to me 🤔

File: ts/parts/Interaction.ts (hunk 2 above)
Comment (pawelfus) [reply ts/parts/Interaction.ts]: Yes, we need this here. It's used in two files (`Pointer.js` and `Series.js`) and it's a very common task for series with `inactiveOtherPoints=true` (pie, sankey, networkgraph etc.) - it's called on every point/node/link/slice mouseOver/Out.

IMHO private functions are bad in a library like Highcharts - no way to wrap them, making customizations, plugins and test hard/impossible to write. There's no reason for protected/private functions in our case - we gain nothing, giving up flexibility.

Alternatively, we can create `Series.prototype.utils` object, like in `NavigationBindings` class. Maybe we should make this a common practice?

**Comment by pawelfus** [comment]
> Btw, do you @pawelfus know what is causing the test to fail on CircleCI? It looks good to me 🤔

Hmm.. this is what I see:
Screen Shot 2019-07-17 at 10 40 28

Test that is failing is the one I added.

File: ts/parts/Pointer.ts (hunk 1 above)
Comment (pawelfus) [reply ts/parts/Pointer.ts]: Doesn't `applyInactiveState` miss `Series` keyword then? Maybe something like hmm.. `inactivateSeries`? I don't know.. what do you think @jon-a-nygaard , @oysteinmoseng , @sebastianbochan ?

File: ts/parts/Interaction.ts (hunk 2 above)
Comment (jon-a-nygaard) [reply ts/parts/Interaction.ts]: > Yes, we need this here. It's used in two files (Pointer.js and Series.js) and it's a very common task for series

Okay, then it makes sense to leave it as is.

**Comment by jon-a-nygaard** [comment]
>Test that is failing is the one I added.

Yes, I noticed, but I had a look at the code for the test, and I do not understand why it would fail on CircleCI, as I believe we have similar async tests already. Would be nice if we are able to keep it somehow.

**Comment by pawelfus** [comment]
> Would be nice if we are able to keep it somehow.

Any ideas how to debug it? Locally it works fine (both, karma and browser). In CircleCI it seems that JS files are not built or hovering a non existing point..

File: ts/parts/Pointer.ts (hunk 3 above)
Comment (pawelfus) [reply ts/parts/Pointer.ts]: The same as `Highcharts.Series#setAllPointsState` - different files, affection for all series with `inactiveOtherPoints=true`.

File: ts/parts/Pointer.ts (hunk 1 above)
Comment (jon-a-nygaard) [reply ts/parts/Pointer.ts]: I do not think `Series` should be included in the name since it may also set the state on points. I think I prefer @bre1470 suggestion of `applyInactiveState` or plural `applyInactiveStates`.

Alternatively `setInactiveStates`, but I do not like that much since it is not setting the state on the points we pass in, and also it does not seem much like a regular setter function.

**Comment by jon-a-nygaard** [comment]
> Any ideas how to debug it?

I have no clue unfortunately, and Jan Martin is currently on vacation. Maybe you could just add `QUnit.skip` and an explanation to the test for now? Then it is at least registered as a test that needs our attention in the future.

**Comment by bre1470** [comment]
> > Would be nice if we are able to keep it somehow.
> 
> Any ideas how to debug it? Locally it works fine (both, karma and browser). In CircleCI it seems that JS files are not built or hovering a non existing point..

I made a fresh clone with checkout and it fails for me local in headless Chrome.

**Comment by bre1470** [comment]
and in utils it fails too. So make everything new and you can probably debug it.

File: ts/parts/Pointer.ts (hunk 1 above)
Comment (pawelfus) [reply ts/parts/Pointer.ts]: You are right @bre1470 and @jon-a-nygaard - my mistake, where were my eyes.. 👀 Fix coming soon!

**Comment by pawelfus** [comment]
@jon-a-nygaard - refactored as you and @bre1470 suggested. Thanks!

Found the root of the failing commit:
In Karma tests we run a few additional tests: `templates`. Those tests create charts that exist through the entire testing process. In my test I used `document.querySelectorAll('.highcharts-point-inactive');` - which returned more points than expected (some pie chart was interfering). I simply added a class name to the chart to avoid this.

@bre1470 - any thoughts about this problem? Can we somehow resolve this, so other devs won't fail into this trap? :)

**Comment by bre1470** [comment]
@pawelfus  Actually, that is the purpose of the templates to not destroy charts between tests. I wonder, why you do not do a `querySelectorAll` on the chart container?

**Comment by pawelfus** [comment]
> Actually, that is the purpose of the templates to not destroy charts between tests.

Yes, I realized that :) 
> I wonder, why you do not querySelectorAll on the chart container?

It seems that charts were created in the same container (or on top of each other). I didn't dig deeper, but in general TestController fired events for unrelated charts.

Still, can we do something about this? Perhaps adding info in docs? Maybe here:
- https://github.com/highcharts/highcharts/tree/master/test#features
- https://github.com/highcharts/highcharts/tree/master/samples#tests

**Comment by bre1470** [comment]
The template containers are a fixed stack, but they only lay over your template-less chart, if they get used (positive z-index). When to many events are firing, maybe something in Highcharts is going wrong.

The same situation would be in RL like having a webpage with several charts and a popup where another chart is available. Now when you interact with the chart in the popup, there should be no events firing on the chart underneath imho.

**Comment by pawelfus** [comment]
> Now when you interact with the chart in the popup, there should be no events firing on the chart underneath imho.

That's how it works, see: https://jsfiddle.net/BlackLabel/zv75g6wm/
I'm not sure what do you meant with to many events - my test has just one event `controller.mouseOver(x, y);`, could you elaborate?

**Comment by bre1470** [comment]
TestController is working by getting the element on top and firing there your requested event. As I understood you, the problem for you is, that events from other charts are interfering your test and your solution was to check for the SVG output. My point was, that something is wrong with Highcharts, if unexpected events on other charts get fired.
