### PR TITLE
dash/bugfix-highcharts-component-multiple-tables

### LINKED ISSUE #23445: In Dashboards the chart displays only the first series described in connector array
#### Expected behaviour
All chart's series are displayed on the chart.

#### Actual behaviour
The chart in dashboard displays only one series, the first one described in connector array.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/d3mskepc/

#### Product version
Highcharts Dashboards

### PR DESCRIPTION
**Pull request by ddragula**
Fixed #23445, components with multiple connectors loaded only first data table correctly.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1211044568865308

### CODE REVIEW

**Review by KamilKubik — APPROVED** [review]

File: ts/Dashboards/Components/Component.ts [hunk 1]
```diff
@@ -666,10 +657,20 @@ abstract class Component {
...
 
-                if (oldConnectorId !== newConnectorId) {
+                // Check if the data table key has changed.
+                if (
+                    connectorOptions[i]?.dataTableKey !==
+                    this.connectorHandlers[i]?.options.dataTableKey
+                ) {
                     connectorsHaveChanged = true;
                     break;
                 }
```
Comment (sebastianbochan) [inline ts/Dashboards/Components/Component.ts:669]: Do we need two separate IFs?

You can merge them into one OR.

Comment (ddragula) [reply ts/Dashboards/Components/Component.ts:669]: Good point!

**Review by sebastianbochan — APPROVED** [review]
