### PR TITLE
bugfix/21924-custom-size-img-marker-state

### LINKED ISSUE #21924: Marker width/height ignored with custom symbol, and enabled false, with dense lines
#### Expected behaviour
The markers should have the size that have been configured.

#### Actual behaviour
The markers size as if no custom width/height were configured

#### Live demo with steps to reproduce
Here is a fiddle that shows the problem:

https://jsfiddle.net/eg1q2dfc/

It contains 2 series, close to each other. Each with a custom symbol for the marker, and a width/height (that have intentionally been set quite big). The "enabled" is set to false, causing the markers to disappear if the graph is "too crowded".

When running the graph you will notice that the markers to not appear (correct). When you hover over a maker, it does appear (correct), however in the wrong size!

#### Product version

Highcharts JS v11.4.8 (2024-08-29), but this also fails in v10.2.3

#### Affected browser(s)
Chrome and Edge (other not tested, but presumably all browsers are affected).

### PR DESCRIPTION
**Pull request by MarkusBarstad**
Fixed #21924, custom sizes in marker states did not work.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208444295941769

### CODE REVIEW

File: ts/Core/Series/Point.ts [hunk 1]
```diff
@@ -1513,7 +1513,11 @@ class Point {
                                         markerAttribs.x,
                                         markerAttribs.y,
                                         markerAttribs.width,
-                                        markerAttribs.height
+                                        markerAttribs.height,
+                                        extend(
```
Comment (bre1470) [inline ts/Core/Series/Point.ts:1517]: Use `merge`. Unlike `extend` it will not change `markerOptions` in-place by default.

**Review by bre1470 — CHANGES_REQUESTED** [review]

**Review by bre1470 — APPROVED** [review]
Looks good. 👍
