### PR TITLE
bugfix/8742-stackLabels-dataLabels

### LINKED ISSUE #8742: Some of stackLabels are not displayed when dataLabels are
#### Expected behaviour
**All** stackLabels should be displayed independently from dataLabels.

#### Actual behaviour
Some stackLabels are not displayed when dataLabels are displayed.

#### Live demo
https://jsfiddle.net/BlackLabel/rht1j40w/

#### Product version
6.1.1

#### Workaround 
Set yAxis.stackLabels.allowOverlap to true.

Looks like regression after commit ae932768305de4824ae0d1584f96d3343fb9bc4c

### PR DESCRIPTION
**Pull request by khlieng**
Fixed #8742, some `stackLabels` did not render with `dataLabels` enabled.

### CODE REVIEW

File: ts/Extensions/Stacking.ts [hunk 1]
```diff
@@ -373,7 +373,7 @@ class StackItem {
         }
 
         // Rank it higher than data labels (#8742)
-        this.label.labelrank = chart.plotHeight;
+        this.label.labelrank = chart.inverted ? chart.plotWidth : chart.plotHeight;
```
Comment (TorsteinHonsi) [inline ts/Extensions/Stacking.ts:376]: We have `chart.plotSizeY`, it would save us a few bytes

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks! Only a minor optimization tip, otherwise fine.

File: ts/Extensions/Stacking.ts (hunk 1 above)
Comment (TorsteinHonsi) [reply ts/Extensions/Stacking.ts:376]: In addition, please add this issue to the comment above:

**Review by TorsteinHonsi — APPROVED** [review]
