### PR TITLE
bugfix/13838-exporting-collapsed-points

### LINKED ISSUE #13838: Gantt - exporting collapsed points
#### Expected behaviour

Toggling the node by the user should change the `point.collapsed` property which will make visible nodes after for the exporting.  

#### Actual behaviour

Toggling the nodes doesn't have an impact on the exported chart (the chart is rendering for the export with the initial options). 

#### Live demo with steps to reproduce

Demo: https://jsfiddle.net/BlackLabel/5ygt6pqv/

**Workaround:**
https://jsfiddle.net/BlackLabel/cy27xwz5/

#### Product version

 Highcharts Gantt JS v8.1.2 (2020-06-16)

### PR DESCRIPTION
**Pull request by Basts**
Fixed #13838, toggled nodes in the tree grid were not reflected correctly in the exported chart.

### CODE REVIEW

File: ts/Core/Axis/TreeGridAxis.ts [hunk 1]
```diff
@@ -851,6 +853,19 @@ namespace TreeGridAxis {
...
             breaks.push(obj);
+            // Change the collapsed flag #13838
+            node.collapsed = true;
+            axis.series.forEach(function (series): void {
+                const data = series.options.data;
+
+                if (data && data.length) {
+                    data.forEach(function (data): void {
+                        if ((data as PointOptionsObject).id === node.id) {
+                            (data as PointOptionsObject).collapsed = true;
```
Comment (pawelfus) [inline ts/Core/Axis/TreeGridAxis.ts:864]: Can Gantt a point be defined as an array instead of an object? If yes, then this won't work with arrays. For the reference, you can check how `PieSeries.slice()` is implemented (where `point.sliced` option is updated).

File: ts/Core/Axis/TreeGridAxis.ts [hunk 2]
```diff
@@ -851,6 +853,19 @@ namespace TreeGridAxis {
                 obj = getBreakFromNode(node, axis.max);
 
             breaks.push(obj);
+            // Change the collapsed flag #13838
+            node.collapsed = true;
+            axis.series.forEach(function (series): void {
+                const data = series.options.data;
+
+                if (data && data.length) {
+                    data.forEach(function (data): void {
```
[the remark this answers is not in the document]
Comment (pawelfus) [reply ts/Core/Axis/TreeGridAxis.ts:862]: Perhaps `var point = chart.get('id')` will be enough?

File: samples/unit-tests/gantt/treegrid/demo.js [hunk 3]
```diff
@@ -433,4 +433,10 @@ QUnit.test('series.data[].collapsed', assert => {
         2,
         'should have axis.max equal 2 when "Node 1" is expanded.'
     );
+
+    assert.strictEqual(
+        axis.series[0].points[0].collapsed,
```
Comment (pawelfus) [inline samples/unit-tests/gantt/treegrid/demo.js:438]: Please check also `series.options.data[0].collapsed`

File: ts/Core/Axis/TreeGridAxis.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (oysteinmoseng) [reply ts/Core/Axis/TreeGridAxis.ts:862]: Even better

File: ts/Core/Axis/TreeGridAxis.ts (hunk 1 above)
Comment (oysteinmoseng) [reply ts/Core/Axis/TreeGridAxis.ts:864]: [I don't think it works right now](https://github.com/highcharts/highcharts/issues/13768), but it should.

**Review by pawelfus — APPROVED** [review]
I see nothing wrong :)

**Review by TorsteinHonsi — APPROVED** [review]
