### PR TITLE
bugfix/23430-candlestick-vertical-panning

### LINKED ISSUE #23430: Vertical panning on candlestick chart in Highcharts Stock
#### Expected behaviour
Panning on the  candlestick chart works in x and y directions.

#### Actual behaviour
On candlestick chart, panning doesn't work with 'y' type, in type 'xy' only horizontal panning works.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/9ug5h2wp/

Zoom in and try to move around using panning. It's only possible in x direction, not in y.
Switch the type from candlestick to line and vertical panning will start working.

#### Product version
Highcharts Stock

### PR DESCRIPTION
**Pull request by jedrzejruta**
Fixed #23430, vertical panning didn't work in series using OHLC data.

### CODE REVIEW

**Review by pawelfus — APPROVED** [review]
Looks good!

File: samples/unit-tests/chart/panning/demo.js [hunk 1]
```diff
@@ -353,6 +353,58 @@ QUnit.test('Stock panning (#6276, #21319)', function (assert) {
...
+    });
+
+    chart.xAxis[0].setExtremes(1726617600000, 1726704000000);
+    const { max } = chart.yAxis[0].getExtremes();
+    controller.pan([100, 100], [200, 200]);
+
+    assert.strictEqual(
+        chart.yAxis[0].max > max,
+        true,
+        'Panning vertically works for candlestick series, #23430.'
```
Comment (kamil-musialowski) [inline samples/unit-tests/chart/panning/demo.js]:
```suggestion
        'Panning vertically should work for candlestick series, #23430.'
```

File: ts/Core/Chart/Chart.ts [hunk 2]
```diff
@@ -3844,9 +3844,10 @@ class Chart {
                 !allExtremes
             ) {
                 for (const series of axis.series) {
+                    const valueColumnkey = series.dataColumnKeys()[1];
```
Comment (kamil-musialowski) [inline ts/Core/Chart/Chart.ts]:
```suggestion
                    const valueColumnKey = series.dataColumnKeys()[1];
```

Comment (jedrzejruta) [reply ts/Core/Chart/Chart.ts]: Good catch, thanks!

File: ts/Core/Chart/Chart.ts [hunk 3]
```diff
@@ -3844,7 +3844,7 @@ class Chart {
                 !allExtremes
             ) {
                 for (const series of axis.series) {
-                    const valueColumnkey = series.dataColumnKeys()[1];
+                    const valueColumnKey = series.dataColumnKeys()[1];
                     const seriesExtremes = series.getExtremes(
                         series.getProcessedData(true).modified
                             .getColumn(valueColumnkey) as Array<number> || [],
```
Comment (kamil-musialowski) [inline ts/Core/Chart/Chart.ts]: You forgot about this one 👁️ 👁️

**Comment by jedrzejruta** [comment]
> Did you try that? It is shorter, more consistent, and probably safer than looking at the `dataColumnKeys`.

Actually, that didn't cross my mind - I agree it seems a safer and faster bet, thanks for pointing it out!

**Review by TorsteinHonsi — APPROVED** [review]
