### PR TITLE
bugfix/20529-rangeselector-option

### LINKED ISSUE #20529: `rangeSelector.selected` not working when used with `Highcharts.chart` constructor
#### Expected behaviour
Selected range is chosen on initial load of the chart.

#### Actual behaviour
Selected range isn't chosen and the extremes don't change.

#### Live demo with steps to reproduce

The issue happens only when using the `Highcharts.chart` constructor, with Highcharts Stock it works fine.
[https://jsfiddle.net/BlackLabel/L4q10dje/](https://jsfiddle.net/BlackLabel/L4q10dje/)

#### Product version
Regression introduced in Highcharts v11.3.0

_Internal note:_ Bisected to [999f29cc](https://github.com/highcharts/highcharts/commit/999f29cce6386948e471e0756754cd0e48e01f88)

### PR DESCRIPTION
**Pull request by Xillez**
Fixed #20529, range selector not working with `chart` constructor.
---

Added a test that checks that the same ranges are selected in charts made with both chart and stockChart constructor (both with and without axis options).

Asana task: https://app.asana.com/0/1204848917817812/1206451184953576/f

### CODE REVIEW

File: samples/unit-tests/rangeselector/chart-stock-option-comparison/demo.js [hunk 1]
```diff
@@ -0,0 +1,90 @@
+function testChartsRangeIsSame(assert, chartInfo, stockChart) {
+}
+
```
Comment (bre1470) [inline samples/unit-tests/rangeselector/chart-stock-option-comparison/demo.js:3]: This can be cleaned up.

**Review by bre1470 — CHANGES_REQUESTED** [review]
Works for me. 👍 

Some adjustment requests... RangeSelector is part of Highcharts Stock, so the folder name of the test does not need to mention Stock.

**Review by bre1470 — APPROVED** [review]
Thank you! Looks good. 👍

File: samples/unit-tests/rangeselector/chart-option-comparison/demo.js [hunk 2]
```diff
@@ -0,0 +1,87 @@
+QUnit.test('#20529: Chart-stockChart-constructor rangeselector first-load comparison.', function (assert) {
+
+    var done = assert.async();
```
Comment (KacperMadej) [inline samples/unit-tests/rangeselector/chart-option-comparison/demo.js:3]: var -> const

File: samples/unit-tests/rangeselector/chart-option-comparison/demo.js [hunk 3]
```diff
@@ -0,0 +1,87 @@
...
+                    selected: 1 // 3 months
+                },
+                series: [
+                    {
+                        data: aaplCJson
+                    }
+                ]
+            };
+
+            var chart = Highcharts.chart('container', options),
```
Comment (KacperMadej) [inline samples/unit-tests/rangeselector/chart-option-comparison/demo.js:19]: var -> let

**Review by KacperMadej — APPROVED** [review]
Some `var`s but other than that looks good 👍

File: ts/Stock/RangeSelector/RangeSelector.ts [hunk 4]
```diff
@@ -364,9 +364,16 @@ class RangeSelector {
 
         // Update the chart
         if (!baseAxis) {
+            // X-axis options not defined, avoids undefined error and
+            // sets deferred range to undefined (#20529).
+            if (!chart.userOptions.xAxis) {
+                chart.userOptions.xAxis = {};
+            }
```
Comment (TorsteinHonsi) [inline ts/Stock/RangeSelector/RangeSelector.ts:371]: As a rule of thumb we avoid checking `userOptions`, because we expect `options` to be correctly updated, regardless of the option in question comes from the user or the defaults.  Another rule of thumb is to not modify user options, because, well, then they are no longer user options.

Do we have another way of solving this? What happened on line 369 with the old logic? Did the splat result in `undefined`? In that case, could we do something like this?

`baseXAxisOptions = splat(chart.options.xAxis || {})[0];`

Comment (Xillez) [reply ts/Stock/RangeSelector/RangeSelector.ts:371]: To keep it short, when I started the task:
- The `chart.options` for some reason wasn't updated with the rangeSelection options and any attempts I made at updating them either had no effect or only broke multiple other tests. Currently, it seems rangeSelector options has been worked on separately by someone else in a separate PR as `options` are now properly updated before the range selection code runs, as far as I can see.
- I presumed, by your refactor (roughly a year ago, see bisected commit) which swapped `options` for `userOptions` in `Chart.getAxes()`, that `userOptions` was to be used, as there had to be a reason for why you refactored `getAxes` to use `userOptions`.

So, if `options` is to be used and not `userOptions`, should I change both of `RangeSelector.clickButton()` and `Chart.getAxes()` back to only use `options`? and of course fix the tests that fail when doing so?

Comment (TorsteinHonsi) [reply ts/Stock/RangeSelector/RangeSelector.ts:371]: @Xillez The `Chart.getAxes` were part of a bigger refactor where the end game was to make sure that default options and user options were more cleanly separated. This happens at an earlier stage before the `chart.options` are reliably created, therefore we use `userOptions`.

You should not change `Chart.getAxis`, only `RangeSelector.clickButton` if that works.

**Review by TorsteinHonsi — APPROVED** [review]
Thanks, looks good to me! Also adding @pawelfus for reveiw.

File: ts/Stock/RangeSelector/RangeSelector.ts [hunk 5]
```diff
@@ -365,16 +363,24 @@ class RangeSelector {
...
             // Axis not yet instantiated. Temporarily set min and range
-            // options and remove them on chart load (#4317).
+            // options and axes once defined and remove them on
+            // chart load (#4317 & #20529).
             baseXAxisOptions = splat(chart.options.xAxis)[0];
-            rangeSetting = baseXAxisOptions.range;
-            baseXAxisOptions.range = range;
-            minSetting = baseXAxisOptions.min;
-            baseXAxisOptions.min = rangeMin;
+            const axisRangeUpdateEvent = addEvent(
```
Comment (pawelfus) [inline ts/Stock/RangeSelector/RangeSelector.ts:369]: An alternative and simple fix would be to modify `chart.userOptions.xAxis` (instead of `chart.options.xAxis`).

However that raises a question: why the previous versions used to contain "userOptions" (the reference) in `chart.options.xAxis`? Just to be on the same page: I prefer the current solution (different `chart.options.xAxis` and `chart.userOptions.xAxis` objects). Should we expect more similar issues @TorsteinHonsi? 🤔

**Review by pawelfus — CHANGES_REQUESTED** [review]
Nice! Just some minor improvements in the test

File: samples/unit-tests/rangeselector/chart-option-comparison/demo.html [hunk 6]
```diff
@@ -0,0 +1,7 @@
+<script src="https://code.highcharts.com/stock/highstock.js"></script>
+
+<div id="qunit"></div>
+<div id="qunit-fixture"></div>
+
+<div id="container"></div>
+<div id="stockChartContainer"></div>
```
[the remark this answers is not in the document]
Comment (Xillez) [reply samples/unit-tests/rangeselector/chart-option-comparison/demo.html:7]: No worries & thanks :+1:

File: samples/unit-tests/rangeselector/chart-option-comparison/demo.js [hunk 7]
```diff
@@ -0,0 +1,87 @@
+QUnit.test('#20529: Chart-stockChart-constructor rangeselector first-load comparison.', function (assert) {
+
+    const done = assert.async();
+    fetch('https://cdn.jsdelivr.net/gh/highcharts/highcharts@v7.0.0/samples/data/aapl-c.json')
```
[the remark this answers is not in the document]
Comment (Xillez) [reply samples/unit-tests/rangeselector/chart-option-comparison/demo.js:4]: very true, I'll limit the set👍

File: ts/Stock/RangeSelector/RangeSelector.ts (hunk 5 above)
Comment (TorsteinHonsi) [reply ts/Stock/RangeSelector/RangeSelector.ts:369]: In principle, `userOptions` should never be modified, they should be what it says, the user-defined options. All business code should use `.options` because that is the merged and processed options to be used. Ideally I wanted to remove `userOptions` altogether, but there are some very few cases where we need to check whether the user-defined option is explicitly different from the default.

> Should we expect more similar issues?

@pawelfus We might. I have tackled a few of those during refactoring in the past.

**Review by pawelfus — APPROVED** [review]
Thanks!

**Comment by pawelfus** [comment]
Nothing to add, ready to merge @TorsteinHonsi
