### PR TITLE
bugfix/13807-stock-tools-adding-indicator-breaks-the-chart

### LINKED ISSUE #13807: stock tools - indicator breaks the chart
#### Expected behaviour

The new indicator should move both initial series and yAxis up.

#### Actual behaviour

Added indicator breaks the chart with multiple yAxis.

#### Live demo with steps to reproduce

Demo: https://jsfiddle.net/BlackLabel/rsy19kxp/ - add some indicator - Accumulation/Distribution i.e.

#### Product version

Highcharts JS v8.1.2 (2020-06-16)

### PR DESCRIPTION
**Pull request by pawellysy**
Fixed #13807, Stock tools: Adding a technical indicator when multiple axes were predefined used to break the chart

### CODE REVIEW

File: ts/Stock/StockToolsBindings.ts [hunk 1]
```diff
@@ -499,48 +500,63 @@ extend(NavigationBindings.prototype, {
...
         yAxes: Array<AxisType>,
         plotHeight: number,
-        defaultHeight: number
+        defaultHeight: number,
+        deleteIndicatorAxis?: boolean
     ): Array<Record<string, number>> {
-        var positions: (Array<Record<string, number>>|undefined),
-            allAxesHeight = 0;
-
+        var positions,
```
Comment (karolkolodziej) [inline ts/Stock/StockToolsBindings.ts:516]: Can we specify the `positions` type more precisely?
Later in the code, you are casting to `any` a few times.

Comment (pawellysy) [reply ts/Stock/StockToolsBindings.ts:516]: I can specify the type as previously: (Array<Record<string, number>>|undefined)

File: ts/Stock/StockToolsBindings.ts [hunk 2]
```diff
@@ -499,48 +500,63 @@ extend(NavigationBindings.prototype, {
...
+                    correctFloat(yAxis.top - yAxis.chart.plotTop) / plotHeight;
+
+            // New axis' height is NaN so we can check if
+            // the axis is newly created this way
+            if (!deleteIndicatorAxis) {
+                if (!isNumber(height)) {
+                // check if the previous axis is the
+                // indicator axis (every indicator inherits from sma)
+
+                    height = (yAxes as any)[index - 1].series.every((s: Series): boolean => s.is('sma')) ?
```
Comment (karolkolodziej) [inline ts/Stock/StockToolsBindings.ts:539]: I guess here we might try `yAxes: Array<AxisType>`

**Review by karolkolodziej — CHANGES_REQUESTED** [review]
Besides a few TS issues, it looks ok!

File: ts/Stock/StockToolsBindings.ts (hunk 2 above)
Comment (pawellysy) [reply ts/Stock/StockToolsBindings.ts]: Probably 'as any' is not necessary at all, Since the yAxes variable has already the ' Array<AxisType>' assigned. Thanks!

File: samples/unit-tests/stock-tools/indicators/demo.js [hunk 3]
```diff
@@ -42,89 +42,605 @@ QUnit.test('Managing tech indicators in Stock Tools', function (assert) {
...
+    );
+
+    assert.close(
+        parseFloat(chart.yAxis[0].options.height),
+        100,
+        0.0001, // up to 0.0001% is fine
+        'Correct Height for Main axis after deleting all indicators. Main axis -> 100% height'
+    );
+
+    chart.destroy();
```
Comment (pawelfus) [inline samples/unit-tests/stock-tools/indicators/demo.js:198]: Is it necessary to recreate the chart?

File: samples/unit-tests/stock-tools/indicators/demo.js [hunk 4]
```diff
@@ -42,89 +42,605 @@ QUnit.test('Managing tech indicators in Stock Tools', function (assert) {
...
+        'Correct Height for Indicator axis after deleting 1 indicator. Main axis originally 60% height'
+    );
+
+    assert.close(
+        parseFloat(chart.yAxis[2].options.top),
+        75,
+        0.0001, // up to 0.0001% is fine
+        'Correct Top for Indicator axis after deleting 1 indicator. Main axis originally 60% height'
+    );
+    chart.destroy();
```
Comment (pawelfus) [inline samples/unit-tests/stock-tools/indicators/demo.js:353]: Another chart destroy. Perhaps we could just update items on the chart (e.g. yAxes)?

File: samples/unit-tests/stock-tools/indicators/demo.js [hunk 5]
```diff
@@ -42,89 +42,605 @@ QUnit.test('Managing tech indicators in Stock Tools', function (assert) {
...
+        'Correct Top for Main axis after adding 1 indicators. Mixed axis heights'
+    );
+    assert.close(
+        parseFloat(chart.yAxis[1].options.height),
+        60,
+        0.0001, // up to 0.0001% is fine
+        'Correct Height for  second Main axis after adding 1 indicator. Mixed axis heights'
+    );
+
+    chart.destroy();
```
Comment (pawelfus) [inline samples/unit-tests/stock-tools/indicators/demo.js:572]: 3rd one

File: ts/Stock/StockToolsBindings.ts [hunk 6]
```diff
@@ -287,8 +293,9 @@ bindingsUtils.manageIndicators = function (
             series.remove(false);
 
             if (indicatorsWithAxes.indexOf(series.type) >= 0) {
+                const removedYAxisHeight = yAxis.options.height;
                 yAxis.remove(false);
-                navigation.resizeYAxes();
+                navigation.resizeYAxes(removedYAxisHeight as string);
```
Comment (pawelfus) [inline ts/Stock/StockToolsBindings.ts:298]: Instead of telling TS it will be a string, we should rather support both possible values (string and number). Or make sure `height` is cast to string

File: ts/Stock/StockToolsBindings.ts [hunk 7]
```diff
@@ -595,112 +625,63 @@ extend(NavigationBindings.prototype, {
...
-            positions[allAxesLength - 1] = {
-                top: correctFloat(100 - defaultHeight),
-                height: defaultHeight
-            };
+            resizers = this.getYAxisResizers(yAxes);
 
+        if (
+            !removedYAxisHeight &&
+            allAxesHeight <= correctFloat(0.8 + defaultHeight / 100)
+        ) {
```
Comment (pawelfus) [inline ts/Stock/StockToolsBindings.ts:663]: Could you please add a comment here? I'm not sure what is the purpose of this if-else

**Review by pawelfus — CHANGES_REQUESTED** [review]
A few minor changes, overall good 👍

File: ts/Stock/StockToolsBindings.ts (hunk 6 above)
Comment (raf18seb) [reply ts/Stock/StockToolsBindings.ts:298]: In this case, we are sure that the `height` of the indicator axis that is being removed is always a string as percents. To remove an axis through gui, we need to add it first. When adding, the height is defined here (always as string):
```js
yAxes[index].update({
    height: position.height + '%',
    top: position.top + '%',
...
```

File: samples/unit-tests/stock-tools/indicators/demo.js (hunk 3 above)
Comment (pawellysy) [reply samples/unit-tests/stock-tools/indicators/demo.js]: I replaced the recreating of the chart with updates.

File: samples/unit-tests/stock-tools/indicators/demo.js (hunk 4 above)
Comment (pawellysy) [reply samples/unit-tests/stock-tools/indicators/demo.js]: I replaced the recreating of the chart with updates.

File: samples/unit-tests/stock-tools/indicators/demo.js (hunk 5 above)
Comment (pawellysy) [reply samples/unit-tests/stock-tools/indicators/demo.js]: I replaced the recreating of the chart with updates.

File: samples/unit-tests/stock-tools/indicators/demo.js [hunk 8]
```diff
@@ -42,89 +42,635 @@ QUnit.test('Managing tech indicators in Stock Tools', function (assert) {
...
+            },
+            type: 'atr'
+        }
+    );
+
+    assert.close(
+        parseFloat(chart.yAxis[0].options.height),
+        100 / 1.2,
+        0.0001, // up to 0.0001% is fine
+        'Correct Height for Main axis after adding 1 indicator. Main axis -> 100% height'
```
Comment (pawelfus) [inline samples/unit-tests/stock-tools/indicators/demo.js:68]: `should` ;)

File: samples/unit-tests/stock-tools/indicators/demo.js [hunk 9]
```diff
@@ -42,89 +42,635 @@ QUnit.test('Managing tech indicators in Stock Tools', function (assert) {
...
+                'params.index': '0',
+                'params.period': '5'
+            },
+            type: 'atr'
+        }
+    );
+
+    assert.close(
+        parseFloat(chart.yAxis[0].options.height),
+        100 / 1.2,
```
Comment (pawelfus) [inline samples/unit-tests/stock-tools/indicators/demo.js:66]: Why it's `100 / 1.2`? Could you add an explanation?

File: samples/unit-tests/stock-tools/indicators/demo.js [hunk 10]
```diff
@@ -42,89 +42,635 @@ QUnit.test('Managing tech indicators in Stock Tools', function (assert) {
...
+    );
+
+    assert.close(
+        parseFloat(chart.yAxis[0].options.height),
+        100,
+        0.0001, // up to 0.0001% is fine
+        'Correct Height for Main axis after deleting all indicators. Main axis -> 100% height'
+    );
+
+    // chart.destroy();
```
Comment (pawelfus) [inline samples/unit-tests/stock-tools/indicators/demo.js:198]: If unnecessary, please remove :)

File: ts/Stock/StockToolsBindings.ts [hunk 11]
```diff
@@ -499,51 +506,74 @@ extend(NavigationBindings.prototype, {
...
+        if (removedYAxisHeight) {
+            removedHeight = correctFloat((parseFloat(removedYAxisHeight) / 100));
+        }
+
+        positions = yAxes.map(function (yAxis: AxisType, index: number): Record<string, number> {
             var height = isPercentage(yAxis.options.height) ?
-                    parseFloat(yAxis.options.height as any) / 100 :
-                    yAxis.height / plotHeight,
+                    correctFloat(parseFloat(yAxis.options.height as any) / 100) :
+                    correctFloat(yAxis.height / plotHeight),
```
Comment (pawelfus) [inline ts/Stock/StockToolsBindings.ts:539]: Micro optimalization: instead of `isPercentage() ? correctFloat(a) : correctFloat(b)` you can use `correctFloat(isPercentage() ? a : b)`

File: ts/Stock/StockToolsBindings.ts (hunk 6 above)
Comment (pawelfus) [reply ts/Stock/StockToolsBindings.ts:298]: Ah, makes sense. Thanks!

File: ts/Stock/StockToolsBindings.ts [hunk 12]
```diff
@@ -499,51 +506,74 @@ extend(NavigationBindings.prototype, {
      * @param {number} defaultHeight
      *        Default height in percents.
      *
-     * @return {Array}
-     *         An array of calculated positions in percentages.
-     *         Format: `{top: Number, height: Number}`
+     * @param {string} removedYAxisHeight
+     *        Height of the removed yAxis.
```
Comment (pawelfus) [inline ts/Stock/StockToolsBindings.ts:510]: In the description please add the unit (pixels/percents)

**Review by pawelfus — APPROVED** [review]
Looks great, thanks!

File: samples/unit-tests/stock-tools/indicators/demo.js [hunk 13]
```diff
@@ -42,89 +42,542 @@ QUnit.test('Managing tech indicators in Stock Tools', function (assert) {
...
+                    .options.id
+        }
+    );
+
+    chart.yAxis[0].update({
+        height: '60%',
+        labels: {
+            align: 'left'
+        }
+    });
```
Comment (raf18seb) [inline samples/unit-tests/stock-tools/indicators/demo.js:333]: You can set `redraw` flag to `false` to avoid multiple redraws.

**Review by raf18seb — APPROVED** [review]
I've found one small thing left to improve, except that excellent work!

**Review by karolkolodziej — APPROVED** [review]
