### PR TITLE
bugfix/23151-polar-interaction

### LINKED ISSUE #23151: set startAngle wont trigger click event
#### Expected behaviour
Click event is supposed to trigger when click on a series

#### Actual behaviour
Nothing happens, the click event wont fire.

#### Live demo with steps to reproduce
https://codepen.io/plzn/pen/ByNmKKm

Comment out pane: {startAngle: -45} to make the click event fire
#### Product version
12.2.0

#### Affected browser(s)
Chrome, Firefox, Brave

### PR DESCRIPTION
**Pull request by magdalena-gut**
Fixed #23151, polar chart points were not hoverable at some `startAngle` values.

### CODE REVIEW

File: ts/Extensions/Pane/PaneComposition.ts [hunk 1]
```diff
@@ -123,32 +123,38 @@ function isInsidePane(
...
     if (defined(startAngle) && defined(endAngle)) {
         // Round angle to N-decimals to avoid numeric errors
-        const angle = Math.atan2(
+        let angle = Math.atan2(
             correctFloat(y - cy, 8),
             correctFloat(x - cx, 8)
         );
 
+        // Normalize angle to [0, 2π)
+        angle = (angle + 2 * Math.PI) % (2 * Math.PI);
```
Comment (MarkusBarstad) [inline ts/Extensions/Pane/PaneComposition.ts]: Instead of calculating `2 * Math.PI` multiple times, let's just calculate it once

**Review by MarkusBarstad — CHANGES_REQUESTED** [review]
Good job! Just a small nitpick from me!

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
