### PR TITLE
bugfix/14416-rangeselector-timezone

### LINKED ISSUE #14416: Range input changes date when losing focus (blur)
#### Expected behaviour
1. Click inside the "To" input (focus)
2. Click outside the "To" input (blur)
3. Nothing should happen because nothing was modified

#### Actual behaviour
1. Click inside the "To" input (focus)
2. Click outside the "To" input (blur)
3. The "To" date changes from `Jan 4 1970` to `Jan 3 1970`
hc-range-input-bug

#### Live demo with steps to reproduce
https://jsfiddle.net/nunoarruda/ys9qzubn/22/

This issue seems to happen only with the following set of options:
```
time: {
    timezoneOffset: 420
},
xAxis: {
    minRange: 3600 * 1000 // one hour
},
series: [
    {
      pointInterval: 24 * 3600 * 1000,
      data: [1, 2, 3, 4, 5]
    }
]
```

#### Product version
Highstock JS v8.2.2 (2020-10-22)

#### Affected browser(s)
All of them

### PR DESCRIPTION
**Pull request by khlieng**
Fixed #14416, range selector ignored `chart.time.timezoneOffset`.

### CODE REVIEW

File: ts/Extensions/RangeSelector.ts [hunk 1]
```diff
@@ -1318,6 +1318,7 @@ class RangeSelector {
                 dataMax = dataAxis.dataMax;
 
             value = (options.inputDateParser || defaultInputDateParser)(inputValue, chart.time.useUTC);
+            value += (chart.time.timezoneOffset || 0) * 60 * 1000; // #14416
```
Comment (TorsteinHonsi) [inline ts/Extensions/RangeSelector.ts:1321]: In the [defaultInputDateParser](https://github.com/highcharts/highcharts/blob/v8.2.2/ts/Extensions/RangeSelector.ts/#L1282), we are already correction the values for `date.getTimezoneOffset`. I am wondering if we can improve that correction to use the current state of `chart.time`, by using `time.getTimezoneOffset` instead. We may have to pass in the `time` as an argument though, in case `defaultInputDateParser` is not bound to the `RangeSelector` scope.

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]

File: ts/Extensions/RangeSelector.ts (hunk 1 above)
Comment (khlieng) [reply ts/Extensions/RangeSelector.ts:1321]: The `date.getTimezoneOffset` correction in `defaultInputDateParser` seems to just be correcting for the #433 fix that happened before `defaultInputDateParser` existed :)

Comment (TorsteinHonsi) [reply ts/Extensions/RangeSelector.ts:1321]: Okay, but can we combine them? Using `time.getTimezoneOffset` should in theory apply to the old issue as well.

**Review by TorsteinHonsi — APPROVED** [review]
Nice work, thanks!
