### PR TITLE
Fixed #20429 toggling bellcurve visibility throws error

### LINKED ISSUE #20429: Updating bell curve series visible option
#### Expected behaviour
Changing the bell curve `visible` option between `true` and `false` by using `series.update` method should work correctly.

#### Actual behaviour
Changing the bell curve `visible` option between `true` and `false` by using `series.update` produces an error in the console and breaks the chart.

#### Live demo with steps to reproduce
**Live demo:** https://jsfiddle.net/BlackLabel/w1Lfeuvm/
1. Click the 'Show bell curve' button.
2. Click the 'Hide bell curve' button.
3. Click the 'Show bell curve' button again -> issue.

#### Workaround
Use `setVisible` method to change the visibility of the bell curve series.
**Live demo with workaround:** https://jsfiddle.net/BlackLabel/h1kon94a/

### PR DESCRIPTION
**Pull request by MarkusBarstad**
Fixed #20429, toggling bellcurve visibility threw error

~~Fixed #20429, series.points were all destroyed when setData attempted to use them.~~

I am not entirely sure how to word this PR

When setData is called on a series without visibility, points will be destroyed. For the Bellcurve series, setData seems to be called every time the series is updated. So when turning visibility off, then on, an error will throw because setData attempts to use the very properties it destroyed the last time it ran.

Perhaps there are other ways of fixing this, such as shifting when setData is called for the BellcurveSeries 🤔 .

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1206335993588357

### CODE REVIEW

File: ts/Series/Bellcurve/BellcurveSeries.ts [hunk 1]
```diff
@@ -164,6 +164,11 @@ class BellcurveSeries extends AreaSplineSeries {
         if (series.baseSeries?.yData?.length || 0 > 1) {
             series.setMean();
             series.setStandardDeviation();
+
+            if (series.points?.length && series.points[0]?.destroyed) {
+                series.points = series.data;
+            }
+
```
Comment (hubertkozik) [inline ts/Series/Bellcurve/BellcurveSeries.ts:171]: I think there is a possibility for a much easier solution. The issue is based on that, setData tries to update points, which don't exist (are destroyed). I've just tested and if we set a 4th flag (`updatePoints`) as false for `setData` in this method (`setDerivedData`) then everything works as expected.

**Review by hubertkozik — CHANGES_REQUESTED** [review]
Below comment about the solution. Also, can you add a unit-test?

File: ts/Series/Bellcurve/BellcurveSeries.ts (hunk 1 above)
Comment (MarkusBarstad) [reply ts/Series/Bellcurve/BellcurveSeries.ts:171]: Alright, good catch!

**Comment by MarkusBarstad** [comment]
> Below comment about the solution. Also, can you add a unit-test?

A bit unsure about what properties to test here, @hubertkozik , so I simply toggle visibility off then on and test that it is indeed visible.

**Review by goransle — APPROVED** [review]
LGTM

**Comment by hubertkozik** [comment]
@MarkusBarstad Example chart config to test if there are no errors and graph is drawn: https://jsfiddle.net/BlackLabel/3sk92tnm/

**Review by hubertkozik — APPROVED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!

> I am not entirely sure how to word this PR

@MarkusBarstad I renamed it to the wording you used in the PR description, as per [Writing content for the changelog](https://github.com/highcharts/highcharts/tree/master/changelog#writing-content-for-the-changelog), paragraph 7.
