### PR TITLE
bugfix/19892-rangeSelector-with-heikinashi

### LINKED ISSUE #19892: StockTools rangeSelector after changing series throws an error
#### Expected behaviour
Range selector should work normally after changing the series type.

#### Actual behaviour
After changing the series to i.e Heikin-Aski and then clicking 1m/3m on rangeSelector chart is gone and error is shown in the console.

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/stock-tools-gui

#### Product version
Stock 11.1.0

_Internal note: Check other series types after the fix._

### PR DESCRIPTION
**Pull request by kamil-musialowski**
Fixed #19892, HeikinAshi and Hollow Candlestick were not working with certain `dataGrouping` periods.

- [x] Add tests for both HeikinAshi and HollowCandlestick

### CODE REVIEW

File: ts/Series/HollowCandlestick/HollowCandlestickSeries.ts [hunk 1]
```diff
@@ -169,31 +169,26 @@ class HollowCandlestickSeries extends CandlestickSeries {
...
-            for (let i = 1; i < processedYData.length; i++) {
-                const dataPoint: any = processedYData[i],
-                    previousDataPoint: any = processedYData[i - 1];
-
-                hollowCandlestickData.push(series.isBullish(
-                    dataPoint,
-                    previousDataPoint
-                ));
-            }
+        hollowCandlestickData.length = 0;
```
Comment (pawelfus) [inline ts/Series/HollowCandlestick/HollowCandlestickSeries.ts:176]: Why do we need to clear this always? I think we have cleared this in `updatedData` event 🤔 If not, perhaps we should add `updated` event too? Updating this on each chart's redraw seems a bit too aggressive.

**Review by pawelfus — CHANGES_REQUESTED** [review]

File: ts/Series/HollowCandlestick/HollowCandlestickSeries.ts (hunk 1 above)
Comment (kamil-musialowski) [reply ts/Series/HollowCandlestick/HollowCandlestickSeries.ts:176]: Previously, it didn't work at all. Similar scenario to heikinashi, `hollowCandlestickData` had a wrong length.
Not working on master: https://jsfiddle.net/BlackLabel/6um2gctx/

Comment (pawelfus) [reply ts/Series/HollowCandlestick/HollowCandlestickSeries.ts:176]: Yes, I know, I know. Just wanted to clarify if we need to clear that array length on each redraw. It seems heikinashi has the same problem. We clear and build the dataset on each redraw (aaand we have event on updated data which is redundant now, isn't it?). Let's keep this solution for now, however adding this to the Performance profile

Comment (kamil-musialowski) [reply ts/Series/HollowCandlestick/HollowCandlestickSeries.ts:176]: Sounds fair! I'll add the test, and we are good to go. We can discuss it later F2F, since it's a good case to work on perf optimization.

**Review by DJTechnoo — APPROVED** [review]
Good stuff!

**Review by bm64 — APPROVED** [review]

**Review by pawelfus — APPROVED** [review]
Thanks!

**Review by TorsteinHonsi — APPROVED** [review]
