### PR TITLE
Fixed #12537, packedBubble incorrect color/linewidth after dehover.

### LINKED ISSUE #12537: Big bubbles lost borders after hovering and de-hovering on a small bubble in the Split Packed bubble chart
#### Expected behaviour
After hovering the mouse to focus on a small bubble and then moving the focus away from it to return to the initial state, the border of the big bubbles should appear again.

#### Actual behaviour
The bubbles of the big bubbles disappear after hovering the mouse to focus on a small bubble and then moving the focus away from it.

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/packed-bubble-split/

1. Wait until the bubbles settle down to their final positions. Note that there is a border around each big bubble.
2. mouse over on one of the small bubbles to bring focus on it
3. Click outside the bubbles (e.g. the chart title) to move the focus away from the small bubble
4. Note that the borders around the bubbles are gone.

#### Product version
Highcharts latest version in master branch

#### Affected browser(s)
Tested in Latest Chrome Version 78.0.3904.108 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by DJTechnoo**
Fixed #12537, disappearing `lineWidth` and fill-color after de-hovering a bubble in packed bubble series.

### CODE REVIEW

File: ts/Series/PackedBubble/PackedBubbleSeries.ts [hunk 1]
```diff
@@ -1151,6 +1167,26 @@ class PackedBubbleSeries extends BubbleSeries implements Highcharts.DragNodesSer
         return arr;
     }
 
+    public pointAttribs(
+        point?: PackedBubblePoint,
+        state?: StatesOptionsKey
+    ): SVGAttributes {
+        let options = this.options,
+            hasParentMarker = point && point.isParentNode,
+            markerOptions = hasParentMarker && options.layoutAlgorithm && options.layoutAlgorithm.parentNodeOptions ?
```
Comment (Izothep) [inline ts/Series/PackedBubble/PackedBubbleSeries.ts:1176]: In general, I would rather go with ternary operator with simple boolean checks, like `oneVariable` ? `optionA` : `optionB`. If we need to check 3 variables in ternary operator, then good idea might be to prepare a separate boolean checking all of it before ternary operator (or simply using an `if` statement)

File: ts/Series/PackedBubble/PackedBubbleSeries.ts [hunk 2]
```diff
@@ -1151,6 +1167,26 @@ class PackedBubbleSeries extends BubbleSeries implements Highcharts.DragNodesSer
...
+                options.layoutAlgorithm.parentNodeOptions.marker :
+                options.marker,
+            fillOpacity = (markerOptions as any).fillOpacity,
```
Comment (Izothep) [inline ts/Series/PackedBubble/PackedBubbleSeries.ts:1179]: Do you know why we need the `any` casting in here? We should avoid it if possible. Maybe all we need to do is to simply change the TS type somewhere above?

File: ts/Series/PackedBubble/PackedBubbleSeries.ts [hunk 3]
```diff
@@ -1151,6 +1167,26 @@ class PackedBubbleSeries extends BubbleSeries implements Highcharts.DragNodesSer
...
+            attr = Series.prototype.pointAttribs.call(this, point, state);
+
+        if (fillOpacity !== 1) {
+            attr.fill = color(attr.fill as any)
```
Comment (Izothep) [inline ts/Series/PackedBubble/PackedBubbleSeries.ts:1183]: Similar as before, we need to avoid all `any` castings in new code

File: ts/Series/PackedBubble/PackedBubbleSeries.ts [hunk 4]
```diff
@@ -1347,6 +1383,81 @@ class PackedBubbleSeries extends BubbleSeries implements Highcharts.DragNodesSer
...
+        let series = this,
+            options = series.options,
+            stateOptions = options.states,
+            graph = series.graph,
+            layoutOptions = options.layoutAlgorithm,
+            lineWidth,
+            attribs,
+            stateAnimation = pick(
+                (
+                    (stateOptions as any)[state || 'normal'] &&
```
Comment (Izothep) [inline ts/Series/PackedBubble/PackedBubbleSeries.ts:1419]: Do we need `as any` in here? Maybe we need to import something from StateOptions file

File: ts/Series/PackedBubble/PackedBubbleSeries.ts [hunk 5]
```diff
@@ -1347,6 +1383,81 @@ class PackedBubbleSeries extends BubbleSeries implements Highcharts.DragNodesSer
...
+                    attribs = {
+                        'stroke-width': lineWidth
+                    };
+
+                    // Animate the graph stroke-width.
+                    graph.animate(
+                        attribs,
+                        stateAnimation
+                    );
+                    while ((series as any)['zone-graph-' + i]) {
```
Comment (Izothep) [inline ts/Series/PackedBubble/PackedBubbleSeries.ts:1449]: Do we need `as any`? And the whole `while` loop in general?

**Review by Izothep — CHANGES_REQUESTED** [review]
In general - really good job! :) I have added some comments on the parts of code that we should change in my opinion.

File: ts/Core/Series/Point.ts [hunk 6]
```diff
@@ -1506,10 +1506,18 @@ class Point {
...
+                layoutAlgorithm.parentNodeOptions.marker
+            ) ?
+                layoutAlgorithm.parentNodeOptions.marker :
+                series.options.marker,
             markerOptions = (
                 (defaultOptions.plotOptions as any)[series.type as any].marker &&
-                series.options.marker
-            ),
+                marker
+            ) as PointMarkerOptions | undefined,
```
[the remark this answers is not in the document]
Comment (DJTechnoo) [reply ts/Core/Series/Point.ts:1520]: Nice catch! We didn't need this one

File: ts/Series/PackedBubble/PackedBubbleSeries.ts [hunk 7]
```diff
@@ -1151,6 +1167,26 @@ class PackedBubbleSeries extends BubbleSeries implements Highcharts.DragNodesSer
         return arr;
     }
 
+    public pointAttribs(
```
[the remark this answers is not in the document]
Comment (DJTechnoo) [reply ts/Series/PackedBubble/PackedBubbleSeries.ts:1170]: This one is still needed, the colour changes slightly after de-hovering. I'll add some comments to it 😄

File: ts/Series/PackedBubble/PackedBubbleSeries.ts [hunk 8]
```diff
@@ -1151,6 +1167,26 @@ class PackedBubbleSeries extends BubbleSeries implements Highcharts.DragNodesSer
...
+                options.layoutAlgorithm.parentNodeOptions.marker :
+                options.marker,
+            fillOpacity = (markerOptions as any).fillOpacity,
+            attr = Series.prototype.pointAttribs.call(this, point, state);
+
+        if (fillOpacity !== 1) {
+            attr.fill = color(attr.fill as any)
+                .setOpacity(fillOpacity)
+                .get('rgba');
+        }
```
Comment (TorsteinHonsi) [inline ts/Series/PackedBubble/PackedBubbleSeries.ts:1186]: Instead of converting the fill to `rgba`, it is probably better to add `attr['fill-opacity']`.

File: ts/Series/PackedBubble/PackedBubbleSeries.ts [hunk 9]
```diff
@@ -1347,6 +1383,81 @@ class PackedBubbleSeries extends BubbleSeries implements Highcharts.DragNodesSer
...
+                        (series as any)['zone-graph-' + i].animate(
+                            attribs,
+                            stateAnimation
+                        );
+                        i = i + 1;
+                    }
+                }
+            }
+        }
+    }
```
Comment (TorsteinHonsi) [inline ts/Series/PackedBubble/PackedBubbleSeries.ts:1459]: This function is largely a repetition of `Series.setState`, which is unfortunate. It also repeats calls to `graph.animate` directly after the super function has called `graph.animate`. 

Is the `lineWidth` the only thing we actually change? In that case we can just change `options.lineWidth` temporarily in the method override. Otherwise, we should consider an event that can handle this more precisely.

```ts
const originalLineWidth = this.options.lineWidth;
this.options.lineWidth = /* insert calculation here */
Series.prototype.setState.apply(this, arguments);
// Reset
this.options.lineWidth = originalLineWidth;
```

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks! Please see inline comments.

File: samples/unit-tests/series-packedbubble/positions/demo.js [hunk 10]
```diff
@@ -139,3 +139,43 @@ QUnit.test('PackedBubble layout simulation', function (assert) {
         'Bubbles should not get stuck during simulation (#14439).'
     );
 });
+
+QUnit.test('PackedBubble hover and dehover (#12537)', function (assert) {
```
[the remark this answers is not in the document]
Comment (DJTechnoo) [reply samples/unit-tests/series-packedbubble/positions/demo.js:143]: I tried this, but I recall there is a problem with `chart.update` when adding `lineWidth`. (Did not get added) I will have a look and see if I can try something else.

File: samples/unit-tests/series-packedbubble/positions/demo.js [hunk 11]
```diff
@@ -139,3 +139,43 @@ QUnit.test('PackedBubble layout simulation', function (assert) {
...
+                zMax: 1000,
+                lineWidth: 10,
+                layoutAlgorithm: {
+                    splitSeries: true,
+                    enableSimulation: false
+                }
+            }
+        },
+        series: [{
+            value: '1'
```
[the remark this answers is not in the document]
Comment (DJTechnoo) [reply samples/unit-tests/series-packedbubble/positions/demo.js:162]: Indeed, it should be

File: ts/Series/PackedBubble/PackedBubbleSeries.ts (hunk 9 above)
Comment (DJTechnoo) [reply ts/Series/PackedBubble/PackedBubbleSeries.ts:1459]: Thanks for the suggestion! It appeared the entire function was not needed anymore after all.

File: ts/Series/PackedBubble/PackedBubbleSeries.ts [hunk 12]
```diff
@@ -1151,6 +1167,47 @@ class PackedBubbleSeries extends BubbleSeries implements Highcharts.DragNodesSer
...
+            options.layoutAlgorithm.parentNodeOptions
+        ) {
+            markerOptions = options.layoutAlgorithm.parentNodeOptions.marker;
+        }
+
+        fillOpacity = (markerOptions as BubblePointMarkerOptions).fillOpacity;
+        attr = Series.prototype.pointAttribs.call(this, point, state);
+
+        if (fillOpacity !== 1) {
+            attr.fill = color(attr.fill as any).get();
```
Comment (TorsteinHonsi) [inline ts/Series/PackedBubble/PackedBubbleSeries.ts:1204]: No need to reset `attr.fill`. This line can be removed.

File: ts/Series/PackedBubble/PackedBubbleSeries.ts [hunk 13]
```diff
@@ -1151,6 +1167,47 @@ class PackedBubbleSeries extends BubbleSeries implements Highcharts.DragNodesSer
...
+     * undefined, normal state is assumed.
+     *
+     * @return {Highcharts.SVGAttributes}
+     * The presentational attributes to be set on the point.
+     */
+    public pointAttribs(
+        point?: PackedBubblePoint,
+        state?: StatesOptionsKey
+    ): SVGAttributes {
+        let options = this.options,
```
Comment (TorsteinHonsi) [inline ts/Series/PackedBubble/PackedBubbleSeries.ts:1186]: Please resolve `let` vs `const`

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Please resolve the remaining comments and verify the two visual changes. If they are legitimate, approve them with a comment.

File: ts/Series/PackedBubble/PackedBubbleSeries.ts (hunk 7 above)
[the remark this answers is not in the document]
Comment (TorsteinHonsi) [reply ts/Series/PackedBubble/PackedBubbleSeries.ts:1182]: Did you add those comments? If so you can resolve this conversation.

File: ts/Series/PackedBubble/PackedBubblePoint.ts [hunk 14]
```diff
@@ -20,7 +20,13 @@ import type PackedBubblePointOptions from './PackedBubblePointOptions';
 import type PackedBubbleSeries from './PackedBubbleSeries';
 import Chart from '../../Core/Chart/Chart.js';
 import Point from '../../Core/Series/Point.js';
+import Series from '../../Core/Series/Series.js';
+import Color from '../../Core/Color/Color.js';
+const { parse: color } = Color;
 import SeriesRegistry from '../../Core/Series/SeriesRegistry.js';
+import type { StatesOptionsKey } from '../../Core/Series/StatesOptions';
+import type SVGAttributes from '../../Core/Renderer/SVG/SVGAttributes';
+
```
[the remark this answers is not in the document]
Comment (TorsteinHonsi) [reply ts/Series/PackedBubble/PackedBubblePoint.ts:25]: Is this resolved @DJTechnoo ?

**Comment by DJTechnoo** [comment]
Any updates on this PR?

**Review by TorsteinHonsi — APPROVED** [review]
Looks good to me! Pending @Izothep 's approval.

**Comment by Izothep** [comment]
Good to me, good job!

**Review by Izothep — APPROVED** [review]
