### PR TITLE
bugfix/13342-tooltip-position-update-height

### LINKED ISSUE #13342: Tooltip does not to properly pop up when changing chart height dynamically since Chrome 81
### Expected behaviour

After dynamically increasing chart height (say, from 0.1 to 400), tooltip should still pop up not only when the mouser cursor is on the line but also when the cursor is on the empty space in a chart.

### Actual behaviour

**After upgrading from chrome 80 to chrome 81,**
Tooltip does not pop up as you move the mouse cursor on the empty space in the chart, but it does pop up if you move the cursor onto the line.

### Live demo with steps to reproduce
[Reproduction in CodeSandbox](https://codesandbox.io/s/highcharts-vue-demo-93b6i)

**Google Chrome 80.0.3987.149**
chrome80

**Google Chrome 81.0.4044.113**
chrome81

### Product version
* highcharts: 8.0.3
* highcharts-vue: 1.3.5

### Affected browser(s)
Chrome 81

### PR DESCRIPTION
**Pull request by sebastianbochan**
Fixed #13342, tooltip tracking was broken after height update.

### CODE REVIEW

File: ts/parts/Chart.ts [hunk 1]
```diff
@@ -2652,8 +2652,12 @@ class Chart {
     public updateContainerScaling(): void {
         const container = this.container;
         if (
-            container.offsetWidth &&
-            container.offsetHeight &&
+            /**
```
Comment (TorsteinHonsi) [inline ts/parts/Chart.ts:2655]: Use the `//` syntax for inline comments. `/**` signifies a doclet.

**Comment by sebastianbochan** [comment]
I committed your suggestions. The PR is ready to merge.
@TorsteinHonsi
