### PR TITLE
bugfix/14320-export-data-table 

### LINKED ISSUE #14320: Export data table update issue
#### Expected behaviour

Last properly working version is 8.1.2: https://jsfiddle.net/BlackLabel/gf8bum23/

#### Actual behaviour

In the actual version, the data table doesn't update after the series updating.

#### Live demo with steps to reproduce

Demo of the current version: https://jsfiddle.net/BlackLabel/7vx1uykj/

#### Product version

Highcharts JS v8.2.0 (2020-08-20)

### PR DESCRIPTION
**Pull request by karolkolodziej**
Fixed #14320, the table was not re-rendered after a data update.

Replaces https://github.com/highcharts/highcharts/pull/14344

### CODE REVIEW

File: ts/Extensions/ExportData.ts [hunk 1]
```diff
@@ -466,6 +466,9 @@ addEvent(Chart, 'render', function (): void {
         !this.dataTableDiv
     ) {
         this.viewData();
+    } else if (this.dataTableDiv) {
+        // Data table was not re-rendered after a data update, #14320.
+        AST.setElementHTML(this.dataTableDiv, this.getTable());
```
Comment (TorsteinHonsi) [inline ts/Extensions/ExportData.ts:471]: This seems a bit out of place, especially since we're otherwise doing the `setElementHTML` in the `toggleData` function. I found that the table successfully updates if I just remove the `!this.dataTableDiv` part of the condition:

```ts
addEvent(Chart, 'render', function (): void {
    if (
        this.options &&
        this.options.exporting &&
        this.options.exporting.showTable &&
        !this.options.chart.forExport
    ) {
        this.viewData();
    }
});
```

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks, see the inline comment.

**Review by TorsteinHonsi — APPROVED** [review]
