### PR TITLE
bugfix/21521-overlapping-plotband-and-plotline-labels

### LINKED ISSUE #21521: Improve responsiveness for plot band labels
It would be great if Highcharts could enhance the responsiveness for overlapping labels on plot bands.

#### Expected behaviour
Show ellipsis with an option to display more information on hover, similar to the approach Highcharts uses when labels overlap.

#### Actual behaviour
Plot band labels overlap on small devices. 

Screenshot 2024-07-11 at 09 16 48

#### Live demo with steps to reproduce
See https://codepen.io/htveit/full/dyBPgBP on a mobile device

#### Product version
Highcharts v 11

#### Affected browser(s)
All

### PR DESCRIPTION
**Pull request by MarkusBarstad**
Fixed #21521, plot band labels and plot line labels would overlap if positioned too close. Added `inside` and `allowOverlap` options to the [Axis.plotBands.label](https://api.highcharts.com/highcharts/xAxis.plotBands.label) options.

### CODE REVIEW

File: ts/Core/Axis/Axis.ts [hunk 1]
```diff
@@ -493,6 +493,35 @@ class Axis {
         // List of plotLines/Bands
         axis.plotLinesAndBands = [];
 
+        // Creating labelCollector for plotLines/Bands
+        const collectors = chart.labelCollectors,
+            plotBandCollector = (
+                function (): (SVGElement | undefined)[] {
```
Comment (goransle) [inline ts/Core/Axis/Axis.ts:499]: Maybe this should be a (static?) class method? That would make things more flexible in terms for extensions of Axis

Comment (goransle) [reply ts/Core/Axis/Axis.ts:499]: maybe it could be a `defaultCollectors` array/object 🤔

Comment (MarkusBarstad) [reply ts/Core/Axis/Axis.ts:499]: It cannot be static because of non-static references to class-instance (`this.options` etc), some strange stuff also happened to `this` references when I simply made it a class method 🤔 , so instead there is now a class factory function, `createCollector` which users then can override and collect whatever labels they want.

Comment (goransle) [reply ts/Core/Axis/Axis.ts]: I was thinking something like:

```ts
    public static defaultCollector(axis: Axis): (SVGElement | undefined)[] {

        // It is possible that plotLinesAndBands and options
        // is/becomes undefined.
        const plotLinesAndBands = (
            !axis?.options?.labels?.allowOverlap &&
                axis?.plotLinesAndBands
        );

        if (plotLinesAndBands) {
            const labels: (SVGElement | undefined)[] = [];

            for (const { label } of plotLinesAndBands) {
                labels.push(label);
            }
            return labels;
        }

        return [];
    }
    /**
     * Overridable function which creates a function collecting labels.
     * The returned function is used for detecting overlapping labels.
     *
     * @function Highcharts.Axis#createCollector
     *
     * @return {Highcharts.LabelCollectorFunction}
     * A function which returns labels.
     */
    public createCollector(): Chart.LabelCollectorFunction {
        return (): (SVGElement | undefined)[] =>
            Axis.defaultCollector(this);
    }

```

Which seems to be working. But just having createCollector works too :)

**Review by goransle — CHANGES_REQUESTED** [review]
Code looks good to me. Of the visual changes I am a bit unsure if the changes in the annotations here are intended?

**Comment by MarkusBarstad** [comment]
@goransle , After talking to @TorsteinHonsi my understanding is that yes, labels, regardless of their origin (annotation/axis/etc) should be evaluated against one another.

Though I am a bit concerned about how the demo you posted will appear on mobile. With a slightly bigger width, the label in question will not hide with, but idk if this is enough. I will try to test this. 

Worst case, we can maybe disable overlapping behavior for that demo.

File: ts/Core/Axis/PlotLineOrBand/PlotLineOrBand.ts [hunk 2]
```diff
@@ -659,6 +701,19 @@ export default PlotLineOrBand;
  * @apioption xAxis.plotBands.label.align
  */
 
+/**
+ * Wether or not the text of the label can exceed the width of the label.
```
Comment (TorsteinHonsi) [inline ts/Core/Axis/PlotLineOrBand/PlotLineOrBand.ts:705]:
```suggestion
 * Whether or not the text of the label can exceed the width of the label.
```

File: ts/Core/Axis/PlotLineOrBand/PlotLineOrBand.ts [hunk 3]
```diff
@@ -72,8 +73,30 @@ class PlotLineOrBand {
...
         AxisClass: T
     ): ReturnType<typeof PlotLineOrBandAxis.compose> {
+
+        addEvent(ChartClass, 'afterInit', function (): void {
+            this.labelCollectors.push((): SVGElement[] => {
+                const labels: SVGElement[] = [];
+
+                for (const axis of this.axes) {
+
+                    if (!axis.options.labels.allowOverlap) {
```
Comment (TorsteinHonsi) [inline ts/Core/Axis/PlotLineOrBand/PlotLineOrBand.ts:86]: This option is about the axis labels. I wouldn't expect it to affect the plot band/plot line labels. How does this work currently?

What I would expect is an `allowOverlap` option on the `plotBand.label` itself.

**Review by TorsteinHonsi — COMMENTED** [review]
Thanks! This PR now actually does two things - add the `label.inside` option, and add the overlapping handling. So we need to state that in the paragraph for the changelog.

**Review by TorsteinHonsi — APPROVED** [review]
