### PR TITLE
Fixed #22807, SVGRenderer.fontMetrics throw exception with number input.

### LINKED ISSUE #22807: SVGRenderer.fontMetrics won't take in a number
Hi,

We are currently upgrading our repo to consume HC12 and ran into an issue wrt SVGRenderer.fontMetrics(). We have extracted out the code out from HC10's version of the fontMetrics method as per Dawid's suggestion on this forum post - https://www.highcharts.com/forum/viewtopic.php?p=196893#p196893. However, we would prefer to be able to use the Highcharts.fontMetrics() method out of the box to avoid specific implementation or code porting on our side.

Thanks!

#### Expected behaviour

According to the method signature in the code docs, the method can take in a number type as a parameter.
https://github.com/highcharts/highcharts/blob/master/ts/Core/Renderer/SVG/SVGRenderer.ts#L1702-L1704

I am also curious to know if there is any handling for other fontSize units like 'em' or 'rem'

#### Actual behaviour
win.getComputedStyle errors out when passed in a fontSize (string) or a font size (number)
``` 'Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'. ```

#### Live demo with steps to reproduce
14px (string with px): https://jsfiddle.net/zsr3tpdh
14 (number): https://jsfiddle.net/zsr3tpdh/1/

Please open dev chrome console to see the exact same error message we see
``` 'Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'. ```

#### Product version
HC 12.1.2

#### Affected browser(s)
Chrome 134.0.6998.89

### PR DESCRIPTION
**Pull request by bre1470**
Fixed #22807, `SVGRenderer.fontMetrics` did not support numeric arguments.

### CODE REVIEW

File: samples/unit-tests/svgrenderer/text/demo.js [hunk 1]
```diff
@@ -864,6 +864,26 @@ QUnit.test('Text height', function (assert) {
             })
             .add();
 
+        // Backwards compatibility, #22807
+        assert.deepEqual(
+            renderer.fontMetrics(14),
+            {
+                h: 17,
+                b: 14,
+                f: 14
```
Comment (MarkusBarstad) [inline samples/unit-tests/svgrenderer/text/demo.js:873]: Hmmmm, this errors locally for me, but its just off by a couple 🤔 

Idk how much it matters for karma tests but should we use assert.close instead maybe?

Comment (bre1470) [reply samples/unit-tests/svgrenderer/text/demo.js:873]: These have to be exact, because the calculation in fontMetrics is static and has no wiggle room:

```
        const h = f < 24 ? f + 3 : Math.round(f * 1.2),
            b = Math.round(h * 0.8);
```

I suggest PP to figure out what is going on.

Comment (MarkusBarstad) [reply samples/unit-tests/svgrenderer/text/demo.js:873]: Alright!

**Review by MarkusBarstad — APPROVED** [review]
:rocket:

File: ts/Core/Renderer/SVG/SVGRenderer.ts [hunk 2]
```diff
@@ -1726,18 +1726,21 @@ class SVGRenderer implements SVGRendererLike {
      *
      * @function Highcharts.SVGRenderer#fontMetrics
      *
-     * @param {Highcharts.SVGElement|Highcharts.SVGDOMElement|number} [element]
-     *        The element to inspect for a current font size. If a number is
-     *        given, it's used as a fall back for direct font size in pixels.
+     * @param {Highcharts.SVGElement|Highcharts.SVGDOMElement|number|string} [ref]
```
Comment (magdalena-gut) [inline ts/Core/Renderer/SVG/SVGRenderer.ts]: Should ref be optional as it was before in the API or the brackets there by mistake? 🤔

Comment (bre1470) [reply ts/Core/Renderer/SVG/SVGRenderer.ts]: Good catch. 😃 I believe it is a mistake.

File: ts/Core/Renderer/SVG/SVGRenderer.ts [hunk 3]
```diff
@@ -1726,18 +1726,20 @@ class SVGRenderer implements SVGRendererLike {
...
+     * The element to inspect for a current font size. If a number or string is
+     * given, it's used as a fall back for direct font size in pixels.
      *
      * @return {Highcharts.FontMetricsObject}
-     *         The font metrics.
+     * The font metrics.
      */
     public fontMetrics(
-        element: (DOMElementType|SVGElement)
+        ref: (DOMElementType|SVGElement|number|string)
```
Comment (TorsteinHonsi) [inline ts/Core/Renderer/SVG/SVGRenderer.ts]: Only `px` strings work as expected, as seen in https://jsfiddle.net/highcharts/d1pxb5co/. Internally we read non-pixel units by applying them to an element and read the computed height. That's why the function primarily takes an element as argument. 

Since string support is not reliable, I think we should just disable it (in ts/doclet at least) and retain elements and numbers.

**Review by TorsteinHonsi — APPROVED** [review]
