### PR TITLE
bugfix/17007-vbp-indicator-redraw-issue

### LINKED ISSUE #17007: VBP indicator doesn't recalculate values on redraw
This is a continuation of https://github.com/highcharts/highcharts/issues/16397

The above ticket solved the issue when the VBP indicator didn't recalculate on data update. But there's still issue when we not only update data, but update params or set `series.visible(true)`.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/rpfxv16L/
All updates should work without any console errors. For now, only the third update (`series.update({ visible: false })`) is working fine.

#### Product version
9.3.3

Workaround: update options first without redraw, then recalculate data manually, and then redraw the series.
Demo with a workaround: https://jsfiddle.net/BlackLabel/23ojL10w/

FYI @karolkolodziej

### PR DESCRIPTION
**Pull request by jakubSzuminski**
Fixed #17007, VBP indicator did not update correctly.

**Problem:**
_the problem was that the values, for example_ `volumeDataArray`, _for the indicator series were not updated after_ `series.update`

**Solution:**
_after each update, trigger_ `series.recalculateValues()`

### CODE REVIEW

File: samples/unit-tests/indicator-volume-by-price/recalculations/demo.js [hunk 1]
```diff
@@ -154,6 +154,24 @@ QUnit.test('Test algorithm on data updates.', function (assert) {
...
+    VBPIndicator.update({
+        params: {
+            ranges: 6
+        }
+    });
+
+    assert.strictEqual(
+        VBPIndicator.options.params.ranges,
+        6,
+        'We should be able to update VBP params with update(), #17007.'
```
Comment (kamil-musialowski) [inline samples/unit-tests/indicator-volume-by-price/recalculations/demo.js:166]: The test looks absolutely fine, just two minor suggestions:

- Maybe we also should check for the `volumeSeriesData.length` since it was causing the problem?
`volumeSeriesData.length === VBPIndicator.options.params.ranges` should do the job.

- I would suggest changing the description to something more consistent with other tests, i.e:
"VBP params should be updated after update(), #17007"

**Review by kamil-musialowski — CHANGES_REQUESTED** [review]
Other than a one small comment regarding the test, everything looks good to me!

**Review by pawelfus — CHANGES_REQUESTED** [review]
Please, investigate the other solution first (without adding a new event)

**Review by pawelfus — APPROVED** [review]
Nice, thanks!

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
