### PR TITLE
bugfix/17358-heatmap-border-properties

### LINKED ISSUE #17358: Heatmap borderWidth and borderColor properties missing in API documentation
#### Expected behaviour
Add `borderWidth` and `borderColor` documentaiton to [the API](https://api.highcharts.com/highcharts/series.heatmap)

#### Actual behaviour
Properties are correctly applied to the chart but they are missing in API docs.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/j5dL1fw0/
#### Product version
 Highcharts JS v10.1.0 (2022-04-29)

### PR DESCRIPTION
**Pull request by mfilipiec**
Fixed #17358, missing heatmap border width and color information in API

### CODE REVIEW

File: ts/Series/Heatmap/HeatmapSeries.ts [hunk 1]
```diff
@@ -119,7 +119,12 @@ class HeatmapSeries extends ScatterSeries {
         animation: false,
 
         /**
-         * The border radius for each heatmap item.
+         * The border radius for each heatmap itemdvxv. Border width and color
```
Comment (raf18seb) [inline ts/Series/Heatmap/HeatmapSeries.ts:122]: "itemdvxv"?

Comment (raf18seb) [inline ts/Series/Heatmap/HeatmapSeries.ts:122]: Shorter and sounds better IMO:
```
The border's width and color can be set in marker options.
```

The `plotOptions.heatmap.marker.lineWidth` path is not necessary because you added reference to it in the `@see` section.

File: ts/Series/Heatmap/HeatmapSeries.ts [hunk 2]
```diff
@@ -119,7 +119,12 @@ class HeatmapSeries extends ScatterSeries {
...
+         * you can set in marker: plotOptions.heatmap.marker.lineWidth
+         * plotOptions.heatmap.marker.lineColor
+         *
+         * @see [lineWidth](#plotOptions.heatmap.marker.lineWidth)
+         * @see [lineColor](#plotOptions.heatmap.marker.lineColor)
```
Comment (raf18seb) [inline ts/Series/Heatmap/HeatmapSeries.ts:127]: Please sort it alphabetically

**Review by raf18seb — CHANGES_REQUESTED** [review]
I have few comments, see below

**Comment by TorsteinHonsi** [comment]
@mfilipiec Please attend to Rafael's comments.

File: ts/Series/Heatmap/HeatmapSeries.ts [hunk 3]
```diff
@@ -120,6 +120,10 @@ class HeatmapSeries extends ScatterSeries {
 
         /**
          * The border radius for each heatmap item.
+         * The border's color and width can be set in marker options.
```
Comment (raf18seb) [inline ts/Series/Heatmap/HeatmapSeries.ts:123]: One more thing: please do not break lines in one paragraph, see [style guidelines](https://github.com/highcharts/highcharts/blob/master/repo-guidelines.md#style-guide)

**Review by raf18seb — CHANGES_REQUESTED** [review]

**Review by raf18seb — APPROVED** [review]
Thanks!
