### PR TITLE
bugfix/13898-gantt-scroll-break

### LINKED ISSUE #13898: Gantt- Collapsible subtask not working properly with scrollbar.
#### Expected behaviour
After clicking on the Design row and collapsing the subtasks, there should be still 4 rows.
The scroll should work smooth, like scrolling without collapsing the subtasks.

#### Actual behaviour
After clicking on the Design row and collapsing the subtasks, there are 3 rows.
The scroll is not working properly.

#### Live demo with steps to reproduce
https://jsfiddle.net/a7uwqjpc/19/

#### Product version
Highcharts Gantt JS v8.1.2 (2020-06-16)

#### Affected browser(s)
All

### PR DESCRIPTION
**Pull request by KacperMadej**
Fixed #13898, collapsible subtask were not working properly with scrollbar.

### CODE REVIEW

**Comment by KacperMadej** [comment]
Breaks are now calculated for the data range fixing `toValue` and `toPixels` functions results for out-of-visible range input.

This PR is also attempting to close #20984 

There's an event (`pointOutsideOfBreak`) that is no longer valid nor needed to achieve any documented functionality as far as I can tell. Normally, removing a documented option would be a breaking change but since that event was wrongly documented I would argue that this can be removed as a part of documentation clarification.

File: samples/highcharts/axisbreak/break-repeated/demo.js [hunk 1]
```diff
@@ -19,7 +19,7 @@ Highcharts.chart('container', {
         gapSize: 1,
         data: (function () {
             const data = [];
-            for (let i = 0; i < 30; i = i + 1) {
+            for (let i = 0; i <= 30; i = i + 1) {
```
Comment (MarkusBarstad) [inline samples/highcharts/axisbreak/break-repeated/demo.js]: I know you didn't write it, but why not `i++` here? 🤔

File: ts/Core/Axis/TreeGrid/TreeGridTick.ts [hunk 2]
```diff
@@ -517,20 +518,63 @@ class TreeGridTickAdditions {
...
+                }
+
+                axis.setExtremes(
+                    correctFloat(newMinVal),
+                    correctFloat(newMaxVal),
+                    false,
+                    false,
+                    { trigger: 'toggleCollapse' }
+                );
+            }
```
Comment (MarkusBarstad) [inline ts/Core/Axis/TreeGrid/TreeGridTick.ts:565]: In regards to `axis.treeGrid`, `axis.dataMin`, and `axis.tickmarkOffset`, they are referred to multiple times. Maybe we should create local variables out of them to limit property lookup time on the axis object? 🤔

**Review by MarkusBarstad — APPROVED** [review]
Awesome work! 🚀 


I have tested: 
- Scrolling works great now, the original issue regarding rows dissappearing seems solved
- Gantt demos seems to function fine
- Breaks too (have not tested events since we have a unit-test for this and it seems happy)

One thing to note (could very well be outside the scope of this PR):
Toggling the scrollbar with items hidden can sometimes lead to different point heights: https://jsfiddle.net/mkb93/s2qn8eg6/


Not sure if it matters.

File: samples/highcharts/axisbreak/break-repeated/demo.js (hunk 1 above)
Comment (KacperMadej) [reply samples/highcharts/axisbreak/break-repeated/demo.js]: Good catch 👍 `i++` is the better choice.
I missed that this is a demo and not a test.

File: ts/Core/Axis/TreeGrid/TreeGridTick.ts (hunk 2 above)
Comment (KacperMadej) [reply ts/Core/Axis/TreeGrid/TreeGridTick.ts:565]: Shorter lines and more readable code are important, so I'll try to shorten the code a bit. Local variables take more memory, but those changes are neglectable memory- and performance-wise.

BTW: `collapse` and `expand` do not follow the same logic as `toggleCollapse`, which is not great, but there's a room for refactor for those repetitive functions. I'm not convinced this PR should refactor and resolve this.

**Comment by KacperMadej** [comment]
Toggling scrollbar wasn't working before either, but I will fix it. A workaround could be to set chart `height` to `null` before the yAxis is updated. Demo: https://jsfiddle.net/BlackLabel/ejmuLox7/1/
The fix might not work for every case, but I tested relevant chart configs and seems ok.

**Review by TorsteinHonsi — APPROVED** [review]
Thanks, great work!
