### PR TITLE
Fixed ScatterSeries with Boost shows incorrect values in tooltip

### LINKED ISSUE #20621: Scatter with Boost shows incorrect values in tooltip
#### Actual behaviour
Tooltip shows incorrect x/y values for ceratin points in boosted charts.

#### Live demo with steps to reproduce
Hover over the points in top right corner:
https://jsfiddle.net/BlackLabel/ou9y2wr1/

#### Product version
HC Core 11.3.0 + Boost

#### Internal note
Last working version 11.2.0, broken in 11.3.0
Bisected to 6136c18

### LINKED ISSUE #21815: Zooming in X direction in scatter chart with boost mode does not show the correct points
#### Conditions
Scatter chart with boost mode enabled, and **at least 300 points**

#### Expected behaviour

When zooming in X direction, the points showed should be the ones included in the zoom range

#### Actual behaviour
The points showed are always the first points of the serie

#### Live demo with steps to reproduce
[https://jsfiddle.net/nfkbudm6/4/](https://jsfiddle.net/nfkbudm6/4/)

1. Zoom between the range 40-60 in the X axis
2. Mouse over the points to show the tooltip
3. The points displayed are not in the range 40-60, they are the first points of the serie

#### Product version
**11.4.8**
Bug is not present in 11.2.0, and is present in 11.3.0

### PR DESCRIPTION
**Pull request by Eskils**
Fixed #21815, scatter series with Boost showed incorrect values in tooltip when zooming

---

Closes #20621.
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208290826973737
  - https://app.asana.com/0/0/1206590827055050

### CODE REVIEW

**Comment by Eskils** [comment]
I’m not sure why the new unit test fails in Cypress. It also fails locally for `npx gulp test --tests unit-tests/boost/tooltip` (Headful and Headless). However the unit test works as intended in Chrome and Safari when run normally.

Are the tests configuring something differently that I need to take into consideration?

**Comment by bre1470** [comment]
@Eskils Very likely as in karma all modules and tests get loaded in one big session.

File: samples/unit-tests/boost/tooltip/demo.js [hunk 1]
```diff
@@ -40,3 +40,76 @@ QUnit.test('Tooltip on a boosted chart with categories', function (assert) {
...
+    'Scatter with boost should show correct values in tooltip (#20621)',
+    function (assert) {
+
+        Highcharts.addEvent(Highcharts.Series, 'setOptions', e => {
+            const series = e.target;
+            const yAxis = series.chart.axes[1];
+            yAxis.treeGrid = false;
+        });
+
+        var chart = Highcharts.chart('container', {
```
Comment (MarkusBarstad) [inline samples/unit-tests/boost/tooltip/demo.js:54]: Probably does not matter much if at all but `const chart`" is more appropriate since `chart` is not reassigned within the scope and this allows the engine to optimize around that. 

(I know there is tons of `var chart` in the tests but iirc we are moving away from it)

**Review by MarkusBarstad — COMMENTED** [review]
Good job, LGTM, just a single nitpick in the unit-test! 🚀 

And a note on your PR text: 
Afaik the first line of the PR text is put into the changelog, but not anything below 🤔 

Idk what the correct approach here is but in those cases I suspect we must condense it to a single line i.e. "Fixed #issue1, #issue2" and try to describe both cases in that line.

**Comment by Eskils** [comment]
Thank you for pointing that out. I changed the unit-test and PR description

**Review by MarkusBarstad — APPROVED** [review]
Good job!

**Review by KacperMadej — APPROVED** [review]
Looks good.

File: ts/Extensions/Boost/BoostSeries.ts [hunk 2]
```diff
@@ -874,17 +874,29 @@ function getPoint(
         return boostPoint as BoostPointComposition;
     }
 
-    const xData = (
+    const isScatter = series.type === 'scatter',
```
Comment (TorsteinHonsi) [inline ts/Extensions/Boost/BoostSeries.ts:877]: By using the `is` function, we ensure inherited series types are covered.

```suggestion
    const isScatter = series.is('scatter'),
```

File: ts/Extensions/Boost/BoostSeries.ts [hunk 3]
```diff
@@ -874,17 +874,29 @@ function getPoint(
...
+                series.getColumn('x', true) :
+                void 0) ||
             (series.getColumn('x').length ? series.getColumn('x') : void 0) ||
             seriesOptions.xData ||
             series.getColumn('x', true) ||
             false
         ),
+        yData = (
+            series.getColumn('y', true) ||
+            series.getColumn('y') ||
```
Comment (TorsteinHonsi) [inline ts/Extensions/Boost/BoostSeries.ts:889]: This condition is probably redundant, because if procesed data is not available, `series.getColumn` will return the unprocessed. Don't take my word for it though, it should be tested.
```suggestion
            series.getColumn('y', true)
```

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks!

File: ts/Extensions/Boost/BoostSeries.ts (hunk 3 above)
Comment (Eskils) [reply ts/Extensions/Boost/BoostSeries.ts]: Based on inspection of the code and testing, your assumption seems correct. 
I have changed this – thank you.

**Review by TorsteinHonsi — APPROVED** [review]
