### PR TITLE
bugfix/23087-series-options-keyed-vals-not-on-boost-point

### LINKED ISSUE #23087: A data point object is missing a value mapped by series.keys property under boost mode
#### Expected behaviour

A data point object should have the value mapped by the [series.keys](https://github.com/highcharts/highcharts/issues/14834) properties regardless of whether boost mode is applied or not.  I'm trying to access this value inside the [series.tooltip.pointFormatter](https://api.highcharts.com/highcharts/series.scatter.tooltip.pointFormat) callback to produce a custom tooltip.

#### Actual behaviour

A data point object does not have the value once the chart goes into boost mode.

#### Live demo with steps to reproduce

This is a simplified version of the chart I'm trying to create.
It works with Highcharts version 12.0.2:

https://jsfiddle.net/ktakahashimtb/0rqnusf6

Image

It no longer works with version 12.1.0 and after:

https://jsfiddle.net/ktakahashimtb/gqzuceLa

Image

#### Product version
Highcharts Core.
Version 12.1.0 and later.

#### Affected browser(s)

Chrome, Firefox, Edge, Safari

### PR DESCRIPTION
**Pull request by MarkusBarstad**
Fixed #23087, `series.options.keys` properties did not exist on boost points.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1210330657027495

### CODE REVIEW

File: ts/Extensions/Boost/BoostSeries.ts [hunk 1]
```diff
@@ -913,16 +914,35 @@ function getPoint(
...
+        seriesOptions.keys &&
+        data && (
+            seriesOptions.keys.length || 0
+        ) > 2
+    ) {
+        const keys = seriesOptions.keys;
+        let keysIndex = (keys.length || 0);
+
+        // Don't reassign X and Y properties as they're already handled above
+        while (--keysIndex > 1) {
```
Comment (magdalena-gut) [inline ts/Extensions/Boost/BoostSeries.ts]: What about changing this to a `for` loop for better readability?🤔

**Review by magdalena-gut — CHANGES_REQUESTED** [review]

File: ts/Extensions/Boost/BoostSeries.ts [hunk 2]
```diff
@@ -913,16 +914,38 @@ function getPoint(
...
                 )[boostPoint.i],
-            xData ? xData[boostPoint.i] : void 0
+            xData ? xData[pointIndex] : void 0
         ) as BoostPointComposition;
 
+    if (
+        isScatter &&
+        seriesOptions.keys &&
+        data && (
+            seriesOptions.keys.length || 0
```
Comment (magdalena-gut) [inline ts/Extensions/Boost/BoostSeries.ts]: keys are already checked to exist so I guess `|| 0` is not necessary

File: ts/Extensions/Boost/BoostSeries.ts [hunk 3]
```diff
@@ -913,16 +914,38 @@ function getPoint(
...
+        ) > 2
+    ) {
+        const keys = seriesOptions.keys;
+
+        // Don't reassign X and Y properties as they're already handled above
+        for (
+            let keysIndex = (keys.length || 1) - 1;
```
Comment (magdalena-gut) [inline ts/Extensions/Boost/BoostSeries.ts]: `|| 1` not necessary as `key.length` already > 2

File: ts/Extensions/Boost/BoostSeries.ts [hunk 4]
```diff
@@ -913,16 +914,38 @@ function getPoint(
...
+            keysIndex > 1;
+            keysIndex--
+        ) {
+            (point as any)[(keys[keysIndex] as any)] = (
```
Comment (magdalena-gut) [inline ts/Extensions/Boost/BoostSeries.ts]: casting `keys[keysIndex]` and `data[pointIndex]` seems to not necessary

**Review by magdalena-gut — CHANGES_REQUESTED** [review]
Spotted a few minor things 🙈

**Comment by MarkusBarstad** [comment]
Thank you for good feedback, @magdalena-gut ! 

Note that I still had to cast `data` :grimacing: (but was able to avoid casting `data[pointIndex]` as you suggested!)

**Review by magdalena-gut — APPROVED** [review]
LGTM!

**Comment by MarkusBarstad** [comment]
Oh, my bad @TorsteinHonsi , I didn't consider x/y, just additional keys - should be simple enough to change.

**Comment by MarkusBarstad** [comment]
Hey @TorsteinHonsi keys seem correct now: https://jsfiddle.net/mkb93/t9w8bgop/

x and y can have any position, and so can any other key
