### PR TITLE
bugfix/13136-tickAmount-small-chart-height

### LINKED ISSUE #13136: tickAmount don't works when chart size is small
#### Expected behaviour
tickAmount working.

#### Actual behaviour
tickAmount don't changes nothing.

#### Live demo with steps to reproduce
https://jsfiddle.net/bsqn1v0u/1/

See how there's no 3 ticks, but only 2. But if you change the height to 400px you will get 3 ticks (or whatever amount you put, like 100 ticks, so is not a density problem).

#### Product version
Latest

#### Affected browser(s)
Chrome

### PR DESCRIPTION
**Pull request by karolkolodziej**
Fixed #13136, couldn't set `yAxis.tickAmount` when the chart size was small.

~~Fixed #13136, didn't able to set the tick amount when the chart size was small.~~

### CODE REVIEW

File: ts/parts/Axis.ts [hunk 1]
```diff
@@ -5794,11 +5794,11 @@ class Axis implements AxisComposition {
         var axis: Highcharts.Axis = this as any,
             options = this.options,
             tickAmount = options.tickAmount,
-            tickPixelInterval = options.tickPixelInterval;
+            tickPixelInterval = options.tickPixelInterval as number;
```
Comment (TorsteinHonsi) [inline ts/parts/Axis.ts:5797]: We should leave this as `any` for now. Later on, we will fix typing for the options (using Partial and DeepPartial), so that this option is always a number.
