### PR TITLE
bugfix/23238-drilldown-break

### LINKED ISSUE #23238: Map series breaking on update
#### Expected behaviour
Apply any type of update to the map series and be able to drilldown/up after

#### Actual behaviour
After applying the update and drilling down to next level the map breaks

#### Live demo with steps to reproduce
1. Drilldown once to any place
2. Change opacity using the Button at the bottom.
3. Drilldown again to any place.
4. Scroll OUT using the mouse wheel.

You will see that the map will show broken data labels, both the 3rd level of drilldown and other polygons from 2nd level.

https://jsfiddle.net/zncLsmdh/1/

#### Product version
Maps '12.1.2'

### PR DESCRIPTION
**Pull request by hubertkozik**
Fixed #23238, preserved drilldown levels after map series updates.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1210653818709580

### CODE REVIEW

File: samples/unit-tests/maps/drilldown/demo.js [hunk 1]
```diff
@@ -591,4 +591,164 @@ QUnit.test(
...
+                );
+            }, duration * 14);
+
+            TestUtilities.lolexRunAndUninstall(clock);
+        } finally {
+            TestUtilities.lolexUninstall(clock);
+
+            // Clear cache for other tests
+            delete alTopology.objects.default['hc-decoded-geojson'];
+            delete usTopology.objects.default['hc-decoded-geojson'];
```
Comment (KacperMadej) [inline samples/unit-tests/maps/drilldown/demo.js]: Is this really clearing cache? Playwright fetches the maps from installed Map Collection package via node_modules AFAIK. If this is needed maybe it should be part of some after- or before- staging for tests?

File: ts/Extensions/Drilldown/Drilldown.ts [hunk 2]
```diff
@@ -665,12 +672,16 @@ class ChartAdditions {
 
                 if (level.levelNumber === levelToRemove) {
                     level.levelSeries.forEach((series): void => {
+                        const levelNumber = pick(
```
Comment (KacperMadej) [inline ts/Extensions/Drilldown/Drilldown.ts]: `??` is prefered over `pick`

File: ts/Extensions/Drilldown/Drilldown.ts [hunk 3]
```diff
@@ -560,6 +562,10 @@ class ChartAdditions {
                 series.options.colorIndex = series.colorIndex;
                 series.options._levelNumber =
                     series.options._levelNumber || levelNumber; // #3182
+                series.userOptions._levelNumber = (
```
Comment (KacperMadej) [inline ts/Extensions/Drilldown/Drilldown.ts]: Is `||` safe? Should `0` be skipped?
Also in general, `||=` / `??=` are shorter.

**Review by KacperMadej — CHANGES_REQUESTED** [review]
📃 If you could add internal doclet with description for `_levelNumber` it would be helpful for future maintenance - at least verifying if generated description is ok would be a great starting point.

🐛 Tested on the OP's demo with local (compile on demand) code after the fix (does not happen on the current release) - https://jsfiddle.net/zncLsmdh/1/

- zoom twice (e.g. Texas > Brewster): 1 lvl labels blink like:
Image

File: samples/unit-tests/maps/drilldown/demo.js (hunk 1 above)
Comment (hubertkozik) [reply samples/unit-tests/maps/drilldown/demo.js]: Deleted.

File: ts/Extensions/Drilldown/Drilldown.ts (hunk 2 above)
Comment (hubertkozik) [reply ts/Extensions/Drilldown/Drilldown.ts]: Fixed.

File: ts/Extensions/Drilldown/Drilldown.ts (hunk 3 above)
Comment (hubertkozik) [reply ts/Extensions/Drilldown/Drilldown.ts]: Fixed.

**Review by KacperMadej — APPROVED** [review]
Great 🎉👍

I got bamboozled for a bit by the OP's demo but 3rd drilldown level is hardcoded to Baldwin County, Alabama, so all is working fine.

**Review by TorsteinHonsi — COMMENTED** [review]
Thanks!

Just a question about the `userOptions` change  - can we avoid it? I mostly consider reading `userOptions` an antipattern. The general design goal is that `series.options` always should be up to date. There are some cases where I don't see a good alternative to reading `userOptions` though, but I'm wondering if it is necessary in this case?

**Comment by hubertkozik** [comment]
Good point, I removed `userOptions` reads/writes for this fix. `_levelNumber` is now sourced from `series.options` only, and I added a `Series.update` hook to preserve `_levelNumber` across updates when it isn't explicitly provided.

**Review by TorsteinHonsi — APPROVED** [review]
