### PR TITLE
bugfix/12834-hidden-series-wrong-extremes

### LINKED ISSUE #12834: Highstock: trying to move the scrollbar when series are hidden and xAxis min and max are set breaks the min and max
#### Expected behaviour

Nothing should happen when a user try to move the scrollbar and no series is visible.

#### Actual behaviour

If a min and a max are set for the x axis and all the series are not visible, trying to move the scrollbar breaks the min and max.

#### Live demo with steps to reproduce
https://codepen.io/Korbraan/pen/jOEXoRW

Hide the series with the button and then try to move the scrollbar.

#### Product version
Highstock 6.0.3+

#### Affected browser(s)
Firefox, Opera, Chrome, ...

### PR DESCRIPTION
**Pull request by sebastianbochan**
Fixed #12834, hidden series applied wrong extremes on X axis when scrolling.

~~Fixed #12834, hidden series applied wrong extremes on xaxis when scroll.~~

### CODE REVIEW

**Comment by sebastianbochan** [comment]
Will debug it.

File: ts/parts/ScrollbarAxis.ts [hunk 1]
```diff
@@ -224,7 +235,9 @@ class ScrollbarAxis {
         addEvent(AxisClass, 'afterGetOffset', function (): void {
             var axis = this as ScrollbarAxis,
                 index = axis.horiz ? 2 : 1,
-                scrollbar = axis.scrollbar;
+                scrollbar = axis.scrollbar,
+                axisMin = pick(axis.options.min, axis.min as any),
+                axisMax = pick(axis.options.max, axis.max as any);
```
Comment (pawelfus) [inline ts/parts/ScrollbarAxis.ts]: I don't see these values used in this scope - is that necessary?

**Comment by TorsteinHonsi** [comment]
Awaiting @pawelfus' approval
