### PR TITLE
bugfix/23662-boost-threshold

### LINKED ISSUE #23662: BoostThreshold: 0 does not disable Boost module as documented
#### Expected behaviour
Setting boostThreshold to 0 on a series should disable the Boost module for that series, according to the API documentation:

`To disable boosting on the series, set the boostThreshold to 0. Setting it to 1 will force boosting.`
API: https://api.highcharts.com/highcharts/plotOptions.series.boostThreshold

Therefore, the series should render using the standard SVG renderer, and series.boosted should be false.

#### Actual behaviour
When boostThreshold is set to 0, the series is still boosted.
The property series.boosted returns true, and the series is rendered via the Boost module.

The behavior suggests that the Boost module treats boostThreshold: 0 as threshold = 0 (always boost) instead of as “disable boost”.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/vp8wq1z3/

#### Product version
Highcharts 12.4.0

#### Affected browser(s)
All

### PR DESCRIPTION
**Pull request by KamilKubik**
Fixed #23662, `boostThreshold` 0 did not disable boost as documented

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1211586338466106

### CODE REVIEW

File: ts/Extensions/Boost/BoostSeries.ts [hunk 1]
```diff
@@ -781,23 +788,32 @@ function hasExtremes(
...
-            // Defined (and required) xAxis extremes
-            (!checkX ||
-                (isNumber(xAxis.min) && isNumber(xAxis.max))
-            ) &&
-            // Defined (e.g. heatmap) colorAxis extremes
-            (!colorAxis ||
-                (isNumber(colorAxis.min) && isNumber(colorAxis.max))
-            );
+    return (
+        dataLength > threshold &&
```
Comment (hubertkozik) [inline ts/Extensions/Boost/BoostSeries.ts]: If I understand correctly, this line can lead to regression, because we want to enable boost from the given threshold. Shouldn't be here `>=`?

Comment (KamilKubik) [reply ts/Extensions/Boost/BoostSeries.ts]: I've left the condition as it was before, but I agree that we should always check for `>=`, good catch, changed.
