### PR TITLE
bugfix/15752-parallel-coordinates-arearange

### LINKED ISSUE #15752: The arearange series isn't working in parallel coordinates
#### Expected behaviour
Let's consider this arearange data:
```js
data: [
      [23, 25],
      [-1, -0.5],
      [1.5, 4],
      [1.5, 5],
      [4, 5]
]
```
The arearange series should be displayed like this:

image

#### Actual behaviour
With the above data, the arearange series is displayed incorrectly:
image

To display it correctly, we need to correct the data - calculate the `high` value based on the first yAxis scale:
```js
data: [
      [23, 25],
      [-1, 23.5],
      [1.5, 25],
      [1.5, 26],
      [4, 24]
]
```

#### Live demo with steps to reproduce
Real data, not working: https://jsfiddle.net/BlackLabel/qobuj3tp/
Corrected data, but obviously it shouldn't work like that: https://jsfiddle.net/BlackLabel/kmgh8fad/

#### Product version
Highcharts 9.1.0

### PR DESCRIPTION
**Pull request by K009**
Fixed #15752, arearange didn’t work in parallel coordinates.

### CODE REVIEW

File: ts/Series/AreaRange/AreaRangeSeries.ts [hunk 1]
```diff
@@ -284,14 +286,28 @@ class AreaRangeSeries extends AreaSeries {
...
+                } else {
+                    point.plotHigh = yAxis.translate(
+                        series.dataModify ?
+                            series.dataModify.modifyValue(high) : high,
+                        0 as any,
+                        1 as any,
+                        0 as any,
+                        1 as any
+                    );
+                }
```
Comment (raf18seb) [inline ts/Series/AreaRange/AreaRangeSeries.ts:309]: Repeated code. The only difference here is `yAxis` used, so I think you could simplify it to a simple variable:
```js
const yAxis = isParallelCor ? chart.yAxis[i] : series.yAxis;
```

File: ts/Series/AreaRange/AreaRangeSeries.ts [hunk 2]
```diff
@@ -268,13 +268,15 @@ class AreaRangeSeries extends AreaSeries {
      */
     public translate(): void {
         const series = this,
-            yAxis = series.yAxis;
+            yAxis = series.yAxis,
+            chart = series.chart;
```
Comment (raf18seb) [inline ts/Series/AreaRange/AreaRangeSeries.ts:272]: You're using `chart` variable in 2 places only.

If you'd like to keep your variable, then it's a good practice to use the smallest possible scope (block scope instead of function scope). (the same with `yAxis` variable - scope could be reduced)
If you don't have many characters in a line (less than 80), then you don't need to declare a `chart` variable at all.

Your call which one you decide :)

File: samples/unit-tests/chart/parallel-coordinates-updates/demo.js [hunk 3]
```diff
@@ -145,3 +145,71 @@ QUnit.test('Update parallel coordinates plot', function (assert) {
...
+    const firstAxisMin = chart.yAxis[0].dataMin,
+        firstAxisMax = chart.yAxis[0].dataMax,
+        thirdAxisMin = chart.yAxis[2].dataMin,
+        thirdAxisMax = chart.yAxis[2].dataMax;
+
+    assert.deepEqual(23, firstAxisMin, '1st yAxis min should be 23.');
+    assert.deepEqual(25, firstAxisMax, '1st yAxis max should be 25.');
+
+    assert.deepEqual(1.5, thirdAxisMin, '3rd yAxis min should be 1.5.');
+    assert.deepEqual(4, thirdAxisMax, '3rd yAxis max should be 4.');
```
Comment (raf18seb) [inline samples/unit-tests/chart/parallel-coordinates-updates/demo.js:176]: When comparing numbers, use `assert.strictEqual`.

Also, it's better to use universal values like:
```js
assert.strictEqual(
    series.points[0].low, // is it low? I don't remember but you'll know
    firstAxisMin,
    ....
);
```

File: samples/unit-tests/chart/parallel-coordinates-updates/demo.js [hunk 4]
```diff
@@ -145,3 +145,71 @@ QUnit.test('Update parallel coordinates plot', function (assert) {
         'After chart update parallelInfo.counter has correct value (#10081).'
     );
 });
+
+// Calculate yAxis extremes based on the range series points as well (#15752)
+QUnit.test('Take range series points into account while calculating yAxis extremes (#15752)', function (assert) {
```
Comment (raf18seb) [inline samples/unit-tests/chart/parallel-coordinates-updates/demo.js:150]: Please do not exceed 80 characters length

File: samples/unit-tests/chart/parallel-coordinates-updates/demo.js [hunk 5]
```diff
@@ -145,3 +145,71 @@ QUnit.test('Update parallel coordinates plot', function (assert) {
...
+            chart.yAxis[i].translate(
+                series.dataModify ?
+                    series.dataModify.modifyValue(point.high) : point.high,
+                0,
+                1,
+                0,
+                1
+            ),
+            point.plotHigh,
+            "PlotHigh value should be calculated based on the point's yAxis."
```
Comment (raf18seb) [inline samples/unit-tests/chart/parallel-coordinates-updates/demo.js:212]: Double quote

File: samples/unit-tests/chart/parallel-coordinates-updates/demo.js [hunk 6]
```diff
@@ -145,3 +145,71 @@ QUnit.test('Update parallel coordinates plot', function (assert) {
...
+
+    const series = chart.series[0];
+    series.points.forEach(function (
+        point,
+        i
+    ) {
+        assert.deepEqual(
+            chart.yAxis[i].translate(
+                series.dataModify ?
+                    series.dataModify.modifyValue(point.high) : point.high,
```
Comment (raf18seb) [inline samples/unit-tests/chart/parallel-coordinates-updates/demo.js:205]: When writing tests, you should simplify the code as much as you can.

In core, we don't know whether a user is using `dataModify` or not. But here, in test, we know that we're not using it, so you can get rid of it

File: samples/unit-tests/chart/parallel-coordinates-updates/demo.js [hunk 7]
```diff
@@ -145,3 +145,71 @@ QUnit.test('Update parallel coordinates plot', function (assert) {
...
+            ]
+        }]
+    });
+
+    const series = chart.series[0];
+    series.points.forEach(function (
+        point,
+        i
+    ) {
+        assert.deepEqual(
```
Comment (raf18seb) [inline samples/unit-tests/chart/parallel-coordinates-updates/demo.js:202]: `deepEqual` -> `strictEqual`

File: ts/Extensions/ParallelCoordinates.ts [hunk 8]
```diff
@@ -691,8 +690,33 @@ namespace ParallelAxis {
...
             });
 
-            axis.dataMin = arrayMin(currentPoints);
-            axis.dataMax = arrayMax(currentPoints);
+            // Take into account range series points as well (#15752)
+            let min: number = NaN,
+                max: number = NaN;
+
+            currentPoints.forEach(function (point): void {
+                if (Array.isArray(point)) {
```
Comment (raf18seb) [inline ts/Extensions/ParallelCoordinates.ts:698]: In Highcharts, we're using `Highcharts.isArray` (from Utilities) instead of `Array.isArray`

File: ts/Extensions/ParallelCoordinates.ts [hunk 9]
```diff
@@ -691,8 +690,33 @@ namespace ParallelAxis {
...
+                    max = arrayMax(point);
+                    min = arrayMin(point);
+                } else {
+                    return;
+                }
+            });
+
+            if (
+                !Array.isArray(arrayMin(currentPoints)) ||
+                !Array.isArray(arrayMax(currentPoints))
```
Comment (raf18seb) [inline ts/Extensions/ParallelCoordinates.ts:708]: Same as above (Array.isArray)

File: ts/Extensions/ParallelCoordinates.ts [hunk 10]
```diff
@@ -691,8 +690,33 @@ namespace ParallelAxis {
...
+            let min: number = NaN,
+                max: number = NaN;
+
+            currentPoints.forEach(function (point): void {
+                if (Array.isArray(point)) {
+                    max = arrayMax(point);
+                    min = arrayMin(point);
+                } else {
+                    return;
+                }
```
Comment (raf18seb) [inline ts/Extensions/ParallelCoordinates.ts:703]: Is this empty return necessary here? `forEach` returns `undefined` by definition. Is TS rude here again?

File: samples/unit-tests/chart/parallel-coordinates-updates/demo.js [hunk 11]
```diff
@@ -145,3 +145,71 @@ QUnit.test('Update parallel coordinates plot', function (assert) {
...
+
+    assert.deepEqual(23, firstAxisMin, '1st yAxis min should be 23.');
+    assert.deepEqual(25, firstAxisMax, '1st yAxis max should be 25.');
+
+    assert.deepEqual(1.5, thirdAxisMin, '3rd yAxis min should be 1.5.');
+    assert.deepEqual(4, thirdAxisMax, '3rd yAxis max should be 4.');
+});
+
+// Calculate plotHigh value based on each yAxis scale (#15752)
+QUnit.test('Calculate plotHigh value based on each yAxis scale (#15752)', function (assert) {
```
Comment (raf18seb) [inline samples/unit-tests/chart/parallel-coordinates-updates/demo.js:180]: 80

**Review by raf18seb — CHANGES_REQUESTED** [review]
Thanks for the PR!
Except the comments below, I have one important note: when writing unit tests, please try to reuse existing tests (and use updates if necessary) instead of creating new test modules and new charts, especially if they have the same config.
It's very important for performance - we already have thousands of tests and it takes a lot of time at every commit to fire all of them.

- [ ] reuse existing tests instead of creating new ones

File: ts/Extensions/ParallelCoordinates.ts (hunk 10 above)
Comment (K009) [reply ts/Extensions/ParallelCoordinates.ts]: Not necessary 👍

File: samples/unit-tests/chart/parallel-coordinates-updates/demo.js [hunk 12]
```diff
@@ -167,49 +165,46 @@ QUnit.test('Take range series points into account while calculating yAxis extrem
     const firstAxisMin = chart.yAxis[0].dataMin,
         firstAxisMax = chart.yAxis[0].dataMax,
         thirdAxisMin = chart.yAxis[2].dataMin,
-        thirdAxisMax = chart.yAxis[2].dataMax;
+        thirdAxisMax = chart.yAxis[2].dataMax,
+        series = chart.series[0];
```
Comment (raf18seb) [inline samples/unit-tests/chart/parallel-coordinates-updates/demo.js:169]: Wouldn't it be better to declare it like this?
```js
const points = chart.series[0].points;
```

File: samples/unit-tests/chart/parallel-coordinates-updates/demo.js [hunk 13]
```diff
@@ -167,49 +165,46 @@ QUnit.test('Take range series points into account while calculating yAxis extrem
...
-    assert.deepEqual(23, firstAxisMin, '1st yAxis min should be 23.');
-    assert.deepEqual(25, firstAxisMax, '1st yAxis max should be 25.');
-
-    assert.deepEqual(1.5, thirdAxisMin, '3rd yAxis min should be 1.5.');
-    assert.deepEqual(4, thirdAxisMax, '3rd yAxis max should be 4.');
-});
+    assert.strictEqual(
+        series.points[0].low,
+        firstAxisMin,
+        '1st yAxis min should be 23.'
```
Comment (raf18seb) [inline samples/unit-tests/chart/parallel-coordinates-updates/demo.js:174]: Sorry, I forgot to point that you should also change `23` here too )(and below in other assertions). Something like this:
```The first yAxis' min should be equal to the first point's low value.```

File: samples/unit-tests/chart/parallel-coordinates-updates/demo.js [hunk 14]
```diff
@@ -167,49 +165,46 @@ QUnit.test('Take range series points into account while calculating yAxis extrem
...
+        assert.strictEqual(
             chart.yAxis[i].translate(
-                series.dataModify ?
-                    series.dataModify.modifyValue(point.high) : point.high,
+                point.high,
                 0,
                 1,
                 0,
                 1
             ),
```
Comment (raf18seb) [inline samples/unit-tests/chart/parallel-coordinates-updates/demo.js:205]: I think it's short enough now to have it in one line

**Review by raf18seb — CHANGES_REQUESTED** [review]
Few more comments, see below

File: samples/unit-tests/chart/parallel-coordinates-updates/demo.js [hunk 15]
```diff
@@ -144,4 +144,67 @@ QUnit.test('Update parallel coordinates plot', function (assert) {
         3,
         'After chart update parallelInfo.counter has correct value (#10081).'
     );
+
+    // Calculate yAxis extremes based on the range series points (#15752)
+    chart.update({
+        chart: {
+            parallelCoordinates: true
+        },
```
Comment (raf18seb) [inline samples/unit-tests/chart/parallel-coordinates-updates/demo.js:152]: Is it necessary? I think it's already in the config above

File: samples/unit-tests/chart/parallel-coordinates-updates/demo.js [hunk 16]
```diff
@@ -144,4 +144,67 @@ QUnit.test('Update parallel coordinates plot', function (assert) {
...
+        series.points[2].high,
+        thirdAxisMax,
+        '3rd yAxis max should be 4.'
+    );
+
+    // Calculate plotHigh value based on each yAxis scale (#15752)
+    series.points.forEach(function (
+        point,
+        i
+    ) {
```
Comment (raf18seb) [inline samples/unit-tests/chart/parallel-coordinates-updates/demo.js:197]: We can shorten these 4 lines into 1 line.

File: ts/Series/AreaRange/AreaRangeSeries.ts [hunk 17]
```diff
@@ -267,23 +267,28 @@ class AreaRangeSeries extends AreaSeries {
...
         ): void {
-
             const high = point.high,
                 plotY = point.plotY;
 
             if (point.isNull) {
                 point.plotY = null as any;
             } else {
+                const yAxis = series.chart.hasParallelCoordinates ?
+                    series.chart.yAxis[i] :
```
Comment (raf18seb) [inline ts/Series/AreaRange/AreaRangeSeries.ts:286]: Just a note: it's not a mistake and you can leave it as it is, but you could get rid of `i` parameter and use `point.index` (or something similar) instead ;)

**Review by raf18seb — CHANGES_REQUESTED** [review]

File: ts/Series/AreaRange/AreaRangeSeries.ts (hunk 17 above)
Comment (K009) [reply ts/Series/AreaRange/AreaRangeSeries.ts:286]: Nice one, thanks! 👍

File: samples/unit-tests/chart/parallel-coordinates-updates/demo.js (hunk 13 above)
Comment (K009) [reply samples/unit-tests/chart/parallel-coordinates-updates/demo.js]: I hope that line that's length is equal to exactly 80 won't be a problem. 😄

Comment (raf18seb) [reply samples/unit-tests/chart/parallel-coordinates-updates/demo.js]: No, 80 is good ;)

File: ts/Extensions/ParallelCoordinates.ts [hunk 18]
```diff
@@ -691,8 +691,31 @@ namespace ParallelAxis {
...
+            currentPoints.forEach(function (point): void {
+                if (isArray(point)) {
+                    max = arrayMax(point);
+                    min = arrayMin(point);
+                }
+            });
+
+            if (
+                !isArray(arrayMin(currentPoints)) ||
+                !isArray(arrayMax(currentPoints))
```
Comment (raf18seb) [inline ts/Extensions/ParallelCoordinates.ts:707]: `arrayMin` finds a minimum value in **array of values**. Here you're trying to find a minimum value of **array of arrays**

File: ts/Extensions/ParallelCoordinates.ts [hunk 19]
```diff
@@ -691,8 +691,31 @@ namespace ParallelAxis {
...
-            axis.dataMin = arrayMin(currentPoints);
-            axis.dataMax = arrayMax(currentPoints);
+            // Take into account range series points as well (#15752)
+            let min: number = NaN,
+                max: number = NaN;
+
+            currentPoints.forEach(function (point): void {
+                if (isArray(point)) {
+                    max = arrayMax(point);
+                    min = arrayMin(point);
```
Comment (raf18seb) [inline ts/Extensions/ParallelCoordinates.ts:701]: I guess you're here trying to find extremes of yAxis. What if you have more series? Only the last series' points will be really taken into consideration

**Review by raf18seb — CHANGES_REQUESTED** [review]
I think an initial bug is still not fixed. What if we have multiple series? http://jsfiddle.net/BlackLabel/x0zqL6hd/ (uncomment `yAxis` extremes config to see how the graph should look like)

My below comments should help you find the cause.

File: ts/Extensions/ParallelCoordinates.ts (hunk 19 above)
Comment (K009) [reply ts/Extensions/ParallelCoordinates.ts]: You've got a point!

File: ts/Extensions/ParallelCoordinates.ts (hunk 18 above)
Comment (K009) [reply ts/Extensions/ParallelCoordinates.ts]: Exactly, to check if any of the points is not an array (to take into account also points from series like line, column, etc.)

Comment (raf18seb) [reply ts/Extensions/ParallelCoordinates.ts]: But why using `arrayMin` for that? Can't you just do `currentPoints[0]`?

I mean, comparing arrays using `arrayMin` is semantically wrong. If you want to distinguish if the point is a value (line, column etc.) or array (range series), then you should do it differently in my opinion

Comment (raf18seb) [reply ts/Extensions/ParallelCoordinates.ts]: I took a closer look and mixed up non-range and range series: http://jsfiddle.net/BlackLabel/kLhc5j0z/

We can't use `currentPoints[0]`, it was just a blind shot, forget about it.
But I still think that we shouldn't use `arrayMin` in this specific use case. I see you're still working on it so please let me know when it's ready to review ;)

Comment (K009) [reply ts/Extensions/ParallelCoordinates.ts]: Ok, you're right. This solution to the problem with mixed non-range and range series is not the best. In fact, I've got another solution.

File: ts/Extensions/ParallelCoordinates.ts [hunk 20]
```diff
@@ -678,19 +678,24 @@ namespace ParallelAxis {
...
 
             axis.series.forEach(function (series): void {
-                if (
-                    series.visible &&
-                    defined((series.yData as any)[index as any])
-                ) {
-                    // We need to use push() beacause of null points
-                    currentPoints.push((series.yData as any)[index as any]);
+                if (series.yData && series.visible) {
+                    const y = (series.yData)[index as any];
```
Comment (raf18seb) [inline ts/Extensions/ParallelCoordinates.ts:686]: I believe this `as any` can be removed here by checking if `index` is a number type.

**Review by raf18seb — CHANGES_REQUESTED** [review]
Now it looks simple and nice ;)

Small TS comment below.
Could you add a test covering multiple series?

File: ts/Extensions/ParallelCoordinates.ts [hunk 21]
```diff
@@ -678,19 +678,28 @@ namespace ParallelAxis {
...
-                currentPoints: Array<Point> = [];
+            const index = parallelCoordinates.position;
+            let currentPoints: Array<number|null> = [];
 
             axis.series.forEach(function (series): void {
                 if (
+                    series.yData &&
                     series.visible &&
-                    defined((series.yData as any)[index as any])
+                    typeof index === 'number'
```
Comment (raf18seb) [inline ts/Extensions/ParallelCoordinates.ts:688]: Please use our Utils (`Highcharts.isNumber()`)

File: samples/unit-tests/chart/parallel-coordinates-updates/demo.js [hunk 22]
```diff
@@ -144,4 +144,117 @@ QUnit.test('Update parallel coordinates plot', function (assert) {
...
+    });
+
+    chart.addSeries({
+        type: 'arearange',
+        data: [
+            [10, 15],
+            [10, 15],
+            [-3, -1]
+        ]
+    });
```
Comment (raf18seb) [inline samples/unit-tests/chart/parallel-coordinates-updates/demo.js:228]: Some few inconsistencies:

1. You're using different data for single series tests, and new data for multiple series. Could you use one dataset? (the second preferable)
2. You're doing `chart.update()` and `chart.addSeries()` that redraw chart twice - a good pattern is to set a `redraw` flag to `false` for the first update, and redraw chart only once (better performance).
3. Why you're adding the second series using `update()`, but the third series using `addSeries`?
4. You have `type: 'arearange'` lines duplicated multiple times

Perhaps using only 2 series instead of 3 would be better (only one `addSeries` would be required). And you can set `chart: { type: 'arearange' }`.

**Review by raf18seb — CHANGES_REQUESTED** [review]
Still some polishing required, but you're close to the finish line

File: samples/unit-tests/chart/parallel-coordinates-updates/demo.js (hunk 22 above)
Comment (K009) [reply samples/unit-tests/chart/parallel-coordinates-updates/demo.js]: All right, thanks for the feedback 👍

File: ts/Extensions/ParallelCoordinates.ts [hunk 23]
```diff
@@ -678,19 +679,28 @@ namespace ParallelAxis {
...
             axis.series.forEach(function (series): void {
                 if (
+                    series.yData &&
                     series.visible &&
-                    defined((series.yData as any)[index as any])
+                    isNumber(index)
                 ) {
-                    // We need to use push() beacause of null points
-                    currentPoints.push((series.yData as any)[index as any]);
+                    const y = (series.yData)[index];
```
Comment (TorsteinHonsi) [inline ts/Extensions/ParallelCoordinates.ts:691]: Funny parentheses...

File: ts/Extensions/ParallelCoordinates.ts [hunk 24]
```diff
@@ -678,19 +679,28 @@ namespace ParallelAxis {
...
+
+                    // Take into account range series points as well (#15752)
+                    if (isArray(y)) {
+                        currentPoints = currentPoints.concat(y);
```
Comment (TorsteinHonsi) [inline ts/Extensions/ParallelCoordinates.ts:695]: According to the internet, push is way faster than concat, so I think we should refactor this. We can even combine it into one line, using the `splat` utility function:

´currentPoints.push.apply(splat(y))`

File: ts/Extensions/ParallelCoordinates.ts [hunk 25]
```diff
@@ -678,19 +679,28 @@ namespace ParallelAxis {
...
+                    } else {
+                        currentPoints.push(y);
+                    }
                 }
             });
 
+            currentPoints = currentPoints.filter((y): boolean => defined(y));
```
Comment (TorsteinHonsi) [inline ts/Extensions/ParallelCoordinates.ts:702]: Can probably be simplified to 

`currentPoints = currentPoints.filter(defined);`

Or, even safer and probably as efficient:

`currentPoints = currentPoints.filter(isNumber);`

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]

File: ts/Extensions/ParallelCoordinates.ts (hunk 25 above)
Comment (K009) [reply ts/Extensions/ParallelCoordinates.ts]: Sure, thanks for all the feedback.

**Review by raf18seb — APPROVED** [review]
Good job, thanks!!

**Review by TorsteinHonsi — APPROVED** [review]
