### PR TITLE
bugfix/15222-css-overwriting-crosshair-color

### LINKED ISSUE #15222: CSS properties overwrite the lastPrice color
#### Expected behaviour
When `styledMode: false`, the CSS properties should not overwrite the `lastPrice` element attributes.

#### Actual behaviour
When you import the stylesheet from `https://code.highcharts.com/css/highcharts.css`, CSS class `.highcharts-crosshair-thin` overwrite the `lastPrice` line color.

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/sukvqo08/
Comment/remove the stylesheet to see the difference.

#### Product version
Highstock JS v9.0.1 (2021-02-15)

#### Affected browser(s)
All

### PR DESCRIPTION
**Pull request by DJTechnoo**
Fixed #15222, CSS color class not added to `lastPrice` cross-hair.

### CODE REVIEW

File: ts/Core/Axis/Axis.ts [hunk 1]
```diff
@@ -7780,6 +7775,12 @@ class Axis {
                             dashstyle: (options as any).dashStyle
                         });
                     }
+                } else {
+                    graphic.addClass( // #15222
+                        'highcharts-crosshair highcharts-crosshair-' +
+                        (categorized ? 'category ' : 'thin ') +
+                        (options as any).className
```
Comment (karolkolodziej) [inline ts/Core/Axis/Axis.ts:7782]: When `className` does not exist, the class name looks strange: `class="highcharts-crosshair highcharts-crosshair-thin undefined"`.
I would add some condition here like `options.className ? options.className : ''` to prevent that.

**Review by pawelfus — CHANGES_REQUESTED** [review]
I'm not sure if this is a bug (#15222). No matter if styled mode or not, classnames are available anyway. Check simple demo with CSS for the background: https://jsfiddle.net/BlackLabel/me10k4wu/

To make this work the same way in styled and non-styled modes (so color does match the series color), I would consider adding related color-class (`.highcharts-color-{n}`), to match the series color-class. But I believe this should be part of #15195 🤔

**Comment by pawelfus** [comment]
Agreed on: Let's try `.highcharts-color-{n}` solution, after #15195 merge :)

**Review by pawelfus — CHANGES_REQUESTED** [review]
Looks good, thank you! 
Requesting a test :)

**Review by pawelfus — APPROVED** [review]
Thanks! 👍

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
