### PR TITLE
bugfix/22450-es5-errors

### LINKED ISSUE #22450: ES5 build fails in legacy browsers due to Unicode property escape used in regex
#### Expected behaviour
The regex is transformed correctly to be ES5 compatible.

#### Actual behaviour
The regex uses ES6+ Unicode properties, which aren't available in ES5.

#### Product version
Regression since v12.0.0

_Internal note:_ The failing regex is located in _format_ function: https://github.com/highcharts/highcharts/blob/59c06c4172494d3a0c5e266766ba37c03efe0554/ts/Core/Templating.ts#L178-L184

### PR DESCRIPTION
**Pull request by KacperMadej**
Fixed #22450, ES5 build failed in legacy browsers due to Unicode property escape used in regex

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1209061945761312

### CODE REVIEW

**Review by bre1470 — APPROVED** [review]
It does not look pretty, but it works. Looks good! 👍

Alternative for `Element.closest` check would be to add a polyfill to es5-masters if we plan to use it a lot.

File: ts/Core/Globals.ts [hunk 1]
```diff
@@ -201,9 +201,11 @@ namespace Globals {
...
             doc?.createElementNS?.(SVG_NS, 'svg') as SVGSVGElement|undefined
         )?.createSVGRect,
-        pageLang = (
-            doc?.documentElement?.closest('[lang]') as HTMLDOMElement|null
-        )?.lang,
+        // Notice: optimizing pageLang might cause ES5 build error (#22450).
+        pageLang = typeof doc?.documentElement?.closest === 'function' &&
+            (
+                doc.documentElement.closest('[lang]') as HTMLDOMElement|null
+            )?.lang,
```
Comment (TorsteinHonsi) [inline ts/Core/Globals.ts:208]: As Sophie suggests, I think we should add the polyfill in the es5-specific code instead of bogging down our main code with IE11-specific code. [Element.closest](https://caniuse.com/element-closest) has been generally supported since 2017 in modern browsers.

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
