### PR TITLE
bugfix/24442-parallel-coords-grid-lines

### LINKED ISSUE #24442: Parallel coordinates: horizontal grid lines missing when Highcharts Stock is loaded (regression v12.3.0 → v12.4.0)
#### Expected behaviour
Horizontal grid lines should render across all parallel coordinate axes, spanning the full width of the chart. This was working correctly up to and including **v12.3.0**.

#### Actual behaviour
Starting in **v12.4.0**, horizontal grid lines no longer appear on parallel coordinates charts when the Stock module is loaded (i.e. when using `highcharts/highstock` as the entry point). Grid lines are no longer drawn across the chart.

#### Live demo with steps to reproduce
https://jsfiddle.net/daju47zv/3/

**Steps to reproduce:**
1. Open the demo: horizontal grid lines are **missing** between the parallel axes
2. Change all 3 script URLs to load **v12.3.0** instead - horizontal grid lines appear correctly

#### Product version
Highcharts Stock v12.4.0 through v12.5.0 (latest tested)
Last working version: **v12.3.0**

#### Affected browser(s)
All (not browser-specific)

### PR DESCRIPTION
**Pull request by kamil-musialowski**
Fixed #24442, grid lines were not rendered on parallel axes.

### CODE REVIEW

**Review by pawelfus — CHANGES_REQUESTED** [review]
Fix the visual diffs. The fix, preferably, should be directly in the parallel coords module.

**Comment by kamil-musialowski** [comment]
Thanks @pawelfus !

I've checked the visual diffs manually, all of them are fine in real life (no gridLines). I guess, that's because all modules are loaded (Stock included) for visual diffs, hence the difference.

For the fix, my immediate idea for fixing that in Stock was because it was broken in Stock, in this exact method. I simply wanted to fix the regression. However, now that I have investigated Parallel related files, I don't see any clear (and short!) way of fixing that in this module. 
I'm afraid it would add loads of unnecessary code, therefore I would be against that idea, unless you have some clever hacks for that 🤔

File: samples/unit-tests/chart/parallel-coordinates-updates/demo.js [hunk 1]
```diff
@@ -242,4 +242,13 @@ QUnit.test('Update parallel coordinates plot', function (assert) {
         'The third yAxis\' max should be equal to the third point\'s high ' +
         'value.'
     );
+
+    const pathArray = chart.yAxis[0].ticks['8'].gridLine.pathArray;
+
+    assert.notOk(
+        pathArray[0][1] === pathArray[1][1] &&
+        pathArray[0][2] === pathArray[1][2],
```
Comment (jedrzejruta) [inline samples/unit-tests/chart/parallel-coordinates-updates/demo.js]: Isn't checking only the first elements enough? I've noticed that even without the fix, the second argument is true at all times.

**Review by jedrzejruta — APPROVED** [review]
Nice fix, not much to add 👏 

Since this problem only happens within Stock, and the fix is relatively small I'm ok with it being solved here.

File: samples/unit-tests/chart/parallel-coordinates-updates/demo.js (hunk 1 above)
Comment (kamil-musialowski) [reply samples/unit-tests/chart/parallel-coordinates-updates/demo.js]: Yes, it is true - but I decided to cover it "just in case" 😅

File: ts/Core/Chart/StockChart.ts [hunk 2]
```diff
@@ -843,18 +847,16 @@ namespace StockChart {
                 }
 
                 if (!skip) {
-                    const crossingPosName = horiz ? 'top' : 'left',
-                        crossingLenName = horiz ? 'height' : 'width';
                     if (
-                        !acrossPanes &&
                         // If the perpendicular position is set explicitly on
```
Comment (PaulDalek) [inline ts/Core/Chart/StockChart.ts:852]: Question: Is this comment still valid with the latest changes? Didn't it refer to the removed condition?

File: ts/Core/Chart/StockChart.ts [hunk 3]
```diff
@@ -722,6 +722,10 @@ namespace StockChart {
             allPerpendicularAxes = (
                 axis.isXAxis ? chart.yAxis : chart.xAxis
             ) || [],
+            crossingPosName = horiz ? 'top' : 'left',
+            crossingLenName = horiz ? 'height' : 'width',
+            hasCrossingBounds = defined(axis.options[crossingPosName]) ||
```
Comment (PaulDalek) [inline ts/Core/Chart/StockChart.ts]: You can create the `axisOptions = axis.options as AnyRecord` and use it in all occurances since the `axis.options` is used four times.

File: samples/unit-tests/chart/parallel-coordinates-updates/demo.js (hunk 1 above)
Comment (PaulDalek) [reply samples/unit-tests/chart/parallel-coordinates-updates/demo.js]: I agree with Jędrzej that checking only the x-coordinates in this case is enough, and I think that comparing y-values, even though it doesn’t do any harm, makes the test harder to read.

**Review by PaulDalek — CHANGES_REQUESTED** [review]
Great work coming up with a solution that does not use the `hasParallelCoordinates`! Only a few comments from me.

**Review by DJTechnoo — APPROVED** [review]

File: samples/unit-tests/chart/parallel-coordinates-updates/demo.js (hunk 1 above)
Comment (kamil-musialowski) [reply samples/unit-tests/chart/parallel-coordinates-updates/demo.js]: Okay okay, I'm convinced 😄

File: ts/Core/Chart/StockChart.ts (hunk 2 above)
Comment (kamil-musialowski) [reply ts/Core/Chart/StockChart.ts:852]: Hmm, even though it might be tiny bit less readable now, it still refers to the correct code.

The only change is that instead of axis.options... it points to hasCrossingBounds which is basically the same code extracted to a variable.

I think it should stay there 👍

File: ts/Core/Chart/StockChart.ts (hunk 3 above)
Comment (kamil-musialowski) [reply ts/Core/Chart/StockChart.ts]: Looks like `as AnyRecord` is needed only in one place. So I went with `const axisOptions = axis.options;` and used `as AnyRecord` once. I prefer to keep typing as tight as possible (if possible).

**Review by PaulDalek — APPROVED** [review]
Nice one, thanks!

**Review by pawelfus — APPROVED** [review]
Okay, let's try this. If any other problems pop up, we should simply make this available to other modules as discussed (eg via event).

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
