### PR TITLE
bugfix/18303-point-visibility-drillup

### LINKED ISSUE #18303: Default invisible point in the ignoreHiddenPoint: false series bugs out during drillup pie chart
#### Expected behaviour
When drilling up to the main state of the chart, which has `ignoreHiddenPoint` disabled and one of its points is with the parameter `visible: false` set, **the point is not visible, as when the chart is first rendered**.

#### Actual behaviour
When drilling down to the main state of the chart, which has `ignoreHiddenPoint` disabled and one of its points is with the parameter `visible: false` set, **the point is visible even though it is marked as disabled on the legend**.

#### Live demo with steps to reproduce

1. Drilldown to a point called _Drilldown Here_
2. Drillup to main

https://jsfiddle.net/BlackLabel/43mtrxqL/

#### Product version
Highcharts v10.3.2

### PR DESCRIPTION
**Pull request by Vazonik**
Fixed #18303, a point with `visible: false` was shown after drill-up.

### CODE REVIEW

File: ts/Extensions/Drilldown.ts [hunk 1]
```diff
@@ -1533,7 +1533,10 @@ ColumnSeries.prototype.animateDrillupTo = function (init?: boolean): void {
                         dataLabel = point.dataLabel;
 
 
-                    if (point.graphic) { // #3407
+                    if (
+                        point.graphic && // #3407
+                        point.visible // Don't show if invisible (#18303)
```
Comment (TorsteinHonsi) [inline ts/Extensions/Drilldown.ts:1538]: I didn't test this, but I think `point.visible` can be `undefined`, in which case the point is actually visible. In other parts of the code base we test for an explicit `false`:

https://github.com/highcharts/highcharts/blob/1f4eea0567fa6ba26fde40694a22441b8d52f822/ts/Core/Series/DataLabel.ts#L234

Please check if this may be the case here too.

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]

File: ts/Extensions/Drilldown.ts (hunk 1 above)
Comment (Vazonik) [reply ts/Extensions/Drilldown.ts:1538]: Thanks! From what I can see, `visible: undefined` for line and scatter chart's points works as you described, but for column and pie, they are still invisible. Moreover, in the case of the pie chart, the legend item is locked then.

Demo: https://jsfiddle.net/BlackLabel/w8zcvgbt/

Comment (TorsteinHonsi) [reply ts/Extensions/Drilldown.ts:1538]: Yes, but there's a difference between the options and the `Point` properties. Anyway, it seems that it is legit to use `point.visible` directly. See https://jsfiddle.net/highcharts/r9m56cgb/

**Review by TorsteinHonsi — APPROVED** [review]
Looks good 👍  Awaiting CI tests.
