### PR TITLE
bugfix/23566/es5-requirejs

### LINKED ISSUE #23566: Issue with loading ES5 highcharts modules through RequireJS (AMD loader) from v12
#### Expected behaviour
ES5 compiled Highcharts modules should be loaded without issue through AMD module loader like RequireJS.
As per mentioned steps and sample in [Highcharts documentation for loading files with AMD](https://www.highcharts.com/docs/getting-started/installation-with-amd-commonjs.) modules should be loaded without any errors.

#### Actual behaviour
Script error is thrown while loading ES5 compiled highcharts dependent modules such as Solid-gauge, stock, heatmap etc.. with AMD module loader RequireJS after v12.
solid-gauge.js:12  Uncaught TypeError: Cannot read properties of undefined (reading 'defaultOptions')
    at solid-gauge.js:12:1421
    at solid-gauge.js:12:5322
    at Object.execCb (require.js:1697:33)

Same sample provided in highcharts official doc is used below for reference. Same was working with v11.4.8 highcharts modules.

#### Live demo with steps to reproduce
Script error seen:
`<html>
    <head>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.7/require.js"></script>
        <script>
            require.config({
                packages: [{
                    name: 'highcharts',
                    main: 'highcharts'
                }],
                paths: {
                    // Change this to your server if you do not wish to use our CDN.
                    'highcharts': 'https://code.highcharts.com/es5',
					'highcharts-more': 'https://code.highcharts.com/es5/highcharts-more'
                }
            });
        </script>
    </head>
    <body>
        <div id="container"></div>
        <script>
            require([
                'highcharts',
				'highcharts-more',
				'highcharts/modules/solid-gauge'
            ], function (Highcharts) {
                // This function runs when the above files have been loaded.
                // Create a test chart.
                Highcharts.chart('container', {
                    series: [{
                        data: [1,2,3,4,5]
                    }]
                });
            });
        </script>
    </body>
</html>`

working code snippet: v11.4.8
`<html>
    <head>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.7/require.js"></script>
        <script>
            require.config({
                packages: [{
                    name: 'highcharts',
                    main: 'highcharts'
                }],
                paths: {
                    // Change this to your server if you do not wish to use our CDN.
                    'highcharts': 'https://code.highcharts.com/11.4.8/es5',
					'highcharts-more': 'https://code.highcharts.com/11.4.8/es5/highcharts-more'
                }
            });
        </script>
    </head>
    <body>
        <div id="container"></div>
        <script>
            require([
                'highcharts',
				'highcharts-more',
				'highcharts/modules/solid-gauge'
            ], function (Highcharts) {
                // This function runs when the above files have been loaded.
                // Create a test chart.
                Highcharts.chart('container', {
                    series: [{
                        data: [1,2,3,4,5]
                    }]
                });
            });
        </script>
    </body>
</html>`

#### Product version
after v12

#### Affected browser(s)
All

### PR DESCRIPTION
**Pull request by karolkolodziej**
Fixed #23566, the ES5 build for the AMD package was incorrect.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1211383030048804

### CODE REVIEW

File: tools/webpacks/plugins/UMDExtensionPlugin.mjs [hunk 1]
```diff
@@ -32,7 +32,8 @@ import Webpack from 'webpack';
 const HOOKS_NAME = 'Highcharts.UMDExtensionPlugin';
 
 
-const UMD_REGEXP = /(\(function webpackUniversalModuleDefinition\(root, factory\) \{\s+)(.*?)(\s+\}\)\(this, \()/su;
+const UMD_REGEXP_ES5 = /(\(function webpackUniversalModuleDefinition\(root, factory\) \{\s+)(.*?)(\s+\}\)\(this, function\(.*?\) \{)/su;
```
Comment (bre1470) [inline tools/webpacks/plugins/UMDExtensionPlugin.mjs]: You can combine both patterns without any additional code change necessary:

```ts
const UMD_REGEXP = /(\(function webpackUniversalModuleDefinition\(root, factory\) \{\s+)(.*?)(\s+\}\)\(this, (?:function)?\()/su;
```

**Comment by karolkolodziej** [comment]
> What should be the change and why that change should resolve the problem?

Webpack otuputs looks diferent for ES5 and ES6. First one uses the `function()` pattern while the second uses `()=>`.
And the `UMDExtensionPlugin` fails to match that pattern for ES5 correctly.

`npx gulp scripts` should be sufficient to run that demo locally; there are no other steps.
