### PR TITLE
bugfix/22892-packedbubble-hover-error

### LINKED ISSUE #22892: Packedbubble chart crashes when quickly hovering over the chart during it's update with `splitSeries: true`
#### Expected behaviour
The chart renders normally even when hovering over plot area and no error is logged to the console.

#### Actual behaviour
The chart crashes and an error `Cannot read properties of undefined (reading 'appendChild')` is thrown in console.

#### Live demo with steps to reproduce
The issue happens only when `layoutAlgorithm.splitSeries` is enabled.
https://jsfiddle.net/BlackLabel/u8a4Lz5m/

#### Product version
Regression since v8.2.0

_Internal note:_ unable to bisect.

### PR DESCRIPTION
**Pull request by MarkusBarstad**
Fixed #22892 , hovering a changing packed bubble series could result in error thrown.

NOTE:
- The way to trigger this issue is to hover the chart while setInterval is continuously updating the chart, triggering a console error.
- How should a unit-test for this look?
- Should we do the setInterval thing while using testController to hover about the series?

### CODE REVIEW

File: ts/Series/PackedBubble/PackedBubblePoint.ts [hunk 1]
```diff
@@ -25,6 +25,7 @@ import type PackedBubbleSeries from './PackedBubbleSeries';
 import Chart from '../../Core/Chart/Chart.js';
 import Point from '../../Core/Series/Point.js';
 import SeriesRegistry from '../../Core/Series/SeriesRegistry.js';
+import { StatesOptionsKey } from '../../Core/Series/StatesOptions';
```
Comment (goransle) [inline ts/Series/PackedBubble/PackedBubblePoint.ts:28]: Should ideally be `import type { StatesOptionsKey } ...`

File: ts/Series/PackedBubble/PackedBubblePoint.ts [hunk 2]
```diff
@@ -147,6 +148,15 @@ class PackedBubblePoint extends BubblePoint implements DragNodesPoint {
         }
     }
 
+    public setState(
+        state?: (StatesOptionsKey|''),
```
Comment (goransle) [inline ts/Series/PackedBubble/PackedBubblePoint.ts:152]: Is the `|''` part superfluous? Seem likes the StatesOptionsKey type should already include it

**Review by goransle — CHANGES_REQUESTED** [review]
Not 100% sure about the test, but I would try to set something up using [assert.async](https://qunitjs.com/api/assert/async/) and an interval. Possibly it could be manual test if QUnit or Karma doesn't like it 🤔

File: ts/Series/PackedBubble/PackedBubblePoint.ts (hunk 1 above)
Comment (goransle) [reply ts/Series/PackedBubble/PackedBubblePoint.ts:28]: (And moved up with the other type imports)

**Comment by MarkusBarstad** [comment]
Ok, @goransle , got a test! Unfortunately I had to make a seperate QUnit test. Not sure I am using `assert.async` correctly but it does not appear to cause any issues at least 🤔

**Review by goransle — APPROVED** [review]
Looks good!

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks!

About the test, `setInterval` and `setTimeout` are generally unstable in tests because we don't know for sure that the browser has enough resources to process each step. For animation tests, we use lolex, which hijacks the browser's timers and runs them in a synchronous and controlled way. See for example [3d/column-animation](https://github.com/highcharts/highcharts/blob/master/samples/unit-tests/3d/column-animation/demo.js) for how this is set up using our TestUtilities wrappers for lolex. A little disclaimer though that I am not sure how this will play with the packed bubble simulation.

**Comment by MarkusBarstad** [comment]
@TorsteinHonsi Alright, using lolex now, seems to play fine with packedbubble (simulation/animation is disabled, like the original issue demo)

The one failing test is `samples/highcharts/boost/arearange/` , I suspect its unrelated since it is not failing locally

**Review by TorsteinHonsi — APPROVED** [review]
