### PR TITLE
bugfix/13961-half-hour-timezone-ticks

### LINKED ISSUE #13961: The graph doesn't show up first few datetime x-axis values (30min to one hour)
The Chart shows incorrect x-axis after 30 mins of an hour.

Mostly doesn't work with India timezone.

#### Live demo with steps to reproduce
https://codepen.io/shabareesh/pen/jOWRRYa

Could someone please help me to solve this issue?

Thanks in advance!!

image

### PR DESCRIPTION
**Pull request by khlieng**
Fixed #13961, `datetime` axis had missing ticks when `Chart.time` had half-hour `timezone` or `timezoneOffset` set.

### CODE REVIEW

File: ts/Core/Time.ts [hunk 1]
```diff
@@ -347,7 +347,7 @@ class Time {
             if (
                 unit === 'Milliseconds' ||
                 unit === 'Seconds' ||
-                unit === 'Minutes'
+                (unit === 'Minutes' && this.getTimezoneOffset(date) % 3600000 === 0)
```
Comment (TorsteinHonsi) [inline ts/Core/Time.ts:350]: Please add a reference to the issue number - we've been struggling with this before

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
