### PR TITLE
bugfix/20048-newdataannouncer-not-announcing

### LINKED ISSUE #20048: NewDataAnnouncer not announcing
#### Expected behaviour
I would expect announcementFormatter to announce points above 10 to VoiceOver and announcer-container in the DOM.

#### Actual behaviour
Nothing is happening when a point is above 10.

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/accessibility/custom-dynamic

#### Product version
Broken since 9.3.0

#### Affected browser(s)
Chrome

### PR DESCRIPTION
**Pull request by marvin19**
Fixed #20048, `NewDataAnnouncer` was not announcing.

### CODE REVIEW

**Review by goransle — APPROVED** [review]
Looks good!

**Review by oysteinmoseng — CHANGES_REQUESTED** [review]
Nice 🎉 Could we find a way to unit test that something is added to the announce region `div`, though? Would be nice not to have to test this manually.

**Comment by TorsteinHonsi** [comment]
Pending review by @oysteinmoseng

File: samples/unit-tests/accessibility/newdataannouncer/demo.js [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+        assert.ok(
+            announcerDiv.innerHTML,
+            'The announceRegion should contain text content after adding a point'
+        );
+    }, 1);
+
+    assert.strictEqual(
+        announcerDiv.innerHTML,
+        '',
+        'The text in the announceRegion should be removed after a short while'
```
Comment (oysteinmoseng) [inline samples/unit-tests/accessibility/newdataannouncer/demo.js:51]: Should this check be moved into the 2nd setTimeout, so that it runs after the announcement text has first been added, and then removed again?

**Review by oysteinmoseng — CHANGES_REQUESTED** [review]
Nice, small question to the test only!

**Review by oysteinmoseng — APPROVED** [review]
🎉
