### PR TITLE
bugfix/16397-indicator-recalculation 

### LINKED ISSUE #16397: VBP indicator recalculates only for the first main series update
#### Expected behaviour
I expect the VBP to always follow the main series, no matter how many data updates are.

#### Actual behaviour
VBP recalculates only for the first update. The next main series data updates don't change the VBP indicator.

#### Live demo with steps to reproduce
Click the first button - VBP is recalculating.
Click the second button - VBP is **not** recalculating (but should).
Click the third button - VBP is **not** recalculating (but should).

https://jsfiddle.net/BlackLabel/t1hp89ud/

#### Product version
Highcharts Stock 9.2.2

### PR DESCRIPTION
**Pull request by karolkolodziej**
Fixed #16397, the VBP indicator was not recalculated after adding the point.

- [x] tests
- [x] ~braking change message (after reviewers approve the PR)~ no need for that, we modified internal properties
- [ ] adjust documentation (after reviewers approve the PR) #16409

### CODE REVIEW

File: ts/Stock/Indicators/VBP/VBPIndicator.ts [hunk 1]
```diff
@@ -829,10 +829,7 @@ interface VBPIndicator {
 extend(VBPIndicator.prototype, {
     nameBase: 'Volume by Price',
     nameComponents: ['ranges'],
-    bindTo: {
-        series: false,
-        eventName: 'afterSetExtremes'
-    },
+    calculateOnExtremesChagne: true,
```
Comment (pawelfus) [inline ts/Stock/Indicators/VBP/VBPIndicator.ts:832]: Change*

Would it make sense to merge somehow both properties: `calculateOn` and `calculateOnExtremesChange`?

Comment (karolkolodziej) [reply ts/Stock/Indicators/VBP/VBPIndicator.ts]: I combined them but I'm not sure if this is a correct approach.
Each one is responsible for something else and the main issue that I have with it is finding a proper name for this combined property...

**Review by bre1470 — APPROVED** [review]
Looks good! 👍

**Review by TorsteinHonsi — APPROVED** [review]
