### PR TITLE
docs/fixes

### LINKED ISSUE #12358: Simplify type links in options leafs
@TorsteinHonsi says: Make the type links in the headline blue and remove the types from the see also list. The expanded node header at the top stays the same with see also types.

### LINKED ISSUE #12363: "TS2339: Property does not exist on type" for Axis.categories
The [Highcharts.Axis class appears to have no documented `categories` property](https://api.highcharts.com/class-reference/Highcharts.Axis), even though [the Heatmap demo](https://www.highcharts.com/demo/heatmap) uses it for its tooltip formatter. That feature cannot currently be replicated using [format strings](https://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting).

#### Expected behaviour
The following snippet (taken from the heatmap demo linked above) should be considered valid by the Typescript checker.
```ts
import Highcharts from "highcharts/highcharts";

let testTooltip: Highcharts.TooltipOptions = {
    // // pointFormat can't handle categories and has no built-in category formatter
    // pointFormat:'<b>{series.xAxis.categories[this.point.x]}</b> sold <br>' +
    //             '<b>{point.value}</b> items on <br>' +
    //             '<b>{series.yAxis.categories[this.point.y]}</b>',
    formatter: function() {
        return '<b>' + this.series.xAxis.categories[this.point.x] + '</b> sold <br><b>' +
            this.point.value + '</b> items on <br><b>' + this.series.yAxis.categories[this.point.y] + '</b>';
    }
}
}
```

#### Actual behaviour
Typescript reports `TS2339: Property does not exist on type` for both `xAxis.categories` and `yAxis.categories`. 

#### Live demo with steps to reproduce
Can't provide live demo for Typescript type checking.

#### Product version
Highcharts and Highstock v7.1.1 + Online documentation

#### Affected browser(s)
No browsers, only type validation.

### LINKED ISSUE #12392: AxisOptions width is missing in documentation
#### Expected behaviour
Setting the width correctly adjusts the width of the xAxis. This allows to set 2 axes next to each other.
Argument should be documented in documentation and therefore in generated types.

#### Actual behaviour
Width is missing in documentation

#### Live demo with steps to reproduce
1. Configure chart
2. Set width in axis config 
```
{
    xAxis: [
        {
          id: 'xAxis-low',
          type: 'datetime' as 'datetime',
          min: xmin,
          max: xmin + 0.5 * (xmax - xmin),
          width: '50%',
          left: '50%',
          offset: 0,
        },
        {
          id: 'xAxis-high',
          type: 'datetime' as 'datetime',
          min: xmin + 0.5 * (xmax - xmin),
          max: xmax,
          width: '50%',
          offset: 0 
        },
    ]
}
```

#### Product version
Tested with highcharts@7.2.1

I tried to fix the documentation and set a PR but was not sure about the correct formation and there is nothing about correct documentation contribution in the CONTRIBUTING.md.

### PR DESCRIPTION
**Pull request by bre1470**
- Close #12358, Updated generator dependencies with simplified type links.
- Close #12363, Close #12392, Fixed axis doclets for categories and positioning.
- Fixed doclets for declarations.
- Fixed exporting buttons type.
- Added skip option to websearch gulp task.

### CODE REVIEW

File: ts/parts/Axis.ts [hunk 1]
```diff
@@ -1761,6 +1761,30 @@ extend(Axis.prototype, /** @lends Highcharts.Axis.prototype */{
             }
         },
 
+        /**
+         * The left position as the horizontal axis. If it's a number, it is
+         * interpreted as pixel position relative to the chart.
+         *
+         * Since Highstock 2: If it's a percentage string, it is interpreted
```
Comment (pawelfus) [inline ts/parts/Axis.ts]: `left` and `width` are supporting percentage since v5.0.13 ([changelog](https://www.highcharts.com/blog/changelog/#highstock-v5.0.13)).
