### PR TITLE
Fixed #17547, no forced boost with zoom.

### LINKED ISSUE #17547: Unable to exit boost when series contains null points.
#### Expected behaviour
When there are fewer points than `boostThreshold` chart should exit the boost module.

#### Actual behaviour
When one series contains null points, and after zooming and having fewer visible points than the `boostThreshold` the chart is still boosted.
When the null series is not visible on the chart the issue is not visible.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/no0txe2c/

#### Product version
Highcharts JS v10.2.0 (2022-07-05)

#### Affected browser(s)
All

### PR DESCRIPTION
**Pull request by bre1470**
Fixed #17547; When the `chart.zoomType` option is set, boosted rendering will not be forced as long as threshold is not reached.

### CODE REVIEW

File: ts/Extensions/Boost/Boost.ts [hunk 1]
```diff
@@ -366,7 +366,8 @@ export default Boost;
 
 /**
  * If set to true, the whole chart will be boosted if one of the series
- * crosses its threshold, and all the series can be boosted.
+ * crosses its threshold, and all the series can be boosted. If the
+ * `chart.zoomType` option is set, it will default to `false`.
```
Comment (TorsteinHonsi) [inline ts/Extensions/Boost/Boost.ts:370]: The doclet says `@default true`. If the description is right, this means the default should be `undefined`, which means an intelligent guess. The start of the description, "If set to true..." is also confusing, as it indicates that the default is not `true`.

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
In addition to the inline changes, see [Writing content for the changelog](https://github.com/highcharts/highcharts/tree/master/changelog#writing-content-for-the-changelog). Specifically, points 5, 6 and 7.

File: ts/Extensions/Boost/Boost.ts (hunk 1 above)
Comment (bre1470) [reply ts/Extensions/Boost/Boost.ts]: As the whole detection changed, I would argue that the default value is now still legit.

**Comment by bre1470** [comment]
Fixing the root issue (boost checks too early) would come a rewrite near. So I instead changed multiple conditions so that is more often checking extremes to detect range/zoom change.

**Review by TorsteinHonsi — APPROVED** [review]
