### PR TITLE
bugfix/18238-vbp-errors-improvement

### LINKED ISSUE #18238: VBP Overlay Indicator Doesn't Work After Resize
#### Expected behaviour
I expect to be able to resize browser, trigger state changes, and re-render without app crashing

#### Actual behaviour
App crashes when resizing and re-rendering VBP indicator series

#### Live demo with steps to reproduce
https://codesandbox.io/embed/highcharts-react-example-forked-9o6l9p?fontsize=14&hidenavigation=1&theme=dark

#### Product version
highcharts: 10.3.2
highcharts-react-official 3.1.0

#### Affected browser(s)
Chrome

### PR DESCRIPTION
**Pull request by kamil-musialowski**
Fixed #18238, VBP indicator was not throwing an error when volume series had no data, or didn't exist.

### CODE REVIEW

**Review by pawelfus — CHANGES_REQUESTED** [review]
Please, add the test. Apart from that looks good 👍

File: ts/Stock/Indicators/VBP/VBPOptions.d.ts [hunk 1]
```diff
@@ -42,7 +42,7 @@ export interface VBPOptions extends SMAOptions {
 
 export interface VBPParamsOptions extends SMAParamsOptions {
     ranges?: number;
-    volumeSeriesID?: string;
+    volumeSeriesID: string;
```
Comment (pawelfus) [inline ts/Stock/Indicators/VBP/VBPOptions.d.ts:45]: I'm curious about this one. This is true: to render the VbP indicator, `volumeSeriesID` must be set. The same for `linkedTo` option.

However, will that affect also `series.update({ ... });`? `volumeSeriesID` there is optional

Comment (pawelfus) [reply ts/Stock/Indicators/VBP/VBPOptions.d.ts:45]: What do you think @TorsteinHonsi ?

Comment (kamil-musialowski) [reply ts/Stock/Indicators/VBP/VBPOptions.d.ts:45]: My though process with this one was: 
Since we set [the default value](https://github.com/highcharts/highcharts/blob/d1a37ffe3a085206c6d7b42d13381e3d6d0339db/ts/Stock/Indicators/VBP/VBPIndicator.ts#L154) for `volumeSeriesID`, does it make sense to leave it as an optional property in this interface?

Comment (TorsteinHonsi) [reply ts/Stock/Indicators/VBP/VBPOptions.d.ts:45]: If TS is happy, I'm happy. The idea with `series.update()` and other update functions is that they tak `DeepPartial<SeriesOptions>`, which allows us to set non-optional properties on the default options. It is not consistently implemented yet, though.

**Review by pawelfus — APPROVED** [review]
Thanks! 👍

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Looks like some related tests failed now

**Review by TorsteinHonsi — APPROVED** [review]
