### PR TITLE
bugfix/20804-radialaxis-setoptions

### LINKED ISSUE #20804: Solid gauge `yAxis` options not applied with `setOptions`
When type is set to `solidgauge`, specific `yAxis` options are not applied with `Highcharts.setOptions`. They are however applied if using the `chart` function.

This was working in 11.2.0, but broke in 11.3.0.

At least these options are affected (there might be others as well):

- yAxis.tickLength
- yAxis.minorTickLength
- yAxis.labels.distance

#### Expected behaviour
The gauge should be rendered in the same way regardless of whether you use the `setOptions` or `chart` functions.

#### Actual behaviour
Gauge is not rendered in the same way.

#### Live demo with steps to reproduce
1. Open this jsfiddle: https://jsfiddle.net/pkhalle/cy7mp2j5/
3. Observe the gauge's appearance
4. Change the imported Highcharts version to 11.3.0
5. Re-run the fiddle and observe the appearance has changed

#### Product version
Highcharts 11.3.0+

### PR DESCRIPTION
**Pull request by hubertkozik**
Fixed #20804, `setOptions` didn't change Radial Axis defaults.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1206806184259773

### CODE REVIEW

File: ts/Core/Options.d.ts [hunk 1]
```diff
@@ -73,6 +74,8 @@ export interface Options {
 }
 
 export interface DefaultOptions extends Options {
+    defaultCircularOptions?: RadialAxisOptions,
+    defaultRadialGaugeOptions?: RadialAxisOptions
```
Comment (bre1470) [inline ts/Core/Options.d.ts:78]: This should not be hardcoded her, instead in `RadialAxisOptions.d.ts` add a 
```ts
declare module '../Options' {
  // here goes the interface a second time with the properties for type merge
}
```

File: ts/Core/Defaults.ts [hunk 2]
```diff
@@ -2797,6 +2797,22 @@ function setOptions(
...
+    }
+
+    if (defaultOptions.defaultRadialGaugeOptions && options.yAxis) {
+        merge(
+            true,
+            defaultOptions.defaultRadialGaugeOptions,
+            options.yAxis
+        );
+    }
+
```
Comment (bre1470) [inline ts/Core/Defaults.ts:2815]: We should consider an event here, fired on Highcharts, so that we can listen in `RadialAxis.ts` for the `setOptions` event on the `H` object and apply these options.

**Review by bre1470 — CHANGES_REQUESTED** [review]
Good job, fix works for me. 👍

Some code-related comments/requests...

File: ts/Core/Options.d.ts (hunk 1 above)
Comment (hubertkozik) [reply ts/Core/Options.d.ts]: Done!

**Review by bre1470 — APPROVED** [review]
Awesome! LGTM 👍

**Review by TorsteinHonsi — COMMENTED** [review]
Thanks, nice solution!

Gotta work on the description for the changelog though :) And add the appropriate tags for the changelog.

**Comment by hubertkozik** [comment]
@TorsteinHonsi ups... totally missed that - sorry!

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Sorry I didn't catch this yesterday, but there are now a lot of [visual diff](https://vrevs.highsoft.com/pr/20985/review). I tried to check these one by one in the utils, but they don't come out different there.

It is most likely a case of state leakage. My guess is that one sample runs `setOptions`, which affects all the samples downstream. Karma runs the samples in long threads within the same webpage.

I would try modifying the `afterEach` function [where the default options are reset](https://github.com/highcharts/highcharts/blob/b7d67698f81ad6bb95c01a4d7e4c6b6804431fc7/test/karma-setup.js#L458-L474). We probably need to reset the RadialAxis defaults along the same principles. Which also probably means they need to be exposed.

File: test/karma-setup.js [hunk 3]
```diff
@@ -221,6 +222,12 @@ function resetDefaultOptions(testName) {
 
     Highcharts.setOptions(defaultOptionsRaw);
 
+    // Restore radial axis defaults
+    Highcharts._modules['Core/Axis/RadialAxis.js'].RadialDefaultOptions =
+        Highcharts.merge(
+            Highcharts._modules['Core/Axis/RadialAxisDefaults.js']
+        );
```
Comment (TorsteinHonsi) [inline test/karma-setup.js:229]: This will break when we go webpack and `Highcharts._modules` no longer exists. Instead, I would expose `Highcharts.RadialAxis` (from `masters/highcharts-more.src.ts`). The karma-setup can copy those properties before the tests start ([like we do with defaultOptions](https://github.com/highcharts/highcharts/blob/cd5be8300aa6f6c6c1e74cc4efcb13cb0f1b48ad/test/karma-setup.js#L130)), then restore it here.

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
