### PR TITLE
bugfix/17945-colorAxis-grouping--markers-colors

### LINKED ISSUE #17945: When reset zoom button the colors on line will revert back to legend color
#### Expected behaviour
When applying colorKey on the chart, the line colors changed when resetting the zoom. The color changed to the same as the legend color of the line. The issue I posted on highcharts forums so someone replied to me that there is no issue on my side but this issue is on highcharts.

#### Actual behaviour
I want to remain the same colors when reset zoom the chart. I have also attached a gif of my issue.

#### Live demo with steps to reproduce
Check it on my fiddle: https://jsfiddle.net/wz9sn31b/2/
Issue reported on forums: https://www.highcharts.com/forum/viewtopic.php?f=12&t=49776

#### Product version

HIghstock

#### Affected browser(s)
All

#### Issue shown on attached gif file:
Recording 2022-11-03 at 15 46 05

gif link if not loaded: https://media.giphy.com/media/gg5Kx2hx3xTBaxZZR3/giphy.gif

### PR DESCRIPTION
**Pull request by jedrzejruta**
Fixed #17945, colors lost on a color axis after going back to grouped state with data grouping enabled.

### CODE REVIEW

**Review by pawelfus — APPROVED** [review]
Thanks!

___
Note: If that causes any regression, then I would try changing code below to something like this:
```js
let points = this.getPointsCollection() as PointComposition[];

if (!points.length) {
  points = this.points;
}
```
I remember, we discussed this case with @jszuminski and probably Boost (?) could be the reason why `this.data.length` is being checked up.

File: samples/unit-tests/coloraxis/extremes/demo.js [hunk 1]
```diff
@@ -23,3 +23,56 @@ QUnit.test('Extremes are calculated from all series. #6209', function (assert) {
...
+        series: [{
+            dataGrouping: {
+                enabled: true,
+                groupPixelWidth: 15,
+                units: [
+                    [
+                        'week',
+                        [1]
+                    ]
+                ]
```
Comment (pawelfus) [inline samples/unit-tests/coloraxis/extremes/demo.js:48]: Hint: If you want to force dataGrouping with small datasets then simply set `forced = true`. You can resign from options like units, groupPixelWidth and pointStart/Interval

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
