### PR TITLE
bugfix/23056-settings-disabled-new-component

### LINKED ISSUE #23056: The settings sidebar shouldn’t appear when editMode.settings is disabled.
#### Actual behaviour
When `editMode.settings` option disabled, the component editor from the toolbar is correctly disabled. However, the settings sidebar should also not appear when adding a new component.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/vpezscx3/

#### Product version
Highcharts Dashboards v3.3.0

Internal note:
Workaround: https://jsfiddle.net/BlackLabel/pbfda1qo/

### PR DESCRIPTION
**Pull request by karolkolodziej**
Fixed #23056, the sidebar should not be visible when adding a new component and when the `settings` are disabled.

### CODE REVIEW

File: ts/Dashboards/EditMode/EditMode.ts [hunk 1]
```diff
@@ -1043,14 +1043,21 @@ class EditMode {
...
             isSet = cnt?.classList.contains(
                 EditGlobals.classNames.editOverlayActive
             );
 
+        if (forceRemove) {
+            cnt?.classList.remove(EditGlobals.classNames.editOverlayActive);
+            editMode.isEditOverlayActive = false;
+            return;
+        }
+
```
Comment (skrulling) [inline ts/Dashboards/EditMode/EditMode.ts]: I am a bit confused about `forceRemove`. To me it seems to do just the same as `remove`, but without checking if overlay is set.
Why do we need both params? I really think we should manage with just `remove`, unless there is something i dont understand here

File: ts/Dashboards/EditMode/SidebarPopup.ts [hunk 2]
```diff
@@ -513,7 +518,11 @@ class SidebarPopup extends BaseForm {
 
         const componentPromise =
             Bindings.addComponent(options, sidebar.editMode.board, newCell);
-        sidebar.editMode.setEditOverlay();
+
+        sidebar.editMode.setEditOverlay(
+            undefined,
+            !this.editMode.options.settings?.enabled
+        );
```
Comment (skrulling) [inline ts/Dashboards/EditMode/SidebarPopup.ts]:
```suggestion

        sidebar.editMode.setEditOverlay(
            true
        );
```

would this not have worked? And then we would not have to add `forceRemove`?

**Review by skrulling — CHANGES_REQUESTED** [review]

File: ts/Dashboards/EditMode/EditMode.ts (hunk 1 above)
Comment (sebastianbochan) [reply ts/Dashboards/EditMode/EditMode.ts]: I'm not convinced too. Its confusing.

**Comment by karolkolodziej** [comment]
I've removed the `forceRemove` and found an alternative approach.
