### PR TITLE
bugfix/13992-ikh-empty-series-error

### LINKED ISSUE #13992: The Ichimoku Kinco Hyo indicator throwing the error in console, when base series has no data.
#### Expected behaviour
It should not throw the error even when the base series data is empty, like every other indicator.

#### Actual behaviour
The Ichimoku Kinco Hyo indicator throwing the `TypeError: Cannot set property '0' of undefined` when its base series does not have data.

#### Live demo with steps to reproduce
Official IKH demo without data set on base series: https://jsfiddle.net/BlackLabel/u8pjmy6a/

#### Workaround
Applying the below fix of the `getGraphPath` prototype function, which checks whether the calculated SMA is not empty.
```js
(function(H) {
  const SMA = H.seriesTypes.sma;

  H.seriesTypes.ikh.prototype.getGraphPath = function(points) {
    var indicator = this,
      path = [],
      spanA,
      spanAarr = [];

    points = points || this.points;
    if (indicator.fillGraph && indicator.nextPoints) {
      spanA = SMA.prototype.getGraphPath.call(
        indicator,
        indicator.nextPoints
      );
      if (spanA.length) {
        spanA[0][0] = "L";
        path = SMA.prototype.getGraphPath.call(indicator, points);
        spanAarr = spanA.slice(0, path.length);
        for (var i = spanAarr.length - 1; i >= 0; i--) {
          path.push(spanAarr[i]);
        }
      }
    } else {
      path = SMA.prototype.getGraphPath.apply(indicator, arguments);
    }
    return path;
  };
})(Highcharts)
```
Demo with fix: https://jsfiddle.net/BlackLabel/0d1e635j/

### PR DESCRIPTION
**Pull request by madepiet**
Fixed #13992, the Ichimoku Kinco Hyo indicator threw errors in the console when the base series had no data.

### CODE REVIEW

File: js/Stock/Indicators/IKHIndicator.js [hunk 1]
```diff
@@ -548,11 +548,13 @@ seriesType('ikh', 'sma',
             spanA = SMA.prototype.getGraphPath.call(indicator, 
             // Reverse points, so Senkou Span A will start from the end:
             indicator.nextPoints);
-            spanA[0][0] = 'L';
-            path = SMA.prototype.getGraphPath.call(indicator, points);
-            spanAarr = spanA.slice(0, path.length);
-            for (var i = spanAarr.length - 1; i >= 0; i--) {
-                path.push(spanAarr[i]);
+            if (spanA.length) {
```
Comment (sebastianbochan) [inline js/Stock/Indicators/IKHIndicator.js:551]: I would check if spanA exists to avoid random issues.

```
if (spanA && spanA.length) {
```

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
