### PR TITLE
bugfix/18088-heikin-ashi-wrong-color

### LINKED ISSUE #18088: Heikin-Ashi wrong candles color
#### Expected behaviour
Candles with close lower than open should be colored as red (or any "down color").

#### Actual behaviour
Some candles have their color mixed.

#### Live demo with steps to reproduce
Take a look at the Nov 7 candle
https://jsfiddle.net/BlackLabel/Lj5whnuc/

#### Product version
Highstock + Heikin-Ashi 10.3.2 (latest)

### PR DESCRIPTION
**Pull request by kamil-musialowski**
Fixed #18088, color for Heikin-Ashi candles was set incorrectly.

### CODE REVIEW

File: ts/Series/HeikinAshi/HeikinAshiPoint.ts [hunk 1]
```diff
@@ -35,6 +40,9 @@ const {
 
 class HeikinAshiPoint extends CandlestickPoint {
     // clone inheritence
+    public resolveColor(): void {
+        HLCPoint.prototype.resolveColor.call(this);
+    }
```
Comment (TorsteinHonsi) [inline ts/Series/HeikinAshi/HeikinAshiPoint.ts:45]: Instead of wrapping and calling the nested function with the same scope, you can just borrow it:

```ts
class HeikinAshiPoint extends CandlestickPoint {
    // clone inheritence
    public resolveColor = HLCPoint.prototype.resolveColor;
}
```

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks! One minor change request.

**Review by TorsteinHonsi — APPROVED** [review]
