### PR TITLE
bugfix/16169-centerInCategory-reverses-stack 

### LINKED ISSUE #16169: centerInCategory setting reverses stack groups order
#### Expected behaviour
`centerInCategory: true` in combination with `reversedStacks: false` shouldn't affect order of different stacks.

#### Actual behaviour
`centerInCategory: true` affects order of different stacks (also labels are misplaced).

#### Live demo with steps to reproduce
https://jsfiddle.net/gv4skudb/
(_series 1_ and _series 2_ stack group must be first)
#### Product version
8.1.1 and later

#### Affected browser(s)
All

### PR DESCRIPTION
**Pull request by karolkolodziej**
Fixed #16169, stack order was affected when `centerInCategory` enabled and `reversedStacks` set to false.

### CODE REVIEW

File: samples/unit-tests/series/stacking/demo.js [hunk 1]
```diff
@@ -699,4 +699,46 @@ QUnit.test('Date objects as X values, column', function (assert) {
             'Series 3 - Point should start from value=1 (#4024)'
         );
     });
+
+    QUnit.test(
```
Comment (raf18seb) [inline samples/unit-tests/series/stacking/demo.js:703]: No chance to reuse the existing test?

File: samples/unit-tests/series/stacking/demo.js [hunk 2]
```diff
@@ -699,4 +699,46 @@ QUnit.test('Date objects as X values, column', function (assert) {
...
+                        id: 0
+                    }, {
+                        data: [2],
+                        id: 1
+                    }, {
+                        data: [4],
+                        stack: "1"
+                    }, {
+                        data: [1],
+                        stack: "1"
```
Comment (raf18seb) [inline samples/unit-tests/series/stacking/demo.js:733]: Please use single quote when writing JavaScript code

File: samples/unit-tests/series/stacking/demo.js [hunk 3]
```diff
@@ -699,4 +699,46 @@ QUnit.test('Date objects as X values, column', function (assert) {
...
+                        stackLabels: {
+                            enabled: true
+                        }
+                    },
+                    series: [{
+                        data: [5],
+                        id: 0
+                    }, {
+                        data: [2],
+                        id: 1
```
Comment (raf18seb) [inline samples/unit-tests/series/stacking/demo.js:727]: Do we need `id` here?

File: ts/Series/Column/ColumnSeries.ts [hunk 4]
```diff
@@ -822,7 +823,8 @@ class ColumnSeries extends Series {
                                     indexInCategory = totalInCategory;
                                 }
                                 if (stackItem.hasValidPoints) {
-                                    totalInCategory++;
+                                    reversedStacks ?
```
Comment (raf18seb) [inline ts/Series/Column/ColumnSeries.ts:826]: What do you think about adding a comment with a ticket number here so the ticket can be easier to find in case of any problems in the future?

**Review by raf18seb — CHANGES_REQUESTED** [review]
Good job! Just a few small suggestions, see the comments below

File: samples/unit-tests/series/stacking/demo.js (hunk 1 above)
Comment (karolkolodziej) [reply samples/unit-tests/series/stacking/demo.js:703]: The config to recreate the issue is quite specific and I was not able to reuse any of the existing tests.

**Review by raf18seb — APPROVED** [review]
Thanks!

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
