### PR TITLE
enhancement/15649-bullet-target-borderRadius

### LINKED ISSUE #15648: Not able to style target in bullet chart to have a Rounded Corner/ borderRadius even while using the plugin
#### Expected behaviour
Target bar should have a rounded edge

#### Actual behaviour
There is no change in appearence

#### Live demo with steps to reproduce
https://jsfiddle.net/chandanasri/zwrqspej/3/

### LINKED ISSUE #15649: Rounded corners for target bar in bullet chart
# Description of the feature
1. Target bar should have a rounded edge. May be add a borderRadius or make it able to use the rounded corner plugin.
2. Target bar height should be able to extend outside the bullet chart.

#### Live demo with steps to reproduce
https://jsfiddle.net/chandanasri/zwrqspej/2/

**You can vote for this feature by adding a thumbs-up reaction to this post.**

### PR DESCRIPTION
**Pull request by khlieng**
Added bullet target `borderRadius` option, see #15649.

Closes #15649.
Closes #15648.

### CODE REVIEW

File: ts/Series/Bullet/BulletSeries.ts [hunk 1]
```diff
@@ -135,7 +135,14 @@ class BulletSeries extends ColumnSeries {
              *
              * @since   6.0.0
              */
-            borderWidth: 0
+            borderWidth: 0,
+
+            /**
+             * The border radius of the rectangle representing the target.
+             *
+             * In styled mode, use class `highcharts-bullet-target` instead.
```
Comment (TorsteinHonsi) [inline ts/Series/Bullet/BulletSeries.ts:143]: We can't set the border radius of a shape in CSS, so we should remove the reference to styled mode.

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
