### PR TITLE
bugfix/17522-lastPrice-label

### LINKED ISSUE #17522: The lastPrice indicator label trows error.
#### Expected behaviour
Show that label without error.

#### Actual behaviour
When the `lastPrice` label is enabled there is an error in the console.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/gaxzw73p/

#### Product version
Last working version 9.0.1

#### Affected browser(s)
All

### PR DESCRIPTION
**Pull request by karolkolodziej**
Fixed #17522, when the `lastPrice` label was enabled, there was an error in the console.

### CODE REVIEW

File: samples/unit-tests/indicator-price-indicator/recalculations/demo.js [hunk 1]
```diff
@@ -50,6 +50,23 @@ QUnit.test('Price indicator.', function (assert) {
...
+    chart.series[0].update({
+        lastVisiblePrice: {
+            enabled: false
+        },
+        lastPrice: {
+            label: {
+                enabled: true
+            }
+        }
+    });
```
Comment (raf18seb) [inline samples/unit-tests/indicator-price-indicator/recalculations/demo.js:64]: Please use one `redraw` instead of multiple

**Review by raf18seb — CHANGES_REQUESTED** [review]
I have one comment, see below

**Review by raf18seb — APPROVED** [review]
Thanks!

**Review by TorsteinHonsi — APPROVED** [review]
