### PR TITLE
Fixed #20394 updating xRange series color

### LINKED ISSUE #20394: Cannot change XRange series color
#### Expected behaviour
User should have possibility to change color of a XRange series.

#### Actual behaviour
User cannot change color of a XRange series (while the border color is changed properly).

#### Live demo with steps to reproduce
https://jsfiddle.net/vrms6ytw/
1. run demo (series is created with pink color and red border)
2. press Update button (doing this user wants to change series color to lime with green border but only border color is changed)

#### Product version
Highcharts 11.x

#### Affected browser(s)
Chrome, Edge

### PR DESCRIPTION
**Pull request by MarkusBarstad**
Fixed #20394, `series.color` only initially impacted the color of xRange points.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1206330283672333

### CODE REVIEW

**Comment by hubertkozik** [comment]
Hi @MarkusBarstad! Can you add a unit test for that bug? It will be good for someone in the future, to not revert the bug after some refactor.

**Comment by MarkusBarstad** [comment]
> Hi @MarkusBarstad! Can you add a unit test for that bug? It will be good for someone in the future, to not revert the bug after some refactor.

Alright, its done, @hubertkozik !

One thing I see in unit-tests, is that we do not always cache property lookups (we for example refer to `chart.series[0]` many times instead of making a variable pointing to it)

Should we change this when we see it?

Also swapped Kacper with you for review btw since you already looked at this.

**Comment by hubertkozik** [comment]
In terms of tests, I think it depends on personal preferences, if someone wants to declare a special variable and it will make the test more readable, cleaner. If you feel, that something is not clear in the test, and assigning `chart.series[0]` would help, then feel free to change it.

In terms of Highcharts code, an extra variable always takes some extra space (byte or maybe less), so if there is no special need for variable it is better to use an existing object.

File: samples/unit-tests/gantt/xrange-series/demo.js [hunk 1]
```diff
@@ -255,7 +259,14 @@
...
             -1,
-            'The tooltip header should container formatted date (#9301)'
+            'The tooltip header should contain a formatted date (#9301)'
+        );
+
+        chart.series[0].update({ color: 'red' });
+        assert.strictEqual(
+            chart.series[0].color,
+            'red',
+            'The series color should have changed to red'
```
Comment (hubertkozik) [inline samples/unit-tests/gantt/xrange-series/demo.js:269]: If I comment out your fix from the HC code (so the code will be as on the master branch), then the test has passed (success), but the point is green, not red. The test is not catching the issue.

**Review by hubertkozik — CHANGES_REQUESTED** [review]

**Comment by MarkusBarstad** [comment]
> In terms of tests, I think it depends on personal preferences, if someone wants to declare a special variable and it will make the test more readable, cleaner. If you feel, that something is not clear in the test, and assigning `chart.series[0]` would help, then feel free to change it.
> 
> In terms of Highcharts code, an extra variable always takes some extra space (byte or maybe less), so if there is no special need for variable it is better to use an existing object.

Yeah, that makes sense, its not only readability though, but also speed of execution by limiting lookups I am concerned with when writing tests :thinking: But space is important to consider as well!

File: samples/unit-tests/gantt/xrange-series/demo.js (hunk 1 above)
Comment (MarkusBarstad) [reply samples/unit-tests/gantt/xrange-series/demo.js]: Alright, should work now, testing `point.color` instead of `series.color`, which is green without the fix

File: samples/unit-tests/gantt/xrange-series/demo.js [hunk 2]
```diff
@@ -255,7 +259,15 @@
         assert.notEqual(
             chart.tooltip.label.element.textContent.indexOf('Monday'),
             -1,
-            'The tooltip header should container formatted date (#9301)'
+            'The tooltip header should contain a formatted date (#9301)'
+        );
+
+        chart.series[0].update({ color: 'red' });
+        console.log(chart.series[0].points[0].color);
```
Comment (hubertkozik) [inline samples/unit-tests/gantt/xrange-series/demo.js:266]: `console.log` 😬

**Review by hubertkozik — APPROVED** [review]
Good job, but the line mentioned below has to be removed :grinning:

File: samples/unit-tests/gantt/xrange-series/demo.js (hunk 2 above)
Comment (MarkusBarstad) [reply samples/unit-tests/gantt/xrange-series/demo.js:266]: woops, my bad!! i cannot understand how this passes pre-commit 🤔

Comment (MarkusBarstad) [reply samples/unit-tests/gantt/xrange-series/demo.js]: removed

**Review by hubertkozik — APPROVED** [review]

**Review by bre1470 — APPROVED** [review]
LGTM 👍

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
