### PR TITLE
bugfix/21611-downloadSVGLocal-not-applying-classes

### LINKED ISSUE #21611: downloadSVGLocal to png/jpeg does not apply class-based style rules
It's entirely possible this behavior is outside of supported use cases.

#### Expected behaviour
When calling `Highcharts.downloadSVGLocal` with an SVG that applies styling via classes, that styling should be visible in the exported product.

Likewise, with a Highcharts chart where some styling has been applied via classes and exporting to PNG/JPEG, that styling should be visible in the exported product.

#### Actual behaviour
Inline SVG styling (`style` attributes and presentation attributes) applies to the exported .png or .jpg file, but classes do not apply. Thus, the generated image does not match the source.

Similarly, if you use CSS classes to modify a chart, those effects do not apply when exporting to  PNG or JPEG.

#### Live demo with steps to reproduce
https://jsfiddle.net/ujzhLwsq/
Here, we have an SVG containing a circle. The `stroke` is styled via the style attribute, but the `fill` is styled via a css class. The button will export that SVG with `downloadSVGLocal`. The exported image has the correct `stroke` but does not apply the correct `fill`.

https://jsfiddle.net/tay9rb0u/
Here, we have a CSS class modifying a Highcharts chart, changing the column color to green. When exported to PNG or JPEG, that modification does not apply; the color changes back to the default.

https://jsfiddle.net/zywe6hv3/
However, setting `chart.styledMode` and including the default CSS stylesheet does produce the expected behavior.

#### Product version
Highcharts JS v11.4.6 

#### Affected browser(s)
Confirmed in Chrome and Firefox

### PR DESCRIPTION
**Pull request by MarkusBarstad**
Added new option, [exporting.applyStyleSheets](https://api.highcharts.com/highcharts/exporting.applyStyleSheets), to allow exported charts to be effected by CSS rules in the page regardless of `chart.styledMode`. See #21611.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1207956311385159

### CODE REVIEW

**Review by hubertkozik — COMMENTED** [review]
Good solution! For the `offline-exporting` module we are using manual tests, e.g. [exporting/offline-download](http://utils.highcharts.local/samples/#view/highcharts/exporting/offline-download). Can you add one or use the existing one?

**Review by hubertkozik — APPROVED** [review]
After seeing, that the manual test is really short I started to think, that maybe there is a way to test it automatically, but after a few minutes of going through the code and looking for some event to make an assert there I figured out, that we cannot test the downloaded file. I believe everything is correct, approved.

**Comment by TorsteinHonsi** [comment]
Thank you for the PR! 

This requirement is actually exactly the same as when exporting charts in `styledMode`, as the OP mentions. But styled mode not only honors the default `highcharts.css`, it also honors custom styles. Which means we probably already have the building blocks for making this work, we just need to stitch it together.

As far as I can see, all the logic we need is in the `inlineStyles` function: https://jsfiddle.net/highcharts/befzcp2g/1/. It currently sits on the Chart prototype, which I don't think a very good place for it, as it can be used on any SVG element inheriting styling from a style sheet. I don't know where else to put it though. Ideally, all the exporting functions should be gathered in a separate Exporting class with an instance for each chart. But that's off this topic.

Besides relying on existing and battle-tested code, this approach also supports all types of selectors, not only class names. For example, if you modify the selector in the first OP example, the fix no longer works because it doesn't start with a `.`. And that would be only the tip of the iceberg.
```css
circle.fill-green {
  fill: green !important;
}
```

The OP also mentions mixed styling where `styledMode` is false, but CSS rules are used in order to modify the visuals. This fails not only with the `downloadSVGLocal` function, but also with the export server: https://jsfiddle.net/highcharts/p3dL6ecz/ . So we need to consider this in a slightly broader view. I think it will be a bit dangerous to suddenly start applying `inlineStyles` on all exported charts. Instead, we should probably introduce an option that is false by default, but true when `styledMode` = true. Something like `exporting.applyStyleSheets`.

A lot of words this, so here's what I think we should do:
* Create an option to apply style sheets to exported charts, styled mode or not.
* Maybe that's all we need actually. The OP uses the `downloadSVGLocal` function directly, but that may be for the purpose of isolating the bug. Strictly speaking, `inlineStyles` should probably run _prior_ to that function, because what it promises is just to download an SVG, not modify it in any way.

**Comment by TorsteinHonsi** [comment]
Awesome! Nice and clean and cheap. 

> Edit: Also, should we have a sample for this option? I added one just in case.

A sample per option is always good, but right now it seems like the `apply-stylesheets` options doesn't actually have any CSS that affects the chart? So it doesn't really demonstrate the feature. Also, by the two new samples, did you intend to show both online and offline exporting? In that case I don't think it's really necessary, because this happens when the SVG is generated, and the same SVG is sent both to online and offline download. So I suggest keeping only the `apply-stylesheets` sample, but bring in the CSS and the test note from the other one.

@javolio Does this fix you use case, or would you expect a more direct access to `inlineStyles` to use with custom (non-chart) SVGs?

**Comment by MarkusBarstad** [comment]
@TorsteinHonsi 

Woops, my bad on missing the CSS class!! 

I think you are correct that one illustration of the `applyStyleSheets` is enough since both offline and non-offline exporting gets their SVG the exact same way.

The older demo has been deleted in favor of the new, and the new demo also now has `test-text.md` to instruct manual testing.

File: samples/highcharts/exporting/apply-stylesheets/demo.js [hunk 1]
```diff
@@ -0,0 +1,9 @@
+Highcharts.chart('container', {
+    exporting: {
+        applyStyleSheets: true // Don't loose CSS during exporting
```
Comment (TorsteinHonsi) [inline samples/highcharts/exporting/apply-stylesheets/demo.js:3]:
```suggestion
        applyStyleSheets: true // Don't lose CSS during exporting
```
https://www.merriam-webster.com/grammar/lose-vs-loose-usage

File: samples/highcharts/exporting/apply-stylesheets/demo.details [hunk 2]
```diff
@@ -0,0 +1,6 @@
+---
+ name: Highcharts Demo
+ authors:
+   - Torstein Hønsi
```
Comment (TorsteinHonsi) [inline samples/highcharts/exporting/apply-stylesheets/demo.details:4]: 🤔

File: samples/highcharts/exporting/apply-stylesheets/demo.details
Comment (TorsteinHonsi) [inline samples/highcharts/exporting/apply-stylesheets/demo.details:1]: We also need to add `requiresManualTesting: true`

File: ts/Extensions/OfflineExporting/OfflineExporting.ts [hunk 3]
```diff
@@ -178,7 +178,6 @@ namespace OfflineExporting {
      *
      * - **scale:** Scaling factor of downloaded image compared to source.
      * Default is `1`.
-     *
      * - **libURL:** URL pointing to location of dependency scripts to download
```
Comment (TorsteinHonsi) [inline ts/Extensions/OfflineExporting/OfflineExporting.ts:181]: A line was deleted here, it will probably affect the layout in the docs?

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks! Just some minor nitpicking left now and it's good to go into the master.

File: ts/Extensions/Exporting/ExportingDefaults.ts [hunk 4]
```diff
@@ -65,6 +65,20 @@ const exporting: ExportingOptions = {
...
+    /**
+     * Allow exporting a chart retaining any user-applied CSS.
+     *
+     * Note that this is is default behavior in [styledMode](#chart.styledMode).
+     *
+     * @see [styledMode](#chart.styledMode)
+     *
+     * @sample {highcharts} highcharts/exporting/apply-stylesheets/
+     *
+     * @type      {boolean}
```
Comment (TorsteinHonsi) [inline ts/Extensions/Exporting/ExportingDefaults.ts:77]: Add `@since next`

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
... aaand we need to update the changelog description to actually describe the new feature.

**Comment by javolio** [comment]
@TorsteinHonsi Our use case is specifically using `downloadSVGLocal` to export an inline non-Highcharts SVG. But like I said in the issue, I don't know if that's supported behavior. I've also implemented a workaround in our system: iterating through relevant elements and applying the stroke and fill from `getComputedStyle(element)` to `element.style`, then calling `downloadSVGLocal`, and finally undoing the style changes.

File: samples/highcharts/exporting/apply-stylesheets/demo.details (hunk 2 above)
Comment (MarkusBarstad) [reply samples/highcharts/exporting/apply-stylesheets/demo.details:4]: I was unsure of this because it was your original demo, just slightly altered by me!! 😆

**Comment by MarkusBarstad** [comment]
> ... aaand we need to update the changelog description to actually describe the new feature.

Alright, @TorsteinHonsi should be good now! I assume we still keep the "Fixed" part of the message since its a bugfix, so i kind of wrote it like that.

**Review by TorsteinHonsi — APPROVED** [review]
@MarkusBarstad Actually we are now adding a new option, which takes precedence over the bug fix, so I modified the description a little.
