### PR TITLE
bugfix/14742-scrolling-navigator-range

### LINKED ISSUE #14742: Chart-Scrolling not working when xAxis-Range is equal to range of initial data
#### Expected behaviour
When adding new data with a given range, the chart should scroll and only show the range

#### Actual behaviour
When you set the range exactly like the initial data the scrolling does not work

#### Live demo with steps to reproduce
if you look here, the scrolling works because the range is smaller than the initial data:
(initial data is one minute, range is only 40 seconds):
https://stackblitz.com/edit/ionic-v4-angular-tabs-kcdmqy?file=src/app/tab1/tab1.page.ts

however if i set the range to one minute (which is desired), the chart gets squeezed when updating and does not scroll anymore:
https://stackblitz.com/edit/ionic-v4-angular-tabs-phr1tk?file=src/app/tab1/tab1.page.ts

#### Product version

latest

#### Affected browser(s)
safari/chrome macos

### PR DESCRIPTION
**Pull request by karolkolodziej**
Fixed #14742, the axis `range` property was ignored when there were fewer data points.

### CODE REVIEW

File: ts/Core/Navigator.ts [hunk 1]
```diff
@@ -2555,6 +2553,36 @@ class Navigator {
         }
     }
 
+    /**
+     * Detect if the zoomed area should stick to the minimum or maximum, #14742.
```
Comment (pawellysy) [inline ts/Core/Navigator.ts:2557]: Is this function also checking, if the zoomed area should stick to maximum? If yes, the function name should be renamed e.g. to `shouldStickToExtreme`. If not, then change the comment.

**Review by pawellysy — APPROVED** [review]
See comment

**Review by pawellysy — CHANGES_REQUESTED** [review]
see comment

File: ts/Extensions/RangeSelector.ts [hunk 2]
```diff
@@ -950,6 +950,12 @@ class RangeSelector {
                 return;
             }
         } else if (type === 'all' && baseAxis) {
+            // If the navigator exist and the axis range is declared reset that
+            // range and from now on only use the range set by a user, #14742.
+            if (chart.navigator) {
+                chart.navigator.baseSeries[0].xAxis.options.range = void 0 as any;
```
Comment (pawelfus) [inline ts/Extensions/RangeSelector.ts:956]: Please, check if `baseSeries[]` is defined. I know, it might not be a real use-case, but it's better to not introduce this bug: https://jsfiddle.net/BlackLabel/4nq0ca2b/ (click on "All" button and observe console)

**Review by pawelfus — CHANGES_REQUESTED** [review]

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks! Here's a blocking regression:
1. Open https://jsfiddle.net/highcharts/gbhx09jq/
2. Click the left navigator arrow once so that the navigator range is disconnected from the data max.
3. Click the "Add points" button five times or more. The navigator range is now squeezed. It should maintain the same range and stick to the data min.

**Review by raf18seb — APPROVED** [review]
Looks good 👍

**Comment by TorsteinHonsi** [comment]
One last thing... Can you also add the case reported in my previous comments to the unit tests? It slipped through the cracks the first time, so we must make sure we cover that case in the future.

**Review by pawellysy — APPROVED** [review]
Looks good!

**Review by TorsteinHonsi — APPROVED** [review]
