### PR TITLE
bugfix/20433-scatter-boost-without-min-max

### LINKED ISSUE #20433: Regression: Boosted scatter doesn't render when y-axis extremes not set
#### Expected behaviour
Extremes should be computed from the data.

#### Actual behaviour
When `yAxis.min` or `yAxis.max` are not explicitly set, the series fails to render.

#### Live demo with steps to reproduce
https://jsfiddle.net/highcharts/1905aobL/

#### Product version
v11.3.0

### PR DESCRIPTION
**Pull request by bre1470**
Fixed #20433, boosted scatter chart did not work without axis min/max-options.

~~Fixed #20433; Scatter did not boost without axis min/max-options.~~

### CODE REVIEW

**Review by marvin19 — APPROVED** [review]

File: ts/Extensions/Boost/BoostSeries.ts [hunk 1]
```diff
@@ -954,11 +958,29 @@ function scatterProcessData(
...
+            yDataMax = Math.max(yDataMax, y);
+            yDataMin = Math.min(yDataMin, y);
         } else {
             cropped = true;
         }
     }
 
+    if (!isNumber(xExtremes.max) || !isNumber(xExtremes.min)) {
+        xAxis.setOptions({
+            max: xAxis.options.max || xDataMax,
```
Comment (KacperMadej) [inline ts/Extensions/Boost/BoostSeries.ts:972]: If the check were to be done before the calculation of the xDataMax then it should make the boost run even faster when the axis extremes are set. Should we have some performance tests similar to e.g. the ones for the Stock?

Comment (KacperMadej) [reply ts/Extensions/Boost/BoostSeries.ts:972]: (preferably in a different task but that would help with comments like mine here)

Comment (bre1470) [reply ts/Extensions/Boost/BoostSeries.ts:972]: Performance tests are a good idea, especially for boost.

File: samples/unit-tests/boost/enter-exit/demo.html [hunk 2]
```diff
@@ -2,8 +2,4 @@
 <script src="https://code.highcharts.com/modules/boost-canvas.js"></script>
 <script src="https://code.highcharts.com/modules/boost.js"></script>
 
-
-<div id="qunit"></div>
-<div id="qunit-fixture"></div>
-
```
[the remark this answers is not in the document]
Comment (bre1470) [reply samples/unit-tests/boost/enter-exit/demo.html:8]: I did not saw any purpose in the `demo.js` and `karma-setup.js`, and the other boost-tests lack it. Do you know more about it?

[the remark this answers is not in the document]
Comment (hubertkozik) [reply samples/unit-tests/boost/enter-exit/demo.html:8]: This divs contains the UI for tests. Below is ss with added divs. In my opinion, we should keep it.
image

**Review by hubertkozik — APPROVED** [review]
OP demo works like a charm now! Approving, but left comments in unresolved conversations.

**Review by KacperMadej — APPROVED** [review]

File: ts/Extensions/Boost/BoostSeries.ts [hunk 3]
```diff
@@ -937,11 +937,17 @@ function scatterProcessData(
     // Filter unsorted scatter data for ranges
     const processedData: Array<PointOptions> = [],
         processedXData: Array<number> = [],
-        processedYData: Array<number> = [];
+        processedYData: Array<number> = [],
+        xRangeNeeded = !(isNumber(xExtremes.max) || isNumber(xExtremes.min)),
+        yRangeNeeded = !(isNumber(yExtremes.max) || isNumber(yExtremes.min));
```
Comment (TorsteinHonsi) [inline ts/Extensions/Boost/BoostSeries.ts:942]: I think we should look for `..Extremes.dataMax` and `dataMin` instead of the derived `min` and `max`

File: ts/Extensions/Boost/BoostSeries.ts [hunk 4]
```diff
@@ -954,11 +960,32 @@ function scatterProcessData(
...
+                yDataMax = Math.max(yDataMax, y);
+                yDataMin = Math.min(yDataMin, y);
+            }
         } else {
             cropped = true;
         }
     }
 
+    if (xRangeNeeded) {
+        xAxis.setOptions({
```
Comment (TorsteinHonsi) [inline ts/Extensions/Boost/BoostSeries.ts:977]: Is there any reason to run `setOptions`? It is cheaper to just set the properties directly, and as far as I can see this works. Also taking into consideration that what we are really looking for is `dataMin` and `dataMax`:

```ts
    if (xRangeNeeded) {
        xAxis.dataMax = xDataMax;
        xAxis.dataMin = xDataMin;
    }
```

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks! In addition to the inline comments, please take a look at [Writing content for the changelog](https://github.com/highcharts/highcharts/tree/master/changelog#writing-content-for-the-changelog), rule no. 5.

File: ts/Extensions/Boost/BoostSeries.ts (hunk 3 above)
Comment (bre1470) [reply ts/Extensions/Boost/BoostSeries.ts:945]: I had issues with zoom in/out and boost enter/exit not working as expected.

File: ts/Extensions/Boost/BoostSeries.ts [hunk 5]
```diff
@@ -957,11 +963,28 @@ function scatterProcessData(
...
+                yDataMin = Math.min(yDataMin, y);
+            }
         } else {
             cropped = true;
         }
     }
 
+    if (xRangeNeeded) {
+        xAxis.options.max = xAxis.options.max || xDataMax;
+        xAxis.options.max = xAxis.options.min || xDataMin;
```
Comment (TorsteinHonsi) [inline ts/Extensions/Boost/BoostSeries.ts:981]: I think this fails if `options.min` or `max` is 0. So we want a nullish test:

`xAxis.options.max ??= xDataMax;`

**Review by TorsteinHonsi — APPROVED** [review]
