### PR TITLE
bugfix/24126-negative-color

### LINKED ISSUE #24126: `negativeColor` not working for styledMode
#### Expected behaviour

Chart will not render the `highcharts-negative` class to series/points with negative values.

According to the documentation for [plotOptions.series.negativeColor](https://api.highcharts.com/highcharts/plotOptions.series.negativeColor), we need to set this to `true` to see negative color on the chart.

> In [styled mode](https://www.highcharts.com/docs/chart-design-and-style/style-by-css), a negative color is applied by setting this option to true combined with the .highcharts-negative class name.

It doesn't look like this is the case. I tried omitting it and setting it to `undefined` or `false`. The chart always gets the class.

#### Actual behaviour

The chart will always add the `highcharts-negative` class to series/points with negative values.

#### Live demo with steps to reproduce

[Default example](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/css/series-negative-color/)

- Set the `negativeColor` to `false`
- Set the `negativeColor` to `undefined`
- Set the `negativeColor` to `null`

In every case, we can see the negative points colored as blue

#### Product version
v12.5.0

#### Affected browser(s)
All

### PR DESCRIPTION
**Pull request by sebastianbochan**
Fixed #24126, `negativeColor` was not applied in styled mode.

### CODE REVIEW

File: ts/Core/Series/Point.ts [hunk 1]
```diff
@@ -851,20 +851,34 @@ class Point {
...
-                    ' ' + point.zone.className.replace(
-                        'highcharts-negative', ''
-                    ) :
-                    ''
+                options.negativeColor ||
+                options.negativeFillColor ||
+                options.displayNegative === true ||
+                // Waterfall series uses zone className for negative color
+                point.zone?.className?.includes('highcharts-negative') ||
+                point.series.chart.styledMode
```
Comment (TorsteinHonsi) [inline ts/Core/Series/Point.ts]: Do we need all these extra conditions? The bug report is about the `negativeColor` option, and the API also only mention that option. We could get away with a much simpler fix if we check only for that.

```ts
        return 'highcharts-point' +
            (point.selected ? ' highcharts-point-select' : '') +
            (point.negative && point.series.options.negativeColor !== false ? ' highcharts-negative' : '') +
            (point.isNull ? ' highcharts-null-point' : '') +
```

Comment (sebastianbochan) [reply ts/Core/Series/Point.ts]: Because of two reasons:
- bubble & waterfall series
- types - by default, the negativeColor is `ColorType` type, not boolean.

However, I managed do it by using options variable.

File: ts/Core/Series/Point.ts [hunk 2]
```diff
@@ -851,9 +851,12 @@ class Point {
      */
     public getClassName(): string {
         const point = this;
+        const seriesOptions = point.series.options as Record<string, unknown>;
```
Comment (TorsteinHonsi) [inline ts/Core/Series/Point.ts]: Shoehorning our own types into our code is usually a sign that it's not optimally set up. If I change the type to `ColorType | false`, we don't need the `as`, and the API and external typing also becomes correct. We also need to modify `Series.ts:1152` to `zone.color = options.negativeColor || '';`, then it builds.

File: ts/Core/Series/Point.ts (hunk 1 above)
Comment (TorsteinHonsi) [reply ts/Core/Series/Point.ts]: Awesome! The updated code is nice and tight. I added a comment on the type cast.

File: ts/Core/Series/Point.ts (hunk 2 above)
Comment (sebastianbochan) [reply ts/Core/Series/Point.ts]: Initially, I thought about it, but it looked weird to me and boolean was more valid (true is available according to doclet).

```
@see In styled mode, a negative color is applied by setting this option
     *      to `true` combined with the `.highcharts-negative` class name.
```  
However, it required more changes in the Core.

If the "false" type is enough for now, we can apply it.

Comment (TorsteinHonsi) [reply ts/Core/Series/Point.ts]: Oh, you're right, the correct type is `boolean`, since it is explicitly mentioned in the docs. I changed it now, it required a richer type test in `setOptions` and added some bytes, but not much.

**Review by TorsteinHonsi — APPROVED** [review]
