### PR TITLE
bugfix/14458-3d-drilldown-same-name

### LINKED ISSUE #14458: Drilldown to point of same name as parent column on 3d column chart causes error
#### Expected behaviour
Drilldown when series has 1 point with same name as parent point should work.

#### Actual behaviour
Drilldown when series has 1 point with same name as parent point produces javascript error.
Axis3D.wrapGetSlotWidth - nextTick.label is undefined

#### Live demo with steps to reproduce
http://jsfiddle.net/marklofdahl/re1fjh6y/
Click on "Museums" to drilldown - causes javascript error

#### Product version
Highcharts 8.2

#### Affected browser(s)
all

If the point name is not the same as the parent point, then it does not error.

I worked around it by setting nextTick.label...

    /* wrap Axis.getSlotWidth for 3D, to fix missing label bug */
    Highcharts.wrap(Highcharts.Axis.prototype, 'getSlotWidth', function (proceed, tick) {
        var axis = this;
        var chart = axis.chart;
        var ticks = axis.ticks;
        var gridGroup = axis.gridGroup;
        var width;

        if (axis.categories &&
            chart.frameShapes &&
            chart.is3d() &&
            gridGroup &&
            tick &&
            tick.label) {

            var tickId = tick.pos,
                prevTick = ticks[tickId - 1],
                nextTick = ticks[tickId + 1],
                prevLabel,
                nextLabel;

            if (tickId !== 0 && prevTick && !prevTick.label) {
                prevTick.label = {};
                prevLabel = true;
            }
            if (nextTick && !nextTick.label) {
                nextTick.label = {};
                nextLabel = true;
            }
            width = proceed.apply(axis, [].slice.call(arguments, 1));
            if (prevLabel) {
                delete prevTick.label;
            }
            if (nextLabel) {
                delete nextTick.label;
            }
        } else {
            width = proceed.apply(axis, [].slice.call(arguments, 1));
        }
        return width;
    });
})(Highcharts);

### PR DESCRIPTION
**Pull request by khlieng**
Fixed #14458, drilling down 3d chart points with the same name threw.

### CODE REVIEW

File: ts/Core/Axis/Axis3D.ts [hunk 1]
```diff
@@ -775,7 +775,7 @@ class Axis3D {
             }
             // If next label position is defined, then recalculate its position
             // basing on the perspective.
-            if (nextTick && (nextTick.label as any).xy) {
+            if (nextTick && nextTick.label && (nextTick.label as any).xy) {
```
Comment (pawelfus) [inline ts/Core/Axis/Axis3D.ts:778]: Does it mean we can get rid of `as any` castings above and below? :) Could you try it?

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
