### PR TITLE
bugfix/11483-incorrect-lastvisibleprice-datagrouping

### LINKED ISSUE #11483: [CandleStick] - lastVisiblePrice doesn't follow lastPrice indicator
#### Expected behaviour
The lastVisiblePrice label should follow the last tick price just like the lastPrice indicator.

**Actual behaviour**
lastVisiblePrice doesn't follow lastPrice indicator

**Reproducible live demo:**
https://codesandbox.io/s/reactfunn-003w6

**Steps to reproduce:**
- lastVisiblePrice indicator is not visible on the floating candle.
- Wait till the candle close (1 min). After the candle closes, the lastVisiblePrice indicator appears to follow the closed candle only but not the lastPrice.

**Product version**
7.1.2

Screenshot 2019-07-25 at 12 13 15

### PR DESCRIPTION
**Pull request by sebastianbochan**
Fixed #11483, lastPrice indicator was incorrect with dataGrouping.

### CODE REVIEW

File: samples/unit-tests/indicator-price-indicator/recalculations/demo.js [hunk 1]
```diff
@@ -32,3 +50,47 @@ QUnit.test('Price indicator.', function (assert) {
...
+                },
+                data: getData()
+            }]
+        }),
+        series = chart.series[0];
+
+    assert.strictEqual(
+        series.points[series.points.length - 1].y === series.lastVisiblePrice.y,
+        true,
+        'Correct value when datagrouping enabled.'
```
Comment (jon-a-nygaard) [inline samples/unit-tests/indicator-price-indicator/recalculations/demo.js]: Using `Should ....` for test descriptions is preferred practice. Also it would be good if you could describe what the "correct value" is in this context.

File: samples/unit-tests/indicator-price-indicator/recalculations/demo.js [hunk 2]
```diff
@@ -32,3 +50,47 @@ QUnit.test('Price indicator.', function (assert) {
...
+
+    var min = chart.xAxis[0].min,
+        max = min + 100 * 3600;
+
+    chart.xAxis[0].setExtremes(min, max);
+
+    assert.strictEqual(
+        series.points[series.points.length - 1].y === series.lastVisiblePrice.y,
+        true,
+        'Correct value when setExtremes and disabled datagrouping.'
```
Comment (jon-a-nygaard) [inline samples/unit-tests/indicator-price-indicator/recalculations/demo.js]: Same here as previous comment.

Comment (sebastianbochan) [reply samples/unit-tests/indicator-price-indicator/recalculations/demo.js]: Done

File: samples/unit-tests/indicator-price-indicator/recalculations/demo.js (hunk 1 above)
Comment (sebastianbochan) [reply samples/unit-tests/indicator-price-indicator/recalculations/demo.js]: Done

Comment (TorsteinHonsi) [reply samples/unit-tests/indicator-price-indicator/recalculations/demo.js]: Since we're discussing assertion best practices - there is no point using `strictEqual` with a strict equal comparison in the first parameter and `true` in the second parameter. That is an `assert.ok` statement. Instead, write it like this: 

```js
assert.strictEqual(
        series.points[series.points.length - 1].y === series.lastVisiblePrice.y,
        true,
        'Indicator should show the close value of the last grouped point.'
);
```

File: samples/unit-tests/indicator-price-indicator/recalculations/demo.js (hunk 2 above)
Comment (TorsteinHonsi) [reply samples/unit-tests/indicator-price-indicator/recalculations/demo.js]: Same as my previous comment about strict equals comparison.

File: samples/unit-tests/indicator-price-indicator/recalculations/demo.js [hunk 3]
```diff
@@ -32,3 +50,47 @@ QUnit.test('Price indicator.', function (assert) {
...
+                lastPrice: {
+                    enabled: true,
+                    color: 'red'
+                },
+                data: getData()
+            }]
+        }),
+        series = chart.series[0];
+
+    assert.ok(
```
Comment (TorsteinHonsi) [inline samples/unit-tests/indicator-price-indicator/recalculations/demo.js]: Should be `assert.strictEqual`. Please read QUnit docs.

File: samples/unit-tests/indicator-price-indicator/recalculations/demo.js [hunk 4]
```diff
@@ -32,3 +50,47 @@ QUnit.test('Price indicator.', function (assert) {
...
+        series.lastVisiblePrice.y,
+        'Indicator should show the close value of the last grouped point.'
+    );
+
+    var min = chart.xAxis[0].min,
+        max = min + 100 * 3600;
+
+    chart.xAxis[0].setExtremes(min, max);
+
+    assert.ok(
```
Comment (TorsteinHonsi) [inline samples/unit-tests/indicator-price-indicator/recalculations/demo.js]: Should be `assert.strictEqual`.

File: samples/unit-tests/indicator-price-indicator/recalculations/demo.js (hunk 3 above)
Comment (sebastianbochan) [reply samples/unit-tests/indicator-price-indicator/recalculations/demo.js]: Sorry, I was confused about replacament form above comment.
