### PR TITLE
dash/bugfix-board-destroy-polling-stop

### LINKED ISSUE #23095: Dashboards.board() initiates requests before promise resolution, preventing proper cleanup
Related to issue #22982 

#### Expected behaviour
Calling destroy() on a dashboard should abort any ongoing or pending requests initiated by the dashboard or its connectors — regardless of whether the dashboard has fully mounted.

#### Actual behaviour
When calling Dashboards.board() with a JSON configuration containing connectors, data requests are initiated immediately — even before the Promise returned by Dashboards.board() is resolved.

If destroy() is called before the Promise is fulfilled (i.e., before the board has mounted), the dashboard instance is destroyed, but the underlying data requests continue. This can result in:

- Unnecessary network traffic
- Potential memory/resource leaks
- Unhandled request completions after the dashboard has already been removed

Additionally, in some cases, calling mountedComponents.forEach() may fail if mountedComponents is undefined, likely due to premature access before full initialization.

#### Live demo with steps to reproduce
[JSFiddle](https://jsfiddle.net/trip57/qo2pkt70/20/)

**Steps to reproduce:**

1. Open Chrome DevTools.
2. Let the demo pause on the debugger statement.
3. In the Network tab, enable throttling (e.g., "Slow 3G" or "Custom high latency") to delay data loading.
4. Resume script execution and immediately call destroy() before the dashboard finishes loading.

Observe that network requests continue despite the dashboard being destroyed.

#### Product version
Highcharts Dashboards v3.3.0 (2025-05-15)

#### Affected browser(s)
Version 136.0.7103.114 (64-bit)

### PR DESCRIPTION
**Pull request by KamilKubik**
Fixed #23095, cancel data polling requests after destroying a board.

### CODE REVIEW

File: ts/Data/DataPool.ts [hunk 1]
```diff
@@ -299,16 +299,20 @@ class DataPool implements DataEvent.Emitter {
...
             );
 
             // eslint-disable-next-line @typescript-eslint/no-floating-promises
             connector
                 .load()
-                .then((connector): void => {
-                    this.connectors[options.id] = connector;
+                .then(({ converter, dataTables }): void => {
+                    connector.dataTables = dataTables;
+                    if (converter) {
```
Comment (sebastianbochan) [inline ts/Data/DataPool.ts:312]: It's always true, because you use `connector.dataTables` above. In case of undefined, the error will be earlier.

**Review by sebastianbochan — CHANGES_REQUESTED** [review]

**Review by karolkolodziej — APPROVED** [review]
Please improve the PR msg- [see point 6 and 7.](https://github.com/highcharts/highcharts/blob/master/CONTRIBUTING.md#writing-content-for-the-changelog)

File: ts/Dashboards/Components/ConnectorHandler.ts [hunk 2]
```diff
@@ -93,6 +93,14 @@ class ConnectorHandler {
...
      */
     public presentationTable?: DataTable;
+    /**
+     * Helper flag for detecting whether the connector handler has been
+     * destroyed, used to check and prevent further operations if the connector
+     * handler has been destroyed during asynchronous functions.
+     *
+     * @internal
+     */
+    private destroyed?: boolean;
```
Comment (ddragula) [inline ts/Dashboards/Components/ConnectorHandler.ts]:
```suggestion
     */
    private destroyed?: boolean;
```
Private fields do not need to have the `@internal` flag. They don't show up in the api reference anyway.

File: ts/Data/Connectors/DataConnector.ts [hunk 3]
```diff
@@ -143,6 +143,11 @@ abstract class DataConnector implements DataEvent.Emitter {
      */
     public pollingController?: AbortController;
 
+    /**
+     * Helper flag for detecting whether the data connector is loaded.
+     */
+    public loaded: boolean = false;
```
Comment (ddragula) [inline ts/Data/Connectors/DataConnector.ts]:
```suggestion
    /**
     * Helper flag for detecting whether the data connector is loaded.
     * @internal
     */
    public loaded: boolean = false;
```
There could be `@internal`.

**Review by ddragula — APPROVED** [review]
Seems pretty stable. Thanks!
