### PR TITLE
bugfix/19736-scrollable-indicators

### LINKED ISSUE #19736: Scrollable list of Tech indicators in Stock Tools
#### Expected behaviour
It should be possible to scroll through list of available tech indicators in GUI

#### Actual behaviour
Chart zooms in & out instead 

#### Live demo with steps to reproduce
https://www.highcharts.com/demo/stock/stock-tools-gui

#### Product version
Stock v11.1.0+, version v11.0.0+ are fine

#### Affected browser(s)
All

### PR DESCRIPTION
**Pull request by DJTechnoo**
Fixed #19736 , `mouseWheel` zooming prevented scrolling in Stock Tools popups.

### CODE REVIEW

File: ts/Extensions/MouseWheelZoom/MouseWheelZoom.ts [hunk 1]
```diff
@@ -24,6 +24,7 @@ import type BBoxObject from '../../Core/Renderer/BBoxObject';
 import type { YAxisOptions } from '../../Core/Axis/AxisOptions';
 
 import U from '../../Core/Utilities.js';
+import DOMElementType from '../../Core/Renderer/DOMElementType';
```
Comment (pawelfus) [inline ts/Extensions/MouseWheelZoom/MouseWheelZoom.ts:27]: I believe you can simply import `DOMElementType` type 🤔

**Review by pawelfus — CHANGES_REQUESTED** [review]
Minor improvements, otherwise looks good!

**Review by kamil-musialowski — CHANGES_REQUESTED** [review]
Looks good and works good! 

The original issue is resolved, however one still remains:
- add any label, line, annotation (whatever) to the chart,
- click on it, then click on the pencil icon to edit it,
- try to scroll the edit popup

I don't think it makes any sense to create a separate issue for that, so could you also look into that @DJTechnoo?

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!

**Review by pawelfus — CHANGES_REQUESTED** [review]
Looks good now, but if you could check the suggestion by Kamil, that would be great. If it's a simple fix, let's include it in this PR

**Comment by DJTechnoo** [comment]
I am adding a fix very soon

**Review by pawellysy — APPROVED** [review]

**Review by pawelfus — APPROVED** [review]
Thanks!
