### PR TITLE
dash/fix-duplicated-ids

### LINKED ISSUE #20661: Dashboards: ID collisions causes undefined behavior when rendering
#### Expected behaviour

Using the same ID for grid columns should work fine across Dashboards instances.

#### Actual behavior

I noticed that when instantiating several dashboards on the same page where there are colliding ID's between cells and/or layouts between them, it will render severally garbled.

Presumably this is due to using  `getElementById` instead of keeping references to created nodes around, but that's just a hunch..

My use-case is probably not that strange - this is for an app that cycles various dashboards, and they mostly have a 3x2 layout, so I was initially re-using the layout config object across multiple dashboards. In my case, the boards where quite large, and froze the page for a couple of minutes when loading.

#### Live demo with steps to reproduce
https://jsfiddle.net/y7c4a6k8/ 

#### Affected browser(s)

Latest Firefox and Chrome on Linux

### PR DESCRIPTION
**Pull request by sebastianbochan**
Fixed #20661, dashboards were broken when used non-unique ids of cells.

### CODE REVIEW

**Review by jomar-honsi — APPROVED** [review]

File: samples/dashboards/cypress/duplicated-ids/demo.mjs [hunk 1]
```diff
@@ -0,0 +1,78 @@
+
+// Bring in other forms of Highcharts
+import Dashboards from '../../../../code/dashboards/es-modules/masters/dashboards.src.js';
+import EditMode from '../../../../code/dashboards/es-modules/masters/modules/layout.src.js';
+import DataGrid from '../../../../code/datagrid/es-modules/masters/datagrid.src.js';
+import Highcharts from '../../../../code/es-modules/masters/highcharts.src.js';
+
+Dashboards.HighchartsPlugin.custom.connectHighcharts(Highcharts);
+Dashboards.DataGridPlugin.custom.connectDataGrid(DataGrid);
```
Comment (karolkolodziej) [inline samples/dashboards/cypress/duplicated-ids/demo.mjs:9]: No need for all the Data Grid related stuff here

File: test/cypress/dashboards/integration/layout.cy.js [hunk 2]
```diff
@@ -144,3 +144,21 @@ describe('Chart synchronized series state', () => {
...
 
 });
+
+describe('Components in multiple layouts', () => {
+    before(() => {
+        cy.visit('/dashboards/cypress/duplicated-ids');
+    })
+
+    it('Components should be placed in different dashboards', () => {
+        cy.window().its('Dashboards.boards').should('have.length.gte', 1).then(boards => {
```
Comment (karolkolodziej) [inline test/cypress/dashboards/integration/layout.cy.js:154]: Isn't it safer to check if the length is 2? Isn't it what we expect here? 
The `gte` is a bit confusing

**Review by karolkolodziej — APPROVED** [review]

File: test/cypress/dashboards/integration/layout.cy.js (hunk 2 above)
Comment (sebastianbochan) [reply test/cypress/dashboards/integration/layout.cy.js:154]: I can simplify it.

**Review by Vazonik — APPROVED** [review]
