### PR TITLE
bugfix/23712-infinity-loop

### LINKED ISSUE #23712: Infinte reflow when chart in inside child of flex container
The issue comes when the chart container is placed as a child of an element without height defined (`height: auto`), which itself is a child of a flex container.
In that case, if the chart container has a styling definition with `height: 100%` and some `min-height` set, the presence of a sibling may trigger an infinite reflow loop. That seems to happen because, at the beginning, the browser doesn't know which height the flex child will have, so it first gives the `min-height` of the chart container + the height of its sibling. As the chart container also has `height: 100%`, it will end up taking the calculated (`min-height` + sibling height) value. That seems to be enough to trigger an infinite reflow loop as the new chart will keep growing by the amount of the sibling height each time.

#### Expected behaviour
No infinite reflow

#### Actual behaviour
Infinite reflow

#### Live demo with steps to reproduce
https://jsfiddle.net/diegocardoso/4c2fksrp/21/

1. Open the jsfiddle link
2. Click in any of the buttons

#### Product version
Highchart core, latest

#### Affected browser(s)
Tested on Chrome, Safari, and Firefox

### PR DESCRIPTION
**Pull request by sebastianbochan**
Fixed #23712, flex caused infinite chart reflows

### CODE REVIEW

File: ts/Core/Chart/Chart.ts [hunk 1]
```diff
@@ -1884,11 +1884,13 @@ class Chart {
...
             containerBox = chart.getContainerBox(),
-            enableDefaultHeight = containerBox.height <= 1 ||
-                ( // #21510, prevent infinite reflow
-                    !chart.renderTo.parentElement?.style.height &&
-                    chart.renderTo.style.height === '100%'
-                );
+            renderTo = chart.renderTo,
+            parent = renderTo.parentElement,
+            parentHeight = !parent?.style.height ||
+                (parent.style.height === '100%' && parent.style.minHeight),
```
Comment (TorsteinHonsi) [inline ts/Core/Chart/Chart.ts]: Seems like this check is too specific. For example, by changing the parent height to 99% in the OP demo, the issue prevails: https://jsfiddle.net/ryaxjhsg/ .

File: samples/unit-tests/chart/reflow/demo.html [hunk 2]
```diff
@@ -14,3 +14,14 @@
...
+<!-- #23712: flex child with height 100% + min-height causes infinite reflow -->
+<button id="change-height">Change height</button>
+<div style="display: flex;" id="wrapper">
+    <div style="width: 100%;" id="child">
+        <div style="height: 100%; min-height: 500px;">
+            <div style="height: 100%" id="container3"></div>
+        </div>
+        <div id="blue-div" style="height: 5px;"></div>
+    </div>
+</div>
```
Comment (TorsteinHonsi) [inline samples/unit-tests/chart/reflow/demo.html]: This test will work in the utils, but not in the Playwright test runner, where `demo.html` is not used. It will result in a false positive because of line 347 in demo.js. I think this is a good case for a native Playwright test with full page setup. Alternatively, use QUnit, but build the DOM structure in JavaScript instead.

File: ts/Core/Chart/Chart.ts (hunk 1 above)
Comment (sebastianbochan) [reply ts/Core/Chart/Chart.ts]: I used the regexp instead (its more generic now), I hope that was your intention.

Comment (TorsteinHonsi) [reply ts/Core/Chart/Chart.ts]: It's still easy to break it, for example by [defining the styles in a style sheet](https://jsfiddle.net/highcharts/1eqtp24k/1/).

My intention actually was that we should find a more generic and robust way to deal with this. The basic problem, as I understand it, is that the red div's height is set to 100%, but its parent doesn't have a height, so the parent's height is content driven. But this parent's height includes the blue div. So when the red div has a height of 100% and we render the chart into it, it expands to fill to 100%, then the chart redraws, then the red div expands again, and so we're caught in the loop. 

We should find a generic way to break out of this loop. I tried one thing that may work. Currently, in the `reflow` function, there is a block that compares the container height to the old height.

https://github.com/highcharts/highcharts/blob/25fe97fd7446f9f20b55c363a0ecece9180e4f58/ts/Core/Chart/Chart.ts#L2289-L2292

At this point, the container height has increased, so the condition returns true. I succeeded stopping the loop by updating the `containerBox.height` directly after `setSize` had run, so that it contains the reflowed element height.

```ts
// Set size, it may have been destroyed in the meantime
// (#1257)
if (chart.container) {
    chart.setSize(void 0, void 0, false);
    chart.containerBox.height = chart.getContainerBox().height; // <== Added this to stop the loop
}
``` 

I haven't run regression tests on this, but I think the solution lies somewhere here. Next up would be to see if this works, and if it does, see if we can refine it. For example if we can avoid setting this twice.

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]

File: ts/Core/Chart/Chart.ts (hunk 1 above)
Comment (sebastianbochan) [reply ts/Core/Chart/Chart.ts]: @TorsteinHonsi 
Thanks for the suggestions, you are right, and it looks like even simpler, though.

```
const box = chart.containerBox;
if (box) {
     box.height = chart.chartHeight;
}
```

Instead of calling `getContainerBox()` again, the code now uses `chart.chartHeight`, which is already set after `setSize()`

This solution:
- avoids a second `getContainerBox()` call
- avoids setting the height twice
- keeps the reflow fix working as intended

Comment (TorsteinHonsi) [reply ts/Core/Chart/Chart.ts]: 🎉
