### PR TITLE
bugfix/16896-hovering-map

### LINKED ISSUE #16896: Highmaps: Script error is seen on hover of map series when we have map and mapbubble series if shared tooltip is ON
#### Expected behaviour
Error should not be seen when user tries to view tooltip on highmap.

#### Actual behaviour
Plot highmap using map and mapbubble series with tooltip enabled. On hover of the series, script error is seen on console.

Uncaught TypeError: Cannot read properties of undefined (reading 'pos')
    at h.b.searchPoint (highmaps.src.js:38031)
    at highmaps.src.js:26988
    at Array.forEach (<anonymous>)
    at b.findNearestKDPoint (highmaps.src.js:26984)
    at b.getHoverData (highmaps.src.js:27154)
    at b.runPointActions (highmaps.src.js:27829)
    at b.onContainerMouseMove (highmaps.src.js:27458)

#### Live demo with steps to reproduce
https://jsfiddle.net/amrutaJgtp/4q7ysh8k/1

#### Product version
Latest version v9.3.2

#### Affected browser(s)
All

### PR DESCRIPTION
**Pull request by karolkolodziej**
Fixed #16896, hovering over `mapbubble` with shared tooltip caused an error.

### CODE REVIEW

File: ts/Series/MapBubble/MapBubbleSeries.ts [hunk 1]
```diff
@@ -248,6 +250,8 @@ extend(MapBubbleSeries.prototype, {
 
     processData: MapSeries.prototype.processData,
 
+    searchPoint: noop as any, // #16896
```
Comment (raf18seb) [inline ts/Series/MapBubble/MapBubbleSeries.ts:253]: What about other series types (not only a `mapbubble`)? As far as I know, `tooltip.shared` doesn't work for all the Highcharts Maps series, so maybe we can remove this function from the whole Maps product (`map` series, the rest inherits from `map`)?

File: samples/unit-tests/maps/mapbubble-linewidth/demo.js [hunk 2]
```diff
@@ -1,41 +1,55 @@
...
+        'MapBubble with linewidth- points should have stroke width.'
+    );
+
+    chart.update({
+        tooltip: {
+            shared: true
+        }
+    });
+    // Hover over the chart.
+    controller.mouseMove(200, 200);
```
Comment (raf18seb) [inline samples/unit-tests/maps/mapbubble-linewidth/demo.js:49]: Instead of using TestController, you can simulate hovering with
```js
chart.pointer.runPointActions({ chartX: 400, chartY: 300 });
```

TestController is good, it's your call what you choose. IMHO my way is a little bit easier and faster

**Review by raf18seb — CHANGES_REQUESTED** [review]

File: ts/Series/MapBubble/MapBubbleSeries.ts (hunk 1 above)
Comment (TorsteinHonsi) [reply ts/Series/MapBubble/MapBubbleSeries.ts:253]: It looks like at least the `map` series is covered (it has `searchPoint: noop`.

However, it may be that we actually want to use k-d-search with the MapBubble. So I propose not setting it to noop but rather implement it:

```ts
    public searchPoint(e: PointerEvent, compareX?: boolean): Point | undefined {
        return this.searchKDTree({
            clientX: e.chartX - this.chart.plotLeft,
            plotY: e.chartY - this.chart.plotTop
        }, compareX, e);
    }
```

File: ts/Series/MapBubble/MapBubbleSeries.ts [hunk 3]
```diff
@@ -248,6 +262,8 @@ extend(MapBubbleSeries.prototype, {
...
```
Comment (TorsteinHonsi) [inline ts/Series/MapBubble/MapBubbleSeries.ts:265]: Forgot to remove this line? 🤔

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]

**Review by raf18seb — APPROVED** [review]
Thanks!

File: ts/Series/MapBubble/MapBubbleSeries.ts (hunk 3 above)
Comment (karolkolodziej) [reply ts/Series/MapBubble/MapBubbleSeries.ts:265]: indeed! Thanks!

**Review by TorsteinHonsi — APPROVED** [review]
