### PR TITLE
bugfix/10106-showempty-and-hasdata-fix

### LINKED ISSUE #10106: axis.showEmpty does not hide title in heatmap
#### Expected behaviour

Axis titles should be hidden, similar to the behaviour for a line series: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/yaxis/showempty/

#### Actual behaviour

Axis titles are still displayed, even if there is no data being shown.

#### Live demo with steps to reproduce
https://jsfiddle.net/monicajianu/64owL3df/

#### Product version
Highcharts v7.0.2

#### Affected browser(s)
All

### PR DESCRIPTION
**Pull request by Basts**
Fixed #10106, moving hasData from no-data-modules to Axis.js and Series.js to repair showEmpty feature.

### CODE REVIEW

File: js/parts-map/ColorAxis.js [hunk 1]
```diff
@@ -558,6 +558,12 @@ extend(ColorAxis.prototype, {
         });
     },
 
+    // Define hasData function for non-cartesian seris.
```
Comment (KacperMadej) [inline js/parts-map/ColorAxis.js]: The comment is about series, but this is a colorAxis.
Also, there's another problem with comments - a repeated typo: `seris`

File: js/parts/Axis.js [hunk 2]
```diff
@@ -5591,15 +5591,8 @@ H.extend(Axis.prototype, /** @lends Highcharts.Axis.prototype */{
...
-        return (
-            this.hasVisibleSeries ||
-            (
-                defined(this.min) &&
-                defined(this.max) &&
-                this.tickPositions &&
-                this.tickPositions.length > 0
-            )
-        );
+        return this.series.some(s => s.hasData()) ||
```
Comment (TorsteinHonsi) [inline js/parts/Axis.js]: Arrow functions can't be used in source code yet.
