### PR TITLE
bugfix/17359-polar-stickyTracking 

### LINKED ISSUE #17359: Sticky tracking doesn't work for charts with polar=true config
#### Expected behaviour
Sticky tracking works exactly as expected when polar = false, but not when polar = true

#### Actual behaviour
Sticky tracking should work with chart having config polar = true

Reference: https://www.highcharts.com/forum/viewtopic.php?t=45216

#### Live demo with steps to reproduce
 https://jsfiddle.net/patonomatic/a5bmw0se/6 (polar) vs https://jsfiddle.net/patonomatic/a5bmw0se/9 (non-polar)

#### Product version
Highcharts - 9.3.3

### PR DESCRIPTION
**Pull request by karolkolodziej**
Fixed #17359, `stickyTracking` was not respected correctly for polar charts.

### CODE REVIEW

File: ts/Core/Pointer.ts [hunk 1]
```diff
@@ -795,8 +795,9 @@ class Pointer {
             [hoverSeries as any] :
             // Filter what series to look in.
             series.filter(function (s): boolean {
-                return eventArgs.filter ? eventArgs.filter(s) : filter(s) &&
-                    s.stickyTracking;
+                return eventArgs.filter ?
+                    eventArgs.filter(s) && s.stickyTracking :
+                    filter(s) && s.stickyTracking;
```
Comment (TorsteinHonsi) [inline ts/Core/Pointer.ts:800]: Looks like we can trim this expression a bit?
```ts
            series.filter((s): boolean => s.stickyTracking &&
                (eventArgs.filter || filter)(s));
```

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks! I think we can combine the condition a bit to become denser.

File: ts/Core/Pointer.ts (hunk 1 above)
Comment (TorsteinHonsi) [reply ts/Core/Pointer.ts:800]: I think the requested change was applied to the wrong filter function... I requested a change to the filter function on line 798, but it was applied to the one on line 815, probably altering the functionality.

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
