### PR TITLE
bugfix/24114-reduce-navigator-instance-events

### LINKED ISSUE #24057: Stock chart navigator scroll is not performant
#### Expected behaviour
Navigator scroll should be performant.

#### Actual behaviour
Navigator scroll can be quite laggy, from what I can tell there are 2 sources:

1. Navigator.addMouseEvents is called 3 times during chart init meaning each mouse movement triggers navigator.onMouseUp (which ultimately redraws the chart) 3 times. This should only be added once.

2. Navigator 'setRange' event is added to the Navigator class. When multiple stock charts are on the same page this means every Navigator will accumulate the setRange events. https://github.com/highcharts/highcharts/blob/17bd5d5de6c92dc8ccf973cf2627ff332cd7a2f3/ts/Stock/Navigator/Navigator.ts#L2170

The end result is that while dragging the navigator around the chart ends up redrawing 3 * (# of charts on page) times more than it should.

#### Live demo with steps to reproduce
https://jsfiddle.net/kohlglenn/19ndxg56/

- See # of times addMouseEvents is called for 3 charts (9 total, 3 is expected)
- See # of setRange events added for chart1 navigator (3 total, 1 is expected)

#### Product version
Highcharts Stock

#### Affected browser(s)
Chrome

### LINKED ISSUE #24114: setExtremes event is called multiple times on navigator mouse click and touch
#### Expected behaviour
Event should be fired once when clicking or tapping on not selected part of the navigator.
#### Actual behaviour
Event is often fired multiple times. 
Using touch fires the event at least double the above. 
**Notice that dragging the whole navigator selection or changing it's min/max fires the event only once.** 

#### Live demo with steps to reproduce
[https://jsfiddle.net/8vjrku0w/1/](https://jsfiddle.net/8vjrku0w/1/)

1. Click on navigator outside of currently selected range. Try few times, as it does not occur for every click. 
2. Check console for multiple console logs

#### Product version

Highcharts Stock latest 12.5.0
#### Affected browser(s)
I can replicate it on Chrome and Firefox

### PR DESCRIPTION
**Pull request by kamil-musialowski**
Fixed #24114, #24057 `setExtremes`  and `setRange` event was called more than once on navigator.

**Review notes:**

- This PR removes additional functions added in #24115, and simplifies the events logic back to reduce file size.
- Thanks to @DJTechnoo `if statement` improvements in #24115 I could remove unnecessary mouseEvents additions added in f30f96b12ff2f2aade65c47f81db2032b6a68b28, bringing us back to one `setExtremes` call per one click. My thinking in that commit was incorrect, and a valid fix was to change the if statement, not to add new event.
- Added fix #24057, to not create new PR for such small and related code change.
- Due to the large amount of `as any` castings I decided to remove those that won't affect the Navigator internal logics, I'd recommend reviewing this PR by going through commits one-by-one to avoid changes from [Removed great amount of as any castings in Navigator.ts.](https://github.com/highcharts/highcharts/commit/efaf006b30a31d5b59f8c76f135e8f487ea179f6) mixing with the actual logic changes.

### CODE REVIEW

File: ts/Stock/Navigator/Navigator.ts [hunk 1]
```diff
@@ -163,14 +163,15 @@ class Navigator {
     public left!: number;
     public mouseMoveHandler?: Function;
     public mouseUpHandler?: Function;
-    public navigatorEnabled!: boolean;
+    public navigatorEnabled?: boolean;
```
Comment (pawelfus) [inline ts/Stock/Navigator/Navigator.ts]: Why this change? It is set in constructor, so shouldn't be `navigatorEnabled!` ?

File: ts/Stock/Navigator/Navigator.ts [hunk 2]
```diff
@@ -552,6 +550,19 @@ class Navigator {
                         .css(mouseCursor);
                 }
             });
+
+            if (redrawHandles) {
```
Comment (pawelfus) [inline ts/Stock/Navigator/Navigator.ts:554]: This flag is set always for the second handle. I guess it is unlikely to update just one handle though.

File: ts/Stock/Navigator/Navigator.ts [hunk 3]
```diff
@@ -1284,13 +1265,11 @@ class Navigator {
...
-                unbind();
-            });
-            this.eventsToUnbind = void 0;
-        }
-        this.removeShadesAndHandlesEvents();
+        this.eventsToUnbind?.forEach((unbind: Function): void => {
+            unbind();
+        });
+        this.eventsToUnbind = void 0;
+
```
Comment (pawelfus) [inline ts/Stock/Navigator/Navigator.ts:1274]: Q: No need to remove `partsEventsToUnbind`?

File: ts/Stock/Navigator/Navigator.ts (hunk 1 above)
Comment (kamil-musialowski) [reply ts/Stock/Navigator/Navigator.ts]: We could go back to `navigatorEnabled?` but then, everywhere in this file where navigator is accessed we should then check if it's not undefined (that's why there were so many `as any` castings).

File: ts/Stock/Navigator/Navigator.ts (hunk 3 above)
Comment (kamil-musialowski) [reply ts/Stock/Navigator/Navigator.ts:1274]: No need for that, since these events get removed when we destroy DOM elements (handles and shades). 

Therefore, we might delete the part responsible for removing `eventsToUnbind` as well (as discussed on Slack).

Comment (pawelfus) [reply ts/Stock/Navigator/Navigator.ts:1274]: No removing of `eventsToUnbind` array. That array should store event attached to elements outside the Naviagtor's universe (eg `chart.renderTo`, `xAxis` or `series`) - which are not destroyed on Nav's update, and we want to avoid events' duplication.

**Review by pawelfus — CHANGES_REQUESTED** [review]
Could you merge master branch in? Too many tools have failed.

File: ts/Stock/Navigator/Navigator.ts [hunk 4]
```diff
@@ -926,11 +907,11 @@ class Navigator {
     public getPartsEvents(
         eventName: string
     ): Array<Function> {
-        const navigator = this,
+        const navigator = this as any,
```
Comment (pawelfus) [inline ts/Stock/Navigator/Navigator.ts]: I don't recommend casting to any `this`. Even if it's used in the function only with other as any casting. In the future someone might make a type `navigator.scrolIbar` and it will be easy to miss out that.

File: ts/Stock/Navigator/Navigator.ts [hunk 5]
```diff
@@ -926,11 +907,11 @@ class Navigator {
...
             events = [] as Array<Function>;
 
         ['shades', 'handles'].forEach(function (name: string): void {
```
Comment (pawelfus) [inline ts/Stock/Navigator/Navigator.ts]: If you really want to get rid of as any below, then `(['shades', 'handles'] as const)` should work.

Then later you should be able to use ```navigator[`${name}Mousedown`](e, index);``` (not tested)

File: ts/Stock/Navigator/Navigator.ts (hunk 1 above)
Comment (pawelfus) [reply ts/Stock/Navigator/Navigator.ts]: I think I'm missing something here still. I mean, you still have a lot of `navigator?`. And this is true to all.

File: ts/Stock/Navigator/Navigator.ts [hunk 6]
```diff
@@ -552,6 +550,19 @@ class Navigator {
                         .css(mouseCursor);
                 }
             });
+
+            if (redrawHandles) {
+                navigator.partsEventsToUnbind?.forEach(
+                    (unbind: Function): void => {
+                        unbind();
+                    }
+                );
```
Comment (pawelfus) [inline ts/Stock/Navigator/Navigator.ts:559]: Q: As discussed, try removing this `partsEventsToUnbind` array completely and double-check. If you are right in the implementation, then DOM elements are removed beforehand (with events), thus no need to store them.

Comment (pawelfus) [reply ts/Stock/Navigator/Navigator.ts:559]: Never mind, we need this. It possible to update only one handle (second one). Then the first one is not removed, but without this unbinder, we end up with duplicated events. Keep it.

File: ts/Stock/Navigator/Navigator.ts
Comment (pawelfus) [inline ts/Stock/Navigator/Navigator.ts]: Could you add a comment that shades and handles events are added elsewhere?

File: samples/unit-tests/navigator/navigator/demo.js [hunk 7]
```diff
@@ -80,6 +119,31 @@ QUnit.test(
             plotSizeYAfter,
             'Navigator toggle should not shrink the chart. (#21775)'
         );
+
+        leftHandle = chart.navigator.handles[0];
```
Comment (PaulDalek) [inline samples/unit-tests/navigator/navigator/demo.js:123]: Question: Do the `leftHandle` and `rightHandle` need to be reassigned?

Comment (kamil-musialowski) [reply samples/unit-tests/navigator/navigator/demo.js:123]: Yes, we do because in https://github.com/highcharts/highcharts/blob/8754b4d526bed04fbec5e52f3f0b5233449bab68/samples/unit-tests/navigator/navigator/demo.js#L103-L114 we disable and enable navigator (so old handles are destroyed and reference to them is lost)

**Review by pawelfus — APPROVED** [review]
Thanks!
