### PR TITLE
bugfix/19740-marker-clusters-datetime

### LINKED ISSUE #19740: Cluster Markers Crash Browser Tab when using a Datetime series with Timestamps in Milliseconds
#### Expected behaviour
Cluster markers should work whether there are 0, 1 or 100 data points in the series. They should also work with date time axis that provide a millisecond-level precision.

#### Actual behaviour
When using milliseconds as the X axis unit, while the X axis is set to the 'datetime' type, the clustering code will spin infinitely, making the page unresponsive. This causes the page to crash, rendering debugging using devtools impossible. Dividing the X axis units by 1000 lets the page work as intended again.

#### Live demo with steps to reproduce
https://jsfiddle.net/sbyLerpo/24/

Set the multiplier to 1 and reload the page in order to see it work again.

#### Product version
Latest version on https://code.highcharts.com/, highcharts 11.4.0 and highcharts-vue 1.4.3

#### Affected browser(s)
Tested on Firefox, Chrome

### PR DESCRIPTION
**Pull request by wchmiel**
Fixed #19740, marker clusters with datetime axes froze the browser when x values were millisecond timestamps.

### CODE REVIEW

File: ts/Extensions/MarkerClusters/MarkerClusterScatter.ts [hunk 1]
```diff
@@ -1481,7 +1482,10 @@ function seriesGetScaledGridSize(
     const gridSize = mapView ?
         series.gridValueSize * mapView.getScale() :
         xAxis.toPixels(series.gridValueSize) - xAxis.toPixels(0);
-    const scale = +(processedGridSize / gridSize).toFixed(14);
+
+    // Fix, #19740: Prevent division by zero error.
+    const scale = gridSize > 0 ?
```
Comment (pawelfus) [inline ts/Extensions/MarkerClusters/MarkerClusterScatter.ts]: I think you should strictly check for `0`. In reversed xAxis, the results can be negative: https://jsfiddle.net/BlackLabel/v6eugcr5/1/ - which always will return `scale = 1` which probably is not. Alternatively, `gridSize` could be Math.abs'ed in the line above.

**Review by pawelfus — CHANGES_REQUESTED** [review]
Thanks! Just one tiny thing.

File: ts/Extensions/MarkerClusters/MarkerClusterScatter.ts (hunk 1 above)
Comment (PaulDalek) [reply ts/Extensions/MarkerClusters/MarkerClusterScatter.ts]: I also think it should be wrapped with the `Math.abs` function, otherwise the `scale` could become -1 and the loop might never stop. Something like this:

`const scale = gridSize !== 0 ? Math.abs(+(processedGridSize / gridSize).toFixed(14)) : 1;`

File: tests/highcharts/series/series-marker-clusters.spec.ts [hunk 2]
```diff
@@ -216,4 +216,62 @@ test.describe('series/marker-clusters', {
...
+            modules: ['modules/marker-clusters.js']
+        });
+
+        // Ensure the page event loop is responsive right after chart creation.
+        // A blocked main thread would prevent the timer from firing.
+        await page.evaluate(() => new Promise<void>(resolve => {
+            window.setTimeout(() => resolve(), 0);
+        }));
+
+        expect(
```
Comment (PaulDalek) [inline tests/highcharts/series/series-marker-clusters.spec.ts:293]: I would also add a test that checks the reversed axis.

**Review by PaulDalek — CHANGES_REQUESTED** [review]

**Review by PaulDalek — APPROVED** [review]
Nice job, now it works!

**Review by DJTechnoo — APPROVED** [review]
LGTM! 🎉

**Review by pawelfus — APPROVED** [review]
Thanks!

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
