### PR TITLE
bugfix/21530-numbers-padding-categories

### LINKED ISSUE #21530: Numbers on axis labels
#### Details
- I have bubble chart with text values on xAxis. But chart extremes returning not existent numeric values. Can you check if this is a wrong implementation or HC bug?

#### Expected behaviour
- Axis rendered without numbers

#### Actual behaviour
- Axis rendered with numbers on extremes

image

#### Live demo with steps to reproduce
- https://codesandbox.io/p/sandbox/spring-cookies-6wmrdw?file=%2Fsrc%2FExample.tsx

- **Note**: if don't see the numbers, resize codesandbox preview tab. 

#### Product version
- Highcharts - 11.3.0

#### Affected browser(s)
- Google Chrome

### PR DESCRIPTION
**Pull request by MarkusBarstad**
Fixed #21530, tick values were padded onto user-defined category axes

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1207792651837956

### CODE REVIEW

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks, the fix looks good! 

A little spice should be added to the PR:
* A unit test.
* Some comment(s) within the actual code explaining why we are doing this, and with a reference to the issue. Will save our futures selves from some head scratching.

File: ts/Series/Bubble/BubbleSeries.ts [hunk 1]
```diff
@@ -175,6 +175,41 @@ function onAxisFoundExtremes(
...
+            dataMin = 0,
+            dataMax = 0,
+            categories,
+            options,
+            series
+        } = this,
+        type = options.type;
+
+    if (series.find((s): boolean => s.bubblePadding === true)) {
+        if ((categories && categories.length) || type === 'category') {
```
Comment (TorsteinHonsi) [inline ts/Series/Bubble/BubbleSeries.ts:197]: These two if's can be combined into one. Run the `categories?.length` check first because it is cheaper than `find`.

File: ts/Series/Bubble/BubbleSeries.ts [hunk 2]
```diff
@@ -175,6 +175,41 @@ function onAxisFoundExtremes(
...
+    const {
+            ticks,
+            tickPositions,
+            dataMin = 0,
+            dataMax = 0,
+            categories,
+            options,
+            series
+        } = this,
+        type = options.type;
```
Comment (TorsteinHonsi) [inline ts/Series/Bubble/BubbleSeries.ts:194]: Doens't really need a constant since it's only used once.

File: ts/Series/Bubble/BubbleSeries.ts [hunk 3]
```diff
@@ -175,6 +175,41 @@ function onAxisFoundExtremes(
...
+        if ((categories && categories.length) || type === 'category') {
+            let tickCount = tickPositions.length;
+
+            while (tickCount--) {
+                const tick = ticks[tickPositions[tickCount]],
+                    pos = tick.pos || 0;
+
+
+                if (tick.label && (pos > dataMax || pos < dataMin)) {
+                    tick.label.hide();
```
Comment (TorsteinHonsi) [inline ts/Series/Bubble/BubbleSeries.ts:206]: Slightly terser:

```suggestion
                if (pos > dataMax || pos < dataMin) {
                    tick.label?.hide();
```

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks, it works well!

File: ts/Series/Bubble/BubbleSeries.ts [hunk 4]
```diff
@@ -175,6 +175,42 @@ function onAxisFoundExtremes(
...
+            ticks,
+            tickPositions,
+            dataMin = 0,
+            dataMax = 0,
+            categories
+        } = this,
+        type = this.options.type;
+
+    if (
+        ((categories && categories.length) || type === 'category') &&
```
Comment (TorsteinHonsi) [inline ts/Series/Bubble/BubbleSeries.ts:195]:
```suggestion
        (categories?.length || type === 'category') &&
```

File: ts/Series/Bubble/BubbleSeries.ts [hunk 5]
```diff
@@ -175,6 +175,42 @@ function onAxisFoundExtremes(
...
+        this.series.find((s): boolean => s.bubblePadding === true)
```
Comment (TorsteinHonsi) [inline ts/Series/Bubble/BubbleSeries.ts:196]:
```suggestion
        this.series.find((s): boolean|undefined => s.bubblePadding)
```

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Another two possibilities for squeezing out bytes

**Comment by MarkusBarstad** [comment]
@TorsteinHonsi Good catches!

**Review by TorsteinHonsi — APPROVED** [review]
