### PR TITLE
bugfix/10555-scrollablePlotArea-absolute

### LINKED ISSUE #10555: scrollablePlotArea does not work properly on Firefox
#### Expected behaviour
scrollablePlotArea should work correctly on all browsers.

#### Actual behaviour
scrollablePlotArea doesn't work on Firefox.

#### Live demo with steps to reproduce
view: https://jsfiddle.net/BlackLabel/ko92esqx/show
editor: https://jsfiddle.net/BlackLabel/ko92esqx/

#### Product version
Highcharts

#### Affected browser(s)
Firefox 64.0 (macOS Mojave 10.14.3)

### PR DESCRIPTION
**Pull request by goransle**
Fixed #10555, scrollablePlotArea not rendering correctly on FireFox.

No fix applied: https://jsfiddle.net/BlackLabel/ko92esqx/show
Fix applied: https://jsfiddle.net/L5zbtc9y/show

### CODE REVIEW

File: ts/Extensions/ScrollablePlotArea.ts [hunk 1]
```diff
@@ -254,10 +254,22 @@ Chart.prototype.setUpScrolling = function (): void {
...
+    // Insert a container with position relative
+    // that scrolling and fixed container renders to (#10555)
+    const relContainer = createElement(
+        'div',
+        void 0,
+        {
+            position: 'relative'
+        },
+        this.renderTo,
+        true
```
Comment (oysteinmoseng) [inline ts/Extensions/ScrollablePlotArea.ts:266]: We probably don't need the `nopad` argument to be `true` for a div?

File: ts/Extensions/ScrollablePlotArea.ts [hunk 2]
```diff
@@ -254,10 +254,22 @@ Chart.prototype.setUpScrolling = function (): void {
         attribs.overflowY = 'auto';
     }
 
+    // Insert a container with position relative
+    // that scrolling and fixed container renders to (#10555)
+    const relContainer = createElement(
+        'div',
+        void 0,
```
Comment (oysteinmoseng) [inline ts/Extensions/ScrollablePlotArea.ts:261]: Would consider adding a class name `highcharts-scrolling-parent` or similar just in case someone needs access to this container. Maybe also store the element on the chart object

File: ts/Extensions/ScrollablePlotArea.ts [hunk 3]
```diff
@@ -355,14 +366,14 @@ Chart.prototype.applyFixed = function (): void {
...
+                top: 0
             },
             null as any,
             true
         );
-        this.renderTo.insertBefore(
-            this.fixedDiv,
-            this.renderTo.firstChild
+        this.scrollingContainer?.parentNode.appendChild(
+            this.fixedDiv
```
Comment (oysteinmoseng) [inline ts/Extensions/ScrollablePlotArea.ts:376]: This puts the fixed container after the scrolling container in the DOM, while it used to be before. Assuming this is not an issue?

Comment (goransle) [reply ts/Extensions/ScrollablePlotArea.ts:376]: Does not seem to be an issue, but I'll restore the order.
