### PR TITLE
bugfix/20792-plotline-html-labels

### LINKED ISSUE #20792: Plotlines with HTML labels render incorrectly (11.4.0 regression)
#### Expected behaviour
Plotlines with HTML labels have their labels rendered next to the plotline

#### Actual behaviour
The label is rendered all the way to the right, see screenshot:
image

#### Live demo with steps to reproduce
https://jsfiddle.net/txsLuny9/1/

#### Product version
Highcharts 11.4.0, we were not seeing this in 11.2.0, not sure about 11.3.0.

#### Affected browser(s)
Noticed in Firefox, reproducible in Chrome

### PR DESCRIPTION
**Pull request by hubertkozik**
Fixed #20792, plotlines HTML labels rendered incorrectly.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1206783142516648

### CODE REVIEW

**Review by MarkusBarstad — APPROVED** [review]
LGTM, works well!

File: samples/unit-tests/plotbandslines/plotbandslines/demo.js [hunk 1]
```diff
@@ -81,8 +88,18 @@ QUnit.test('Plot band labels', function (assert) {
         'Highcharts - after'
     );
 
+    const line = chart.xAxis[0].plotLinesAndBands[3].svgElem.getBBox(),
+        label = chart.xAxis[0].plotLinesAndBands[3].label.getBBox();
+
+    assert.close(
+        line.x,
+        label.x + chart.plotLeft,
+        3,
```
Comment (goransle) [inline samples/unit-tests/plotbandslines/plotbandslines/demo.js:97]: Test is failing for me, maybe the tolerance should be larger?

```sh
Firefox 123.0 (Mac OS 10.15) Highcharts Plot band labels FAILED
        HTML label should be placed (x-pos) near the plot line (#20792).
        Expected: 154
        Actual: 148.5
        @samples/unit-tests/plotbandslines/plotbandslines/demo.js:94:12
        runTest@node_modules/qunit/qunit/qunit.js:2526:35
        run@node_modules/qunit/qunit/qunit.js:2509:16
        queue/runTest/<@node_modules/qunit/qunit/qunit.js:2780:16
        processTaskQueue@node_modules/qunit/qunit/qunit.js:3937:30
        processTaskQueue/<@node_modules/qunit/qunit/qunit.js:3941:23
```

Comment (hubertkozik) [reply samples/unit-tests/plotbandslines/plotbandslines/demo.js:97]: I'm still not sure if that's a good way of testing this feature. I'll try to figure out some different tests.

File: ts/Core/Axis/PlotLineOrBand/PlotLineOrBand.ts [hunk 2]
```diff
@@ -325,7 +325,11 @@ class PlotLineOrBand {
                     align: optionsLabel.textAlign || optionsLabel.align,
                     rotation: optionsLabel.rotation,
                     'class': 'highcharts-plot-' + (isBand ? 'band' : 'line') +
-                        '-label ' + (optionsLabel.className || ''),
+                        '-label' + (
+                        optionsLabel.className ?
+                            '-' + optionsLabel.className :
```
Comment (TorsteinHonsi) [inline ts/Core/Axis/PlotLineOrBand/PlotLineOrBand.ts:330]: This can't be right? So if I set the `className` to `my-label`, the output will be `highcharts-plot-band-label-my-label`? That's not the intension...

Comment (hubertkozik) [reply ts/Core/Axis/PlotLineOrBand/PlotLineOrBand.ts:330]: Ah, you're right. There should be a space and that change was applied before https://github.com/highcharts/highcharts/pull/20708. I'll remove my changes.

**Review by goransle — APPROVED** [review]
Looks good!

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
