### PR TITLE
dash/connector-data-polling-abort-controller

### LINKED ISSUE #22982: Connector Requests Not Aborted After Dashboard Destruction
### Expected Behavior
When a dashboard is destroyed using Dashboards.board().destroy(), all network requests initiated by its connectors should be canceled or aborted immediately.

### Actual Behavior
Destroying the dashboard does not cancel in-progress connector requests. These requests remain in a pending state and continue to await a server response, even though the associated dashboard and its components no longer exist in the DOM.

This can lead to unnecessary network load, especially in conditions with poor connectivity or when multiple components with polling connectors are used.

### Live demo with steps to reproduce
[JSFiddle](https://jsfiddle.net/trip57/qo2pkt70/10/)

**Steps to reproduce:**

1. Open Chrome DevTools and navigate to the Network tab.
2. (Optional but helpful) Enable throttling (e.g., High latency / Low download speed).
3. Wait for a dashboard connector request.
4. While the request is still pending, click the "Destroy dashboard" button.

Observe the network request in DevTools — it remains in a pending state despite the dashboard being destroyed.

**Impact**

- Potential memory leaks and unnecessary bandwidth consumption.
- Noticeable performance degradation under limited network conditions or dashboards with many JSON connectors.

### Product Version
Highcharts Dashboards v3.2.0 (Released: 2025-03-26)

### Affected browser(s)
Tested on Chrome version 135.0.7049.115 64-bit

### PR DESCRIPTION
**Pull request by KamilKubik**
Fixed #22982, added the data connector request abort controller.

### CODE REVIEW

**Review by karolkolodziej — APPROVED** [review]

File: ts/Data/Connectors/DataConnector.ts [hunk 1]
```diff
@@ -100,6 +100,12 @@ abstract class DataConnector implements DataEvent.Emitter {
      */
     public readonly table: DataTable;
 
+    /**
+     * The corresponding request abort controller, which gets assigned when data
+     * polling starts. Used to abort the request when data polling stops.
+     */
+    public abortController?: AbortController;
```
Comment (sebastianbochan) [inline ts/Data/Connectors/DataConnector.ts:107]: 1. I would suggest replacing it with `pollingController`, which is much more meaningful. Especially, that in the further part of code we use `abortController.abort();`
2. The doclet is a bit not understandable.

Comment (KamilKubik) [reply ts/Data/Connectors/DataConnector.ts]: I agree with the naming, and the changes have been pushed. Thanks!

**Review by sebastianbochan — APPROVED** [review]

**Review by skrulling — APPROVED** [review]
Nice
