### PR TITLE
bugfix/15733-missing-label-stock-tools

### LINKED ISSUE #15733: Stock Tools: APO is missing "period" fields in the popup
#### Expected behaviour
"Periods" label should be displayed above the period inputs

#### Actual behaviour
Only "Index" label is displayed, "Periods" is missing:

Zrzut ekranu 2021-05-17 o 17 41 57

#### Live demo with steps to reproduce
[Demo](https://www.highcharts.com/demo/stock/stock-tools-gui)

#### Product
Highcharts Stock

### PR DESCRIPTION
**Pull request by DJTechnoo**
Fixed #15733, missing 'Periods' label in Stock Tools pop-up for some indicators.

### CODE REVIEW

File: ts/Extensions/Annotations/Popup.ts [hunk 1]
```diff
@@ -295,6 +295,23 @@ H.Popup.prototype = {
             lang = this.lang,
             inputName = PREFIX + type + '-' + optionName;
 
+        if (optionParamList.length === 3 && optionName === '0') { // If a label refers to multiple fields (15733)
```
Comment (sebastianbochan) [inline ts/Extensions/Annotations/Popup.ts:298]: Why we use `optionParamList.length === 3` ?

Comment (DJTechnoo) [reply ts/Extensions/Annotations/Popup.ts:298]: Because in the case of 'Periods' (plural), which represents an array of numbers for the input fields, it appends an index. So the `optionsParamList` will look something like `['params', 'periods', '0']`. 
'Periods' seems to be the only case like this.

**Review by sebastianbochan — APPROVED** [review]

**Comment by sebastianbochan** [comment]
@pawellysy any feedback here?

**Comment by khlieng** [comment]
This also fixes #15734 and possibly #15732 right?

**Comment by DJTechnoo** [comment]
> This also fixes #15734 and possibly #15732 right?

Yes, indeed it does fix both 😄

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
