### PR TITLE
Tree.ts now doesnt throw error on missing parents

### LINKED ISSUE #15196: removing parent point in gantt chart does not work as expected
#### Expected behaviour
I expect the row for the data point to be removed and everything else shifted up/redrawn correctly.

#### Actual behaviour
It depends on how you remove the data point.

- If you do a `chart.update(newOptions);` the row is removed, but the collapse icon (the small triangle in the first column) is still shown on a non-parent data point.
- If you remove the point using any other method I could find (`series.removePoint()`, `point.remove()`, `series.setData()`, and `series.update()`), the rectangle in the gantt chart is removed, but the rest of the row's data, including the dependency arrows, remains.

#### Live demo with steps to reproduce
I have commented out the various other methods I have tried.

https://codepen.io/brettk-dev/pen/yLVzvxB

#### Product version

Highgantt 9.0.1

#### Affected browser(s)

- Firefox 85.0.2
- Chrome 88.0.4324.182 (Official Build) (x86_64)
- Safari 14.0.3 (16610.4.3.1.4)

### PR DESCRIPTION
**Pull request by MarkusBarstad**
Fixed #15196, gantt chart threw error when nodes in the data set were orphaned.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1205432171194783

### CODE REVIEW

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks, the fixes look good!

It now fixes part 1 of the issue, which was to render correctly in a static chart when a parent node was missing.

However part 2 still fails - the case when a parent node is dynamically removed. See https://jsfiddle.net/highcharts/ezufy4qc/ . 

I'd say we _can_ merge this right now, as it clearly fixes a bug, but it doesn't fully fix #15196.

File: ts/Gantt/Tree.ts [hunk 1]
```diff
@@ -71,37 +71,40 @@ const getListOfParents = function (
...
-            delete (list as any)[parent];
+    const root = '';
+
+    Object.keys(listOfParents).forEach(
+        (node: string): void => {
+            if ((node !== root) && (ids.indexOf(node) === -1)) {
+                listOfParents[root] = [
+                    ...listOfParents[root],
+                    ...listOfParents[node]
+                ];
```
Comment (goransle) [inline ts/Gantt/Tree.ts:101]: `listOfParents[root].push(...listOfParents[node])` [might be marginally quicker](https://www.measurethat.net/Benchmarks/Show/4223/0/array-concat-vs-spread-operator-vs-push#latest_results_block)

Comment (MarkusBarstad) [reply ts/Gantt/Tree.ts:101]: Cool to know, we will push and not spread in that case! 

On a sidenote, I love that site, but I wish it had a more structured way of browsing it instead of just "the latest" :/

**Comment by TorsteinHonsi** [comment]
Yes it does run without errors, but there are still issues. Apparently related to the ones in the OP, though the OP demo is lost. In your fiddle, after the update, we can see the following issues in the tree grid:

* There's a dead dependency triangle next to "Launch" 
* Clicking "New product launch" does nothing
* On mouseover and mouseout on the triangle next to "New product launch", there are JS errors
* The three orphaned categories do not receive bold font style like root elements should

For clarity, this is how it currently looks after the update...
Skjermbilde 2023-09-15 kl  19 05 59

... while we would expect it to look and function identical to what we get when we start out with the `relocate` node deleted:
Skjermbilde 2023-09-15 kl  19 06 59

**Comment by MarkusBarstad** [comment]
Just an update here, its the TreeGrid-axis code.

**Comment by TorsteinHonsi** [comment]
I put this back to draft mode to get it out of my "review" canban column. Please set it to Ready to review when you're done.

**Comment by MarkusBarstad** [comment]
Another update here, (just to log progress on this bug):
`GridNode.depth` is not being updated which makes it so that `highcharts-treegrid-level-` does not reflect changes to the parent-child structure (at least not in my working case based off of the project-manager demo)

**Comment by MarkusBarstad** [comment]
Note to self regarding the orphaned nodes not showing up on the `yAxis` (using the project-management `demo`):
- Categories are handled ok but;
- Nodes receive a `pos` outside of the `yAxis`-range and `yAxis` does not react to the changes.

Will deal with `labels` and `yAxis` first;
- [ ] Need to make sure the `yAxis` is updated to hold the labels, 
- [ ] Maybe we want to alter where orphaned nodes show up on the `yAxis`.

**Review by goransle — COMMENTED** [review]
Looks good to me. Can we add a karma/cypress test for this?

**Review by goransle — APPROVED** [review]
Seems good to me 👍

**Comment by TorsteinHonsi** [comment]
Thanks so far! The changes look good in general. Maybe you're aware of it, but I noticed a glitch here: https://jsfiddle.net/highcharts/kzhots93/

1. Click the Update button to re-id the Relocate node
2. Click the "New product launch" grid item => nothing happens

File: samples/unit-tests/gantt/gantt/demo.js [hunk 2]
```diff
@@ -411,6 +411,16 @@
...
             'Collapsed graphics should not be rendered (#12617)'
         );
+
+        // Changing id of a parent
+        points[1].update({ id: '_moving' });
+
+        assert.strictEqual(
+            chart.series[0].yAxis.treeGrid.tree.children.length,
+            5,
+            'Orphaned nodes should appear as direct children of root'
```
Comment (hubertkozik) [inline samples/unit-tests/gantt/gantt/demo.js:421]: It would be good to add GH issue number if someone would like to get more information about this test.

File: ts/Core/Axis/TreeGrid/TreeGridAxis.ts [hunk 3]
```diff
@@ -328,12 +328,16 @@ function getTreeGridFromData(
             start: number,
             result: Record<string, GridNode>
         ): Record<string, GridNode> {
-            const nodes = gridNode.nodes,
+
+            const
+                nodes = gridNode.nodes,
```
Comment (hubertkozik) [inline ts/Core/Axis/TreeGrid/TreeGridAxis.ts:333]: Just indentation. I believe we are not making enters (new lines) after `const` or `let`.

**Review by hubertkozik — CHANGES_REQUESTED** [review]
Good job! It's good, that there is no error in the console now. I think the bug mentioned by Torstein should be also fixed in that branch.

File: samples/unit-tests/gantt/gantt/demo.js (hunk 2 above)
Comment (MarkusBarstad) [reply samples/unit-tests/gantt/gantt/demo.js:421]: True! Also I am not completely sure this one unit-test "covers it". 

I suppose visual tests should pick up on this stuff since the stuff in this fix deals with visual errors, but still idk what the praxis is here 😬

File: ts/Core/Axis/TreeGrid/TreeGridAxis.ts (hunk 3 above)
Comment (MarkusBarstad) [reply ts/Core/Axis/TreeGrid/TreeGridAxis.ts:333]: Alright, but I am afraid to tell you, Hubert 😬 , I think I may have been doing this for a while 😆

**Comment by MarkusBarstad** [comment]
> Thanks so far! The changes look good in general. Maybe you're aware of it, but I noticed a glitch here: https://jsfiddle.net/highcharts/kzhots93/
> 
>     1. Click the Update button to re-id the Relocate node
> 
>     2. Click the "New product launch" grid item => nothing happens

Good catch!

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks, it works well now!

I would like to request that Hubert's initial comments were adressed:
* GH issue number reference in the tests (and perhaps in code?) will potentially save us time down the line.
* Go over and change back unnecessary whitespace changes. Newline after `let` and `const`, and there are also new empty lines, presumably remnants of inserting debug and console statements.

**Review by TorsteinHonsi — APPROVED** [review]

**Review by MarkusBarstad — COMMENTED** [review]
LGTM 🚀
