### PR TITLE
Bugfix/11617 scrollable split tooltip

### LINKED ISSUE #11617: split tooltip and scrollbalePlotArea
#### Expected behaviour
Tooltip with full opacity

#### Actual behaviour
Tooltip hidden behind the scrollable mask

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/jbk9qpnx/

Scroll down to the xAxis and hover any point.

Screenshot:

Screen Shot 2019-08-06 at 14 56 35

#### Product version
v7.1.2

### PR DESCRIPTION
**Pull request by jon-a-nygaard**
Fixed #11617, support `tooltip.split` with `chart.scrollablePlotArea`.

---
# Description
Added support for split tooltip with scrollable plot area.

- Limit the tooltip to render within the plot area when `scrollablePlotArea` is enabled.
- Updated `getChartPosition` to use `scrollingContainer` when it exists, to position tooltip correctly when `container` is moved during scrolling. [See #diff-31a7e6aaf7bdf7daa73993cea91fd9efR375]( https://github.com/highcharts/highcharts/compare/bugfix/11617-scrollable-split-tooltip?expand=1#diff-31a7e6aaf7bdf7daa73993cea91fd9efR375)
- Added utility function `clamp`
- Refactored to `renderSplit` to gather logic in smaller sections, added scoped functions `getAnchor`, `defaultPositioner`, and `updateTooltip`. 
- Removed `any` casts in `renderSplit` where possible.

# Example(s)
- [Demo of issue](https://jsfiddle.net/BlackLabel/jbk9qpnx/)
- [Demo of issue with fix applied](https://jsfiddle.net/jon_a_nygaard/q5dhzv2y/)
- [Demo of #11493 with current changes](https://jsfiddle.net/jon_a_nygaard/w3cq1Lt5/) - Manually tested against regressions.
- [Demo of #9590 with current changes](http://jsfiddle.net/jon_a_nygaard/w4L7brqs/) - Manually tested against regressions.

# Related issue(s)
- Closes #11617

### CODE REVIEW

File: ts/parts/Utilities.ts [hunk 1]
```diff
@@ -1314,6 +1314,19 @@ H.merge = function<T> (): T {
...
+/**
+ * Constrain a value to within a lower and upper threshold.
+ *
+ * @private
+ * @param {number} value The initial value
+ * @param {number} min The lower threshold
+ * @param {number} max The upper threshold
+ * @return {number} Returns a number value within min and max.
+ */
+function clamp(value: number, min: number, max: number): number {
```
Comment (TorsteinHonsi) [inline ts/parts/Utilities.ts]: This is a quite frequent operation in Highcharts. Now that we have a utility function for that, we should at the same time identify all other places where it is done, and implement the utility function. Search for places with nested `Math.min` and `Math.max` calls.

File: js/parts/Tooltip.js [hunk 2]
```diff
@@ -8,9 +8,25 @@
  *
  * */
 'use strict';
+var __read = (this && this.__read) || function (o, n) {
```
Comment (TorsteinHonsi) [inline js/parts/Tooltip.js]: See if we can avoid the code that makes TypeScript include this polyfill. Likely candidate is array destructuring.

File: ts/parts/Tooltip.ts [hunk 3]
```diff
@@ -1188,202 +1189,281 @@ H.Tooltip.prototype = {
...
+                xAxis: [{ opposite }]
+            },
+            options,
+            options: {
+                distance = 16,
+                positioner
+            }
+        } = tooltip;
+
+        const boundaries = {
```
Comment (TorsteinHonsi) [inline ts/parts/Tooltip.ts]: From reading this code it looks like in a scrolling chart the boundaries are the _plot area_, whereas it is the whole chart otherwise? Is that because of the masks? In that case, a comment here would help.

File: ts/parts/Tooltip.ts [hunk 4]
```diff
@@ -1188,202 +1189,281 @@ H.Tooltip.prototype = {
...
+
+        const tooltipLabel = tooltip.getLabel();
+        const headerTop = Boolean(opposite);
+
+        let distributionBoxTop = plotTop;
+        let headerHeight = 0;
+        let rightAlign = false;
+
+        /**
+         * Calculates the anchor position for the tooltip
```
Comment (TorsteinHonsi) [inline ts/parts/Tooltip.ts]: A bit confusing description - we are talking about a partial tooltip here, right? So the comment would be clearer if it read something like "Calculates the anchor position for the partial tooltip"

File: ts/parts/Tooltip.ts [hunk 5]
```diff
@@ -1188,202 +1189,281 @@ H.Tooltip.prototype = {
...
+            }
+
+            // Limit values to plot area
+            anchorX = clamp(anchorX, boundaries.left, boundaries.right);
+            anchorY = clamp(anchorY, boundaries.top, boundaries.bottom);
+            return [anchorX, anchorY];
+        }
+
+        /**
+         * Calculates the position of the tooltip
```
Comment (TorsteinHonsi) [inline ts/parts/Tooltip.ts]: As above, confusing whether this applies to the `Tooltip` instance (`this`) or a partial tooltip for the split tooltip.

File: ts/parts/Tooltip.ts [hunk 6]
```diff
@@ -1188,202 +1189,281 @@ H.Tooltip.prototype = {
...
+                    x = boundaries.right - boxWidth;
+                }
+            }
+
+            // NOTE: y is relative to distributionBoxTop
+            return { x, y };
+        }
+
+        /**
+         * Updates the attributes and styling of the tooltip. Creates a new
```
Comment (TorsteinHonsi) [inline ts/parts/Tooltip.ts]: Partial tooltip...

File: ts/parts/Tooltip.ts [hunk 7]
```diff
@@ -1188,202 +1189,281 @@ H.Tooltip.prototype = {
...
+         * tooltip if it does not exists.
+         *
+         * @private
+         * @param {Highcharts.Tooltip|undefined} tooltip The tooltip to update
+         * @param {Highcharts.Point} point The point related to the tooltip
+         * @param {boolean|string} str The label for the tooltip
+         * @return {Highcharts.SVGElement} Returns the updated tooltip
+         */
+        function updateTooltip(
+            tooltip: (Highcharts.SVGElement|undefined),
```
Comment (TorsteinHonsi) [inline ts/parts/Tooltip.ts]: Use `partialTooltip` to avoid confusion with the Tooltip instance.

File: ts/parts/Utilities.ts (hunk 1 above)
Comment (TorsteinHonsi) [reply ts/parts/Utilities.ts]: Still an issue.

**Comment by TorsteinHonsi** [comment]
To do: 
 - [ ] Use `tooltip.distance` instead of `tooltip.options.distance`.
 - [ ] Rename partial tooltips in code and comments.
 - [ ] Use `clamp` in other parts of the code where appropriate.

**Comment by jon-a-nygaard** [comment]
@TorsteinHonsi Please see latest changes.

> Use clamp in other parts of the code where appropriate.

Yes, I agree, but if you do not mind, then I would like to apply this in a follow up PR.
This is to avoid potential visual diffs to blend in with the ones in this PR.

**Comment by TorsteinHonsi** [comment]
> Yes, I agree, but if you do not mind, then I would like to apply this in a follow up PR

Ok, makes sense!
