### PR TITLE
bugfix/21686-annotations-drag-after-change-extremes

### LINKED ISSUE #21566: Incorrect annotation drawing position when there is more than one series & one of them is scatter.
#### Expected behaviour
Drawing annotations should start and end at the point of mouse click.

#### Actual behaviour
Drawing annotations start and end well beyond the mouse pointer.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/4qam25s3/

#### Product version
Highcharts Stock v11.4.6
**_First bad commit:_** https://github.com/highcharts/highcharts/commit/f99ad8565cea2f5ae7b699417ad2e3917c337c7e

#### Workaround
https://jsfiddle.net/BlackLabel/epztc9sy/

### LINKED ISSUE #21686: annotation dragging error on stock when changing zoom
#### Expected behaviour
Annotation dragging works without change after zoom and navigator slider change.

#### Actual behaviour
Annotation changes its position unexpectedly to the right side of the chart

#### Live demo with steps to reproduce
https://jsfiddle.net/rforristall/Lr96bfp4/64/

#### Product version
Regression starting from v11.1.0
Bisected to: [3f001a8c](https://github.com/highcharts/highcharts/commit/3f001a8cf7be58a60caeb02df25db68bfbec3191)

### LINKED ISSUE #21689: Pivot Points Cause Annotation Tools to Shift and Disappear When Moved
#### Expected behaviour
When applying Pivot Points to a chart and using the drawing tools, the drawings should follow the cursor precisely without any offset. Furthermore, when trying to move a selected drawing, it should remain visible and move according to the cursor movement.

#### Actual behaviour
After applying Pivot Points to the chart and using drawing tools, the drawings appear shifted and do not follow the cursor accurately. Additionally, when attempting to move a selected drawing, the drawing disappears instead of moving as expected.

#### Live demo with steps to reproduce
[fiddle](https://jsfiddle.net/stealkvas/a4wrt01j/1/)

Steps to reproduce:

1. Load the chart in the provided fiddle.
2. Apply Pivot Points to the chart.
3. Select a drawing tool.
4. Start drawing on the chart – notice that the drawings are shifted and do not follow the cursor correctly.
5. Select the drawing and try to move it – the drawing disappears instead of moving.

https://github.com/user-attachments/assets/e37c8668-6b23-4e63-a62f-6fc395fc272f

### LINKED ISSUE #21916: Zoom with bubbles with ordinal set to true doesn't pick the correct date range
#### Expected behaviour

1. Create a large line chart with many years of data and bubbles, range selector set to YTD and ordinal set to true.

2. Zoom by dragging a selection on the chart while it's on YTD (or any date range that's much smaller than the whole dataset).

3. The chart should zoom to the correct date range (e.g. if YTD is 2024, the date range should be within 2024).

#### Actual behaviour

It picks a totally different date range (generally around where the bubbles begin, so if your bubble data starts in 2015, that's where the date range will be.

#### Live demo with steps to reproduce

https://jsfiddle.net/khoomeister/hLsuejmo/1/

#### Product version

Highcharts Stock & More 11.4.8

#### Affected browser(s)

I'm using Chrome 129.

Might be related to https://github.com/highcharts/highcharts/issues/17128

### PR DESCRIPTION
**Pull request by pawellysy**
Fixed #21916, pixel-to-value axis calculations with ordinal and data grouping were incorrect.

Fixed #21689.
Fixed #21686.
Fixed #21566.

### CODE REVIEW

**Review by bm64 — APPROVED** [review]
lgtm

File: samples/unit-tests/stock-tools/stock-annotation-dragging/demo.js [hunk 1]
```diff
@@ -37,36 +59,108 @@ QUnit.test('Dragging annotation', function (assert) {
...
+        const max = 1718733600000 - tenMinutes;
+        chart.xAxis[0].setExtremes(min, max);
+
+        const annotation = chart.annotations[0];
+
+        const diff = 1;
+        const testController = new TestController(chart);
+        const originalPlotX = annotation.shapes[0].points[0].plotX;
+        const start = chart.plotLeft + originalPlotX;
+        testController.pan([start, 200], [diff + start, 200], {}, true);
```
Comment (pawelfus) [inline samples/unit-tests/stock-tools/stock-annotation-dragging/demo.js:157]: - are we panning by 1px? and then we expect the annotation to move by ~1px (using `assert.close()`)? 
- unnecessary marker in test

**Review by kamil-musialowski — APPROVED** [review]

File: ts/Core/Axis/OrdinalAxis.ts [hunk 2]
```diff
@@ -1436,6 +1436,10 @@ namespace OrdinalAxis {
 
             // When more series assign to axis, find the smallest one, #15987.
             axis.series.forEach((series): void => {
+                // Don't include indicators and invisible series
+                if (!series.visible || series.is('sma')) {
```
Comment (pawelfus) [inline ts/Core/Axis/OrdinalAxis.ts:1440]: Why are indicators out? Some indicators, for example IKH, adds more points at the end of the chart (points are in the future, compared to the linked to series). Why PivotPoints indicator causes this?

**Review by pawelfus — CHANGES_REQUESTED** [review]
See my comments inline

File: ts/Core/Axis/OrdinalAxis.ts (hunk 2 above)
Comment (pawellysy) [reply ts/Core/Axis/OrdinalAxis.ts:1440]: it is for finding the first point, which is in `ordinalPositions`. `pivotPoints` is a series, so it has points, but it is more like annotation, so its points don't matter alone. When it comes to IKH, it adds the points at the end, so it shouldn't be an issue, but I will test it out. 

Maybe the whole logic is to be rewritten? :D

File: samples/unit-tests/stock-tools/stock-annotation-dragging/demo.js [hunk 3]
```diff
@@ -37,36 +59,107 @@ QUnit.test('Dragging annotation', function (assert) {
...
+    const annotation = chart.annotations[0];
 
-    const originalPlotX = annotation.points[0].plotX;
-    const testController = new TestController(chart);
     const diff = 25;
+    const testController = new TestController(chart);
+    const originalPlotX = annotation.points[0].plotX;
     const start = chart.plotLeft + originalPlotX;
-    testController.pan([start, 200], [diff + start, 200]);
+    testController.pan([start, 200], [diff + start, 200], {}, true);
```
Comment (DJTechnoo) [inline samples/unit-tests/stock-tools/stock-annotation-dragging/demo.js:68]: It looks like the debug is still on

**Review by DJTechnoo — APPROVED** [review]
Small comment, so small that I still approve!

File: ts/Core/Axis/OrdinalAxis.ts (hunk 2 above)
Comment (pawelfus) [reply ts/Core/Axis/OrdinalAxis.ts:1440]: It looks like we are hiding the real culprit here, instead of finding the issue's root. Indicators itself shouldn't be a problem. If we replace PivotPoints with a scatter series we get the same issue: https://jsfiddle.net/BlackLabel/6mfwdop7/2/ (I just copied x-values from pivot points and set y=200 for each point).

**Review by pawelfus — CHANGES_REQUESTED** [review]

**Review by pawelfus — CHANGES_REQUESTED** [review]
This solution looks exactly the same as it was back in v9.1:

```ts
                Composition.prototype.getIndexOfPoint = function (val, ordinalArray) {
                    var ordinal = this,
                        axis = ordinal.axis,
                        firstPointVal = ordinal.positions ? ordinal.positions[0] : 0, 
                        // toValue for the first point.
                        firstPointX = ordinal.slope ? ordinal.slope * axis.transA : 0;
                    // Distance in pixels between two points
                    // on the ordinal axis in the current zoom.
                    var ordinalPointPixelInterval = axis.translationSlope *
                            (ordinal.slope || axis.closestPointRange || ordinal.overscrollPointsRange),
                        shiftIndex = (val - firstPointX) / ordinalPointPixelInterval;
                    return Composition.findIndexOf(ordinalArray, firstPointVal) + shiftIndex;
                };
```

And it doesn't work:
ann-ordinal

Related ticket: https://github.com/highcharts/highcharts/issues/18459

**Review by pawelfus — APPROVED** [review]
Thanks!

**Review by bm64 — APPROVED** [review]

**Review by kamil-musialowski — APPROVED** [review]
Nice 👏

**Review by DJTechnoo — APPROVED** [review]
Great job!

**Review by TorsteinHonsi — APPROVED** [review]
Nice work, thanks!
