### PR TITLE
bugfix/22850-coloraxis-ticks-dont-align-on-redraw

### LINKED ISSUE #22850: ColorAxis legend doesn't realign ticks on resize
#### Expected behaviour
I have a treemap/heatmap with colorAxis and a percentage width set `width: '90%'`.
Ticks should realign/rescale with color bar when window/ chart wrapper resizes

#### Actual behaviour
When a page or wrapped element is resized then ticks aren't realigned. Everything scales besides the labels below the color bar.

#### Live demo with steps to reproduce
DEMO https://codepen.io/codeapi/pen/EaxpgLX

Open the demo and make a small screen, refresh the page, then resize the screen to a wider one and u will see that ticks get realigned very weirdly. Like values get scaled but the place they occupy doesn't.

Images to illustrate
Init view

Image

After resize

Image

#### Product version
Latest version

### PR DESCRIPTION
**Pull request by MarkusBarstad**
Fixed #22850, ticks of the color axis did not align properly on redraw.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1209796514813952

### CODE REVIEW

**Review by goransle — COMMENTED** [review]
Looks good. Would it be too complicated to do anything the `any` cast?

File: ts/Core/Axis/Color/ColorAxisComposition.ts [hunk 1]
```diff
@@ -131,6 +131,17 @@ namespace ColorAxisComposition {
 
             wrapChartCreateAxis(ChartClass);
 
+            addEvent(ChartClass, 'redraw', function (): void {
+
```
Comment (goransle) [inline ts/Core/Axis/Color/ColorAxisComposition.ts]: Also, this blank line could be removed

**Comment by MarkusBarstad** [comment]
Hey @goransle , I can see that the `geoheatmap` demo is failing visual review but I have no issues with this demo locally 🤔 

I suspect it could be unrelated but now sure 😬

**Review by goransle — APPROVED** [review]
Looks good! It seems that it's the reference for the maps demo that has changed on master 🤔

File: ts/Core/Axis/Color/ColorAxisComposition.ts [hunk 2]
```diff
@@ -131,6 +131,16 @@ namespace ColorAxisComposition {
 
             wrapChartCreateAxis(ChartClass);
 
+            addEvent(ChartClass, 'redraw', function (): void {
+                for (const colorAxis of this.colorAxis || []) {
+                    if (colorAxis.width !== colorAxis.labelRight) {
+                        colorAxis.update(
```
Comment (TorsteinHonsi) [inline ts/Core/Axis/Color/ColorAxisComposition.ts]: This update call triggers an extra Chart.redraw, that we don't want: https://jsfiddle.net/highcharts/fwerukh9/

The preferred pattern for operations like this is to mark components with `isDirty` if they need to be redrawn, then the [Chart.redraw function will pick it up](https://github.com/highcharts/highcharts/blob/cccbb79295fd249b70cd0763c4de47255b35d6b5/ts/Core/Chart/Chart.ts#L998).

In this case however it appears to be simpler, since the axis is already dirty, already redrawing and only the labels are left in their old position. I found that in this code, `labelLeft` and `labelRight` is only set on "First time only":

https://github.com/highcharts/highcharts/blob/cccbb79295fd249b70cd0763c4de47255b35d6b5/ts/Core/Axis/Color/ColorAxis.ts#L362-L369

Moving them out of this condition fixes the issue. There might be more to it though, but tests should show.

**Review by TorsteinHonsi — APPROVED** [review]
Thanks, looks good!
