### PR TITLE
bugfix/22821-labels-missing

### LINKED ISSUE #22821: chart.marginLeft affects rendering of labels on the right side
#### Expected behaviour
Labels on the right side of the chart should be rendered intact.

#### Actual behaviour
Labels on the right side doesn't shows up.

#### Live demo with steps to reproduce
[https://jsfiddle.net/BlackLabel/zgcvs3wt/](https://jsfiddle.net/BlackLabel/zgcvs3wt/)

#### Product version
Highcharts Core & Stock, version 12 (previous versions are unaffected)

### PR DESCRIPTION
**Pull request by magdalena-gut**
Fixed #22821, right-side axis labels clipped when `marginLeft` and `spacingLeft` set.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1209750926041146

### CODE REVIEW

File: samples/unit-tests/axis/labels/demo.js [hunk 1]
```diff
@@ -996,6 +990,50 @@ QUnit.test('Label reserve space', function (assert) {
...
+            categories: ['Long label should not be clipped'],
+            labels: {
+                style: {
+                    fontSize: '13px'
+                }
+            }
+        }]
+    }, false);
+
+    chart.redraw();
```
Comment (hubertkozik) [inline samples/unit-tests/axis/labels/demo.js]: We can use `redraw` flag in `update` method.

File: samples/unit-tests/axis/labels/demo.js [hunk 2]
```diff
@@ -996,6 +990,50 @@ QUnit.test('Label reserve space', function (assert) {
...
+        chart: {
+            marginLeft: 5,
+            spacingLeft: 10
+        },
+        yAxis: [{
+            opposite: true
+        }]
+    }, false);
+
+    chart.redraw();
```
Comment (hubertkozik) [inline samples/unit-tests/axis/labels/demo.js]: Same as above ☝️

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!

**Comment by magdalena-gut** [comment]
> Oh, there is a conflict. Can you have a look at that?

I had slightly overwritten test, so the conflict popped up. Merged master and kept my changes.

**Review by TorsteinHonsi — APPROVED** [review]
