### PR TITLE
enhancement/23303-tooltip-behaviour

### LINKED ISSUE #23303: Prevent Tooltip from Hiding When Cursor Moves Toward Tooltip (With stickOnContact Enabled)
#### Expected behaviour
If `stickOnContact` is enabled and the cursor moves toward the tooltip container (e.g., via the highcharts-background), the tooltip should not disappear immediately. Instead, a short delay should be introduced before triggering the mouseout handler. If the cursor enters the tooltip container within this delay, the tooltip should remain visible.
This would allow users to successfully reach and interact with elements like the pin icon without the tooltip vanishing.

#### Actual behaviour
When hovering near the bottom of a bar and moving the cursor toward the tooltip (specifically in the direction of the tooltip's blue arrow - refer attached image), the tooltip disappears immediately due to the mouseout event - even if the user is trying to interact with elements inside the tooltip, such as the pin icon.

Image

#### Live demo with steps to reproduce
https://jsfiddle.net/1j5d8vfb/1/

#### Product version
Highcharts 11.4.8

#### Affected browser(s)
Same behaviour in all browsers

#### Proposed Solution
- Continue starting the hideTimer on mouseout as usual.
- If the mouse enters the tooltip container (e.g., element with class highcharts-tooltip) before the timer completes, cancel the hideTimer.
- If the mouse does not enter the tooltip container within the delay, allow the tooltip to hide normally.
- Maintain current behaviour for switching between adjacent bars - i.e., show the new bar's tooltip and hide the old one as expected.

### PR DESCRIPTION
**Pull request by magdalena-gut**
Fixed #23303, tooltips with `stickOnContact` now remain visible when the cursor leaves a point and re-enters the tooltip container within `hideDelay`.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/1/222651295669536/project/1204879359430251/task/1210743342802340?focus=true

### CODE REVIEW

File: samples/unit-tests/tooltip/stickoncontact/demo.js [hunk 1]
```diff
@@ -206,3 +206,57 @@ QUnit.test(
         );
     }
 );
+
+QUnit.test(
+    `With stickOnContact enabled, if the mouse leaves a point but enters the
```
Comment (KacperMadej) [inline samples/unit-tests/tooltip/stickoncontact/demo.js]: When test is described this narrowly it make it hard to add any future assertions to it. Could the test name be more general, so that it could be later extended if needed?

File: ts/Core/Tooltip.ts [hunk 2]
```diff
@@ -558,6 +558,53 @@ class Tooltip {
...
+
+                addEvent(tooltipElement, 'mouseover', (): void => {
+                    U.clearTimeout(this.hideTimer);
+                });
+
+                addEvent(
+                    tooltipElement,
+                    'mouseout',
+                    (e: PointerEvent): void => {
+                        const relatedTarget = e.relatedTarget as any;
```
Comment (KacperMadej) [inline ts/Core/Tooltip.ts]: There should be something better than `as any`. Could there be something better than `as DOMElementType|null` without any bigger changes?

File: ts/Core/Tooltip.ts [hunk 3]
```diff
@@ -558,6 +558,53 @@ class Tooltip {
...
+                        const isPoint =
+                            relatedTarget &&
+                            (
+                                this.pointer.inClass(
+                                    relatedTarget,
+                                    'highcharts-point'
+                                )
+                            );
+
+                        if (isTooltip || isPoint) {
```
Comment (KacperMadej) [inline ts/Core/Tooltip.ts]: If those 2 consts are added just for the `if` check then they could be optimized to have less checks and code.

**Review by KacperMadej — CHANGES_REQUESTED** [review]
There is something that looks a bit unstable when comparing between current code version and your changes.
Demo: https://jsfiddle.net/BlackLabel/m7y6x4bo/

Steps:

Image

1. follow red arrow
2. wait for the tooltip to hide
3. move left
4. the tooltip will appear

The difference is that tooltip was not hiding when hovering through it.
Similarly with column, if stickyTracking is set to true.
Demo: https://jsfiddle.net/BlackLabel/u4763bao/53/

1. hover over a middle of a darker column
2. move to the side of the column, outside of the point
3. the tooltip stays, but if you enter and leave into the chart background it hides

About the comments in code - those might look like a bit too nitpicky, but if we can make changes to the Core to keep the code minimal or optimal then it's worth a try.

File: ts/Core/Tooltip.ts [hunk 4]
```diff
@@ -558,6 +559,48 @@ class Tooltip {
...
+                                    'highcharts-tooltip-box'
+                                ) ||
+                                this.pointer.inClass(
+                                    relatedTarget,
+                                    'highcharts-point'
+                                )
+                            )
+                        ) {
+                            U.clearTimeout(this.hideTimer);
+                            return;
```
Comment (KacperMadej) [inline ts/Core/Tooltip.ts]: This `return;` has no purpose now.

**Review by TorsteinHonsi — APPROVED** [review]
