### PR TITLE
bugfix/21725-missing-datalable-after-visibility-toggle-on-pie

### LINKED ISSUE #21725: Missing dataLabel after point visibility toggle in pie chart with `dataLabel.distance` set
#### Expected behaviour
The dataLabel is visible after toggling the point visibility.

#### Actual behaviour
The dataLabel has `opacity: 0` added as inline style and isn't visible after toggling.

#### Live demo with steps to reproduce
[https://jsfiddle.net/BlackLabel/ygncq3hL/](https://jsfiddle.net/BlackLabel/ygncq3hL/)
This happens only when the `distance` is set, setting `crop: false` & `overflow: 'allow'` doesn't resolve the problem.

#### Product version
Regression starting from Highcharts v11.2.0

_Internal note:_ Unable to bisect

### PR DESCRIPTION
**Pull request by AndrzejBuleczka**
Fixed #21725, `pie.dataLabels` with negative distance set missing after update or visibility toggle.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208163504577849

### CODE REVIEW

File: ts/Series/Pie/PieDataLabel.ts [hunk 1]
```diff
@@ -525,6 +525,61 @@ namespace ColumnDataLabel {
...
+                                width: bBox.width,
+                                height: bBox.height
+                            };
+
+                            // Check against other internal labels in
+                            // the same series
+                            for (const otherPoint of series.points) {
+                                const otherLabel = otherPoint.dataLabel;
+                                const otherPos = otherLabel?.dataLabelPosition;
+                                const otherCoords = otherPos?.posAttribs;
```
Comment (hubertkozik) [inline ts/Series/Pie/PieDataLabel.ts]: I am not sure about this logic. We can define multiple data labels for one point, but here we're just checking first data label from the other point.

File: ts/Core/Series/OverlappingDataLabels.ts [hunk 2]
```diff
@@ -361,8 +361,6 @@ function onChartRender(
                                 label.oldOpacity = label.opacity;
                                 label.newOpacity = 1;
                                 hideOrShow(label, chart);
-
-                            // Do not allow overlap
```
Comment (hubertkozik) [inline ts/Core/Series/OverlappingDataLabels.ts:363]: Why removing this comment?

File: ts/Series/Pie/PieDataLabel.ts [hunk 3]
```diff
@@ -525,6 +525,61 @@ namespace ColumnDataLabel {
                             }
                         }
 
+                        // Fix #21725 - apply overlap check on final position
+                        if (
+                            labelPosition.distance <= 0 &&
+                            dataLabelOptions.allowOverlap === false
```
Comment (hubertkozik) [inline ts/Series/Pie/PieDataLabel.ts]: Isn't `!dataLabelOptions.allowOverlap` enough?

File: package-lock.json
Comment (hubertkozik) [inline package-lock.json:1]: Let's revert the changes in this file, not needed in this PR.

**Review by hubertkozik — CHANGES_REQUESTED** [review]

File: ts/Core/Series/OverlappingDataLabels.ts (hunk 2 above)
Comment (AndrzejBuleczka) [reply ts/Core/Series/OverlappingDataLabels.ts:363]: fixed

File: ts/Series/Pie/PieDataLabel.ts (hunk 3 above)
Comment (AndrzejBuleczka) [reply ts/Series/Pie/PieDataLabel.ts]: no, here we have specific logic for labels inside the pie, allowOveralp is not enough; lables outside the pie point are handled separately in the code

File: package-lock.json
Comment (AndrzejBuleczka) [reply package-lock.json:1]: done

File: ts/Series/Pie/PieDataLabel.ts (hunk 1 above)
Comment (AndrzejBuleczka) [reply ts/Series/Pie/PieDataLabel.ts]: good point, thanks a lot, fix added

File: ts/Series/Pie/PieDataLabel.ts (hunk 3 above)
Comment (hubertkozik) [reply ts/Series/Pie/PieDataLabel.ts]: I mean, instead of `=== false`

File: package-lock.json
Comment (hubertkozik) [inline package-lock.json:1]: The file is still here 😬

File: ts/Series/Pie/PieDataLabel.ts (hunk 3 above)
Comment (AndrzejBuleczka) [reply ts/Series/Pie/PieDataLabel.ts]: Sure, fixed.

File: package-lock.json
Comment (AndrzejBuleczka) [reply package-lock.json:1]: Fixed

**Review by hubertkozik — APPROVED** [review]

**Comment by TorsteinHonsi** [comment]
Thanks!

Did you check why the regular overlapping-label logic isn't working? [There are signs](https://github.com/highcharts/highcharts/blob/18bce3448da36b67e729bbe9268304ed3882c317/ts/Core/Series/OverlappingDataLabels.ts#L357-L359) in the OverlappingDataLabels.ts file that similar situations should be handled there.

**Comment by AndrzejBuleczka** [comment]
Hi @TorsteinHonsi, that's a great point. I investigated fixing this within OverlappingDataLabels.ts initially, but it led to several regressions in Cartesian series.

The core issue is that Pie charts have their own specialized anti-collision logic in PieDataLabel.ts (the distribute logic). When OverlappingDataLabels also processes these labels - especially during a visibility toggle - it incorrectly detects collisions during the animation state and applies opacity: 0 as an inline style.

Since inline styles have higher specificity, they override the visibility attributes managed by the Pie layout engine. By handling the state cleanup in PieDataLabel.ts, we ensure the Pie series maintains authority over its own labels without interfering with the generic collision logic used by other series types (Column, Bar, etc.), which don't have a radial distribution safety net.

**Comment by TorsteinHonsi** [comment]
@AndrzejBuleczka Thanks for the explanation! 

> The core issue is that Pie charts have their own specialized anti-collision logic

This special anti-collision logic only applies if `distance` > 0. When the distance is negative, the shared anti-collision is used. Can we leverage this to apply a leaner fix within OverlappingDataLabels.ts?

**Comment by AndrzejBuleczka** [comment]
Hi @TorsteinHonsi , it took my a while, but I hope I have a simpler, more generic solution - force overlap evaluation on the final position in case of toggle etc - what do you think?

**Comment by TorsteinHonsi** [comment]
Thanks! Is the addition to PieDataLabel.ts still in use? When I remove it, it still works well. Maybe you forgot to remove it? In that case, the solution looks very lean and promising.

**Comment by AndrzejBuleczka** [comment]
Hi, apologies, I was sure I removed it, fixed now.

**Review by TorsteinHonsi — APPROVED** [review]
