### PR TITLE
bugfix/18459-moving-ordinal-annotations

### LINKED ISSUE #18459: Moving Annotations Bug
#### Expected behaviour
After drawing an annotation (such as a trend line) on a chart it should be possible to edit it to change the position by clicking it and moving it with the mouse.

#### Actual behaviour
In the following situation when trying to move an annotation with a mouse the movement of the annotation doesn't track the position of the pointer:
- Set up a stock chart with a reasonably long timeseries of data
- Set the view to less than the full range - eg 1 Year
- Add an indicator - in my testing I've used SMA and EMA indicators
- Draw a simple annotation such as a line
- If you try to move this annotation it won't track the mouse

This bug only seems to appear under those specific conditions. If the technical indicator is removed or the zoom level is set to view the full timeseries then the annotation can be moved as expected.

#### Live demo with steps to reproduce
It is possible to reproduce this with the standard Stock Tools GUI example chart:
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/stock-tools-gui

#### Product version
 Highstock JS v10.3.3 (2023-01-20)

#### Affected browser(s)
Firefox 109.0.1 on Fedora (64-bit)
Chromium Version 109.0.5414.74 (Official Build) Fedora Project (64-bit)

### PR DESCRIPTION
**Pull request by kamil-musialowski**
Fixed #18459, dragging annotations on chart with ordinal axes was inconsistent.

### CODE REVIEW

File: ts/Core/Axis/OrdinalAxis.ts [hunk 1]
```diff
@@ -1407,26 +1407,31 @@ namespace OrdinalAxis {
...
+            axis.series.forEach((series): void => {
+                const firstPoint = series.points?.[0];
+
+                if (
+                    defined(firstPoint?.plotX) &&
+                    hasPointsInside(series) &&
+                    (
+                        !defined(firstPointX) ||
+                        firstPoint.plotX < firstPointX
+                    )
```
Comment (pawelfus) [inline ts/Core/Axis/OrdinalAxis.ts:1427]: Could you please change the order of conditions? In general, the most consuming ones should be the last ones (they are evaluated only if others are truthy). I mean `hasPointsInside` imho should be the last one

**Review by pawelfus — CHANGES_REQUESTED** [review]
Just a minor polishing, nice!

File: ts/Core/Axis/OrdinalAxis.ts (hunk 1 above)
Comment (kamil-musialowski) [reply ts/Core/Axis/OrdinalAxis.ts:1427]: Absolutely right, thank you for spotting that!

**Review by pawelfus — APPROVED** [review]
Thanks!

File: samples/unit-tests/axis/ordinal/demo.js [hunk 2]
```diff
@@ -355,9 +355,11 @@ QUnit.test('lin2val- unit test for values outside the plotArea.', function (asse
         },
         series: [{
             points: [{
+                isInside: true, // #18459
                 x: 3,
                 plotX: -20
             }, {
+                isInside: true, // #18459
```
Comment (TorsteinHonsi) [inline samples/unit-tests/axis/ordinal/demo.js:362]: There is no such option... Only the internal, computed property `Point.isInside`. So is this test realistic, or are we cheating by forcing a property that should be computed?

**Review by TorsteinHonsi — COMMENTED** [review]
Just one question

File: samples/unit-tests/axis/ordinal/demo.js (hunk 2 above)
Comment (kamil-musialowski) [reply samples/unit-tests/axis/ordinal/demo.js:362]: Sure thing, there is no such property - but since we don't even create a chart there, and use fake points, this property won't get computed (right?). We test `lin2val` outside the chart environment. Therefore I decided to manually put it in there, to ensure that a new logic will treat those points as they are inside the chart.

In fact, I think line 358 should be removed here.

Comment (TorsteinHonsi) [reply samples/unit-tests/axis/ordinal/demo.js:362]: Ok, I didn't realize it was mock points.
