### PR TITLE
bugfix/20965 label align animation

### LINKED ISSUE #20965: Unwanted animation of label when right aligned
#### Expected behaviour
When a label is aligned to the right or centered, and changing its text value, the right or center should stay fixed

#### Actual behaviour
It animates from old left side to new left side.

#### Live demo with steps to reproduce
https://jsfiddle.net/highcharts/tqjakcf5/2/

#### Product version
11.4.1

### PR DESCRIPTION
**Pull request by TorsteinHonsi**
Fixed #20965, unwanted animation of right-aligned label when only the text changed

### CODE REVIEW

File: ts/Core/Renderer/SVG/SVGElement.ts [hunk 1]
```diff
@@ -474,13 +479,21 @@ class SVGElement implements SVGElementLike {
...
         attribs[alignByTranslate ? 'translateY' : 'y'] = Math.round(y);
 
         // Animate only if already placed
         if (redraw) {
+
+            // Right- and center-aligned labels should not animate when we're
+            // only changing the text (#20965)
+            if (!animateX) {
+                this.attr({
+                    [alignByTranslate ? 'translateX' : 'x']: x
```
Comment (pawelfus) [inline ts/Core/Renderer/SVG/SVGElement.ts:494]: Can we use computed property names?

**Review by pawelfus — APPROVED** [review]
LGTM! 👍

File: ts/Core/Renderer/SVG/SVGElement.ts (hunk 1 above)
Comment (TorsteinHonsi) [reply ts/Core/Renderer/SVG/SVGElement.ts:494]: Yes, apparently [supported since 2016](https://caniuse.com/?search=computed%20property%20names) in the major browsers.
