### PR TITLE
dash/22492-chart-constructor-update

### LINKED ISSUE #22492: HighchartsComponent `chartConstructor` update does not work.
#### Expected behaviour
`component.update({ chartConstructor: ... })` should change the chart type.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/a2og4w3t/

#### Product version
Highcharts Dashboards v3.1.0

#### Workaround
https://jsfiddle.net/BlackLabel/7pex8wou/

### PR DESCRIPTION
**Pull request by ddragula**
Fixed #22492, updating `HighchartsComponent` with the new `chartConstructor` did not work.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1209106737918892

### CODE REVIEW

**Review by sebastianbochan — APPROVED** [review]

File: ts/Dashboards/Components/HighchartsComponent/HighchartsComponent.ts [hunk 1]
```diff
@@ -421,9 +421,15 @@ class HighchartsComponent extends Component {
...
-        if (this.chart) {
-            this.chart.update(merge(this.options.chartOptions) || {});
+        if (this.options.chartConstructor !== this.chartConstructor) {
+            this.chartConstructor = this.options.chartConstructor || 'chart';
+            this.chartOptions = this.options.chartOptions || {};
+            this.chart?.destroy();
+            delete this.chart;
         }
+
+        this.chart?.update(merge(this.options.chartOptions) || {});
```
Comment (KamilKubik) [inline ts/Dashboards/Components/HighchartsComponent/HighchartsComponent.ts:431]: If the above `if` statement removes the chart, shouldn't we keep this update as `else` to the above?

**Review by KamilKubik — CHANGES_REQUESTED** [review]

File: ts/Dashboards/Components/HighchartsComponent/HighchartsComponent.ts (hunk 1 above)
Comment (ddragula) [reply ts/Dashboards/Components/HighchartsComponent/HighchartsComponent.ts:431]: Good point, thanks!
