### PR TITLE
bugfix/21217-navigator-disabled-in-setOptions

### LINKED ISSUE #21217: Disabling navigator via `setOptions` doesn't work
#### Expected behaviour
Disabling navigator in `setOptions` doesn't render navigator.

#### Actual behaviour
The navigator is still present.

#### Live demo with steps to reproduce
[https://jsfiddle.net/BlackLabel/ev19mau5/](https://jsfiddle.net/BlackLabel/ev19mau5/)

#### Product version
Regression introduced in v11.4.0

_Internal note:_
Bisected to [bcbb63b](https://github.com/highcharts/highcharts/commit/bcbb63b820301b4d4bf987663bd656e02aeb1b16)

### PR DESCRIPTION
**Pull request by kamil-musialowski**
Fixed #21217, navigator was still rendered after disabling it in `setOptions`.

### CODE REVIEW

**Review by pawellysy — APPROVED** [review]

**Review by pawelfus — APPROVED** [review]
Thanks!

**Review by bm64 — APPROVED** [review]

**Review by DJTechnoo — APPROVED** [review]

File: samples/unit-tests/navigator/navigator/demo.js [hunk 1]
```diff
@@ -63,6 +63,33 @@ QUnit.test(
...
+        'Navigator should not be rendered when disabled in setOptions (#21217).'
+    );
+});
+
+// Enabled navigator again for further tests
+Highcharts.setOptions({
+    navigator: {
+        enabled: true
+    }
+});
```
Comment (pawelfus) [inline samples/unit-tests/navigator/navigator/demo.js:91]: It seems tests are failing because of that (default is undefined, not `true`. `true` is only for Stock`).

**Review by pawelfus — CHANGES_REQUESTED** [review]

**Comment by kamil-musialowski** [comment]
@pawelfus @TorsteinHonsi The solution is finally fixed, tests are improved and everything seems to be working both locally, in Utils and in Karma. Two tests are failing, but that is unrelated to the PR (they are failing in other PRs as well).

**Review by pawelfus — APPROVED** [review]
This looks good, thanks!

**Review by TorsteinHonsi — APPROVED** [review]
