### PR TITLE
bugfix/22664-missing-plotline-labels

### LINKED ISSUE #22664: PlotLine label getting wrong opacity and disappearing
#### Expected behaviour
When I have two plotLines close to each other with labels positioned on the opposite sites, both of them should be visible as there is no overlap

#### Actual behaviour
 When I have two plotLines close to each other with labels positioned on the opposite sites, the one on the right disappears due to the wrong opacity

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/1c5w0bon/
Note that the label on the right side is missing, inspect with dev tools and see the wrong opacity: 0 assigned

#### Product version
Highcharts Core

Workaround: explicitly set style: { opacity: 1}

#### Affected browser(s)
all

### PR DESCRIPTION
**Pull request by MarkusBarstad**
Fixed #22664 , labels were accidentally being hidden when they should not.

Note: There could possibly be better ways of preventing this from happening.

The issue is that `label.absoluteBox` does not take alignment into account, thus the wrong positions are compared by the overlapping logic.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1209422338911598

### CODE REVIEW

**Comment by MarkusBarstad** [comment]
> I am not sure if this fix is enough. Let's take a look at this demo: https://jsfiddle.net/BlackLabel/pxg3vL2n/ For `align: center` the `absoluteBox` is wrong 😬

Good catch! 

I think we can easily ameliorate this in `getAbsoluteBox`, however, issue remains that it would be nice to not have to make up for this after label creation 🤔 

Will fix center-aligned labels first tho

**Comment by MarkusBarstad** [comment]
Alright, @hubertkozik , `absoluteBox` seems better now, but i have noticed something curious:

`absoluteBox` is quite similar to return value of `label.element.getBoundingClientRect()`

Should we try to just alter this instead of assembling/calculating `absoluteBox` ourselves? 🤔 

My idea is that this could maybe save execution time by just using what the browser returns and slightly altering it, instead of having to assemble/calculate the whole box ourselves.

If you look at [getAbsoluteBox](https://github.com/highcharts/highcharts/blob/22664-plotline-labels-wrong-opacity/ts/Core/Series/OverlappingDataLabels.ts), it could be nice to shorten this function.

Demo showing (the new) `absoluteBox` in green, and `getBoundingClientRect` in red: 
- PlotLine/Band labels: https://jsfiddle.net/mkb93/zpv8q5km/131/
- StackLabels also have an absoluteBox close to `getBoundingClientRect()`: https://jsfiddle.net/mkb93/0bjvye8h/

Should we try it 🤔 ?

File: ts/Core/Series/OverlappingDataLabels.ts [hunk 1]
```diff
@@ -106,15 +106,30 @@ function chartHideOverlappingLabels(
...
+            switch (alignValue) {
+                case 'right':
+                    alignOffset = width;
+                    break;
+                case 'center':
+                    alignOffset = (width / 2);
+                    break;
+                default:
+                    break;
+            }
```
Comment (TorsteinHonsi) [inline ts/Core/Series/OverlappingDataLabels.ts:127]: Use the [getAlignFactor](https://github.com/highcharts/highcharts/blob/2f11abca284057d324d5fb58b8ecce897bebb803/ts/Core/Utilities.ts#L1371-L1376) function

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks! Yes it may be worth a shot to look at synergies with `getBoundingClientRect`. But maybe in a separate PR so that we don't lose track of the original issue in this PR?

**Comment by MarkusBarstad** [comment]
@TorsteinHonsi Regarding the visual diffs, the first doesn't seem bad to me, the second I am unsure of 🤔

**Comment by TorsteinHonsi** [comment]
@MarkusBarstad Both visual diffs are legit as far as I can see.

**Review by TorsteinHonsi — APPROVED** [review]
