### PR TITLE
bugfix/rangeselector-dropdown-refactor

### LINKED ISSUE #20644: RangeSelector's buttons don't update on click when in dropdown mode
#### Expected behaviour
When selecting a new period, the button should update the text.

#### Actual behaviour
The button's label never changes.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/npfqLthm/

Select some period in the RangeSelector's dropdown
Result: The text never changes.

Regression since https://github.com/highcharts/highcharts/pull/20248
#### Product version
v11.3

#### Affected browser(s)
all

### PR DESCRIPTION
**Pull request by kamil-musialowski**
Fixed #20644, `rangeSelector` state was not updated in dropdown.

TODO:
- [x]  `rangeSelector.verticalAlign` doesn't affect dropdown (probably `group` issue)
- [ ] after master merge, tick off -9999 translation here https://github.com/highcharts/highcharts/issues/15863#issuecomment-986695390

### CODE REVIEW

File: samples/unit-tests/rangeselector/dropdown/demo.js [hunk 1]
```diff
@@ -43,9 +33,10 @@ QUnit.test('RangeSelector.dropdown', assert => {
         chart.rangeSelector.buttons.every(b => b.visibility !== 'hidden'),
         '800px + responsive: All the buttons should be visible'
     );
-    assert.notOk(
-        isSelectInsideChart(),
-        'Select should be outside chart'
+    assert.ok(
+        chart.rangeSelector.dropdown.style.visibility === 'hidden' &&
+        chart.rangeSelector.dropdownLabel.visibility === 'hidden',
+        'Dropdown and its label should be hidden'
```
Comment (pawellysy) [inline samples/unit-tests/rangeselector/dropdown/demo.js:39]: Could we change it to `assert.equals`? (and possibly just check one property)

File: samples/unit-tests/rangeselector/dropdown/demo.js [hunk 2]
```diff
@@ -58,9 +49,10 @@ QUnit.test('RangeSelector.dropdown', assert => {
         chart.rangeSelector.buttons.every(b => b.visibility !== 'hidden'),
         '800px + never: All the buttons should be visible'
     );
-    assert.notOk(
-        isSelectInsideChart(),
-        'Select should be outside chart'
+    assert.ok(
+        chart.rangeSelector.dropdown.style.visibility === 'hidden' &&
+        chart.rangeSelector.dropdownLabel.visibility === 'hidden',
+        'Dropdown and its label should be hidden'
```
Comment (pawellysy) [inline samples/unit-tests/rangeselector/dropdown/demo.js:55]: Same as above

File: samples/unit-tests/rangeselector/dropdown/demo.js [hunk 3]
```diff
@@ -69,14 +61,14 @@ QUnit.test('RangeSelector.dropdown', assert => {
...
+    assert.ok(
+        chart.rangeSelector.buttons.every(b => b.visibility === 'hidden'),
+        '800px + always: Every button should be hidden'
     );
     assert.ok(
-        isSelectInsideChart(),
-        'Select should be inside chart'
+        chart.rangeSelector.dropdown.style.visibility !== 'hidden' &&
+        chart.rangeSelector.dropdownLabel.visibility !== 'hidden',
+        'Dropdown and its label should be visible'
```
Comment (pawellysy) [inline samples/unit-tests/rangeselector/dropdown/demo.js:71]: as above

File: samples/unit-tests/rangeselector/dropdown/demo.js [hunk 4]
```diff
@@ -85,14 +77,14 @@ QUnit.test('RangeSelector.dropdown', assert => {
...
-        '400px + always: Only 1 button should be visible'
+    assert.ok(
+        chart.rangeSelector.buttons.every(b => b.visibility === 'hidden'),
+        '400px + always: Every button should be hidden'
     );
     assert.ok(
-        isSelectInsideChart(),
-        'Select should be inside chart'
+        chart.rangeSelector.dropdown.style.visibility !== 'hidden' &&
+        chart.rangeSelector.dropdownLabel.visibility !== 'hidden',
```
Comment (pawellysy) [inline samples/unit-tests/rangeselector/dropdown/demo.js:86]: as above

File: samples/unit-tests/rangeselector/dropdown/demo.js [hunk 5]
```diff
@@ -101,14 +93,14 @@ QUnit.test('RangeSelector.dropdown', assert => {
...
-        '400px + resonsive: Only 1 button should be visible'
+    assert.ok(
+        chart.rangeSelector.buttons.every(b => b.visibility === 'hidden'),
+        '400px + resonsive: Every button should be hidden'
     );
     assert.ok(
-        isSelectInsideChart(),
-        'Select should be inside chart'
+        chart.rangeSelector.dropdown.style.visibility !== 'hidden' &&
+        chart.rangeSelector.dropdownLabel.visibility !== 'hidden',
```
Comment (pawellysy) [inline samples/unit-tests/rangeselector/dropdown/demo.js:102]: as above

File: samples/unit-tests/rangeselector/dropdown/demo.js [hunk 6]
```diff
@@ -121,9 +113,10 @@ QUnit.test('RangeSelector.dropdown', assert => {
         chart.rangeSelector.buttons.every(b => b.visibility !== 'hidden'),
         '400px + never: All the buttons be visible'
     );
-    assert.notOk(
-        isSelectInsideChart(),
-        'Select should be outside chart'
+    assert.ok(
+        chart.rangeSelector.dropdown.style.visibility === 'hidden' &&
+        chart.rangeSelector.dropdownLabel.visibility === 'hidden',
```
Comment (pawellysy) [inline samples/unit-tests/rangeselector/dropdown/demo.js:118]: as above

File: samples/unit-tests/rangeselector/position-antycollision/demo.js [hunk 7]
```diff
@@ -115,14 +115,14 @@ QUnit.test('Inputs and buttons aligning.', function (assert) {
...
-    assert.ok(
-        (chart.plotWidth - selectorGroupBBox.width) / 2 +
-            chart.plotLeft -
-            selectorGroupBBox.x <=
-            1,
-        'rangeSelector buttons should be centered correctly (#13014).'
+    assert.close(
+        plotWidth / 2,
+        (x + width) / 2,
+        5,
```
Comment (pawellysy) [inline samples/unit-tests/rangeselector/position-antycollision/demo.js:124]: To further invastigation - I think this calculations are wrong 🤔

File: ts/Stock/RangeSelector/RangeSelector.ts [hunk 8]
```diff
@@ -1310,36 +1319,61 @@ class RangeSelector {
...
+                    userButtonTheme?.padding,
+                    8
+                )
+            }),
+            states && states.hover,
+            states && states.select,
+            states && states.disabled
+        )
+            .add(this.buttonGroup)
+            .hide();
```
Comment (pawellysy) [inline ts/Stock/RangeSelector/RangeSelector.ts:1354]: Swap this 2 lines. (Theoretically, painting of the screen is done after the whole JS is performed, but why risk it, to make the dropdown label displayed for a split ms?)

File: ts/Stock/RangeSelector/RangeSelector.ts [hunk 9]
```diff
@@ -1982,20 +1905,23 @@ class RangeSelector {
...
+                bBox = dropdownLabel.attr({ x: chart.plotLeft }).getBBox();
+
             css(dropdown, {
                 left: (chart.plotLeft + translateX) + 'px',
                 top: (translateY + 0.5) + 'px',
+                visibility: 'inherit',
                 width: bBox.width + 'px',
                 height: bBox.height + 'px'
             });
+            dropdownLabel.show();
```
Comment (pawellysy) [inline ts/Stock/RangeSelector/RangeSelector.ts:1924]: move the `show` to the line, where we are calling `getBBox`

**Review by pawellysy — CHANGES_REQUESTED** [review]
Great job. Just minor polishing

File: samples/unit-tests/rangeselector/dropdown/demo.js (hunk 1 above)
Comment (kamil-musialowski) [reply samples/unit-tests/rangeselector/dropdown/demo.js:39]: As we agreed, separating these two into two separate asserts (since they check two different elements)

**Review by pawellysy — APPROVED** [review]
LGTM

File: samples/unit-tests/rangeselector/position-antycollision/demo.js (hunk 7 above)
Comment (kamil-musialowski) [reply samples/unit-tests/rangeselector/position-antycollision/demo.js:124]: After all refactors, we can bring back the old test - it's working properly.
