### PR TITLE
bugfix/12422-boost-zones-zoom

### LINKED ISSUE #9124: Zoom in/out when using zones not working with boost
#### Expected behaviour
When zooming in and out I expect to only have one line per serie

#### Actual behaviour
If I zoom in and out multiple times I sometimes get two lines for a serie. This happens when I use zones together with the boost module.

#### Live demo with steps to reproduce
http://jsfiddle.net/81vhr764/5/

The fiddle shows a use case where I want multiple axes with one serie per axis stacked in the same graph. I use a zone for each graph to hide any points that lays below the axis min value. If I zoom in and out multiple times, sometimes the bottom serie get multiple lines visible in the graph. 

#### Product version
Highcharts 6.1.1

#### Affected browser(s)
Tested in chrome

### LINKED ISSUE #12422: Boosted charts have unboosted data remaining on the chart after zoom and reset zoom
#### Expected behaviour
Start with a boosted chart that uses zones.  Zoom in, chart is no longer boosted.  Reset zoom, chart becomes boosted again.

#### Actual behaviour
Start with a boosted chart that uses zones.  Zoom in, chart is no longer boosted.  Reset zoom, chart becomes boosted again.  However, the unboosted traces remain on the graph.  **Seems to only happen if zones are being used.**

#### Live demo with steps to reproduce
[https://jsfiddle.net/5xq29pwn/](https://jsfiddle.net/5xq29pwn/)

Upon load you'll see:
image
Zoom way in like this:
image
Now reset Zoom:
image

#### Product version
Highcharts & Boost Module, current versions (7.1.1+)

#### Affected browser(s)
Chome, no other browsers tested.

### PR DESCRIPTION
**Pull request by khlieng**
Fixed #12422, #9124, un-boosted graphics remained visible after resetting zoom on boosted charts when using zones.

Closes #9124.

### CODE REVIEW

File: ts/Extensions/Boost/BoostInit.ts [hunk 1]
```diff
@@ -159,6 +159,15 @@ function init(): void {
...
             }
+            if ((this as any).getZonesGraphs) {
+                const props: string[][] = (this as any).getZonesGraphs([['graph', 'highcharts-graph']]);
+                props.forEach((prop): void => {
+                    const zoneGraph: Highcharts.SVGElement = (this as any)[prop[0]];
+                    if (zoneGraph) {
+                        (this as any)[prop[0]] = zoneGraph.destroy();
+                    }
+                });
+            }
```
Comment (TorsteinHonsi) [inline ts/Extensions/Boost/BoostInit.ts:170]: I think this block should be in the `destroyGraphics` function itself along with the destruction of the graphs and the points.

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
