### PR TITLE
Fixed #23432, could not drill down to added treemap nodes

### LINKED ISSUE #23432: Cannot drilldown properly after adding new points in Heatmap series
#### Expected behaviour
When clicked, an area should drilldown to its children.

#### Actual behaviour
The area is not drilling down to its children when clicked anywhere on the area but it drills down only when clicked on the data label.

#### Live demo with steps to reproduce
**https://jsfiddle.net/av73x0c9/**

In the below example notice that when clicked on the area on **Child 2**, drill down does not happen, but happens only when clicking on the label **Child 2**. Similarly, when clicking on area **Grandchild 5** drill down does not happen but only when clicked on the label **Grandchild 5**.

Image

#### Product version
Latest Highcharts

#### Affected browser(s)
Chrome

### PR DESCRIPTION
**Pull request by TorsteinHonsi**
Fixed #23432, could not drill down to treemap nodes when children were added dynamically

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1211015355475410

### CODE REVIEW

File: samples/unit-tests/series-treemap/update/demo.js [hunk 1]
```diff
@@ -75,3 +75,97 @@ QUnit.test('Treemap and updates', function (assert) {
...
+        ]
+    });
+
+    function navigateToNode(nodeId) {
+        const series = chart.series[0];
+        series.setRootNode(nodeId, true);
+    }
+    function addData(newData) {
+        const series = chart.series[0];
+        console.log(series.options.data);
```
Comment (KacperMadej) [inline samples/unit-tests/series-treemap/update/demo.js]: This `console.log` should be safe to remove.

File: ts/Series/Treemap/TreemapSeries.ts [hunk 2]
```diff
@@ -965,8 +964,10 @@ class TreemapSeries extends ScatterSeries {
                     (series as any)[groupKey] = renderer.g(groupKey)
                         .attr({
                             // @todo Set the zIndex based upon the number of
-                            // levels, instead of using 1000
-                            zIndex: 1000 - (levelDynamic || 0)
+                            // levels, instead of using 1000.
+                            // Use the static level in order to retain z-index
+                            // when data is updated (#23432).
+                            zIndex: 1000 - (point.node.level || 0)
```
Comment (KacperMadej) [inline ts/Series/Treemap/TreemapSeries.ts]: Wouldn't using `zIndex: -(point.node.level || 0)` give the same results and also resolve the above `@todo` comment?

Comment (TorsteinHonsi) [reply ts/Series/Treemap/TreemapSeries.ts]: @KacperMadej Indeed. Negative `z-index` is [valid in CSS too](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_positioned_layout/Understanding_z-index#layers_on_the_z-axis).

**Review by KacperMadej — APPROVED** [review]
