### PR TITLE
Fixed #24042, translate3dPoints was broken for dataGrouping

### LINKED ISSUE #24042: Abnormal display when using 3D icons with large data volumes
#### Expected behaviour
display normal

#### Actual behaviour
When the data volume is small, it displays normally; however, once the amount of data increases, the 3D chart transforms into a 2D chart while the axes remain unchanged.

Image

At this point, if a selection zoom is performed, an exception will be thrown.

Image

#### Live demo with steps to reproduce
[code](https://jsfiddle.net/mr85cxyh/)

#### Product version
12.5.0

#### Affected browser(s)
chrome 140

### PR DESCRIPTION
**Pull request by annavvis**
Fixed #24042, wrong rendering of 3d chart series when data grouping kicked in.

~~Fixed #24042, when `dataGrouping` was applied on a 3d chart, `translate3dPoints` used series.data instead of series.points.~~

**Review notes:**

- With `dataGrouping`, series.data is an empty array as grouped points are stored inside `groupedData` property.
- Fix proposed in the PR ads a condition to check if series.data exists, otherwise uses series.points.

### CODE REVIEW

File: samples/unit-tests/3d/series-line/demo.js [hunk 1]
```diff
@@ -60,3 +60,58 @@ QUnit.test('3D line series', function (assert) {
...
+                },
+                data: [
+                    [0, 2],
+                    [2, 4],
+                    [3, 9],
+                    [5, 6],
+                    [7, 8],
+                    [8, 5],
+                    [10, 4]
+                ]
```
Comment (jedrzejruta) [inline samples/unit-tests/3d/series-line/demo.js]: Nitpicking here, however I believe that this can be transformed into a 1d array, e.g. `data: [2, 4, ..., 4]` and the result will be the same (data grouping applied).

File: samples/unit-tests/3d/series-line/demo.js [hunk 2]
```diff
@@ -60,3 +60,58 @@ QUnit.test('3D line series', function (assert) {
         'The generated SVG should not contain paths starting with line segment'
     );
 });
+
+QUnit.test('3D line series with datagrouping (#24042)', function (assert) {
+    var chart = Highcharts.chart('container', {
```
Comment (jedrzejruta) [inline samples/unit-tests/3d/series-line/demo.js]: Let's change it to const, also could you transform variables in above test too?

File: samples/unit-tests/3d/series-line/demo.js [hunk 3]
```diff
@@ -60,3 +60,58 @@ QUnit.test('3D line series', function (assert) {
...
+        chart: {
+            type: 'line',
```
Comment (jedrzejruta) [inline samples/unit-tests/3d/series-line/demo.js]: Chart type is always set as 'line' by default, let's remove this line in both tests.

File: samples/unit-tests/3d/series-line/demo.js [hunk 4]
```diff
@@ -60,3 +60,58 @@ QUnit.test('3D line series', function (assert) {
...
+        yAxis: {
+            min: 0,
+            max: 10
+        },
+
+        series: [
+            {
+                dataGrouping: {
+                    enabled: true,
+                    groupPixelWidth: 400
```
Comment (jedrzejruta) [inline samples/unit-tests/3d/series-line/demo.js:88]: Nice one, really smart approach 🎉

File: samples/unit-tests/3d/series-line/demo.js [hunk 5]
```diff
@@ -60,3 +60,58 @@ QUnit.test('3D line series', function (assert) {
...
+        ]
+    });
+
+    const series = chart.series[0];
+
+    assert.strictEqual(
+        series.data.length,
+        0,
+        'series.data should be empty when dataGrouping is applied'
+    );
```
Comment (jedrzejruta) [inline samples/unit-tests/3d/series-line/demo.js]: This can be transformed into `assert.ok()` with a simple boolean check.

File: ts/Core/Series/Series3D.ts [hunk 6]
```diff
@@ -130,7 +130,10 @@ class Series3D extends Series {
         series.zPadding = stack *
             (seriesOptions.depth || 0 + (seriesOptions.groupZPadding || 1));
 
-        series.data.forEach((rawPoint): void => {
+        // #24042, when the series uses dataGrouping, use series.points
+        const points = series.data.length > 0 ? series.data : series.points;
```
Comment (jedrzejruta) [inline ts/Core/Series/Series3D.ts]: Micro optimization:
```suggestion
        const points = series.data.length ? series.data : series.points;
```

**Review by jedrzejruta — APPROVED** [review]
All good now, thanks!

File: ts/Core/Series/Series3D.ts [hunk 7]
```diff
@@ -130,7 +130,10 @@ class Series3D extends Series {
         series.zPadding = stack *
             (seriesOptions.depth || 0 + (seriesOptions.groupZPadding || 1));
 
-        series.data.forEach((rawPoint): void => {
+        // #24042, when the series uses dataGrouping, use series.points
+        const points = series.data.length ? series.data : series.points;
```
Comment (TorsteinHonsi) [inline ts/Core/Series/Series3D.ts]: I'd expect this to use `series.points` under any circumstance, also when not data-grouping. Can you try that out? It will reduce code complexity.

Comment (annavvis) [reply ts/Core/Series/Series3D.ts]: You're right! I've checked it on our other 3D charts and all works well.
