### PR TITLE
dash/23862-multi-data-table-sync

### LINKED ISSUE #23862: MultiDataTable support and Sync highlight
#### Expected behaviour
Using other than the first DataTable from many in a connector should properly propagate events and highlight respective columns/rows in other components using the same dataTable.

#### Actual behaviour
No highlight sync. Actually, it seems all syncs go to the first dataTable

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/jkwxt7gL/

#### Product version
Dashboards v3 and v4

#### Affected browser(s)
N/A

*Internal note:*
Did some digging before reporting (to make sure it's not a Connectors problem). It seems always the first dataTable is used when syncs are enabled. Here:

https://github.com/highcharts/highcharts/blob/b4c45cedca5a45d032d6d364b6b75ba557af08b3/ts/Dashboards/Components/HighchartsComponent/HighchartsSyncs/HighchartsHighlightSync.ts#L396-L408

### PR DESCRIPTION
**Pull request by karolkolodziej**
Fixed #23862, highlight sync was incorrect when the connector was used with multiple data tables.

### CODE REVIEW

File: ts/Dashboards/Components/Component.ts [hunk 1]
```diff
@@ -413,17 +428,38 @@ abstract class Component {
...
+     * The id of the connector.
+     *
+     * @param dataTableKey
+     * The key of the data table within the connector.
+     *
+     * @returns
+     * The data table, or undefined if no matching handler is found.
      */
-    public getFirstConnector(): Component.ConnectorTypes | undefined {
-        return this.connectorHandlers[0]?.connector;
```
Comment (skrulling) [inline ts/Dashboards/Components/Component.ts:421]: Is this a breaking change to the API?

Comment (ddragula) [reply ts/Dashboards/Components/Component.ts:421]: @karolkolodziej let's leave this method for now, but we can mark it as deprecated and remove it in v3.0
