### PR TITLE
Fixed #12090, a11y module breaks legend navigation.

### LINKED ISSUE #12090: Accessibility module breaks legend's navigation
#### Expected behaviour
Legend navigation should work.

#### Actual behaviour
It doesn't because of accessibility module. Everything works well if the module is not imported.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/1d5qarn9/ 
Click legend navigation arrow.

#### Product version
Highcharts 7.2.0

### PR DESCRIPTION
**Pull request by oysteinmoseng**
Fixed #12090, a11y module breaks legend navigation.
___
A11y legend proxy buttons were overlaying navigation arrows. These are now hidden unless the corresponding legend item is on the current page.

Added a `legend.afterScroll` event that fires after legend scroll animation is complete in order to update proxies.

No other changes to non-a11y files.

### CODE REVIEW

File: ts/parts/Legend.ts [hunk 1]
```diff
@@ -1622,8 +1623,15 @@ Highcharts.Legend.prototype = {
 
             this.currentPage = currentPage;
             this.positionCheckboxes();
-        }
 
+            // Fire event after scroll animation is complete
+            const animOptions = H.animObject(
+                pick(animation, chart.renderer.globalAnimation, true)
+            );
+            setTimeout((): void => {
```
Comment (TorsteinHonsi) [inline ts/parts/Legend.ts]: Use `syncTimeout` so that it will run sync when duration is 0.

Comment (oysteinmoseng) [reply ts/parts/Legend.ts]: Fixed in separate PR
