### PR TITLE
bugfix/19233-moving-annotations-with-null-points

### LINKED ISSUE #19233: Insertion and drag of stock annotation failure when there are null points.
#### Expected behaviour
The annotation is inserted exactly at the mouse click, and the annotation does not "escape" when dragging.

#### Actual behaviour
The annotation is added slightly next to the place of clicking the mouse on the chart, the sliding causes the annotation to "escape" to the left.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/5a379snx/

1. Draw a circle (Use the *Add Circle* button)
2. Move the circle

#### Product version
Highcharts v11.1.0

---
The issue is closely related to regression reported as #18459, but it seems that it has not been fully solved. Interestingly, [this workaround](https://github.com/highcharts/highcharts/issues/18459#issuecomment-1551424002) solves the problem.

**Workaround demo:** https://jsfiddle.net/BlackLabel/dyhf4csx/

### PR DESCRIPTION
**Pull request by kamil-musialowski**
Fixed #19233, dragging annotations on chart with null points was inconsistent.

_Internal note:_ Previous refactor of `getIndexOfPoint` ignored null points, because they have a property `isInside` set to false.
Demo: https://jsfiddle.net/BlackLabel/zuhw5tjr/

### CODE REVIEW

File: ts/Core/Axis/OrdinalAxis.ts [hunk 1]
```diff
@@ -1410,7 +1410,16 @@ namespace OrdinalAxis {
 
             // Check whether the series has at least one point inside the chart
             const hasPointsInside = function (series: Series): boolean {
-                return series.points.some((point): boolean => !!point.isInside);
+                return series.points.some(function (point): boolean {
+                    let hasPointsInside = false;
+
+                    if (axis.min && axis.max) {
```
Comment (pawelfus) [inline ts/Core/Axis/OrdinalAxis.ts:1416]: Nitpicking: move this condition outside of the `some()` method. There's no need to check this condition for every point, right?

**Review by pawelfus — CHANGES_REQUESTED** [review]

File: ts/Core/Axis/OrdinalAxis.ts (hunk 1 above)
Comment (kamil-musialowski) [reply ts/Core/Axis/OrdinalAxis.ts:1416]: That's a good point, thank you!

I have also simplified the code to improve the readability.

Comment (kamil-musialowski) [reply ts/Core/Axis/OrdinalAxis.ts:1416]: That's a good point, thank you

I have also simplified the code to improve readability.

Comment (kamil-musialowski) [reply ts/Core/Axis/OrdinalAxis.ts]: Also, I have added the `isNumber` check, since if `axis.min` would be 0, previously it would fail.

**Review by pawelfus — APPROVED** [review]
Looks good, waiting for tests 👍

File: ts/Core/Axis/OrdinalAxis.ts [hunk 2]
```diff
@@ -1410,7 +1410,15 @@ namespace OrdinalAxis {
...
-                return series.points.some((point): boolean => !!point.isInside);
+                const { min, max } = axis;
+
+                if (defined(min) && defined(max)) {
+                    return series.points.some((point): boolean =>
+                        point.x >= min && point.x <= max
+                    );
+                }
+
+                return false;
```
Comment (TorsteinHonsi) [inline ts/Core/Axis/OrdinalAxis.ts:1421]: So this change is basically done because `point.isInside` isn't reliable, right? Do we know why `point.isInside` isn't up-to-date? Should we look into a fix that fixes that instead? That may fix other side-effects too, that we are not yet aware of.

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]

File: ts/Core/Axis/OrdinalAxis.ts (hunk 2 above)
Comment (kamil-musialowski) [reply ts/Core/Axis/OrdinalAxis.ts:1421]: Yes, the `point.isInside` is failing, because for null points `plotY` property is set to `undefined`.
So it fails right there: https://github.com/highcharts/highcharts/blob/3f75b6145731b0624348c823872215d3e041143e/ts/Core/Series/Series.ts#L3649

As a fix, for `point.isNull === true` we could omit this check, and maybe check only for `plotX` properties?

For example, we could set the compare value of `point.plotY` to 0 if `point.isNull === true`?  Like -> `point.plotY || 0`?

Comment (TorsteinHonsi) [reply ts/Core/Axis/OrdinalAxis.ts:1421]: Okay, as long as there's a good reason for it, I think we should just leave it like it is. As far as I understand, the `Point.isInside` flag is correct. Null points are not inside, as expected.

**Review by TorsteinHonsi — APPROVED** [review]
