### PR TITLE
bugfix/24220-treemap-zoom-datalabels-visibility

### LINKED ISSUE #24220: Misaligned data labels on Treemap after zoom
Hi, I'm using the below packages:
"highcharts": "^12.5.0",
"highcharts-angular": "^5.4.0",
"highcharts-custom-events": "^4.0.2",
"highcharts-grouped-categories": "^1.3.3",
"highcharts-regression": "^2.2.0",

### Describe the bug

I logged the bug on the Highcharts repo, but it was closed as resolved. But I still get the same behavior on the latest version available on Github.
https://github.com/highcharts/highcharts/issues/23100#issuecomment-3818386368

When zooming into a treemap chart, the child labels are still misaligned including the child tooltips. An Example can be seen here:

https://stackblitz.com/edit/stackblitz-starters-ugbvxt4z

After zooming out, everything is as it should be, it's only after zooming in that the issue occurs.

Before zooming:

Image

After zooming in:

Image

### Setup used

- NodeJS version v22.16.0
- Angular version 20.3.12
- Typescript version 5.9.3

### PR DESCRIPTION
**Pull request by jedrzejruta**
Fixed #24220, treemap data labels outside of zoomed range were still visible.

### CODE REVIEW

File: samples/unit-tests/series-treemap/zooming/demo.js [hunk 1]
```diff
@@ -67,6 +67,18 @@ QUnit.test(
...
+            'hidden',
+            'Data label outside of zoomed range should not be visible, #24220.'
+        );
+
+        assert.strictEqual(
+            chart.series[0].points[2].dataLabel.visibility,
+            'inherit',
+            'Data label inside of zoomed range should be visible, #24220.'
+        );
+
```
Comment (kamil-musialowski) [inline samples/unit-tests/series-treemap/zooming/demo.js]: Could you also please check if the dataLabel doesn't have the visibility set on `style` prop? That was the main issue if I remember correctly 🤔

Comment (jedrzejruta) [reply samples/unit-tests/series-treemap/zooming/demo.js]: You're absolutely right, it should be here too, added to the test.

File: samples/unit-tests/series-treemap/zooming/demo.js [hunk 2]
```diff
@@ -68,17 +69,24 @@ QUnit.test(
         );
 
         assert.strictEqual(
-            chart.series[0].points[1].dataLabel.visibility,
+            points[1].dataLabel.visibility &&
+            points[1].dataLabel.getStyle('visibility'),
             'hidden',
```
Comment (kamil-musialowski) [inline samples/unit-tests/series-treemap/zooming/demo.js]: If you would like to compare multiple values, you should go with e.g `deepEqual` or sth like:
```
assert.ok(
    vis === 'hidden' && styleVis ==='hidden'
)
```

otherwise, since strings are truthy  and in `&&` if all arguments are truthy we return last argument, your code will produce

```
true && 'hidden' === 'hidden'
```

so in case of 
```
'inherit' && 'hidden' === 'hidden'
```

your test will still pass 😄

File: samples/unit-tests/series-treemap/zooming/demo.js [hunk 3]
```diff
@@ -67,6 +68,24 @@ QUnit.test(
             'xAxis.max is correct according to zoom'
         );
 
+        assert.ok(
+            points[1].dataLabel.visibility === 'hidden' &&
+            points[1].dataLabel.getStyle('visibility') === 'hidden',
+            'Data label outside of zoomed range should not be visible, #24220.'
+        );
+
+        assert.strictEqual(
```
Comment (PaulDalek) [inline samples/unit-tests/series-treemap/zooming/demo.js:77]: Not a big deal but the following two asserts can be combined in one, just as in the example with the `points[1]`.

Comment (jedrzejruta) [reply samples/unit-tests/series-treemap/zooming/demo.js:77]: Indeed, however I wanted to keep them separate for clarity if one of these assertion fails
