### PR TITLE
bugfix/13950-stocktools-dg-approximation

### LINKED ISSUE #13950: SMA volume in stock tools is not visible in high price ranges
#### Expected behaviour
The stock tools demo allows adding the SMA indicator to AAPL line chart. Alternative to price can volume be referenced. The volume thought is much lower than the price and in the default price view not visible.

#### Actual behaviour
SMA volume should get its own (hidden axis), so that the volume is visible in every view.

#### Live demo with steps to reproduce
https://www.highcharts.com/demo/stock/stock-tools-gui

#### Product version
Highstock 8.1.2

#### Affected browser(s)
all

### PR DESCRIPTION
**Pull request by pawelfus**
Fixed #13950, in StockTools, adding technical indicators to column-type series did not use the same `dataGrouping.approximation`.
___
Alternative approach is to add this logic in Indicators core (instead of StockTools, like in this PR), where indicator will decide its approximation by overwriting `getDGApproximation()`. But that would be inconsistent (DG approx would depend on parent series type) and might be misleading for developers ("I'm adding SMA to A-type and B-type series, why lines are different?!"). Right now it's up to the developer to decide DG approx when using indicator. We need this change in StockTools because end-user has no way to choose an approximation, so we must set approx to the best one we can guess.

### CODE REVIEW

File: ts/Stock/StockToolsBindings.ts [hunk 1]
```diff
@@ -19,11 +19,13 @@ import type Point from '../Core/Series/Point';
 import H from '../Core/Globals.js';
 import NavigationBindings from '../Extensions/Annotations/NavigationBindings.js';
 import U from '../Core/Utilities.js';
+import dataGrouping from '../Extensions/DataGrouping';
```
Comment (bre1470) [inline ts/Stock/StockToolsBindings.ts:22]: This needs to have the file extension, or otherwise it will fail as an ES6 module.

File: ts/Stock/StockToolsBindings.ts [hunk 2]
```diff
@@ -286,6 +290,25 @@ bindingsUtils.manageIndicators = function (
...
         seriesConfig.id = uniqueKey();
         navigation.fieldsToOptions(data.fields, seriesConfig);
+        parentSeries = chart.get(seriesConfig.linkedTo);
+        defaultOptions = getOptions().plotOptions as any;
+
+        // Make sure that indicator uses the SUM approx if SUM approx is used
+        // by parent series (#13950).
+        if (
+            parentSeries &&
+            parentSeries instanceof Highcharts.Series &&
```
Comment (bre1470) [inline ts/Stock/StockToolsBindings.ts:300]: For optimization consider testing with `typeof parentSeries !== 'undefined'`, as it does not go up the `super` constructor.

Comment (pawelfus) [reply ts/Stock/StockToolsBindings.ts:300]: Okay!

File: ts/Stock/StockToolsBindings.ts (hunk 1 above)
Comment (pawelfus) [reply ts/Stock/StockToolsBindings.ts:22]: I'm surprised it's even here. Already made a commit that removes that line, probably IDE auto-imported this during development.. thanks!

Comment (pawelfus) [reply ts/Stock/StockToolsBindings.ts]: Done 👍

File: ts/Stock/StockToolsBindings.ts (hunk 2 above)
Comment (pawelfus) [reply ts/Stock/StockToolsBindings.ts:299]: Done 👍
