### PR TITLE
bugfix/13042-getTimezoneOffset-param-type

### LINKED ISSUE #13042: getTimeZoneOffset callback passes inconsistent value type
#### Expected behaviour
`time.getTimezoneOffset` should take a parameter `timestamp` that is milliseconds since January 1 1970 [according to docs](https://api.highcharts.com/highstock/time.getTimezoneOffset)

#### Actual behaviour
Effectively `timestamp` is sometimes the number of milliseconds, but also a `Date()` object. I think it depends on what kind of "thing" is being transformed (label, axis, value, ...).

#### Live demo with steps to reproduce
https://jsfiddle.net/tw6gujfv/ (observe in console)

#### Product version
Highcharts JS v8.0.0 (2019-12-10)

#### Affected browser(s)
all

### PR DESCRIPTION
**Pull request by bre1470**
Fixed #13042, `getTimeZoneOffset` callback passed inconsistent value type.

### CODE REVIEW

File: ts/parts/Time.ts [hunk 1]
```diff
@@ -152,7 +152,7 @@ declare global {
  * @callback Highcharts.TimezoneOffsetCallbackFunction
  *
  * @param {number} timestamp
- * Timestamp in terms of milliseconds since January 1 1970.
+ * Date instance or timestamp in terms of milliseconds since January 1 1970.
```
Comment (mediafreakch) [inline ts/parts/Time.ts]: Since you changed the occurences in the code to return `.valueOf()`, is this always a timestamp now?

Comment (bre1470) [reply ts/parts/Time.ts]: Thanks, good catch! Yes, this doclet change is therefor invalid.
