### PR TITLE
bugfix/14236-stacked-area-broken-axis

### LINKED ISSUE #14236: No color fill in stacked area chart with broken-axis module.
#### Expected behaviour
No console errors. Chart filling is ok. 

#### Actual behaviour
 - Console errors (6.2.0 version). In actual version no console errors
 - Color filling is broken in the middle of chart

#### Live demo with steps to reproduce
https://jsfiddle.net/necobaka/0u9cxqrt/6/

#### Product version
Highcharts-6.2.0

#### Affected browser(s)
all

### PR DESCRIPTION
**Pull request by khlieng**
Fixed #14236, stacked area chart did not render correctly with the `broken-axis` module loaded and a `gapSize` greater than `0`.

### CODE REVIEW

File: samples/unit-tests/axis/breaks/demo.js [hunk 1]
```diff
@@ -704,3 +704,663 @@ QUnit.test('Axis breaks on Y axis', function (assert) {
...
+                connectNulls: true
+            },
+            series: {
+                gapSize: 1
+            }
+        },
+        series: [
+            {
+                type: 'area',
+                data: [
```
Comment (TorsteinHonsi) [inline samples/unit-tests/axis/breaks/demo.js:725]: That's a lot of data... Test samples should be small for two reasons: easier to read and understand for future us, and small data performs better so we reduce the time required to run the tests. This setup is sufficient to reproduce the bug:

```js
const chart = Highcharts.chart('container', {
    plotOptions: {
        area: {
            stacking: 'normal',
            connectNulls: true
        },
        series: {
            gapSize: 1
        }
    },
    series: [{
            type: 'area',
            data: [
                [0, 0],
                [1, 0],
                [3, 0],
                [4, 0]
            ]
        },
        {
            type: 'area',
            data: [
                [0, 1],
                [1, 1],
                [2, 1],
                [3, 1],
                [4, 1]
            ]
        }
    ]
});
```

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
