### PR TITLE
bugfix/16165-borderRadius-disappear-hover

### LINKED ISSUE #16165: "borderRadius" disappears after hovering the pointer over plot in heatmap
Hello! 
Faced such a problem:

#### Expected behaviour
"borderRadius" doesn't disappear 

#### Actual behaviour
If you set the "borderRadius" of the plots, then after hovering over them with the pointer, the rounding disappears 
(https://api.highcharts.com/highcharts/series.heatmap.borderRadius)

#### Live demo with steps to reproduce
Live: https://jsfiddle.net/Lpsb2c1v/6/
1. Move the pointer over some plot
2. Move the pointer away

#### Product version
Version: 9.1.2

#### Affected browser(s)
OSX
Firefox: 90.0.2
Chrome: 89.0.4389.114

### PR DESCRIPTION
**Pull request by K009**
Fixed #16165, border radius disappeared after hovering a point in heatmap.

### CODE REVIEW

File: samples/unit-tests/series-heatmap/members/demo.js [hunk 1]
```diff
@@ -219,3 +219,46 @@ QUnit.test('seriesTypes.heatmap.pointClass.setState', function (assert) {
         'When state:select zIndex is 0'
     );
 });
+
+QUnit.test('Check if borderRadius is correct according to user settings', function (assert) {
```
Comment (raf18seb) [inline samples/unit-tests/series-heatmap/members/demo.js:223]: Usually, we don't want to create a separate test with a new chart's instance, because creating thousands of new charts during the tests increases theirs time. Can we reuse the above test that tests something very similar?

**Review by raf18seb — CHANGES_REQUESTED** [review]
I'm thinking whether we could add the possibility for setting the `borderWidth` and `borderRadius` per point here. It's a very popular users request in heatmap.

Something like
```js
if (
    this.options.borderRadius ||
    point.options.borderRadius
) {
    point.graphic.attr({
        r: point.options.borderRadius || this.options.borderRadius
    });
}
if (point.shapeArgs) {
    point.shapeArgs.r = point.options.borderRadius || this.options.borderRadius;
}
```

Also, please see comments below.

File: ts/Series/Heatmap/HeatmapSeries.ts [hunk 2]
```diff
@@ -440,6 +440,10 @@ class HeatmapSeries extends ScatterSeries {
                         });
                     }
 
+                    // Applying borderRadius from options (#16165)
+                    (point.shapeArgs || {}).r = this.options.borderRadius;
+                    (point.shapeArgs || {}).d = point.graphic.pathArray;
```
[the remark this answers is not in the document]
Comment (K009) [reply ts/Series/Heatmap/HeatmapSeries.ts:446]: Yes, without that the `d` value doesn't match the actual shape of path.

File: samples/unit-tests/series-heatmap/members/demo.js (hunk 1 above)
Comment (K009) [reply samples/unit-tests/series-heatmap/members/demo.js]: Sure 👍

File: samples/unit-tests/series-heatmap/members/demo.js [hunk 3]
```diff
@@ -210,12 +211,34 @@ QUnit.test('seriesTypes.heatmap.pointClass.setState', function (assert) {
...
+        'Border radius should have the value set in options on state:normal'
+    );
+
+    setState.call(point, 'hover');
+    assert.strictEqual(
+        point.graphic.d.split(' ')[1] - point.graphic.getBBox().x,
+        point.series.options.borderRadius,
+        'Border radius should have the value set in options on state:hover'
+    );
+
```
Comment (raf18seb) [inline samples/unit-tests/series-heatmap/members/demo.js:238]: I think `setState.call(point, '');` is missing here

File: samples/unit-tests/series-heatmap/members/demo.js [hunk 4]
```diff
@@ -210,12 +211,34 @@ QUnit.test('seriesTypes.heatmap.pointClass.setState', function (assert) {
...
     );
+
+    setState.call(point, '');
+    assert.strictEqual(
+        point.graphic.d.split(' ')[1] - point.graphic.getBBox().x,
+        point.series.options.borderRadius,
+        'Border radius should have the value set in options on state:normal'
+    );
+
+    setState.call(point, 'hover');
```
Comment (raf18seb) [inline samples/unit-tests/series-heatmap/members/demo.js:232]: Instead of setting these states again, can we reuse the previouse `setState.call(point, '');` and `setState.call(point, 'hover');`?

So, instead of doing `setState.call(...` 6 times, we could do it 4 times.

File: samples/unit-tests/series-heatmap/members/demo.js [hunk 5]
```diff
@@ -210,12 +211,34 @@ QUnit.test('seriesTypes.heatmap.pointClass.setState', function (assert) {
...
+    assert.strictEqual(
+        point.graphic.d.split(' ')[1] - point.graphic.getBBox().x,
+        point.series.options.borderRadius,
+        'Border radius should have the value set in options on state:hover'
+    );
+
+    assert.strictEqual(
+        point.graphic.d.split(' ')[1] - point.graphic.getBBox().x,
```
Comment (raf18seb) [inline samples/unit-tests/series-heatmap/members/demo.js:240]: Why `point.graphic.d.split(' ')[1] - point.graphic.getBBox().x` instead of `point.graphic.r`?

**Review by raf18seb — CHANGES_REQUESTED** [review]
Few questions, see below comments

File: samples/unit-tests/series-heatmap/members/demo.js (hunk 3 above)
Comment (K009) [reply samples/unit-tests/series-heatmap/members/demo.js:227]: that's true, thanks!

File: samples/unit-tests/series-heatmap/members/demo.js (hunk 4 above)
Comment (K009) [reply samples/unit-tests/series-heatmap/members/demo.js]: Yes, it should work. Thanks 👍

File: samples/unit-tests/series-heatmap/members/demo.js (hunk 5 above)
Comment (K009) [reply samples/unit-tests/series-heatmap/members/demo.js:237]: Unfortunately, `point.graphic.r` had the wrong (old) value and couldn't be used for the test. That's why I calculated it in a different way.

**Review by raf18seb — APPROVED** [review]
Good for me, thanks!

**Comment by TorsteinHonsi** [comment]
I think we need to dig deeper. The fix for #15757 was already a patch for something that should be handled in `translate` or `pointAttribs`/`markerAttribs`, and now we're creating a patch for the patch. I've create a commit where it is added to `shapeArgs` directly, but had to modify `Series.drawPoints`. Let's see how the visual tests go.

**Comment by TorsteinHonsi** [comment]
The visual tests failed. I found myself digging deeper and deeper until the depth of the `SVGRenderer.symbol` function. So resolving that would be time consuming and dangerous. I added a comment so that we can consider refactoring this at a later stage.
