### PR TITLE
bugfix/23760-datalabels-drilldown

### LINKED ISSUE #23760: Mappoint data label missing after drilldown/up
#### Expected behaviour
Enabled data labels for mappoint series are visible where relevant after drilldown/drillup actions

#### Actual behaviour
Data labels for mappoint are missing after any drilldown/drillup action

#### Live demo with steps to reproduce
1. https://jsfiddle.net/BlackLabel/e5gs902j/ - LA label is visible
2. Drilldown to California 
3. drill up (by USA breadcrump)
4. The LA datalabel is missing.

#### Product version
Highcharts Maps
Regression from version 11.1.0

### PR DESCRIPTION
**Pull request by sebastianbochan**
Fixed #23760, data label was hidden when drilled down and up.

### CODE REVIEW

File: samples/unit-tests/maps/drilldown/demo.js [hunk 1]
```diff
@@ -520,4 +520,90 @@ QUnit.test(
...
+            mappointSeries.dataLabelsGroups?.length,
+            'Mappoint should have dataLabelsGroups after drill up.'
+        );
+        assert.ok(
+            mappointSeries.group?.attr('opacity') !== 0,
+            'Mappoint group should be visible after drill up.'
+        );
+
+        delete usTopology.objects.default['hc-decoded-geojson'];
+        delete caTopology.objects.default['hc-decoded-geojson'];
```
Comment (sebastianbochan) [inline samples/unit-tests/maps/drilldown/demo.js]:
```suggestion
```
