### PR TITLE
bugfix/14138-misplaced-tooltip-column

### LINKED ISSUE #14138: Misplaced tooltip when yAxis max value set (column chart)
I configured a column chart so that the yAxis has a max value and allowed to draw a tooltip outside of the chart as well. Columns that are cut off because of the max value seem to effect the tooltip position with their original size. 
When displaying negative values in combination with a min value set the same problem occurs.

image

I would expect the tooltip to be positioned on top of the visible column.

Please see https://jsfiddle.net/rarakiroa/zbm92j7k/4/ to reproduce the issue. Hover any of the points exceeding the value of 100.

### PR DESCRIPTION
**Pull request by Izothep**
Fixed #14138, tooltip was displayed outside plotArea for columns when they were exceeding yAxis extremes.

### CODE REVIEW

File: samples/unit-tests/series-column/tooltip/demo.js [hunk 1]
```diff
@@ -52,4 +52,48 @@ QUnit.test("Shared tooltip should compare point.distX, not point.dist to find ab
...
+
+    var point = chart.series[0].data[0],
+        controller = new TestController(chart);
+
+    controller.mouseOver(
+        chart.plotLeft + point.plotX + 4,
+        chart.plotTop
+    );
+
+    assert.strictEqual(
```
Comment (pawelfus) [inline samples/unit-tests/series-column/tooltip/demo.js:93]: Could be just `ok()` instead of `strictEqual()`

**Review by pawelfus — APPROVED** [review]
Thanks!

**Review by TorsteinHonsi — APPROVED** [review]
