### PR TITLE
Boost and devicePixelRatio (Retina)

### LINKED ISSUE #10096: Boost mode retina support (high DPI displays)
Boost mode does not support retina displays (and displays with devicePixelRatio > 1).
The first image without boost optimisation. 

|screenshot 2019-02-07 at 21 47 07| screenshot 2019-02-07 at 21 47 13

Fix for canvas looks like this:
```(js)
const dpr = window.devicePixelRatio || 1;

canvas.setAttribute('width', width * dpr);
canvas.setAttribute('height', height * dpr);
canvas.style.width = `${width}px`;
canvas.style.height = `${height}px`;

const ctx = canvas.getContext('2d');
ctx.scale(dpr, dpr);
```
https://www.html5rocks.com/en/tutorials/canvas/hidpi/
But it doesn't work for WebGL.

### PR DESCRIPTION
**Pull request by TorsteinHonsi**
Added option, `boost.pixelRatio`, providing Retina and device pixel ratio support to the Boost module. 
___

Closes #10096

### Demo
https://jsfiddle.net/highcharts/mbfjL26c/

### Usage
https://github.com/highcharts/highcharts/blob/d5fc68e50dbd5f0f87ef786c2ed01697f0f6c7cb/ts/Extensions/Boost/BoostOptions.ts#L209-L234

### To do
 - [x] Default [is not working](https://github.com/highcharts/highcharts/blob/d5fc68e50dbd5f0f87ef786c2ed01697f0f6c7cb/ts/Extensions/Boost/WGLRenderer.ts#L211-L213). ~~It's time to introduce a DefaultOptions object for the Boost.~~
 - [x] Marker sizes are not scaled up
 - [x] Bubble sizes, probably the same cause
 - [x] Heatmap
 - [x] Treemap

### CODE REVIEW

File: ts/Extensions/Boost/BoostAttach.ts [hunk 1]
```diff
@@ -18,7 +18,7 @@ import type SVGElement from '../../Core/Renderer/SVG/SVGElement';
 import Chart from '../../Core/Chart/Chart.js';
 import GLRenderer from './WGLRenderer.js';
 import H from '../../Core/Globals.js';
-const { doc } = H;
+const { doc, win } = H;
```
Comment (pawelfus) [inline ts/Extensions/Boost/BoostAttach.ts:21]: Unused variable

**Review by pawelfus — CHANGES_REQUESTED** [review]
Just a minor thing, the rest looks good 👍

**Review by raf18seb — APPROVED** [review]
👍
