### PR TITLE
data/math-modifier-negative-value-multiplication

### LINKED ISSUE #23130: MathModifier with negative multiplication
#### Expected behaviour
Formula:
```
                dataModifier: {
                    type: 'Math',
                    columnFormulas: [{
                        column: 'USD',
                        formula: 'B1 * -1'
                    }]
                }
```
Should return negative value of the Column B

#### Actual behaviour
Subtraction is returned.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/2k7uLbaf/

#### Product version
Highcharts Dashboards

#### Affected browser(s)
N/A

#### Workaround
Use `PRODUCT(B1, -1)` instead: https://jsfiddle.net/BlackLabel/2k7uLbaf/1/

### PR DESCRIPTION
**Pull request by KamilKubik**
Fixed #23130, math modifier negative value multiplication.

### CODE REVIEW

**Review by karolkolodziej — APPROVED** [review]

File: ts/Data/Formula/FormulaParser.ts [hunk 1]
```diff
@@ -572,7 +572,18 @@ function parseFormula(
...
         match = next.match(decimalRegExp);
         if (match) {
-            formula.push(parseFloat(match[0]));
+            let number = parseFloat(match[0]);
+            // If the current value is multiplication-related and the previous
+            // one is a minus sign, set the current value to negative and remove
+            // the minus sign.
+            if (
+                formula[formula.length - 1] === '-' &&
+                formula[formula.length - 2] === '*'
```
Comment (ddragula) [inline ts/Data/Formula/FormulaParser.ts]: This is not universal enough. Check other operators than only `*`, e.g. `/` or `^`. Do we even need to check what specifically it is? Maybe `length > 1` and `last == '-'` is enough?

**Review by ddragula — CHANGES_REQUESTED** [review]

File: ts/Data/Formula/FormulaParser.ts (hunk 1 above)
Comment (KamilKubik) [reply ts/Data/Formula/FormulaParser.ts]: The sequence for the negative value multiplication is basically `['*', '-', number]`. I don't like those specific checks either, but the issue is that if we check for the `'-'` only, we exclude the simple subtraction, so that's why we also check for the `'*'`. To sum up, the issue is to distinguish subtraction from multiplication by a negative value at some level (I'm saying that because I was thinking about handling it at the regex/extracting level, where we build the proper formula). 

Additionally, we can have multiple multiplications, such as `-x * -y * -z`, so I think it's the safest option to always base it on the previous elements from the particular iteration.

Comment (ddragula) [reply ts/Data/Formula/FormulaParser.ts]: As for the multiplication,`'B1 * -C1'` also doesn't work, but it should.
image

We are currently patching too small part of the bigger problem in my opinion.

**Comment by KamilKubik** [comment]
> Isn't that fixed by the new PR?

_General note:_ The new PR has been merged into this. The current version is final and ready for review.

**Review by skrulling — APPROVED** [review]

**Review by karolkolodziej — APPROVED** [review]

**Review by sebastianbochan — APPROVED** [review]
