### PR TITLE
bugfix/20611-variwide-linear

### LINKED ISSUE #20611: Z plotted points on variwide charts do not expand the X-axis
#### Expected behaviour

For this chart:  https://jsfiddle.net/4g6whsoL/8/
The last point plotted -> [x:14, y:4, z:10]
Gets cut off 
image

#### Actual behaviour
Should expand and show the whole column:
image

#### Live demo with steps to reproduce
https://jsfiddle.net/4g6whsoL/8/

#### Product version
9.2.2

#### Affected browser(s)
Chrome and maybe others

### PR DESCRIPTION
**Pull request by hubertkozik**
Fixed #20611, wrong linear x-axis extremes for variwide series.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1206580038320331

### CODE REVIEW

**Review by magdalena-gut — APPROVED** [review]
LGTM!

File: ts/Series/Variwide/VariwideSeries.ts [hunk 1]
```diff
@@ -235,6 +239,18 @@ class VariwideSeries extends ColumnSeries {
...
+
+    public getXExtremes(
+        xData: Array<number>|Types.TypedArray
+    ): RangeSelector.RangeObject {
+        const max = arrayMax(xData),
+            maxZ = this.getColumn('z')[xData.indexOf(max)];
+
+        return {
+            min: arrayMin(xData),
+            max: max + (!this.xAxis.categories ? maxZ : 0)
```
Comment (TorsteinHonsi) [inline ts/Series/Variwide/VariwideSeries.ts:251]: It's slightly more readable and compact if we avoid the negation
```suggestion
            max: max + (this.xAxis.categories ? 0 : maxZ)
```

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks!

**Review by TorsteinHonsi — APPROVED** [review]

**Review by KacperMadej — APPROVED** [review]
