### PR TITLE
bugfix/23654-export-data-wrong-datetime-format

### LINKED ISSUE #23654: Export of date string broken
#### Expected behaviour
Should export datetime X-values formatted as date string correctly

#### Actual behaviour
Exports datetime X-values formatted as date string always as '1970-01-01 00:00:00'

#### Live demo with steps to reproduce
https://jsfiddle.net/uoev5kyh/1/

Export data or check console

#### Product version
v12.4.0 (latest)

#### Affected browser(s)
All (tested on Firefox and Chrome)

### PR DESCRIPTION
**Pull request by jedrzejruta**
Fixed #23654, wrong `dateTime` parsing when exporting data set as date string.

### CODE REVIEW

File: ts/Extensions/ExportData/ExportData.ts [hunk 1]
```diff
@@ -418,6 +418,7 @@ namespace ExportData {
         options: SeriesOptions;
         pointArrayMap?: Array<string>;
         index: number;
+        xAxis: Axis
```
Comment (pawelfus) [inline ts/Extensions/ExportData/ExportData.ts]:
```suggestion
        xAxis: Axis;
```

File: samples/unit-tests/export-data/basics/demo.js [hunk 2]
```diff
@@ -1120,7 +1141,7 @@ QUnit.test('Descending categories', function (assert) {
         csv = chart.exporting.getCSV().split('\n');
 
     assert.strictEqual(
-        csv[2],
+        csv[1],
```
Comment (pawelfus) [inline samples/unit-tests/export-data/basics/demo.js:1144]: Q: 

Could you elaborate on this change? Indeed output changes from:
```js
0: "\"Category\",\"New\",\"In Progress\""
1: "\"Category 2\",,16"
2: "\"Category 1\",34,66"
```
To:
```js
0: "\"Category\",\"New\",\"In Progress\""
1: "\"Category 1\",34,66"
2: "\"Category 2\",,16"
```

And your solution seems to fix that (order in CSV and on xAxis is the same).

Comment (jedrzejruta) [reply samples/unit-tests/export-data/basics/demo.js:1144]: @pawelfus Before the change, without xAxis assigned to the `mockSeries`, applying options to the mock point tried to assume it's x value by using `series.autoIncrement()`. https://github.com/highcharts/highcharts/blob/2536764ac6ae63541f111df422065444c1e0e352/ts/Core/Series/Point.ts#L666-L688 Since the looping order is chronological, e.g. 1st series is iterated and assigned x = 0 for 1st point, then for 2nd series, 1st point (Category 2 with y = 16) based on auto increment gets the x = 0, and 2nd point gets x = 1, even though it should be other way around. https://github.com/highcharts/highcharts/blob/2536764ac6ae63541f111df422065444c1e0e352/ts/Extensions/ExportData/ExportData.ts#L1035 Then, in exporting data, rows are sorted by xValues array, which in this case is wrongly assigned based on mock point's x value (Category 1 row xValues=[1], category 2 xValues=[0]).
https://github.com/highcharts/highcharts/blob/2536764ac6ae63541f111df422065444c1e0e352/ts/Extensions/ExportData/ExportData.ts#L1081-L1087

Comment (pawelfus) [reply samples/unit-tests/export-data/basics/demo.js:1144]: Right! Without Axis, `nameToX` won't be called out and wrong indexes will be assigned. Thanks for checking!
