### PR TITLE
bugfix/17280-zero-z-bubbles-disappear

### LINKED ISSUE #17280: Bubble series bounded by z=0 causes points to disappear
#### Expected behaviour
Points in bubble series with z = 0 should be handled as any other point when computing the range of z values used for rendering.

#### Actual behaviour
When plotting multiple bubble series, a series whose minimum z value is 0 causes the computation of the global `z` scale to fail. This results in points falling out of the range and not being plotted at all.

I believe the issue is in those lines: https://github.com/highcharts/highcharts/blob/v10.1.0/ts/Series/Bubble/BubbleSeries.ts#L469-L470  If the running `zMin` or `zMax` is 0, the running minimum/maximum is forgotten and replaced with the current series' minimum/maximum in the loop.

#### Live demo with steps to reproduce
https://jsfiddle.net/5ns2ozma/

#### Product version
Highcharts v10.1.0

#### Affected browser(s)
Firefox, Chrome

### PR DESCRIPTION
**Pull request by Vazonik**
Fixed #17280, bubbles with `z: 0` caused points to disappear.

### CODE REVIEW

**Review by pawellysy — APPROVED** [review]
Looks good! Thanks

**Review by raf18seb — CHANGES_REQUESTED** [review]
Nice, the fix is nice and clean, but please add also:
- [x] regression test
- [ ] comment with a small description and issue number so it's easy to find info in the future if necessery

File: samples/unit-tests/series-bubble/extremes/demo.js [hunk 1]
```diff
@@ -91,3 +91,36 @@ QUnit.test('Setting X axis extremes on bubble (#5167)', function (assert) {
     assert.ok(chart.yAxis[0].min < 102.9, 'DE point is within range');
     assert.ok(chart.yAxis[0].max > 102.9, 'DE point is within range');
 });
+
+QUnit.test('Calculation of Z extremes when Z = 0 (#17280)', function (assert) {
+    const chart = Highcharts.chart('container', {
```
Comment (raf18seb) [inline samples/unit-tests/series-bubble/extremes/demo.js:96]: Thanks for the test! Is there a chance to use an already existing test instead of creating a whole new separate test?
Word of explanation: a separate new test creates the whole chart from scratch. When having thousands of tests, we would have to create thousands of charts, and that would be a performance kill (running tests already takes at least a few minutes). Instead, you can use the existing test/chart and use the `update()` method (very often without `redraw` if not needed) - it's much more efficient for a longer period of time.

**Review by raf18seb — CHANGES_REQUESTED** [review]
Thanks! One more comment, please see below

**Review by TorsteinHonsi — APPROVED** [review]
Thanks! Approved, waiting for the CI to approve.
