### PR TITLE
bugfix/12666-sankey-connectNulls-functionality

### LINKED ISSUE #12666: Unable to connectNulls for Sankey charts
#### Expected behaviour
Connecting a Node to `null` should increase the starting Node weight. Not crash.

Example from the [Sankey demo](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/css/sankey/):

```js
series: [{
    keys: ['from', 'to', 'weight'],
    connectNulls: true,
    data: [
        ['Oil', 'Transportation', 94],
        ['Natural Gas', 'Transportation', 3],
        ['Coal', 'Transportation', 0],
        ['Renewable', 'Transportation', 0],
        ['Nuclear', 'Transportation', 3],

        ['Oil', 'Industrial', 41],
        ['Natural Gas', 'Industrial', 40],
        ['Coal', 'Industrial', 7],
        ['Renewable', 'Industrial', 11],
        ['Nuclear', 'Industrial', 0],

        ['Oil', 'R&C', 17],
        ['Natural Gas', 'R&C', 76],
        ['Coal', 'R&C', 1],
        ['Renewable', 'R&C', 7],
        ['Nuclear', 'R&C', 0],

        ['Oil', 'Electric Power', 1],
        ['Natural Gas', 'Electric Power', 18],
        ['Coal', 'Electric Power', 48],
        ['Renewable', 'Electric Power', 11],
        ['Nuclear', null, 25], /* Nuclear goes to nowhere, no pun intended */
    ],
}]
```

I would expect the chart to look like this:

image

#### Actual behaviour
Highcharts crashes in:

```js
          generatePoints: function () {
                H.NodesMixin.generatePoints.apply(this, arguments);
                /**
                 * Order the nodes, starting with the root node(s). (#9818)
                 * @private
                 */
                function order(node, level) {
                    // Prevents circular recursion:
                    if (typeof node.level === 'undefined') { <- Uncaught TypeError: Cannot read property 'level' of undefined
                        node.level = level;
                        node.linksFrom.forEach(function (link) {
                            order(link.toNode, level + 1);
                        });
                    }
                }
```

#### Live demo with steps to reproduce
[JSFiddle](https://jsfiddle.net/z4391waq/)

#### Product version
Highcharts JS v8.0.0 (2019-12-10)

#### Affected browser(s)
All

### PR DESCRIPTION
**Pull request by Basts**
Fixed #12666, node render to null increase the sum by set weight.

### CODE REVIEW

File: samples/unit-tests/series-sankey/sankey/demo.js [hunk 1]
```diff
@@ -669,4 +669,40 @@ QUnit.test(
...
+                    ['Nuclear', null, 52]
+                ],
+                type: 'sankey'
+            }]
+        });
+
+        assert.strictEqual(
+            chart.series[0].nodes[2].sum,
+            59,
+            'For this node value from the point with linkTo null should be added to sum (#12453)'
```
Comment (pawelfus) [inline samples/unit-tests/series-sankey/sankey/demo.js]: Wrong issue reference.
