### PR TITLE
bugfix/24029-yAxis-extremes-panning-boost

### LINKED ISSUE #24029: Y Panning broken with boost module
#### Expected behaviour
The y panning should be working with boost mode enabled.

#### Actual behaviour
The y panning doesn't work with boost mode enabled.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/vuox0ecr/

In the above fiddle only x panning works after zooming.

Notes:
- it works without boost module
- it works with boost module, but only when yAxis min and max are removed
- y panning works when excessively zoomed in

#### Product version
Highcharts Core

### PR DESCRIPTION
**Pull request by sebastianbochan**
Fixed #24029, y-axis panning was broken with the boost module if the y-axis had explicit extremes.

### CODE REVIEW

File: ts/Extensions/Boost/BoostSeries.ts [hunk 1]
```diff
@@ -796,24 +796,60 @@ function hasExtremes(
...
+                isNumber(xAxis.min) &&
+                isNumber(xAxis.max) &&
+                isNumber(xAxisOptions?.min) &&
+                isNumber(xAxisOptions?.max) &&
+                (xAxis.max - xAxis.min) < (xAxisOptions.max - xAxisOptions.min)
+            )
+        ) {
+            return false;
+        }
+    }
```
Comment (jedrzejruta) [inline ts/Extensions/Boost/BoostSeries.ts]: Since both bodies and returns of these if statements look the same (only y-axis or x-axis changes) does it make sense to merge them into some utility function which takes axis and optional boolean as arguments? What do you think?

File: samples/unit-tests/boost/panning-yaxis-extremes/demo.js [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+
+    // yAxis extremes should have changed after yAxis panning
+    assert.ok(
+        chart.yAxis[0].min !== yAxisZoomExtremes.min ||
+        chart.yAxis[0].max !== yAxisZoomExtremes.max,
+        'yAxis extremes should change after yAxis panning'
+    );
+
+    // xAxis extremes should have changed after xAxis panning
+    console.log(chart.xAxis[0].min, xAxisZoomExtremes.min);
```
Comment (jedrzejruta) [inline samples/unit-tests/boost/panning-yaxis-extremes/demo.js]: 👀

**Comment by jedrzejruta** [comment]
> Have you tried checking if this is a regression?

It was checked twice (by me and @annavvis) that it's not a regression, it has never worked for the y-axis when the extremes are set.

**Comment by sebastianbochan** [comment]
@TorsteinHonsi 
No, it's not the regression as we checked before.

The panning by x works accidentally (because in `hasExtremes()` we missed setting `checkX` as true). If we fix it, then panning would not be supported in the boost at all (both x/y directions) 

The question is, do we want to have panning (if so, then we need to make some extra calculations) or not, because of performance.

We can try to detect first render, when xAxis or yAxis extremes have been changed (when its zoomed for instance) then run my calculations.

EDIT: Where can I run the performance test that you mentioned?

**Comment by TorsteinHonsi** [comment]
@sebastianbochan 

> Where can I run the performance test that you mentioned?

Sorry, I shared the wrong link.
1. Open https://jsfiddle.net/highcharts/ao95wyr1/
2. Run 5+ times and make note of the fastest reported render time in the console
3. Now run the same again with this PR's version of the Highcharts files
4. For me the PR version is ~20% slower

> The question is, do we want to have panning

Yes, I consider this a bug. But without digging too much inside the code, during panning we should also have a situation when `hasExtremes` = true. We do know the axis min and max, so we don't need to loop the data in order to find out the extremes. Again, just my thoughts without actually digging into the existing or proposed code.

**Comment by sebastianbochan** [comment]
@TorsteinHonsi 
Refactored the whole fix, only what's left is the test that you added (processXData). If we agree about removing it, the fix is ready to review.

**Comment by sebastianbochan** [comment]
@TorsteinHonsi 
I applied some modifications, however, when I run my Playwright test, the rendering time is almost the same (no 20% difference).

Screenshot 2026-02-03 at 10 20 39
Screenshot 2026-02-03 at 10 20 34

**Comment by TorsteinHonsi** [comment]
Great, I get the same results! Render time is on par with what it was, because we now return true from `hasExtremes`.
