### PR TITLE
bugfix/13934-xAxis-range-stock-crash

### LINKED ISSUE #13934: Page crashes with memory limit when xAxis intervals are out of range
#### Expected behaviour
Chart should be displayed without any points. 

#### Actual behaviour
When `plotOptions.series.dataGrouping` is enabled, the page crashes. When disabled the chart is rendered.

#### Live demo with steps to reproduce
http://jsfiddle.net/brkxgwq8/

#### Product version
Highstock JS v8.1.2 (2020-06-16)

#### Affected browser(s)
Chrome, Firefox

### PR DESCRIPTION
**Pull request by karolkolodziej**
Fixed #13934, chart crashed when `dataGrouping` was disabled and axis extremes were set outside the data range.

### CODE REVIEW

File: ts/Core/Axis/Axis.ts [hunk 1]
```diff
@@ -6452,7 +6452,7 @@ class Axis implements AxisComposition, AxisLike {
             step,
             bestScore = Number.MAX_VALUE,
             autoRotation: any,
-            range = (this.max as any) - (this.min as any),
+            range = Math.abs((this.max as any) - (this.min as any)),
```
Comment (TorsteinHonsi) [inline ts/Core/Axis/Axis.ts:6455]: I'm not sure I understand why a negative value should be turned positive. Isn't the point to keep it above 0 so that we don't enter an eternal loop? In that case, this would be more logically correct (and easier to understand for future us):

`range = Math.max((this.max as any) - (this.min as any), 0),`

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]

File: ts/Core/Axis/Axis.ts (hunk 1 above)
Comment (karolkolodziej) [reply ts/Core/Axis/Axis.ts]: Yep, you're right, that makes much more sense!

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
