### PR TITLE
 bugfix/21743-gridlines-outside-plotarea

### LINKED ISSUE #21743: Minor grid lines outside the plotArea
#### Expected behaviour
Minor grid lines of the second x-axis should be displayed within the plot area.

#### Actual behaviour
Minor grid lines of the second x-axis are displayed outside the chart.
image

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/ua61yxhw/

#### Product version
Highcharts v11.4.7

### PR DESCRIPTION
**Pull request by Xillez**
Fixed #21743, minor grid lines rendered outside the axis plot area

---

Asana task => https://app.asana.com/0/1204848917817812/1208180869258050/f

### CODE REVIEW

**Review by KacperMadej — APPROVED** [review]
Some smaller comments in code - other that that, works and looks good 👍

**Comment by Xillez** [comment]
Will take a look on Monday 👍

**Review by TorsteinHonsi — COMMENTED** [review]
Thanks! Now with the new logic, we avoid trimming the ticks if the axis is linked, but we make an exception when the length and extremes are identical.

The question is - in what cases are the length and extremes _not_ identical? And are there smarter ways of dealing with that?

In the typical use case for linked axes, they are identical - even if one is categorized and the other not: https://jsfiddle.net/highcharts/awk2L7cg/

**Comment by Xillez** [comment]
the only way I managed to make it at least not visually similar was to force the length to be shorter by setting I think left and len on the axis or something similar, though not entirely sure if it's a feasible scenario.
I was told the ranges of multiple axes can be quite different and therefore non-overlapping sections might undesirably be removed. Perhaps I misunderstood? I can remove the extra check if that's something we see won't ever be a case 👍 
Not entirely sure about a smarter way, if you have some ideas I'm filly open 👍

**Comment by TorsteinHonsi** [comment]
> I can remove the extra check if that's something we see won't ever be a case

@Xillez Yes I think we should take that chance, if all tests pass and nobody else knows why it is there. Better to avoid dead code.

File: ts/Core/Axis/Axis.ts [hunk 1]
```diff
@@ -2183,7 +2183,12 @@ class Axis {
 
         fireEvent(this, 'trimTicks');
 
-        if (!this.isLinked) {
+        if (
+            !this.isLinked ||
+            // Linked non-grid axes should trim ticks, #21743.
+            // Grid axis has custom handling of ticks.
+            !this.grid
+        ) {
```
Comment (TorsteinHonsi) [inline ts/Core/Axis/Axis.ts:2191]: Now do we need the `isLinked` test at all? Wouldn't it be enough with `if (!this.grid)` ?

Comment (Xillez) [reply ts/Core/Axis/Axis.ts:2191]: Could be, I can test more 👍

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
