### PR TITLE
bugfix/22330-waterfall-points-on-axis-break

### LINKED ISSUE #22330: Waterfall chart first point rendering incorrectly with broken axis module
#### Actual behaviour
When using the broken axis feature in a waterfall chart, the first point does not respect the specified break range and renders with an incorrect scale on the y-axis. For example, in the given configuration, the first point (with a y value of -12) should appear at -12 on the y-axis, but it incorrectly renders at -16. 

#### Live demo with steps to reproduce
https://jsfiddle.net/jsfiddle_demo/8wxdh6fv/

### PR DESCRIPTION
**Pull request by kamil-musialowski**
Fixed #22330, rendering of waterfall points crossing axis break was incorrect.

### CODE REVIEW

File: samples/unit-tests/series-waterfall/waterfall/demo.js [hunk 1]
```diff
@@ -100,4 +100,68 @@ QUnit.test('General waterfall tests', function (assert) {
...
+                y: -2
+            }
+        ]
+    });
+
+    assert.close(
+        chart.series[1].points[0].graphic.attr('height'),
+        chart.yAxis[0].toPixels(-4, true),
+        1,
+        'First point of the second stacked should have correct height, #22330.'
```
Comment (jedrzejruta) [inline samples/unit-tests/series-waterfall/waterfall/demo.js]:
```suggestion
        'First point of the second stack should have correct height, #22330.'
```

File: samples/unit-tests/series-waterfall/waterfall/demo.js [hunk 2]
```diff
@@ -100,4 +100,68 @@ QUnit.test('General waterfall tests', function (assert) {
...
+                y: -4
+            }, {
+                y: -2
+            }
+        ]
+    });
+
+    assert.close(
+        chart.series[1].points[0].graphic.attr('height'),
+        chart.yAxis[0].toPixels(-4, true),
```
Comment (pawelfus) [inline samples/unit-tests/series-waterfall/waterfall/demo.js]: I'm not sure - should we check the second series? That one seems good in stacked chart in current release: https://jsfiddle.net/5xufb2zc/

File: ts/Series/Waterfall/WaterfallSeries.ts [hunk 3]
```diff
@@ -706,7 +706,7 @@ addEvent(WaterfallSeries, 'afterColumnTranslate', function (): void {
                     hPos = y;
                 } else {
                     yPos = y;
-                    hPos = y - pointY;
+                    hPos = (pointY >= 0) ? (y - pointY) : (y + pointY);
```
Comment (pawelfus) [inline ts/Series/Waterfall/WaterfallSeries.ts]: Microoptimization:
The above perhaps should be simplified to `hPos = y - Math.abs(pointY);`, however, the whole if-else could be reduced to:

```ts
yPos = y;
hPos = y - Math.abs(pointY);

if (yAxis.reversed) {
  [yPos, hPos] = [hPos, yPos];
}
```

Which actually raises a question: do we need `yPos` (or `y`)? Could you please check this?

Comment (kamil-musialowski) [reply ts/Series/Waterfall/WaterfallSeries.ts]: Thanks, looks like it's not needed and we can just go with `y` 👍

File: samples/unit-tests/series-waterfall/waterfall/demo.js [hunk 4]
```diff
@@ -100,4 +100,69 @@ QUnit.test('General waterfall tests', function (assert) {
...
+            }, {
+                y: -2
+            }
+        ]
+    });
+
+    assert.close(
+        chart.series[0].points[0].graphic.attr('height') +
+        chart.series[1].points[0].graphic.attr('height'),
+        chart.yAxis[0].toPixels(-16, true),
```
Comment (pawelfus) [inline samples/unit-tests/series-waterfall/waterfall/demo.js]: Nitpicking: replace -16 with sum of values taken from series.data/points.
