### PR TITLE
docs/14583-fix-series-threshold-type

### LINKED ISSUE #14583: plotOptions.series.threshold Typescript type does not accept null
#### Expected behaviour
plotOptions.series.threshold can be set to null in order to automatically scale the y-axis according to the data shown, not e.g.  have as lower limit default 0 but a value close to the minimum value of the data.

#### Actual behaviour
plotOptions.series.threshold cannot be set to null, since typescript definition only allows Number and undefined.

#### Live demo with steps to reproduce
I copied this example from https://github.com/highcharts/highcharts/issues/12824, where the problem seems to be solved at least for some cases. "threshold: null" cannot be used when using typescript.

Highcharts.chart('container', {
    xAxis: {
    	categories: ['Apples', 'Pears', 'Bananas', 'Oranges']
    },
    series: [{
        data: [101, 104, 103, 105],
        type: 'area',
        threshold: null
    }]
});

#### Product version
8.2.2

#### Affected browser(s)
Has nothing do with a browser.

### PR DESCRIPTION
**Pull request by bre1470**
Fixed #14583 the types of series threshold options.

### CODE REVIEW

File: ts/Core/Series/Series3D.ts [hunk 1]
```diff
@@ -67,7 +67,7 @@ class Series3D extends LineSeries {
      *
      * */
 
-    public static defaultOptions = merge(LineSeries.defaultOptions);
+    public static defaultOptions = merge(LineSeries.defaultOptions, {});
```
Comment (TorsteinHonsi) [inline ts/Core/Series/Series3D.ts:70]: Why the change? The `merge` function creates a deep copy when fed a single argument...

File: ts/Series/Spline/SplineSeries.ts [hunk 2]
```diff
@@ -62,7 +62,7 @@ class SplineSeries extends LineSeries {
      * @product      highcharts highstock
      * @optionparent plotOptions.spline
      */
-    public static defaultOptions: SplineSeriesOptions = merge(LineSeries.defaultOptions);
+    public static defaultOptions: SplineSeriesOptions = merge(LineSeries.defaultOptions, {});
```
Comment (TorsteinHonsi) [inline ts/Series/Spline/SplineSeries.ts:65]: As above

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]

File: ts/Core/Series/Series3D.ts (hunk 1 above)
Comment (bre1470) [reply ts/Core/Series/Series3D.ts:70]: This is to be consistent with the other change.

File: ts/Series/Spline/SplineSeries.ts (hunk 2 above)
Comment (bre1470) [reply ts/Series/Spline/SplineSeries.ts:65]: Here it is because of the JSDoc parser, as it needs curly brackets.

Comment (TorsteinHonsi) [reply ts/Series/Spline/SplineSeries.ts:65]: What's stopping future us from removing the empty object because we know it doesn't make a difference logically, then breaking JSDoc? Can we fix JSDoc instead? Are there more cases like this?

Comment (bre1470) [reply ts/Series/Spline/SplineSeries.ts:65]: That is the only one, I am aware of. We might get JSDoc fixed instead. I will give it a try tomorrow.

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
