### PR TITLE
bugfix/20499-dataLabels-width-styledMode

### LINKED ISSUE #20499: Data labels do line break only after resize in treegraph with styledMode
#### Expected behaviour
When loading the chart, the data labels have line breaks were needed to fit in the marker.

#### Actual behaviour
The labels are in one line and line breaks are only applied once resizing the chart.

On load:
image

After resizing the window:
image

#### Live demo with steps to reproduce
https://jsfiddle.net/0h1Le3ou/19/
It does seem to not be completely consistent - sometimes on load of the fiddle it'll already have the line break. But saving the fiddle, so only the preview is reloaded without the full page puts it into one line consistently.

Resize the window -> labels will have line breaks

#### Product version
11.3.0

#### Affected browser(s)
Firefox, Chrome

### PR DESCRIPTION
**Pull request by K009**
Fixed #20499, data labels failed to apply width in styled mode.

### CODE REVIEW

**Review by hubertkozik — COMMENTED** [review]
The change looks good to me, but I am little bit afraid about visual difference. Can you check if the change looks legit?

**Review by hubertkozik — APPROVED** [review]

**Review by TorsteinHonsi — COMMENTED** [review]
It looks good to me, but I'm wondering if this is really specific to treegraphs. Can you check other series types where setting the width would make sense? Sunburst (width set internally), treemap (also internally), and the vanilla charts like column, bar, line, pie etc.

**Comment by TorsteinHonsi** [comment]
@K009 I think the first solution is good. I'm also concerned about the visual diffs, but can we try it again and have a look?

File: ts/Core/Series/DataLabel.ts [hunk 1]
```diff
@@ -763,6 +763,13 @@ namespace DataLabel {
                                 dataLabel.css(style).shadow(
                                     labelOptions.shadow
                                 );
+                            } else if (style.width) { // #20499
```
Comment (TorsteinHonsi) [inline ts/Core/Series/DataLabel.ts:766]: Redundant, the issue number is mentioned below
```suggestion
                            } else if (style.width) {
```

File: ts/Core/Series/DataLabel.ts [hunk 2]
```diff
@@ -763,6 +763,13 @@ namespace DataLabel {
...
+                                // In styled mode with a width property set,
+                                // the width should be applied to the
+                                // dataLabel. (#20499)
+                                dataLabel.css({
+                                    width: style.width
```
Comment (TorsteinHonsi) [inline ts/Core/Series/DataLabel.ts:771]: Now that we allowed width, I think we also should allow `textOverflow`. Otherwise implementers will not be able to apply ellipsis. It can't be set in CSS alone because it requires a JavaScript interpretation for SVG text.

```suggestion
                                    width: style.width,
                                    textOverflow: style.textOverflow
```

**Comment by TorsteinHonsi** [comment]
@K009 I don't know, I've never been in the other end of a commit suggestion 😅 . You can probably just apply it, but it needs to be tested afterwards. Maybe ask the other team members how they prefer to deal with the suggestions.

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
