### PR TITLE
bugfix/7802-ema-zero-points

### LINKED ISSUE #7802: EMA - zero points
#### Expected behaviour
Correct values

#### Actual behaviour
All values are 0

#### Live demo with steps to reproduce
Demo:
- http://jsfiddle.net/BlackLabel/ofz7trnj/

#### Affected browser(s)
All

### PR DESCRIPTION
**Pull request by sebastianbochan**

### CODE REVIEW

File: samples/stock/indicators/ema/demo.js [hunk 1]
```diff
@@ -1,5 +1,4 @@
-
-$.getJSON('https://www.highcharts.com/samples/data/aapl-ohlc.json', function (data) {
+$.getJSON('https://www.highcharts.com/samples/data/jsonp.php?filename=aapl-ohlc.json&callback=?', function (data) {
```
Comment (TorsteinHonsi) [inline samples/stock/indicators/ema/demo.js]: We stopped using the jsonp.php endpoints, instead we opened up for CORS directly.
