### PR TITLE
bugfix/21213-axis-labels-padding-type

### LINKED ISSUE #21213: Type of axis label padding changes in 11.4.3
#### Expected behaviour

Wasn't expecting to need to change any code when upgrading from `11.4.1` to `11.4.3`.

#### Actual behaviour

After upgrading from `11.4.1` to `11.4.3`, our build is complaining about some code that's setting `yAxis.labels.padding` to `0` 

```
Type error: Type '{ min: number; max: number; minorTicks: true; reversed: true; crosshair: { snap: false; }; title: { text: null; }; tickPositions: number[]; maxPadding: number; minPadding: number; events: { setExtremes(this: Axis, e: AxisSetExtremesEventObject): void; }; labels: { ...; }; plotLines: YAxisPlotLinesOptions[]; }' is not assignable to type 'YAxisOptions | YAxisOptions[] | undefined'.
  The types of 'labels.padding' are incompatible between these types.
    Type 'number' is not assignable to type 'string'.
```

It seems the type of `padding` has changed from `number` to `string` between these releases. Was that intentional?

#### Live demo with steps to reproduce

Since this is a build issue, I created a [DevBox](https://codesandbox.io/p/devbox/highcharts-typescript-qqg4qd?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwjoogkg00073b6iofzjenxg%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwjoogkf00023b6ir8yzy059%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwjoogkf00043b6io5toqg5w%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwjoogkg00063b6i2a3yg5bh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwjoogkf00023b6ir8yzy059%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwjoogkf00013b6iiwthe7jo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%257D%255D%252C%2522id%2522%253A%2522clwjoogkf00023b6ir8yzy059%2522%252C%2522activeTabId%2522%253A%2522clwjoogkf00013b6iiwthe7jo%2522%257D%252C%2522clwjoogkg00063b6i2a3yg5bh%2522%253A%257B%2522id%2522%253A%2522clwjoogkg00063b6i2a3yg5bh%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clwjoogkf00043b6io5toqg5w%2522%253A%257B%2522id%2522%253A%2522clwjoogkf00043b6io5toqg5w%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwjoogkf00033b6it7srpo2e%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522build%2522%252C%2522id%2522%253A%2522clwjoqm0x00a13b6inf1z19j9%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522clwjosj8a00hb3b6i403bpb03%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clwjosj9d000kdgf9ck2d4pxa%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clwjoqm0x00a13b6inf1z19j9%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) to demonstrate the build error I'm seeing. If you downgrade `highcharts` to `11.4.1` and re-run the build it'll succeed.

#### Product version
`11.4.3`

#### Affected browser(s)

n/a

### PR DESCRIPTION
**Pull request by pawelfus**
Fixed #21213, `yAxis.labels.padding` had incorrect type.

### CODE REVIEW

File: ts/Core/Axis/AxisDefaults.ts [hunk 1]
```diff
@@ -1028,6 +1028,7 @@ namespace AxisDefaults {
              * The pixel padding for axis labels, to ensure white space between
              * them. Defaults to 4 for horizontal axes, 1 for vertical.
              *
+             * @type      {number|undefined}
```
Comment (bre1470) [inline ts/Core/Axis/AxisDefaults.ts:1031]: `undefined` is an implicit type because it is an user option, so it can be skipped.

**Review by bre1470 — APPROVED** [review]
LGTM 👍

File: ts/Core/Axis/AxisDefaults.ts (hunk 1 above)
Comment (pawelfus) [reply ts/Core/Axis/AxisDefaults.ts]: Changed. Thanks!

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
