### PR TITLE
bugfix/22961-wrong-axis-label-styles-on-resize

### LINKED ISSUE #22961: Styles on labels are incorrectly placed after chart resizes
#### Expected behavior
Labels styles should return to the state where they were before chart resizing.

#### Actual behavior
After downsizing the chart under 900px width, and resizing it again, styles like

`
  display: -webkit-box;
  -webkit-line-clamp: 1;
  -webkit-box-orient: vertical;
`

aren't removed/changed to appropriate values.
It only occurs when the labels styles whiteSpace: 'nowrap' style is set up.

#### Live demo with steps to reproduce
[https://jsfiddle.net/BlackLabel/vok3sft7/](https://jsfiddle.net/BlackLabel/vok3sft7/)

#### Workaround
https://jsfiddle.net/BlackLabel/9yt0hje5/

#### Product version
Highcharts Core v12

### PR DESCRIPTION
**Pull request by AndrzejBuleczka**
Fixed #22961, axis labels with line-clamp did not correctly reset after chart resize

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1210056616799395

### CODE REVIEW

File: ts/Core/Renderer/HTML/HTMLElement.ts [hunk 1]
```diff
@@ -316,7 +316,34 @@ class HTMLElement extends SVGElement {
...
         }
-        if (styles?.lineClamp) {
+
+        // Clean up sticky side-effects when lineClamp is explicitly removed
+        // (set to 0) or contradicted by a forced nowrap (#22961)
+        if (
+            (styles && 'lineClamp' in styles && !styles.lineClamp) ||
+            (styles?.whiteSpace === 'nowrap' && this.styles.lineClamp)
+        ) {
+            if (this.element && this.element.style) {
```
Comment (PaulDalek) [inline ts/Core/Renderer/HTML/HTMLElement.ts]: You can correct this `if` statement a little bit, e.g.:
```
const { style } = this.element;
if (this.element?.style) {
  style.removeProperty('-webkit-line-clamp');
  style.removeProperty('-webkit-box-orient');
  // Only clear display if it's currently the injected webkit-box
  if (style.display === '-webkit-box') {
    style.removeProperty('display');
  }
}
```

File: ts/Core/Renderer/HTML/HTMLElement.ts [hunk 2]
```diff
@@ -316,7 +316,34 @@ class HTMLElement extends SVGElement {
...
+                this.element.style.removeProperty('-webkit-line-clamp');
+                this.element.style.removeProperty('-webkit-box-orient');
+                // Only clear display if it's currently the injected webkit-box
+                if (this.element.style.display === '-webkit-box') {
+                    this.element.style.removeProperty('display');
+                }
+            }
+
+            if (this.styles) {
```
Comment (PaulDalek) [inline ts/Core/Renderer/HTML/HTMLElement.ts]: The similar thing can be done here:

```
const thisStyles = this.styles;
if (thisStyles) {
  delete thisStyles.lineClamp;
  if (thisStyles.display === '-webkit-box') {
    delete thisStyles.display;
  }
}
```

**Review by PaulDalek — APPROVED** [review]
Good job, it works well! Only some small suggestions from me.

File: ts/Core/Renderer/HTML/HTMLElement.ts (hunk 1 above)
Comment (AndrzejBuleczka) [reply ts/Core/Renderer/HTML/HTMLElement.ts]: good point :) thanks

File: ts/Core/Renderer/HTML/HTMLElement.ts (hunk 2 above)
Comment (AndrzejBuleczka) [reply ts/Core/Renderer/HTML/HTMLElement.ts]: thanks, agree

**Review by wchmiel — APPROVED** [review]
Looks good ;)

**Review by TorsteinHonsi — COMMENTED** [review]
Thanks! As always I'm looking for cheaper ways of doing things, especially in the core to keep the weight of `highcharts.js` down.

Instead of the changes in `HTMLElement.ts`, it seems like this does the trick. Simply setting `display` to `inline-block` will disable all the line-clamp stuff.

```ts
        if (styles?.lineClamp) {
            styles.display = '-webkit-box';
            styles.WebkitLineClamp = styles.lineClamp;
            styles.WebkitBoxOrient = 'vertical';
            styles.overflow = 'hidden';
        } else if (styles?.lineClamp === 0) {
            styles.display = 'inline-block';
        }
```

All tests pass, except the new strict test for `style.webkitLineClamp`. I don't mind if there are CSS properties left after the reset, if we can remove the line-clamp cheap and simple and the rendered results are correct, it's fine. In that regard, we could consider having the test measure the actual bounding box of the elements to check that it is reset, instead of looking at the internal properties. 

Do you see any problems with this? I haven't checked visual diffs.

**Comment by AndrzejBuleczka** [comment]
Hi @TorsteinHonsi, I'm totally ok with your suggestions - I checked them, and it seems to work, also tests are green, no visual diffs :)
