### PR TITLE
Bugfix/12884 week number error

### LINKED ISSUE #12884: Week number error
#### Expected behaviour
The week number for January 2020 should start with Week 1.
Week 1 should start from 30th December 2019 until 5th January 2020

#### Actual behaviour
The week number for January 2020 start with Week 52.
image

#### Live demo with steps to reproduce
https://jsfiddle.net/cvinhar/4cp0fa1q/3/

#### Product version
https://code.highcharts.com/gantt/highcharts-gantt.js

#### Affected browser(s)
Google Chrome

### PR DESCRIPTION
**Pull request by goransle**
Fixed #12884, by changing the calculation of week numbers. It now starts with the first week that includes a Thursday.

### CODE REVIEW

File: ts/parts-gantt/GridAxis.ts [hunk 1]
```diff
@@ -258,18 +258,21 @@ Axis.prototype.getMaxLabelDimensions = function (
...
-    d.setHours(0, 0, 0, 0);
-    d.setDate(d.getDate() - (d.getDay() || 7));
-    yearStart = new Date(d.getFullYear(), 0, 1);
-    weekNo =
-        Math.ceil(((((d as any) - (yearStart as any)) / 86400000) + 1) / 7);
-    return weekNo as any;
+// Adds week date format
+H.dateFormats.W = function (this: Highcharts.Time, timestamp: number): string {
+    const d = new this.Date(timestamp);
+    const firstDay = (d.getDay() + 6) % 7;
```
Comment (TorsteinHonsi) [inline ts/parts-gantt/GridAxis.ts]: Must be `d.get('Day')` to honor the `Time` object's timezone information

File: ts/parts-gantt/GridAxis.ts [hunk 2]
```diff
@@ -258,18 +258,21 @@ Axis.prototype.getMaxLabelDimensions = function (
...
+    const thursday = new this.Date(d.valueOf());
+    (this.set as any)('Date', thursday, (this.get as any)('Date', d) - firstDay + 3);
+
+    const firstThursday = new this.Date((this.get as any)('FullYear', thursday), 0, 1);
+
+    if (firstThursday.getDay() !== 4) {
```
Comment (TorsteinHonsi) [inline ts/parts-gantt/GridAxis.ts]: As above

File: ts/parts-gantt/GridAxis.ts [hunk 3]
```diff
@@ -258,18 +258,21 @@ Axis.prototype.getMaxLabelDimensions = function (
...
+        (this.set as any)('Month', d, 0);
+        (this.set as any)('Date', d, 1 + (11 - firstThursday.getDay()) % 7);
```
Comment (TorsteinHonsi) [inline ts/parts-gantt/GridAxis.ts]: As above

File: ts/parts-gantt/GridAxis.ts [hunk 4]
```diff
@@ -258,18 +258,21 @@ Axis.prototype.getMaxLabelDimensions = function (
...
+    }
+    return 1 + Math.floor((thursday.valueOf() - firstThursday.valueOf() +
+        (this.timezoneOffset || 0)) / 604800000) as any;
```
Comment (TorsteinHonsi) [inline ts/parts-gantt/GridAxis.ts]: I don't think it should be necessary to deal with `timezoneOffset` here...

**Comment by TorsteinHonsi** [comment]
Nice, thanks! Pending tests...
