### PR TITLE
Bugfix/6553-legend-symbol-usehtml

### LINKED ISSUE #6553: Legend symbol click is not hiding series when legend.useHTML is set to true
#### Expected behaviour
Clicking on legend symbol should work the same when legend useHTML is set and when legend is not using HTML.

#### Actual behaviour
Legend symbol click is not hiding series when legend.useHTML is set to true

#### Live demo with steps to reproduce
http://jsfiddle.net/5n948mqe/

#### Affected browser(s)
All

### PR DESCRIPTION
**Pull request by Basts**
Fixed #6553, legend symbol functionality with the `useHTML` setting.

### CODE REVIEW

File: ts/parts/Interaction.ts [hunk 1]
```diff
@@ -456,7 +456,7 @@ extend(Legend.prototype, {
 
         // Set the events on the item group, or in case of useHTML, the item
         // itself (#1249)
-        (useHTML ? legendItem : (item.legendGroup as any))
+        itemToSet
```
Comment (TorsteinHonsi) [inline ts/parts/Interaction.ts]: Instead of changing the function parameters and the way they are called, I think it would be cleaner just to change it here. Something like this:

```js
const elements = useHTML ? [legendItem, item.legendSymbol] : [item.legendGroup];
elements.forEach(element => {
    element.on('mouseover' ......
```
