### PR TITLE
bugfix/14868-gantt-drilldown-labels-postion

### LINKED ISSUE #14868: Incorrect labels position in drilldown when Gantt module is activated
#### Expected behaviour
image

#### Actual behaviour
image

Data labels are initially rendered correctly. **After entering a deeper level of dropdown, data labels are in the incorrect position.** The effect stays even after returning back to the root level.

#### Live demo with steps to reproduce
https://codesandbox.io/s/highcharts-react-demo-forked-tcltb?file=/demo.jsx

1. Uncomment line no. `15` from `demo.jsx` to turn on the Gantt module.
2. Save & refresh the demo project
3. Click on the label of given month to go deeper into the drilldown.
4. **Check how new labels are positioned. (x axis)**
5. Click on the button to go back to root level
6. **Check how the position of labels changed. (x axis)**

#### Product version
Highcharts v8.2.2

#### Affected browser(s)
- Chrome v89.0
- Safari v14.0
- Firefox v84.0

### PR DESCRIPTION
**Pull request by karolkolodziej**
Fixed #14868, axis labels were positioned incorrectly in non-Gantt charts when the Gantt package was imported.

### CODE REVIEW

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Nice, thanks! I've been wondering why the labels were sometimes slightly off center.

Change requests:
* Is there a specific reason for checking `userOptions.grid.enabled` rather than the usual `options`? Unless looking for things that are set explicitly, we should use the processed `options`.
* Can you also go over the 192 differing visual samples and verify them? Most or all seem to correctly adjust the axis label back to center. But we must also make sure there is not a real regression hiding in between the valid diffs.

**Comment by karolkolodziej** [comment]
You are right, there is no need to use the `userOptions` the `options` works fine in this case. 
I went through all visual differences and each one looked as correct adjustment of label positioning.

File: ts/Core/Axis/GridAxis.ts [hunk 1]
```diff
@@ -910,38 +910,41 @@ class GridAxis {
...
         const userLabels = axis.userOptions.labels || {};
 
-        if (axis.horiz) {
-            if (gridOptions.enabled === true) {
-                axis.series.forEach(function (series): void {
-                    series.options.pointRange = 0;
-                });
-            }
+        // Fire this only for the Gantt type chart, #14868.
+        if (axis.options.grid && axis.options.grid.enabled) {
```
Comment (TorsteinHonsi) [inline ts/Core/Axis/GridAxis.ts:914]: On line 910, we already have `gridOptions = options.grid || {}`. That means line 914 can probably be optimized to `if (gridOptions.enabled) {`

File: ts/Core/Axis/GridAxis.ts [hunk 2]
```diff
@@ -910,38 +910,41 @@ class GridAxis {
...
+            if (axis.horiz) {
+                if (gridOptions.enabled === true) {
```
Comment (TorsteinHonsi) [inline ts/Core/Axis/GridAxis.ts:916]: Now since we're already checking for `gridOptions.enabled` on line 914, we should be able to safely remove the check on line 916.

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks! There seems to be room for some more micro-optimization.

**Review by TorsteinHonsi — APPROVED** [review]
