### PR TITLE
bugfix/1172-column-navigator

### LINKED ISSUE #1172: Column type navigator
Example: http://jsfiddle.net/KeGjx/4/

When using columns in navigator, they will be drawn outside navigator.  Should be cut  or takes less space, I think.

### LINKED ISSUE #3136: cropThreshold doesn't work
Example: http://jsfiddle.net/n6EhL/3/

Try to zoom-in by dragging one of navigator's handles. First column is missing even when we set `cropThreshold`.

Maybe be connected to #2437.

Workaround is to set `cropShoulder` directly in series prototype.

### PR DESCRIPTION
**Pull request by pawelfus**
Fixed #1172, handles positions and `xAxis` extremes were incorrect when using column type series in navigator.
___
Note: This does not fix #3136 - it would be nice to have an official API option to change `cropShoulder`. Otherwise most left/right columns are hidden even when xAxis labels (due to extra space created by columns) are rendered. 

Fixed demos from #1171:

- http://jsfiddle.net/BlackLabel/6rzqoasu/1/
- http://jsfiddle.net/BlackLabel/Lmhqngu5/
- http://jsfiddle.net/BlackLabel/yncevr5j/1/

### CODE REVIEW

**Comment by pawelfus** [comment]
That's interesting. This (new) demo should have small diff: http://utils.highcharts.local/samples/#test/stock/navigator/column

> Left version: 7.2.0; right version: 7.2.0-modified
The generated SVG is different, checking exported images...
The exported images are different (dissimilarity index: 0.02)

File: ts/parts/Navigator.ts [hunk 1]
```diff
@@ -505,6 +505,15 @@ extend(defaultOptions, {
              * The type of the navigator series. Defaults to `areaspline` if
              * defined, otherwise `line`.
              *
+             * Heads up:
```
Comment (TorsteinHonsi) [inline ts/parts/Navigator.ts]: Could we handle this with smarter default options so that we don't need to do manual warnings?

File: ts/parts/Navigator.ts [hunk 2]
```diff
@@ -505,6 +505,15 @@ extend(defaultOptions, {
...
+             * When using `column` type navigator, don't forget to change
+             * [pointRange](#navigator.series.pointRange) to `null`.
+             * In column-type navigator, zooming is limited to at least one
+             * point with it's `pointRange`.
```
Comment (TorsteinHonsi) [inline ts/parts/Navigator.ts]: Typo: ... with its `pointRange`.

File: ts/parts/Navigator.ts (hunk 1 above)
Comment (pawelfus) [reply ts/parts/Navigator.ts]: Sure, not a problem

**Comment by pawelfus** [comment]
Default `pointRange` was a bit more tricky than expected - `type` can be defined in multiple ways (default `defaultSeriesType`, `navigator.series.type` and `series.navigatorOptions.type`), so first type is resolved, then related `pointRange` is picked up.

File: ts/parts/Navigator.ts [hunk 3]
```diff
@@ -2234,6 +2283,17 @@ Navigator.prototype = {
                     baseNavigatorOptions
                 );
 
+                // Once nav series type is resolved, pick correct pointRange
+                mergedNavSeriesOptions.pointRange = pick(
+                    // Stricte set pointRange in options
+                    userNavOptions.pointRange,
+                    baseNavigatorOptions.pointRange,
+                    // Fallback to default values, e.g. `null` for column
+                    (defaultOptions.plotOptions as any)[
```
Comment (pawelfus) [inline ts/parts/Navigator.ts]: @bre1470 - I know I introduce here new `as any`, but the same happens in other files where we need to reference `defaultOptions.plotOptions`. I assume this will be picked altogether with other changes?

Comment (bre1470) [reply ts/parts/Navigator.ts]: I believe this should not be necessary inside the pick function anymore. @jon-a-nygaard made it type safe.

Comment (bre1470) [reply ts/parts/Navigator.ts]: Oh I see now, that it is used with an indexer. `any` is okay in this case.

Comment (pawelfus) [reply ts/parts/Navigator.ts]: Ok, thanks! Sorry, should have highlight more lines to make it more readable..
