### PR TITLE
bugfix/19457-multiple-dataLabels-enabled/disabled-threw-render-error

### LINKED ISSUE #19457: Error when first dataLabel is disabled and second dataLabel is enabled
#### Expected behaviour
The second dataLabel from config should work fine or at least no error in the console occurs (chart should be rendered correctly).

#### Actual behaviour
When disabling the first dataLabel and trying to enable the second one, the error in the console occurs and the chart isn't rendering.

Also, in Highcharts it is possible to define multiple dataLabels (especially in multiple values series like columnrange), but the API suggests that only an object is valid (it is possible to define multiple dataLabels in an array).

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/sz2e7q40/

#### Product version
Current is 11.1.0

Internal notes:
It looks simple at first glance thus tagging as good for beginners, but it needs to be debugged and investigated first.

### PR DESCRIPTION
**Pull request by KamilKubik**
Fixed #19457, multiple `dataLabels` enabled/disabled threw render (console) error.

### CODE REVIEW

File: samples/unit-tests/series/datalabels/demo.js [hunk 1]
```diff
@@ -381,6 +386,19 @@ QUnit.test('Datalabels overlap in hidden series (#3866)', function (assert) {
...
+        'No console error should be displayed (#19457).'
+    );
+
+    assert.strictEqual(
+        chart.options.plotOptions.series.dataLabels.filter(({ enabled }) =>
+            enabled
+        ).length,
+        chart.series[0].points[0].dataLabels.length,
+        'Only the second point\'s data label should be rendered (#19457).'
+    );
```
Comment (hubertkozik) [inline samples/unit-tests/series/datalabels/demo.js:401]: It would be better to move these tests to test, which is responsible for multiple data labels: `unit-tests/datalabels/multiple-labels`. There are already declared data labels as an array, so one update there should be fine.

**Review by hubertkozik — CHANGES_REQUESTED** [review]
One thing about tests is below.

File: samples/unit-tests/series/datalabels/demo.js (hunk 1 above)
Comment (KamilKubik) [reply samples/unit-tests/series/datalabels/demo.js]: Agree, it's cleaner now as there's no need to add any extra chart config, thanks!

**Review by hubertkozik — APPROVED** [review]

File: ts/Core/Series/DataLabel.ts [hunk 2]
```diff
@@ -814,10 +814,10 @@ namespace DataLabel {
                 // Destroy and remove the inactive ones
                 let j = dataLabels.length;
                 while (j--) {
-                    if (dataLabels[j].isActive) {
+                    if (dataLabels[j]?.isActive) {
```
Comment (TorsteinHonsi) [inline ts/Core/Series/DataLabel.ts:817]: According to TypeScript, `dataLabels` is `(SVGElement | SVGLabel)[]`. So somewhere the typing have failed us by allowing an undefined value in the array. Can we dig a bit deeper and find out why/where that happens? It may prevent future issues from the same cause.

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]

File: ts/Core/Series/DataLabel.ts (hunk 2 above)
Comment (KamilKubik) [reply ts/Core/Series/DataLabel.ts:817]: The problem here is that we map through the [pointOptions](https://github.com/highcharts/highcharts/blob/dcf0ac67b30ed690429aac019c5eceb3a1139aaf/ts/Core/Series/DataLabel.ts#L561). Then, we assign the `dataLabels` to an array by the mapping index, but only when the `dataLabel` is enabled. In effect, when e.g. the first `dataLabel` isn't enabled, and the second one is, we have an empty element inside the array, so the `dataLabels[j].isActive` breaks. On the other hand, as you mentioned, we assume that all elements are defined. 

What's more, I think we need to be aware of two cases, new labels, and the existing ones we want to update. Therefore, we should use the mapping indices we have now to properly add or update `dataLabels`, and create elements even if they aren't enabled. I think we need these only in the scope of mapping, and this [check](https://github.com/highcharts/highcharts/blob/dcf0ac67b30ed690429aac019c5eceb3a1139aaf/ts/Core/Series/DataLabel.ts#L815) can base on formatted (enabled only) `dataLabels`.

Comment (TorsteinHonsi) [reply ts/Core/Series/DataLabel.ts:817]: What if we have only one `dataLabel` setting, and that has `enabled: false`? In that case we don't create an element, right? And for a good reason - turning off the data labels will increase performance. So we need to consider allowing these undefined places in the `dataLabels` array. Like it currently works, just with correct typing?

Comment (TorsteinHonsi) [reply ts/Core/Series/DataLabel.ts:818]: Yes, I absolutely agree to this. So we allow `undefined` only in the local scope.

Now related to your latest commit, I think the `// Write back` block can be simplified. Setting `point.dataLabel` to `point.dataLabels[0]` should be save because it is either undefined or an element. For `point.dataLabels` we should be able to do something like this:

`point.dataLabels = dataLabels.filter(defined)`

Or alternatively do the handling further up, so that `dataLabels` is either undefined or filtered.

Comment (KamilKubik) [reply ts/Core/Series/DataLabel.ts:818]: Yes, I think everything is properly typed now. Thanks for the refactoring suggestion, I pushed the changes.

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks again! 

I did some simplification of the code - we already had this case where we spliced out inactive data labels from the array, so I am trying to combine that with the undefined ones.

I think there's a remaining problem though - when experimenting with the code, it seems that your changes to the unit test doesn't actually catch the issue. I had to go back to the OP demo to see if my changes were working. Can you take a look at that? It looks like the unit test doesn't actually have a disabled data label followed by an enabled one.

**Review by TorsteinHonsi — APPROVED** [review]
All right, thanks!
