### PR TITLE
Fixed setting pie plot options with multiple data labels renders incorrectly

### LINKED ISSUE #21928: Setting plot options for pie-chart with multiple data labels does not work
#### Expected behaviour

Setting plot options for pie-chart with multiple data labels should show pie chart.

Using `series` plot options works as expected, but not `pie`.

#### Actual behaviour

Pie chart is not rendered, or rendered incorrectly.

#### Live demo with steps to reproduce
https://jsfiddle.net/soh9583u/1/

The demo is taken from this Highcharts demo https://www.highcharts.com/demo/highcharts/pie-chart
where if `series` is changed to `pie` in `plotOptions`, the following error is thrown:
Screenshot 2024-09-30 at 12 26 25

#### Product version
Highcharts Core v11.2.0

Highcharts Core v11.1.0 does not support multiple data labels, so the chart is displayed without any data labels, but at least the chart is rendered. This could suggest that this bug occurred when multiple data labels were implemented for pie charts in v11.2.0.

#### Affected browser(s)
N/A

### PR DESCRIPTION
**Pull request by Eskils**
Fixed #21928, setting plot options for pie chart with multiple data labels did not work.

- Issue was resolved by merging data label options in pie plot options with the defaults. 
   + This was not already happening because the `merge` function does not merge arrays.
- Updated pie demos with multiple data labels to use pie plot options instead of series plot options. 
   + This seems more correct since the demos will not compile in TypeScript.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208435267040163

### CODE REVIEW

File: ts/Core/Chart/Chart.ts [hunk 1]
```diff
@@ -434,6 +436,10 @@ class Chart {
             const options = merge(defaultOptions, userOptions), // Do the merge
                 optionsChart = options.chart;
 
+            if (options.plotOptions.pie) {
+                this.mergePieDataLabelPlotOptions(options.plotOptions.pie);
+            }
```
Comment (goransle) [inline ts/Core/Chart/Chart.ts:441]: This should likely happen in `PieSeries.ts`. This seems to work:

```ts
addEvent(PieSeries, 'afterInit', (e): void => {
    const chart = e.target.chart;
    if (chart.options.plotOptions.pie) {
        PieSeries.mergePieDataLabelPlotOptions(chart.options.plotOptions.pie);
    }
});
```

Possibly the `update` or `setOptions` events can be used for processing when changing options.

File: samples/unit-tests/series-pie/datalabel/demo.js [hunk 2]
```diff
@@ -652,3 +652,92 @@ QUnit.test('Connector color of individual point (#8864).', function (assert) {
...
+                        },
+                        {
+                            y: 11.84
+                        }
+                    ]
+                }
+            ]
+        });
+
+        assert.ok(
```
Comment (goransle) [inline samples/unit-tests/series-pie/datalabel/demo.js:687]: I would slightly prefer `assert.strictEqual` for test failure reporting

**Review by goransle — CHANGES_REQUESTED** [review]

**Comment by Eskils** [comment]
Thank you for your feedback! The `setOptions` event was what I needed.

**Review by goransle — APPROVED** [review]
Nice, looks good!

**Comment by hubertkozik** [comment]
I think this problem is deeper than only for `PieSeries`. I tried to use the same config for the line series: https://jsfiddle.net/BlackLabel/a8grfdvc/ and sadly the error came up. That would mean, that your fix is not enough and we should fix it somewhere deeper in the code 😕

**Review by hubertkozik — CHANGES_REQUESTED** [review]
I think this problem is deeper than only for `PieSeries`. I tried to use the same config for the line series: https://jsfiddle.net/BlackLabel/a8grfdvc/ and sadly the error came up. That would mean, that your fix is not enough and we should fix it somewhere deeper in the code 😕

**Comment by Eskils** [comment]
> I think this problem is deeper than only for `PieSeries`. I tried to use the same config for the line series: https://jsfiddle.net/BlackLabel/a8grfdvc/ and sadly the error came up. That would mean, that your fix is not enough and we should fix it somewhere deeper in the code 😕

Thank you for testing more broadly—good find! I added a unit-test for line-series and moved my patch to Series.ts.

File: samples/unit-tests/series-line/datalabel/demo.js
Comment (hubertkozik) [inline samples/unit-tests/series-line/datalabel/demo.js:1]: Do we need this new file and this QUnit test instance? Those instances are quite heavy, it is better and we are trying to add some code to the existing test because updates are lighter than creating new tests and new chart instances. Can you put it somewhere in existing test?

File: ts/Core/Series/Series.ts [hunk 3]
```diff
@@ -816,6 +816,19 @@ class Series {
             ),
             userPlotOptionsType = userPlotOptions[this.type] || {};
 
+        // When plot options have multiple data labels, the default data label
+        // plot options are not merged (#21928).
+        const dataLabelOptions = typeOptions.dataLabels;
+        if (dataLabelOptions instanceof Array) {
```
Comment (hubertkozik) [inline ts/Core/Series/Series.ts:822]: I'm thinking about using `splat` function to simplify logic a little bit. Did you consider using `splat` and operating always on the array?

**Review by hubertkozik — COMMENTED** [review]
Sorry for the long wait for review! The notification got lost somehow :(

File: samples/unit-tests/series-line/datalabel/demo.js
Comment (Eskils) [reply samples/unit-tests/series-line/datalabel/demo.js:1]: Good point. I integrated the _series-line/datalabel_ test in the existing _series-line/linewidth_ test. This greatly reduced the test run duration.

The new tests in _series-pie/datalabel_ are already quite swift, and integrating them into existing tests had little to no effect so they are left unchanged (See attached image).

Screenshot 2024-11-11 at 17 37 10

File: ts/Core/Series/Series.ts (hunk 3 above)
Comment (hubertkozik) [reply ts/Core/Series/Series.ts:822]: Right, got it!

File: samples/unit-tests/series-line/datalabel/demo.js
Comment (hubertkozik) [reply samples/unit-tests/series-line/datalabel/demo.js:1]: Nice! Thank you.

File: ts/Core/Series/Series.ts [hunk 4]
```diff
@@ -816,6 +816,19 @@ class Series {
             ),
             userPlotOptionsType = userPlotOptions[this.type] || {};
 
+        // When plot options have multiple data labels, the default data label
+        // plot options are not merged (#21928).
```
Comment (TorsteinHonsi) [inline ts/Core/Series/Series.ts:820]: This comment describes a situation that is no longer true. Instead, describe what the code actually does, and add a reference to the issue.
```suggestion
        // Merge in multiple data label options from the plot option (#21928).
```

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks!

Since we already have logic for this array-merging somewhere else, I think we should refactor to avoid repeating ourselves. There's two reasons for that - both lower code weight, and maintenance benefits if there are bugs in either place.

So I tried this approach that passes the tests:
```diff
diff --git a/ts/Core/Series/DataLabel.ts b/ts/Core/Series/DataLabel.ts
index ffef2466ff..653f40af27 100644
--- a/ts/Core/Series/DataLabel.ts
+++ b/ts/Core/Series/DataLabel.ts
@@ -110,6 +110,10 @@ declare module './SeriesLike' {
             alignTo?: BBoxObject,
             isNew?: boolean
         ): (boolean|undefined);
+        mergeArrays(
+            one: (DataLabelOptions|Array<DataLabelOptions>|undefined),
+            two: (DataLabelOptions|Array<DataLabelOptions>|undefined)
+        ) : (DataLabelOptions|Array<DataLabelOptions>);
         placeDataLabels?(): void;
         setDataLabelStartPos(
             point: ColumnPoint,
@@ -482,6 +486,7 @@ namespace DataLabel {
             seriesProto.alignDataLabel = alignDataLabel;
             seriesProto.drawDataLabels = drawDataLabels;
             seriesProto.justifyDataLabel = justifyDataLabel;
+            seriesProto.mergeArrays = mergeArrays;
             seriesProto.setDataLabelStartPos = setDataLabelStartPos;
             seriesProto.hasDataLabels = hasDataLabels;
         }
diff --git a/ts/Core/Series/Series.ts b/ts/Core/Series/Series.ts
index a63eb55eb2..955c07c6a2 100644
--- a/ts/Core/Series/Series.ts
+++ b/ts/Core/Series/Series.ts
@@ -818,16 +818,10 @@ class Series {
 
         // When plot options have multiple data labels, the default data label
         // plot options are not merged (#21928).
-        const dataLabelOptions = typeOptions.dataLabels;
-        if (dataLabelOptions instanceof Array) {
-            const dataLabelDefaults = defaultPlotOptionsType.dataLabels || {};
-            for (let i = 0; i < dataLabelOptions.length; i++) {
-                dataLabelOptions[i] = merge(
-                    dataLabelDefaults,
-                    dataLabelOptions[i]
-                );
-            }
-        }
+        typeOptions.dataLabels = this.mergeArrays?.(
+            defaultPlotOptionsType.dataLabels,
+            typeOptions.dataLabels
+        );
 
         // Use copy to prevent undetected changes (#9762)
         /**
```

The only thing that doesn't quite sit right here is that `mergeArrays` is a general utility function, but it is attached to the Series prototype for convenience. I think that is okay for now, since it is only used by the data label logic.

**Comment by Eskils** [comment]
Thank you for pointing this out. I’ve changed my code to your approach.

**Review by TorsteinHonsi — APPROVED** [review]
