### PR TITLE
Fixed #14691, FireFox popup reversed.

### LINKED ISSUE #14691: First of the Bolded subtitles in the annotation edit popup is moved to the last place
When clicking the edit button on annotation, the first bolded subtitle is displayed in the wrong place. Should be on top of the list of properties, and is on the bottom. 

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/stock-tools-gui

- Add the rectangle shape annotation to the chart
- Click the edit button
- Notice, that the subtitle (in this case 'shape options') is in the wrong position
Firefox ---->
image

Chrome ----> 
image

For different shape it looks like the first title, that is displayed in the options is moved to the last place: 
Firefox --->
image
Chrome --->
image

#### Product version
Highstock v8.2.2

#### Affected browser(s)
Firefox

### PR DESCRIPTION
**Pull request by DJTechnoo**
Fixed #14691, incorrect order of annotation subtitles in pop-ups in Firefox.

### CODE REVIEW

File: ts/Extensions/Annotations/Popup.ts [hunk 1]
```diff
@@ -686,10 +686,14 @@ H.Popup.prototype = {
             });
 
             if (isRoot) {
-                storage = storage.sort(function (a): number {
-                    return (a as any)[1].match(/format/g) ? -1 : 1;
+                H.stableSort(storage, function (a: any): number {
```
Comment (TorsteinHonsi) [inline ts/Extensions/Annotations/Popup.ts:689]: Instead of referencing `H.stableSort`, get it from the Utilities directly. See for example Legend.ts:
```js
import U from './Utilities.js';
const {
    [...],
    stableSort,
    [...]
} = U;
```

File: ts/Extensions/Annotations/Popup.ts [hunk 2]
```diff
@@ -686,10 +686,14 @@ H.Popup.prototype = {
...
+                    return a[1].match(/format/g) ? -1 : 1;
                 });
 
+                if (H.isFirefox) {
```
Comment (TorsteinHonsi) [inline ts/Extensions/Annotations/Popup.ts:693]: Same here, we're transitioning away from using the namespace, so access `isFirefox` from Utils instead.

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]

File: ts/Extensions/Annotations/Popup.ts (hunk 2 above)
Comment (DJTechnoo) [reply ts/Extensions/Annotations/Popup.ts]: It appears to me that `isFirefox` does not come from Utils yet.🤔

**Review by TorsteinHonsi — APPROVED** [review]
Looking good, just waiting for the tests to pass then it can be merged 👍
