### PR TITLE
bugfix/11148-polar-tracking-outside-plotarea

### LINKED ISSUE #11148: Trackable point outside yAxis extremes (polar)
#### Expected behaviour
No points can be tracked if their value is higher than yAxis.max

#### Actual behaviour
Although the points' y is bigger than yAxis.max, they can be tracked as long as they are within the plot area.

polar

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/goL7b1r6

#### Product version
Highcharts 7.1.2

#### Affected browser(s)
All

### PR DESCRIPTION
**Pull request by raf18seb**
Fixed #11148, a point should not be trackable when is out of his pane. Also, isInsidePlot() works for panes now.

This PR is a continuation of this: https://github.com/highcharts/highcharts/pull/12348
I am not able to build a project and make changes on that branch anymore. The old PR can be closed.

### CODE REVIEW

File: ts/parts/Utilities.ts [hunk 1]
```diff
@@ -3380,6 +3385,16 @@ H.isFunction = function (obj: unknown): obj is Function {
...
+H.isInsidePane = function (
+    x: number,
+    y: number,
+    center: Array<number>
+): boolean {
+    return Math.sqrt(
+        Math.pow(x - center[0], 2) + Math.pow(y - center[1], 2)
+    ) < center[2] / 2;
+};
+
```
Comment (pawelfus) [inline ts/parts/Utilities.ts]: Can we move this function to `Pane.ts` file?

File: ts/parts/Pointer.ts [hunk 2]
```diff
@@ -834,7 +856,7 @@ Highcharts.Pointer.prototype = {
             chart.hoverPoint = hoverPoint;
 
             // Draw tooltip if necessary
-            if (tooltip) {
+            if (tooltip && (!chart.polar || hoverPoint.isInsidePane)) {
```
Comment (pawelfus) [inline ts/parts/Pointer.ts]: Instead of checking `hoverPoint.isInsidePane`, how about `fireEvent(this, 'afterGetHoverData', hoverPoint);` can remove hoverPoint? Something like this:

```js
let e = { hoverPoint };
fireEvent(this, 'afterGetHoverData', e);
hoverPoints = e.hoverPoint;
```

And `hoverPoint` will be undefined when outside the pane.

File: ts/parts/Utilities.ts (hunk 1 above)
Comment (raf18seb) [reply ts/parts/Utilities.ts]: Yes. Should I leave this function hanging in the pane module's scope? Also, I would have to move 2 events from `Polar.ts` to `Pane.ts` that use this function. What do you think about moving all the new code (all 3 events) from `Polar.ts` to `Pane.ts`?

Comment (pawelfus) [reply ts/parts/Utilities.ts]: Do you mean `beforeGetHoverData` and `afterGetHoverData`? I'm fine with that.

**Comment by TorsteinHonsi** [comment]
OK from me, awaiting @pawelfus 's approval 👍

**Comment by raf18seb** [comment]
@pawelfus, changes made.
