### PR TITLE
bugfix/15593-stocktools-overflow

### LINKED ISSUE #15593: StockTools GUI doesn't render correctly in a wrapper with multiple charts
#### Expected behaviour
Inside wrappers add StockTools GUI the same as in the JS (same height as the chart with additional pagination).

#### Actual behaviour
Inside wrappers, StockTools GUI pagination is missing and it occupies too much space, which results in overlaping.

#### Live demo with steps to reproduce
Correct JS: https://jsfiddle.net/BlackLabel/g40s5vzo/
Angular: https://stackblitz.com/edit/highcharts-angular-stock-gui-5byr8x
Vue: https://codesandbox.io/s/highcharts-stockgui-tools-see-whats-happen-with-large-toolbar-20pbm
React: https://codesandbox.io/s/stocktools-gui-hrmbi

#### Product version
Highstock JS v9.0.1 (2021-02-15)

#### Affected browser(s)
All

### PR DESCRIPTION
**Pull request by khlieng**
Fixed #15593, Stock Tools overflowed the chart container when the class `chart` was not set on the container.

### CODE REVIEW

File: ts/Stock/StockToolsGui.ts [hunk 1]
```diff
@@ -1411,12 +1411,15 @@ class Toolbar {
             toolbar,
             wrapper;
 
+        // #15593
+        css(container.parentNode, { position: 'relative' });
```
Comment (pawelfus) [inline ts/Stock/StockToolsGui.ts:1415]: Usually, when we set hardcoded styles, there is a case where users come back and say they need to change it. I think it would make sense to add `stockTools.gui.style` option with this predefined  `{ position }` config

**Review by pawelfus — CHANGES_REQUESTED** [review]
Added Sebastian to confirm I'm not missing anything.

I really appreciate the changes in TS 👍

File: ts/Stock/StockToolsGui.ts (hunk 1 above)
Comment (khlieng) [reply ts/Stock/StockToolsGui.ts:1415]: Calling it just `style` makes it sound like it gets applied to the stocktools and not `renderTo`, should it perhaps be called something like `renderToStyle`?

Comment (pawelfus) [reply ts/Stock/StockToolsGui.ts:1415]: Oh, I thought you added this style to the toolbar container, not the chart's container. I'm not sure if can we do this in [`chart.style`](https://api.highcharts.com/highcharts/chart.style)? So the module would just set this config. I don't know how would we inform users that the Stock Tools module adds this style. Perhaps @TorsteinHonsi has some ideas here

Comment (TorsteinHonsi) [reply ts/Stock/StockToolsGui.ts:1415]: It's dangerous to fiddle too much with the `renderTo`, as it's the implementer's element. Is there a reason why we are not using the `container` itself? It already has `position: relative`.

File: ts/Stock/StockToolsGui.ts [hunk 2]
```diff
@@ -1473,9 +1476,9 @@ class Toolbar {
         // Show hide toolbar
         this.showhideBtn = showhideBtn = createElement(DIV, {
             className: PREFIX + 'toggle-toolbar ' + PREFIX + 'arrow-left'
-        }, null as any, wrapper);
+        }, void 0, wrapper);
```
Comment (sebastianbochan) [inline ts/Stock/StockToolsGui.ts:1479]: Im pretty curios why we use `void 0` instead of an empty object `{}` ?

File: samples/unit-tests/indicator-price-indicator/recalculations/demo.js [hunk 3]
```diff
@@ -185,6 +185,10 @@ function (assert) {
         controller = new TestController(chart),
         button = chart.stockTools.listWrapper.childNodes[0].childNodes[0];
 
+    document.getElementsByClassName(
```
Comment (pawelfus) [inline samples/unit-tests/indicator-price-indicator/recalculations/demo.js:188]: In tests, it's better to use `chart.container.getElementsByClassName()` instead of `document.getElementsByClassName()`, because we have templates available in karma (which are separate charts). Alternatively, you can use `chart.stockTools.wrapper` which should be a reference directly to this DOM element.

**Review by pawelfus — CHANGES_REQUESTED** [review]
It seems this PR breaks exporting: https://jsfiddle.net/BlackLabel/g40s5vzo/2/ - try to download the first and the second chart. The second one works fine. I'm sorry, I don't know why 😓  Because extra HTML is available in the internal container?

**Review by pawelfus — APPROVED** [review]
Looks good, thanks! 👍 
I have one question though:
> // Mimic event behaviour of being outside chart.container

What kind of behaviour is being mimicked? Is it somehow related to the tooltip? Perhaps we can reuse `no-tooltip` class instead?

**Comment by khlieng** [comment]
Yes, but its also about preventing clicks on a submenu from hitting the chart, to not start drawing an annotation when you click the button. We could probably replace some of it with `no-tooltip` when that gets merged.

File: ts/Stock/StockToolsGui.ts (hunk 2 above)
Comment (TorsteinHonsi) [reply ts/Stock/StockToolsGui.ts:1489]: When we don't have any styles to add, it is more effective to add undefined than to create an empty object, which internally in `createElement` will be truthy and passed over to `css`, where again it will be truthy and inspected for keys etc.

**Review by TorsteinHonsi — APPROVED** [review]
Looks good!
