### PR TITLE
Fixed #17907, stuck data label on ortho map

### LINKED ISSUE #17907: Data labels on Orthographic map not hidden
#### Expected behaviour
Data labels to hide when dragged behind horizon

#### Actual behaviour
They stick

#### Live demo with steps to reproduce
[](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/demo/topojson-projection/)

#### Product version
v10.1.0

A regression since https://github.com/highcharts/highcharts/commit/d2a3cc31a05d6a9c69bf0b2852f70b65dd57dfba

### PR DESCRIPTION
**Pull request by TorsteinHonsi**
Fixed #17907, a regression causing data labels on the far side on an orthographic world projection to stick.

### CODE REVIEW

File: ts/Core/Renderer/BBoxObject.d.ts [hunk 1]
```diff
@@ -24,13 +24,22 @@ import type SizeObject from './SizeObject';
...
 
+/* *
+ *
+ *  Declatations
+ *
+ * */
+
+export interface BBoxObjectWithCenter extends BBoxObject {
+    centerX?: number;
+}
```
Comment (pawellysy) [inline ts/Core/Renderer/BBoxObject.d.ts:41]: since this option is only used by x-range series, maybe the better approach would be moving this piece of code to the x-range module, as well as the assignment of `plotX` in the `DataLabel.ts`?

**Review by pawellysy — COMMENTED** [review]
Looks good to me, just 2 small questions :)

File: ts/Core/Series/DataLabel.ts [hunk 2]
```diff
@@ -236,6 +236,7 @@ namespace DataLabel {
             visible =
                 this.visible &&
                 point.visible !== false &&
+                defined(plotX) &&
```
[the remark this answers is not in the document]
Comment (TorsteinHonsi) [reply ts/Core/Series/DataLabel.ts:239]: It's not strictly necessary for that calculation, and we do check it further down as far as I can see.

File: ts/Core/Renderer/BBoxObject.d.ts (hunk 1 above)
Comment (TorsteinHonsi) [reply ts/Core/Renderer/BBoxObject.d.ts:41]: Yes, that was exactly my thought too! I tried it this morning, but modifying `point.plotX` in X-range made one of the other unit tests to fail. So I gave up for now. But feel free to see if you can resolve this eye-sore.
