### PR TITLE
Fixed #17578, showTable issues with keyboard nav.

### LINKED ISSUE #17578: Keybord navigation with scroll
#### Actual behaviour
- After selecting an item in the legend the keyboard navigation (tab/shift tab) breaks and scrolls to the top of the page.
- Selecting an item in the legend re-enables the data table after hiding.

#### Live demo with steps to reproduce
https://jsfiddle.net/FFSteve/k9z8q7go/18/

#### Product version
 Highcharts JS v10.2.0 (2022-07-05)

#### Affected browser(s)
All

### PR DESCRIPTION
**Pull request by oysteinmoseng**

### CODE REVIEW

File: ts/Extensions/ExportData/ExportData.ts [hunk 1]
```diff
@@ -1016,14 +1017,22 @@ function chartToggleDataTable(
...
 
         // Generate the data table
         if (show) {
             this.dataTableDiv.innerHTML = AST.emptyHTML;
             const ast = new AST([this.getTableAST()]);
             ast.addToDOM(this.dataTableDiv);
+
+            if (createContainer || oldDisplay !== style.display) {
+                // Was hidden, is shown
+                fireEvent(this, 'afterDataTableShown', this.dataTableDiv);
```
Comment (TorsteinHonsi) [inline ts/Extensions/ExportData/ExportData.ts:1033]: Instead of adding another event that triggers immediately before the `afterViewData` event, maybe we can just extend the functionality of the original one? If we pass a parameter like `e.wasHidden` or similar, we can just check for that in the a11y handler.

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks!

File: ts/Extensions/ExportData/ExportData.ts (hunk 1 above)
Comment (oysteinmoseng) [reply ts/Extensions/ExportData/ExportData.ts:1033]: That's way smarter!
