### PR TITLE
bugfix/20525-boost-markers-toggling-on-series-hide

### LINKED ISSUE #20525: Makers still visible after hide series using boost
#### Expected behavior
In a line chart with boost enabled, when we hide a series by clicking on its legend item, both the line and its markers should be hidden.

#### Actual behavior
Only the line is hidden; the markers remain visible.

#### Live demo with steps to reproduce
- Render a line with two series and boost enabled
- Zoom to a small part of the chart
- Click on a legend item to hide a series
- Live demo: https://jsfiddle.net/thyagorafaell/069Lx8vz/17/

zoom-marker-boost

#### Product version
11.3.0

#### Affected browser(s)
All

### PR DESCRIPTION
**Pull request by MarkusBarstad**
Fixed #20525, in boosted charts, markers were not being hidden when zoomed in series was hidden.

### CODE REVIEW

File: ts/Extensions/Boost/BoostSeries.ts [hunk 1]
```diff
@@ -690,6 +690,24 @@ function exitBoost(
     series: Series
 ): void {
     const boost = series.boost;
+    const chart = series.chart;
```
Comment (hubertkozik) [inline ts/Extensions/Boost/BoostSeries.ts:693]: We're trying to declare variables after commas, can you change it?

File: ts/Extensions/Boost/BoostSeries.ts [hunk 2]
```diff
@@ -690,6 +690,24 @@ function exitBoost(
...
+    const chartBoost = chart.boost;
```
Comment (hubertkozik) [inline ts/Extensions/Boost/BoostSeries.ts:694]: Also, do we need to set `chart.boost` object as a new variable? New variable is always some extra bytes and in that case I think we can just use `chart.boost`.

File: samples/unit-tests/boost/enter-exit/demo.js
Comment (hubertkozik) [inline samples/unit-tests/boost/enter-exit/demo.js:1]: The test is passing even on the master branch, without your changes.

**Review by hubertkozik — CHANGES_REQUESTED** [review]

File: samples/unit-tests/boost/enter-exit/demo.js
Comment (MarkusBarstad) [reply samples/unit-tests/boost/enter-exit/demo.js:1]: Ah seems that `markerGroups` were acting strangely in that test :S Ive moved it to visibility where they act more normal (and I also test for their visibility there as well which was partly the original issue)

File: ts/Extensions/Boost/BoostSeries.ts (hunk 2 above)
Comment (MarkusBarstad) [reply ts/Extensions/Boost/BoostSeries.ts]: Thing is that we call the variable 3 times in a row so to me it makes sense from a performance perspective to store the reference to `chart.boost` 🤔 

I'm totally open to changing it but when is it appropriate to make/not make a new variable, @TorsteinHonsi ?

Comment (TorsteinHonsi) [reply ts/Extensions/Boost/BoostSeries.ts]: I'm fine with the way it is. We save some bytes downstream when using a local variable. Regarding performance I think it is negligible in this case, since it's not a part of the code that runs thousands of times.

**Review by hubertkozik — APPROVED** [review]
Perfect!

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
