### PR TITLE
bugfix/14426-vertical-pan-zoom

### LINKED ISSUE #14426: Vertical panning after zooming
#### Expected behaviour
Pan on the vertical axis after zoom to `0`.

#### Actual behaviour
After zooming, new min equal the minimal data is set on the y-axis.
Unable to pan on the vertical axis below the `1.2`.

#### Live demo with steps to reproduce
Zoom in, then try to pan below `1.2` on the y-axis.
https://jsfiddle.net/BlackLabel/v27u1tks/

#### Product version
Highcharts JS v8.2.2 (Vertical panning available from 8.1.0)

#### Affected browser(s)
All

### PR DESCRIPTION
**Pull request by khlieng**
Fixed #14426, it was not possible to pan vertically to 0 after zooming.

### CODE REVIEW

File: samples/unit-tests/interaction/panning/demo.js [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+
+    const offset = Highcharts.offset(chart.container);
+
+    // Zoom
+    chart.pointer.onContainerMouseDown({
+        type: 'mousedown',
+        pageX: 250 + offset.left,
+        pageY: 50 + offset.top,
+        target: chart.container
+    });
```
Comment (pawelfus) [inline samples/unit-tests/interaction/panning/demo.js:37]: FYI: Instead of playing with `offset` you can use `TestController` :)

Comment (khlieng) [reply samples/unit-tests/interaction/panning/demo.js:37]: I got "inspired" by the other panning tests :)

File: ts/Core/Interaction.ts [hunk 2]
```diff
@@ -853,7 +853,9 @@ extend(Chart.prototype, /** @lends Chart.prototype */ {
                             isNumber(dataExtremes.dataMax)
                         ) {
                             panningState.startMin = Math.min(
-                                dataExtremes.dataMin, panningState.startMin
+                                pick(series.options.threshold, Infinity),
```
Comment (TorsteinHonsi) [inline ts/Core/Interaction.ts:856]: The handling of `startMin` and `startMax` was previously equivalent, but now `startMin` also takes the `threshold` into account. Gut feeling says they should still be equivalent, and the fail case is when all values are negative, so that the `threshold` is the max value. Try to zoom in, then we should expect to be able to pan up to 0: https://jsfiddle.net/highcharts/zupgLn59/

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]

File: ts/Core/Interaction.ts [hunk 3]
```diff
@@ -853,10 +853,14 @@ extend(Chart.prototype, /** @lends Chart.prototype */ {
...
+                                dataExtremes.dataMin,
+                                panningState.startMin
                             );
                             panningState.startMax = Math.max(
-                                dataExtremes.dataMax, panningState.startMax
+                                pick(series.options.threshold, Infinity),
```
Comment (TorsteinHonsi) [inline ts/Core/Interaction.ts:861]: This means that when `series.options.threshold` is `null` or undefined, `startMax` becomes `Infinity`. And the consequence can be see here: https://jsfiddle.net/highcharts/zupgLn59/1/

I think it should be `pick(series.options.threshold, -Infinity)`

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
