### PR TITLE
bugfix/15512-rangeSelector-dataGrouping-dynamic-series

### LINKED ISSUE #15512: dataGrouping doesn't apply to indicator added via stockTools
#### Expected behaviour
New Indicator has the same dataGrouping enabled as the main series.

#### Actual behaviour
The dataGrouping, that is defined in rangeSelector buttons isn't applied to the new indicator added via stockTools.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/5u2hty3L/

Add ema indicator via stockTools.

#### Product version
v9.0.1

#### Affected browser(s)
all

### PR DESCRIPTION
**Pull request by khlieng**
Fixed #15512, dynamically added series did not use range selector data grouping.

### CODE REVIEW

File: samples/unit-tests/series/datagrouping/demo.js [hunk 1]
```diff
@@ -435,6 +435,12 @@ QUnit.test('Switch from grouped to non-grouped', function (assert) {
         'Monthly columns'
     );
 
+    const dataGrouping = chart.addSeries({}).options.dataGrouping;
+    assert.ok(
+        dataGrouping.forced && dataGrouping.units,
+        '#15512: Datagrouping from range selector should be used'
```
Comment (pawelfus) [inline samples/unit-tests/series/datagrouping/demo.js:441]: Should we rather check if options are exactly the same? Something like `assert.deepEqual(dataGrouping, rangeSelector.buttonOptions[rangeSelector.selected].dataGrouping)`?

**Review by pawelfus — APPROVED** [review]
Looks good, just a minor question

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
