### PR TITLE
bugfix/21650-data-module-axis-update

### LINKED ISSUE #21650: xAxis update
#### Expected behaviour
Switching between types of xAxis should render ticks according to the type of xAxis.

#### Actual behaviour
1. Demo
The switch from categories to linear does not reset categories

2. Demo
The update from datetime to categories does not set categories properly (timestamps still remain and are converted to strings) 

#### Live demo with steps to reproduce
- https://jsfiddle.net/90o5arkp/3/
- https://jsfiddle.net/90o5arkp/4/

#### Product version
11.4.6

#### Affected browser(s)
All

#### Addtional info
It happened in the past https://github.com/highcharts/highcharts/issues/12534

### PR DESCRIPTION
**Pull request by KacperMadej**
Fixed #21650, the data module was not successfully updating the x-axis in some cases.

---------------

TODO:
- [x] verify if TS changes are ok
- [x] fix the bug
- [x] add the changelog description

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208034587004104

### CODE REVIEW

**Review by bre1470 — APPROVED** [review]
Looks good. 👍

File: ts/Extensions/Data.ts [hunk 1]
```diff
@@ -394,47 +400,39 @@ class Data {
      *
      * @function Highcharts.Data#getColumnDistribution
      */
-    public getColumnDistribution(): void {
+    public getColumnDistribution(): asserts this is this & {
+        valueCount: DataValueCountObject
```
Comment (bre1470) [inline ts/Extensions/Data.ts:404]: How about initializing the prop with 0 instead?

File: ts/Extensions/Data.ts [hunk 2]
```diff
@@ -284,7 +284,13 @@ class Data {
...
     public chart: Chart;
     public chartOptions: Partial<Options>;
-    public columns?: Array<Array<DataValueType>>;
+    public columns?: Array<Array<DataValueType> & {
+        isDatetime?: boolean;
+        isNumeric?: boolean;
+        mixed?: boolean;
+        name?: string;
+        unsorted?: boolean;
+    }>;
```
Comment (bre1470) [inline ts/Extensions/Data.ts:293]: Now thinking about this... How about creating an interface `DataColumnsArray extends Array<Array<DataValueType>` then you can skip als these reference hacks, that might confuse some.

**Review by bre1470 — COMMENTED** [review]
See commets.

File: ts/Extensions/Data.ts (hunk 1 above)
Comment (KacperMadej) [reply ts/Extensions/Data.ts:404]: Sadly, this won't help as far as I can see it because `valueCount` is of type:
```ts
interface DataValueCountObject {
    global: number;
    globalPointArrayMap: Array<string>;
    individual: Array<number>;
    seriesBuilders: Array<SeriesBuilder>;
    xColumns: Array<number>;
}
```
and later running function (`complete`) needs it.

Comment (bre1470) [reply ts/Extensions/Data.ts:404]: Okay, what a mess.

**Review by bre1470 — APPROVED** [review]
Thanks! Looks good. 👍

**Review by sebastianbochan — APPROVED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
Thanks! And great job cleaning up typing and code style 👍
