### PR TITLE
bugfix/23666-boost-line-width-multiple-series

### LINKED ISSUE #23666: Line width in boost mode
#### Expected behaviour

As per [v11.4.4](https://www.highcharts.com/changelog/#highcharts-v11.4.4), it is expected that you are able to change to line width for line series in boost mode

#### Actual behaviour

The behavior that I have experienced is that this only works if you are plotting a single series. Once more than one line series is rendered on the chart, the line width goes back to only being 1px. 

#### Live demo with steps to reproduce

Single series, works: https://jsfiddle.net/BlackLabel/Laq9ot0y/
Two series, doesn't work: https://jsfiddle.net/wty3v27p/

#### Product version

Highcharts Core v12.4.0, though I've tried with older version back to v11.4.4 and have experienced the same behavior. 

#### Affected browser(s)
Only tested on
- Firefox 143.0.1 (aarch64)
- Chrome 140.0.7339.133 (Official Build) (arm64)

### PR DESCRIPTION
**Pull request by hubertkozik**
Fixed #23666, line width didn't work for multiple boosted line series.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1211590312398412

### CODE REVIEW

File: ts/Extensions/Boost/BoostSeries.ts [hunk 1]
```diff
@@ -1313,7 +1313,7 @@ function seriesRenderCanvas(this: Series): void {
 
     fireEvent(this, 'renderCanvas');
 
-    if (chartBoost && seriesBoost?.target && lineWidth > 1 && this.is('line')) {
+    if (chartBoost && chart.boost?.target && lineWidth > 1 && this.is('line')) {
```
Comment (MarkusBarstad) [inline ts/Extensions/Boost/BoostSeries.ts]: Maybe chartBoost instead of chart.boost here

File: ts/Extensions/Boost/BoostSeries.ts [hunk 2]
```diff
@@ -1329,7 +1329,7 @@ function seriesRenderCanvas(this: Series): void {
             attributes: { id: 'linewidth' }
         });
 
-        seriesBoost.target.attr({
+        chart.boost.target.attr({
```
Comment (MarkusBarstad) [inline ts/Extensions/Boost/BoostSeries.ts]: and here
