### PR TITLE
bugfix/20572-hcmore-chart-destroy

### LINKED ISSUE #20572: Chart destroy after point hover - Cannot destructure property 'chart' of 'series'
#### Expected behaviour
Works as expected in Highcharts v11.2.0: https://jsfiddle.net/BlackLabel/xnukpa2d/

#### Actual behaviour
Error: `Uncaught TypeError: Cannot destructure property 'chart' of 'series' as it is undefined.`

#### Live demo with steps to reproduce
1. Open jsfiddle: https://jsfiddle.net/BlackLabel/bqcz3nw0/
2. Check the browser console

#### Product version
Highcharts + Highcharts More v11.3.0

#### Affected browser(s)
All

Originally reported on the `highcharts-rect` repository: https://github.com/highcharts/highcharts-react/issues/455

### PR DESCRIPTION
**Pull request by hubertkozik**
Fixed #20572, destroying a chart after point hover produced an error.

### CODE REVIEW

File: ts/Series/PolarComposition.ts [hunk 1]
```diff
@@ -1422,17 +1422,24 @@ function wrapPointPos(
...
-        ];
-    }
+    if (!this.destroyed) {
+        const { plotX, series } = this,
+            { chart } = series;
 
-    return proceed.call(this, chartCoordinates, plotY);
+        if (
+            chart.polar &&
+            !this.destroyed &&
```
Comment (TorsteinHonsi) [inline ts/Series/PolarComposition.ts:1431]: This condition is now redundant, isn't it? Since we're already checking `this.destroyed` on line 1425.

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
