### PR TITLE
bugfix/11928-3d-pie-position-after-update

### LINKED ISSUE #11928: 3d pie is misplaced after calling `series.update`
#### Expected behaviour

The pie chart should be placed correctly.

#### Actual behaviour

The pie chart is misplaced.

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/52z8jfnL/

#### Product version
Highcharts v7.2.0

#### Affected browser(s)
All

### PR DESCRIPTION
**Pull request by mateuszkornecki**
Fixed #11928, 3D pie was misplaced after calling `Series.update`.

### CODE REVIEW

File: samples/unit-tests/3d/series-pie/demo.js [hunk 1]
```diff
@@ -348,5 +351,11 @@ QUnit.test(
...
             'Updating series.depth should change slice\'s depth (#12515).'
         );
-    }
-);
\ No newline at end of file
+
+        assert.ok(
+            chart.series[0].group.oldtranslateX === chart.plotLeft &&
+            chart.series[0].group.oldtranslateY === chart.plotTop,
+            'Updating series shouldn\'t change pie position (#11928).'
```
Comment (TorsteinHonsi) [inline samples/unit-tests/3d/series-pie/demo.js]: Do not use `assert.ok` to test values that should be equal. Instead, break this up into two `strictEqual` assertions.
