### PR TITLE
bugfix/21994-ally-legend-button-offset

### LINKED ISSUE #21994: Select serie from horizontal bottom legend, select other serie.
#### Expected behaviour
When clicking on a series in the chart legend, the corresponding series should be selected or deselected accurately, and the chart should update accordingly. This behavior should work consistently across different web browsers, even when multiple series (e.g., 10 or more) are plotted.

#### Actual behaviour
In Microsoft Edge, when clicking on a series in the chart legend, the wrong series is selected or deselected. The selected series is often misaligned, and the click affects a series two lines below the one that was clicked. This issue occurs when multiple series (e.g., 10 or more) are plotted. In other browsers like Google Chrome, the selection works as expected.

Steps to reproduce:
1. Click on Series 1 in the chart legend. Remember work in Microsoft EDGE.
2. Move the cursor close to the "-" symbol (the part of the legend that represents the series line).
3. Subtly shift the cursor slightly upward without moving too far from the legend item.
4. Click, and notice that Series 7 gets selected or deselected instead of Series 1.

#### Live demo with steps to reproduce
https://jsfiddle.net/kwb6mxda/

#### Product version
Highcharts Core v11.4.8 (but I tested on v11.1.0 too).

#### Affected browser(s)
Microsoft EDGE

### PR DESCRIPTION
**Pull request by Xillez**
Fixed #21994, legend a11y proxy elements not tracking legend items correctly

---

I couldn't manage to make it as a normal unit test nor cypress test due to not being able to programmatically scroll down through the nested iframe structures.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208577154496339

### CODE REVIEW

File: ts/Accessibility/ProxyElement.ts [hunk 1]
```diff
@@ -309,12 +309,16 @@ class ProxyElement {
             pointer = this.chart.pointer;
 
         if (chartDiv && posElement?.getBoundingClientRect && pointer) {
-            const rectEl = posElement.getBoundingClientRect(),
+            const scrollTop = window.scrollY ||
```
Comment (KacperMadej) [inline ts/Accessibility/ProxyElement.ts:312]: Use `H.win` instead of `window` and `H.doc` instead of `document`.

**Review by KacperMadej — CHANGES_REQUESTED** [review]

**Review by KacperMadej — APPROVED** [review]

**Review by bre1470 — APPROVED** [review]
Looks good! 👍
