### PR TITLE
 bugfix/13420-annotations-not-added-on-ios

### LINKED ISSUE #13420: Adding annotations on Highstock GUI doesn't work properly on iOS devices.
#### Expected behaviour
Adding annotations from GUI should work in the same way as on Android devices.

#### Actual behaviour
It's hard to add an annotation to the chart, using GUI implemented in the below demo.
An attend to add any annotation stops on initialization. For example, after choosing the **Eliot 5 Line**, it is possible to start drawing the first line only, but not to create its second anchor point.
ezgif com-optimize

#### Live demo with steps to reproduce
Live example: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/stock-tools-gui/

#### Product version
Highstock v8.0.4 

#### Affected browser(s)
OS: iOS 13.1.1 (iPad 7th Gen)
Chrome v80.0.3987.95
Safari v13

### PR DESCRIPTION
**Pull request by Izothep**
Fixed #13420, adding annotation was not working on iOS devices.

### CODE REVIEW

File: js/annotations/eventEmitterMixin.js [hunk 1]
```diff
@@ -98,23 +110,44 @@ var eventEmitterMixin = {
...
-        emitter.removeMouseUp = addEvent(H.doc, 'mouseup', function (e) {
-            emitter.cancelClick = emitter.hasDragged;
-            emitter.hasDragged = false;
-            emitter.chart.hasDraggedAnnotation = false;
-            // ControlPoints vs Annotation:
-            fireEvent(pick(emitter.target, emitter), 'afterUpdate');
-            emitter.onMouseUp(e);
-        });
+        if (Highcharts.isTouchDevice) {
+            emitter.removeDrag = addEvent(H.doc, 'touchmove', function (e) {
```
Comment (sebastianbochan) [inline js/annotations/eventEmitterMixin.js:114]: Instead of duplicate the block of code, can we use: 

`const dragType = Highcharts.isTouchDevice ? 'touchmove' : 'mousemove'`

and then use it as a param od addEvent?

Comment (Izothep) [reply js/annotations/eventEmitterMixin.js]: All is corrected and working - thanks for this info!
