### PR TITLE
bugfix/23477-shadow-dom-styles

### LINKED ISSUE #23477: Local export with custom stylings does not abide by Shadow DOM boundaries
#### Expected behaviour
When a chart is located inside of a Shadow DOM and makes use of custom styles (styledMode: true) with a local export being triggered, Shadow DOM boundaries should be respected. 

Meaning:
-  The custom styles applied to the chart being exported **ARE and ONLY ARE** taken from within the host Shadow DOM of the chart
- The Light DOMs stylings are ignored completely
- The exported image looks the same as it looks in the browser (obviously excluding exceptions when e.g. styledMode is disabled for export)

#### Actual behaviour
When a chart is located inside of a Shadow DOM (with styledMode: true), Highcharts local export currently always seems to search exclusively inside of the Light DOM for custom stylings.

This means when a chart is inside of a Shadow DOM alongside its custom stylings. Any export will result in a purely black image because the stylings inside the Shadow DOM are not considered.

#### Live demo with steps to reproduce
I created the following JSFiddle with the minimal required steps to reproduce. How to use it is described inside of the JSFiddle:
https://jsfiddle.net/Dragxfly/9eby08u2/121/

#### Product version
_Highcharts v11.4.8_

#### Affected browser(s)
_Chromium Engine Version 139.0.7258.128_ (but probably also on other browsers)

#### For context
At my company we are working in a modern micro frontend (MFE) setup. Each MFE has its own stylings and versions. These encapsulated MFEs are displayed on a single page, with each being mounted individually inside of a Shadow DOM. This particular architecture forbids us to place stylings outside of Shadow DOMs. A workaround with compromises, is to disable styledMode in the chart options used for local export. This then obviously results in the chart not having branded styles.

### PR DESCRIPTION
**Pull request by PaulDalek**
Fixed #23477, styles from shadow DOM weren't applied to exported chart.

### CODE REVIEW

File: ts/Extensions/Exporting/ExportingDefaults.ts [hunk 1]
```diff
@@ -194,6 +194,22 @@ const exporting: ExportingOptions = {
...
+     * Whether to include isolated styles defined inside a Shadow DOM when
+     * exporting the chart.
+     *
+     * Shadow DOM styles are normally isolated from the main document and are
+     * not picked up by the exporting. When enabled, these styles are applied
+     * during export so they can be correctly inlined and rendered in the
+     * exported output.
+     *
+     * @type      {boolean}
+     * @default   true
```
Comment (pawelfus) [inline ts/Extensions/Exporting/ExportingDefaults.ts]: It seems default is `false`?

File: ts/Extensions/Exporting/ExportingOptions.ts [hunk 2]
```diff
@@ -320,6 +320,22 @@ export interface ExportingOptions {
...
+     * Whether to include isolated styles defined inside a Shadow DOM when
+     * exporting the chart.
+     *
+     * Shadow DOM styles are normally isolated from the main document and are
+     * not picked up by the exporting. When enabled, these styles are applied
+     * during export so they can be correctly inlined and rendered in the
+     * exported output.
+     *
+     * @type      {boolean}
+     * @default   true
```
Comment (pawelfus) [inline ts/Extensions/Exporting/ExportingOptions.ts]: It seems default is `false`?

File: ts/Extensions/Exporting/Exporting.ts [hunk 3]
```diff
@@ -1887,6 +1893,57 @@ class Exporting {
...
+            shadowStyles: HTMLStyleElement[] = [];
+
+        // Set the original chart's container as the first node
+        let node = chart.container,
+            rootNode;
+
+        // Find the shadow DOM root node
+        while (node) {
+            rootNode = node.getRootNode();
+            if (rootNode?.nodeType === Node.DOCUMENT_FRAGMENT_NODE) {
```
Comment (pawelfus) [inline ts/Extensions/Exporting/Exporting.ts]: Can this falsy return a node which is not a shadow root? Eg when element is a DocumentFragment? I mean, should we also add a check `&& rootNode instanceOf ShadowRoot`?

**Review by pawelfus — CHANGES_REQUESTED** [review]
Thanks! Mismatching defaults, otherwise looks good! One question though.

File: ts/Extensions/Exporting/Exporting.ts (hunk 3 above)
Comment (PaulDalek) [reply ts/Extensions/Exporting/Exporting.ts]: Yes, you're right it is not 100% bulletproof. I've done some digging and aparently, the best way is to check the `host` as it exists only on `ShadowRoot`. Corrected.

**Review by pawelfus — APPROVED** [review]
Thanks for double-checking! Nothing to add from me.

**Review by jedrzejruta — CHANGES_REQUESTED** [review]
Excellent! 🎉 

It would be great to add a simple test checking, if some property is applied to the Shadow DOM chart by using `chart.exporting.getSVG()` and regex checking it. A good starting point would be the `exporting/styled-mode` sample.

**Review by kamil-musialowski — APPROVED** [review]
LGTM!

One question about naming, most importantly with the options prop.
`includeShadowDomStyles` or `includeShadowDOMStyles`, what do you think?

**Comment by PaulDalek** [comment]
@kamil-musialowski You’re correct. The second version is much more informative. Corrected, thanks!

**Review by jedrzejruta — APPROVED** [review]
Fantastic, thanks! 👏

**Review by DJTechnoo — APPROVED** [review]

**Comment by TorsteinHonsi** [comment]
Thanks! Looks very good. 

One question about the option `includeShadowDOMStyles`. Generally we want to be a bit critical when adding new options, to avoid API complexity. So:
* Do we need this option? In other words - is there a scenario where users _don't_ want to include styles from the shadow DOM?
* And if we need an option for it, maybe it's covered by the existing `applyStyleSheets` option?

**Comment by PaulDalek** [comment]
@TorsteinHonsi Thank you for the insights! I guess using Shadow DOM is a relatively rare case, and when it does occur, it should be possible to apply styles from there, just as the `applyStyleSheets` option allows for normal, user-applied CSS. Additionally, this option is also required for styles from the Shadow DOM to be applied. Therefore, I think getting rid of the `includeShadowDOMStyles` and start using the `applyStyleSheets` option to control this would be the best solution here if we don’t want to introduce a new option, it feels like the most natural choice.

**Review by TorsteinHonsi — APPROVED** [review]
