### PR TITLE
bugfix/16516-legend-symbol-height-zero-value

### LINKED ISSUE #16516: Legend.symbolHeight do not accept 0
#### Expected behaviour
No visible symbol when `symbolHeight` is set to `0`.

#### Actual behaviour
https://github.com/highcharts/highcharts/blob/ff6ddd41f6df9e08ffe9f19471c5a2ef91f7774b/ts/Core/Legend/Legend.ts#L745-L746

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/5u18nvym/

#### Workaround
Use a value close to `0` instead - so something like `0.001` will be ok.
https://jsfiddle.net/BlackLabel/5u18nvym/1/

### PR DESCRIPTION
**Pull request by hubertkozik**
Fixed #16516, legend symbol height didn't accept 0 as a value.

### CODE REVIEW

File: ts/Core/Legend/Legend.ts [hunk 1]
```diff
@@ -738,7 +738,8 @@ class Legend {
                 label.attr('y', legend.baseline);
 
                 legend.symbolHeight =
-                    options.symbolHeight || legend.fontMetrics.f;
+                    isNumber(options.symbolHeight) ?
```
Comment (TorsteinHonsi) [inline ts/Core/Legend/Legend.ts:741]: We can use `pick` here. 

```ts
legend.symbolHeight = pick(options.symbolHeight, legend.fontMetrics.f);
```

**Comment by TorsteinHonsi** [comment]
A related issue - I recently wanted to remove the legend item for a `proximate` layout. My gut feeling was to set `symbolWidth` to 0, and that this would remove the legend item. But that didn't work, there is still a small dot. See https://jsfiddle.net/highcharts/xk7t6nu8/. 

So can we extend this PR to also handle `symbolWidth: 0`, which should result in no rendered symbol?

**Comment by hubertkozik** [comment]
Sure! Let's extend it! I will take a look into it.
