### PR TITLE
bugfix/14063-flags-series-invertible

### LINKED ISSUE #14063: Bug in flags series when using scrollbar on an inverted chart
#### Expected behaviour
Adding a flags series to an inverted chart, when using the scrollbar the flags should be displayed without error.

#### Actual behaviour
Adding a flags series to an inverted chart, when using the scrollbar an error is displayed on the console: 
 - Chrome: `Error: <g> attribute transform: Expected number, "translate(NaN,NaN) rotate(…".`
 - Firefox: `Unexpected value translate(NaN,NaN) rotate(90) scale(-1,1) scale(1 1) parsing transform attribute.`

and near the limit of the chart the flag is cut off.

#### Live demo with steps to reproduce
https://highcharts-8-ts-flags-series.stackblitz.io
https://stackblitz.com/edit/highcharts-8-ts-flags-series?file=index.ts
highcharts-flags-bug

#### Product version
Highstock 8.1.0

#### Affected browser(s)
Google Chrome 84.0.4147.125 64 bits
Firefox 79.0 64-bit

### PR DESCRIPTION
**Pull request by raf18seb**
Fixed #14063, an error was thrown when scrolling an inverted chart with a flag series.

To do:
- [x] test

### CODE REVIEW

File: samples/unit-tests/series-flags/general/demo.js [hunk 1]
```diff
@@ -165,3 +165,53 @@ QUnit.test('Flags visibility', function (assert) {
...
+        containsNaN = false;
+
+    // Move scrollbar 7px down
+    controller.pan(
+        [scrollbar.x + 3, scrollbar.y + scrollbar.scrollbarTop + 3],
+        [scrollbar.x + 3, scrollbar.y + scrollbar.scrollbarTop + 10]
+    );
+
+    chart.container.querySelectorAll('.highcharts-flags-series')
+        .forEach(function (group) {
```
Comment (pawelfus) [inline samples/unit-tests/series-flags/general/demo.js:206]: Try `array.some()` instead of `array.forEach()`+variable

File: samples/unit-tests/series-flags/general/demo.js [hunk 2]
```diff
@@ -165,3 +165,53 @@ QUnit.test('Flags visibility', function (assert) {
...
+                    title: '3'
+                }]
+            }]
+        }),
+        controller = new TestController(chart),
+        scrollbar = chart.xAxis[0].scrollbar,
+        containsNaN = false;
+
+    // Move scrollbar 7px down
+    controller.pan(
```
Comment (pawelfus) [inline samples/unit-tests/series-flags/general/demo.js:200]: Is panning necessary? Can we simply use `setExtremes()`? Just an idea :)

File: samples/unit-tests/series-flags/general/demo.js [hunk 3]
```diff
@@ -165,3 +165,53 @@ QUnit.test('Flags visibility', function (assert) {
         'Flag with box position value equal to 0 is visible.'
     );
 });
+
+// The flag series should be invertible (#14063).
```
Comment (karolkolodziej) [inline samples/unit-tests/series-flags/general/demo.js:169]: Should it? 
Comment in the `FlagSeries.ts` says that it shouldn't be invertible.

**Review by karolkolodziej — CHANGES_REQUESTED** [review]

File: samples/unit-tests/series-flags/general/demo.js (hunk 1 above)
Comment (raf18seb) [reply samples/unit-tests/series-flags/general/demo.js:206]: Right, so obvious...

**Review by karolkolodziej — APPROVED** [review]
Looks good! Thanks ;)

**Review by pawellysy — APPROVED** [review]
Looks good!

**Review by pawelfus — APPROVED** [review]
All good, thanks!

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
