### PR TITLE
bugfix/14833-column-axis-breaks

### LINKED ISSUE #14833: Column series display incorrect values with axis breaks
#### Expected behaviour
A column series on a chart with an x-axis break should behave the same as a line series: columns between `from` and `to` should be removed.

#### Actual behaviour
The columns between `from` and `to` are shifted to the `from` x position. The last column in the break ends up on top, resulting in an incorrect y value for that position.

#### Live demo with steps to reproduce
Adapted from the [docs example](https://api.highcharts.com/highcharts/xAxis.breaks):
https://jsfiddle.net/ug7xhofL/

#### Product version
Highcharts 8.2.2

#### Affected browser(s)
Tested in Chrome 87

### PR DESCRIPTION
**Pull request by khlieng**
Fixed #14833, column series axis breaks did not render correctly.

### CODE REVIEW

File: ts/Series/Column/ColumnSeries.ts [hunk 1]
```diff
@@ -1115,7 +1115,7 @@ class ColumnSeries extends LineSeries {
                 verb = graphic && chart.pointCount < animationLimit ?
                     'animate' : 'attr';
 
-            if (isNumber(plotY) && point.y !== null) {
+            if (isNumber(plotY) && point.y !== null && point.visible !== false) {
```
Comment (TorsteinHonsi) [inline ts/Series/Column/ColumnSeries.ts:1118]: For the sake of consistency, I think we should do this the same way as we do with pie series. We may want to refactor this repeated pattern in the future.

https://github.com/highcharts/highcharts/blob/35163c02456af62b4f26a93a068510844ae7a25d/ts/Series/Pie/PieSeries.ts#L951-L953

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
