### PR TITLE
bugfix/15029-LastPrice-stockTools-functionality

### LINKED ISSUE #15029: StockTools: LastPrice button functionality improvements
#### Expected behaviour
Use cases:
- initializing chart with `lastVisiblePrice.enabled` and `lastPrice.enabled` **disabled** (default): button should show "show" icon. The first click on the button should show labels and plot lines on price series (tech. indicators: to be decided, navigator series: don't). Next clicks toggle the price indicators
- initializing chart where at least one series has `lastVisiblePrice.enabled` and `lastPrice.enabled` enabled: the same behaviour as above
- initializing chart where all price series (excluding navigator series and tech. indicators) have both options enabled: button should show "hide" icon. The first click on the button should hide all last price indicators. Then every subsequent click toggles the price indicators

#### Actual behaviour
The button toggles the visibility of `lastPrice` and `lastVisiblePrice` independently. Initializing series with `lastPrice.enabled = false` and `lastVisiblePrice.enabled = true` means first click on button with switch `lastPrice.enabled` to true and `lastVisiblePrice.enabled` to false. This is strange behaviour, the end-user can not get rid of horizontal lines not matter what, and icons on the button are misleading (show/hide icon is based on `lastPrice.enabled` value).

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/42jxyf6g/3/

#### Product version
v8+

### PR DESCRIPTION
**Pull request by karolkolodziej**
Fixed #15029, improved `currentPriceIndicator` button functionality.

Todo: 
- [x] Change button icon
- [x] Add test for button change
- [x] Merge master after merging  #15195  and #15226  it into master

### CODE REVIEW

**Review by raf18seb — CHANGES_REQUESTED** [review]

File: ts/Stock/StockToolsGui.ts [hunk 1]
```diff
@@ -1223,6 +1227,34 @@ class Toolbar {
...
+        series.forEach(function (serie): void {
+            const lastVisiblePrice = serie.lastVisiblePrice && serie.lastVisiblePrice.enabled,
+                lastPrice = serie.lastPrice && serie.lastPrice.enabled;
+
+            if (lastVisiblePrice || lastPrice) {
+                priceIndicatorEnabled = 'atLeastOneEnabled';
+            }
+
+            if (!lastVisiblePrice && !lastPrice) {
+                priceIndicatorEnabled = 'bothDisabled';
```
Comment (pawellysy) [inline ts/Stock/StockToolsGui.ts:1253]: Having the boolean variable stored as a string seems a bit strange for me. A better way would be creating some kind of enum, where all options are available, which would prevent us from making some typos. If there are only 2 possibilities, the obvious choice seems `boolean`.

**Review by pawellysy — CHANGES_REQUESTED** [review]
Overall good, see comments :)

**Review by pawellysy — APPROVED** [review]
Looks Good!

File: ts/Stock/StockToolsGui.ts [hunk 2]
```diff
@@ -1223,6 +1227,34 @@ class Toolbar {
...
+                lastPrice = serie.lastPrice && serie.lastPrice.enabled;
+
+            if (lastVisiblePrice || lastPrice) {
+                priceIndicatorEnabled = true;
+            }
+
+            if (!lastVisiblePrice && !lastPrice) {
+                priceIndicatorEnabled = false;
+            }
+        });
```
Comment (pawelfus) [inline ts/Stock/StockToolsGui.ts:1255]: This `forEach` in fact is testing only the last series. No matter what we decide for the first series, the last one can define `priceIndicatorEnabled` according to its own internal options.

For example, the first series has `lastPrice` enabled and it's setting `priceIndicatorEnabled` to true. Then the last series has both options disabled, resulting in `priceIndicatorEnabled = false`. If we reverse the series order, then we will always receive `priceIndicatorEnabled=true`, no matter what was set in the first series.

File: ts/Stock/StockToolsBindings.ts [hunk 3]
```diff
@@ -2047,41 +2047,50 @@ var stockToolsBindings: Record<string, Highcharts.NavigationBindingsOptionsObjec
...
             var chart = this.chart,
-                series = chart.series[0],
-                options = series.options,
-                lastVisiblePrice = (
-                    options.lastVisiblePrice &&
-                    options.lastVisiblePrice.enabled
-                ),
-                lastPrice = options.lastPrice && options.lastPrice.enabled,
+                series = chart.series,
+                priceIndicatorEnabled = chart.stockTools && chart.stockTools.priceIndicatorEnabled,
```
Comment (pawelfus) [inline ts/Stock/StockToolsBindings.ts:2051]: Question: Is it safe to store this as a property? Can something change the button state, so we should check it on demand (`isPriceIndicatorEnabled(..)`)? For example on series add/remove?

**Review by pawelfus — CHANGES_REQUESTED** [review]
See comments below

File: ts/Stock/StockToolsBindings.ts (hunk 3 above)
Comment (pawelfus) [reply ts/Stock/StockToolsBindings.ts:2051]: I still have a small problem with storing `priceIndicatorEnabled` variable in `stockTools`. It is a bit bloating the properties, that are related to the tools in general (HTML references, options, chart references etc.). A property specific to just one button.

Can we go for now with the function call in both places? Upon `chart.render` event and here, when clicking on a button. So below would be changed from:

```js
if (priceIndicatorEnabled) {
  ...
}
```
to:
```js
if (chart.stockTools.isPriceIndicatorEnabled(series)) {
 ...
}
```

Or even better, store `isPriceIndicatorEnabled` in `bindingsUtils`, and use it:
```js
if (bindingsUtils.isPriceIndicatorEnabled(series)) {
 ...
}
```

What do you think?

**Review by pawelfus — CHANGES_REQUESTED** [review]

File: ts/Stock/StockToolsBindings.ts [hunk 4]
```diff
@@ -2047,41 +2047,40 @@ var stockToolsBindings: Record<string, Highcharts.NavigationBindingsOptionsObjec
...
+                            lastPrice: {
+                                enabled: true
+                            },
+                            lastVisiblePrice: {
+                                enabled: true,
+                                label: {
+                                    enabled: true
+                                }
+                            }
+                        }, false);
```
Comment (pawelfus) [inline ts/Stock/StockToolsBindings.ts:2078]: Q: Would that make sense to store `bindingsUtils.isPriceIndicatorEnabled(chart.series)` in a local variable? Then we could simplify this long if-else to:

```js
const priceIndicatorEnabled = bindingsUtils.isPriceIndicatorEnabled(chart.series);

if (gui && gui.guiEnabled && chart.stockTools) {
  series.forEach(function (series): void {
    series.update({
      lastPrice: { enabled: !priceIndicatorEnabled },
      lastVisiblePrice: { enabled: !priceIndicatorEnabled, label: { enabled: true } }
    }, false);
  });
}
```

**Review by pawelfus — CHANGES_REQUESTED** [review]
Just a minor clean up :)

File: ts/Extensions/Annotations/NavigationBindings.ts [hunk 5]
```diff
@@ -1486,6 +1504,24 @@ setOptions({
         }
     }
 });
+addEvent(H.Chart, 'render', function (): void {
+    const chart = this,
+        stockTools = chart.stockTools,
+        button = chart.stockTools &&
+            chart.stockTools.toolbar &&
+            chart.stockTools.toolbar.querySelector('.highcharts-current-price-indicator');
```
Comment (raf18seb) [inline ts/Extensions/Annotations/NavigationBindings.ts:1512]: You can use only `stockTools` variable instead of `chart.stockTools`

File: ts/Extensions/Annotations/NavigationBindings.ts [hunk 6]
```diff
@@ -1486,6 +1504,24 @@ setOptions({
         }
     }
 });
+addEvent(H.Chart, 'render', function (): void {
```
Comment (raf18seb) [inline ts/Extensions/Annotations/NavigationBindings.ts:1507]: It would be nice to comment why this event is added or at least add a comment with a related ticket number only. Might be useful in the future

File: ts/Extensions/Annotations/NavigationBindings.ts [hunk 7]
```diff
@@ -1486,6 +1504,24 @@ setOptions({
...
+            chart.stockTools.toolbar &&
+            chart.stockTools.toolbar.querySelector('.highcharts-current-price-indicator');
+
+    // Change the initial button background.
+    if (stockTools && chart.options.series && button) {
+        if (bindingsUtils.isPriceIndicatorEnabled(chart.series)) {
+            (button as any).firstChild.style['background-image'] =
+            'url("' + stockTools.getIconsURL() + 'current-price-hide.svg")';
+        } else {
+            (button as any).firstChild.style['background-image'] =
```
Comment (raf18seb) [inline ts/Extensions/Annotations/NavigationBindings.ts:1520]: Nothing big, but you could declare the variable like this
```js
button = chart.stockTools &&
            chart.stockTools.toolbar &&
            (chart.stockTools.toolbar.querySelector('.highcharts-current-price-indicator') as any).firstChild;
```
and use a shorter version
```js
button.style['background-image'] = ...
```

File: ts/Stock/StockToolsBindings.ts [hunk 8]
```diff
@@ -2047,41 +2047,40 @@ var stockToolsBindings: Record<string, Highcharts.NavigationBindingsOptionsObjec
...
-                gui: Highcharts.Toolbar = chart.stockTools as any,
-                iconsURL = gui.getIconsURL();
-
-            if (gui && gui.guiEnabled) {
-                if (lastPrice) {
-                    (button.firstChild as any).style['background-image'] =
-                        'url("' + iconsURL +
-                        'current-price-show.svg")';
+                series = chart.series,
+                gui: Highcharts.Toolbar = chart.stockTools as any;
```
Comment (raf18seb) [inline ts/Stock/StockToolsBindings.ts:2051]: Hmm, I'm not a TypeScript ninja, but is everything ok with this line?

File: ts/Stock/StockToolsBindings.ts [hunk 9]
```diff
@@ -2047,41 +2047,40 @@ var stockToolsBindings: Record<string, Highcharts.NavigationBindingsOptionsObjec
...
+
+            if (gui && gui.guiEnabled && chart.stockTools) {
+                // Reset all and disable both indicators
+                if (bindingsUtils.isPriceIndicatorEnabled(chart.series)) {
```
Comment (raf18seb) [inline ts/Stock/StockToolsBindings.ts:2055]: You have already declared `var series = chart.series` so use a variable instead

**Review by raf18seb — CHANGES_REQUESTED** [review]

**Review by raf18seb — APPROVED** [review]
Thanks 👍

**Review by pawelfus — APPROVED** [review]
Approved! 👍

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
