### PR TITLE
bugfix/23208-non-cartesian-inverted

### LINKED ISSUE #23208: Non-cartesian zoom on inverted chart
#### Expected behaviour
Non-cartesian zooming works correctly on inverted charts.

#### Actual behaviour
Non-cartesian zooming does not work correctly on inverted charts.

#### Live demo with steps to reproduce
Sankey inverted: https://jsfiddle.net/docpgrq3/2/
Pie inverted: https://jsfiddle.net/j19v75bg/1/

#### Product version
Highcharts v12.3.0

### PR DESCRIPTION
**Pull request by hubertkozik**
Fixed #23208, non-cartesian zoom didn't work for inverted charts.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1210624694792398

### CODE REVIEW

File: ts/Extensions/NonCartesianSeriesZoom/NonCartesianSeriesZoom.ts [hunk 1]
```diff
@@ -92,11 +92,15 @@ function onTransform(
...
 
-                const {
+                let {
                     plotSizeX = 0,
                     plotSizeY = 0
                 } = chart;
 
+                if (chart.inverted) {
+                    [plotSizeX, plotSizeY] = [plotSizeY, plotSizeX];
+                }
```
Comment (TorsteinHonsi) [inline ts/Extensions/NonCartesianSeriesZoom/NonCartesianSeriesZoom.ts]: This means we should probably use `plotWidth` and `plotHeight` instead.

**Review by TorsteinHonsi — APPROVED** [review]
