### PR TITLE
bugfix/14995-dataGrouping-approximation-demo

### LINKED ISSUE #14995: Stock: data grouping approximation demo
#### Behaviour
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/plotoptions/series-datagrouping-approximation

The console logs are bad - the `start` variable is wrongly calculated and the data comes up empty like
`(index):77 dataGroupInfo: Object Raw data: Array(0)`.

The demo is linked in the API reference here: https://api.highcharts.com/highstock/series.line.dataGrouping.approximation

### PR DESCRIPTION
**Pull request by karolkolodziej**
Fixed #14995, changed `dataGroupInfo` in the demo.

### CODE REVIEW

File: samples/stock/plotoptions/series-datagrouping-approximation/demo.js [hunk 1]
```diff
@@ -33,7 +33,7 @@ Highcharts.stockChart('container', {
         data: ADBE,
         dataGrouping: {
             approximation: function () {
-                var start = this.cropStart + this.dataGroupInfo.start;
+                var start = this.dataGroupInfo.start;
```
Comment (raf18seb) [inline samples/stock/plotoptions/series-datagrouping-approximation/demo.js:36]: From my experience, deleting some code (instead of changing it or adding new cases) is dangerous. Did you think about why the `this.cropStart` was there initially? Did you remove it consciously?

Maybe there is a use case when `this.cropStart` is actually necessary. For example:
```js
var start;

if (somethingThatGivesUsCropStart) {
    start = this.cropStart + this.dataGroupInfo.start;
} else { // if cropStart is unnecessary
    start = this.dataGroupInfo.start;
}
```

I don't know, I'm just asking whether you're sure what you're doing.

Comment (karolkolodziej) [reply samples/stock/plotoptions/series-datagrouping-approximation/demo.js:36]: There is no need to longer add `this.cropStart` since this is already included in the `this.dataGroupInfo.start`
Related [commit](https://github.com/highcharts/highcharts/commit/2d0d702c6493aad166ced3d6bb3df07771fa5c54).

**Review by raf18seb — APPROVED** [review]

**Review by pawelfus — APPROVED** [review]
Thanks!

**Review by pawellysy — APPROVED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
