### PR TITLE
bugfix/21879-measure-annotation-control-point

### LINKED ISSUE #21879: Setting controlPointOptions.visible returns error for Measure annotation.
#### Expected behaviour
Control points should be set to visible like this: 
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/annotations-advanced/crooked-line

#### Actual behaviour
The control point can not be set to visible, and returns error.

#### Live demo with steps to reproduce
Set `controlPointOptions.visible: true` for a Measure annotation.
https://jsfiddle.net/DJTechnoo/9rbzLumw/

Workaround: Use `events` to manually set the visibility:
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/annotations-advanced/measure

#### Product version
Highcharts 11.4.8

#### Affected browser(s)
Tested with Chrome and Firefox

### PR DESCRIPTION
**Pull request by kamil-musialowski**
Fixed #21879, control point option was not working for measure annotation.

### CODE REVIEW

**Review by bm64 — APPROVED** [review]

File: ts/Extensions/Annotations/Types/Measure.ts [hunk 1]
```diff
@@ -81,33 +81,28 @@ function bins(
...
         ) {
-            serie.points.forEach((point): void => {
+            s.points.forEach((point): void => {
                 if (
                     !point.isNull &&
-                    (point.x as any) > ext.xAxisMin &&
-                    (point.x as any) <= ext.xAxisMax &&
-                    (point.y as any) > ext.yAxisMin &&
-                    (point.y as any) <= ext.yAxisMax
+                    point.y &&
```
Comment (pawelfus) [inline ts/Extensions/Annotations/Types/Measure.ts:94]: what if `point.y === 0`?

File: ts/Extensions/Annotations/Types/Measure.ts [hunk 2]
```diff
@@ -229,32 +224,33 @@ function max(
...
-            serie.points.forEach((point): void => {
+            s.points.forEach((point): void => {
                 if (
                     !point.isNull &&
-                    (point.y as any) > max &&
-                    (point.x as any) > ext.xAxisMin &&
-                    (point.x as any) <= ext.xAxisMax &&
-                    (point.y as any) > ext.yAxisMin &&
-                    (point.y as any) <= ext.yAxisMax
+                    point.y &&
```
Comment (pawelfus) [inline ts/Extensions/Annotations/Types/Measure.ts:238]: What if `point.y === 0`?

File: ts/Extensions/Annotations/Types/Measure.ts [hunk 3]
```diff
@@ -275,32 +271,33 @@ function min(
...
-            serie.points.forEach((point: Point): void => {
+            s.points.forEach((point: Point): void => {
                 if (
                     !point.isNull &&
-                    (point.y as any) < min &&
-                    (point.x as any) > ext.xAxisMin &&
-                    (point.x as any) <= ext.xAxisMax &&
-                    (point.y as any) > ext.yAxisMin &&
-                    (point.y as any) <= ext.yAxisMax
+                    point.y &&
```
Comment (pawelfus) [inline ts/Extensions/Annotations/Types/Measure.ts:285]: What if.. 
Is this something we could refactor? Instead of using the same code three times?

**Review by pawelfus — CHANGES_REQUESTED** [review]
Looks good, just one (or two) minor thing

File: ts/Extensions/Annotations/Types/Measure.ts [hunk 4]
```diff
@@ -229,32 +236,29 @@ function max(
...
-            serie.points.forEach((point): void => {
+            s.points.forEach((point): void => {
                 if (
-                    !point.isNull &&
-                    (point.y as any) > max &&
-                    (point.x as any) > ext.xAxisMin &&
-                    (point.x as any) <= ext.xAxisMax &&
-                    (point.y as any) > ext.yAxisMin &&
-                    (point.y as any) <= ext.yAxisMax
+                    isNumber(point.y) &&
```
Comment (pawelfus) [inline ts/Extensions/Annotations/Types/Measure.ts:249]: already checked in `isPointWithinExtremes`

File: ts/Extensions/Annotations/Types/Measure.ts [hunk 5]
```diff
@@ -275,32 +279,29 @@ function min(
...
-            serie.points.forEach((point: Point): void => {
+            s.points.forEach((point: Point): void => {
                 if (
-                    !point.isNull &&
-                    (point.y as any) < min &&
-                    (point.x as any) > ext.xAxisMin &&
-                    (point.x as any) <= ext.xAxisMax &&
-                    (point.y as any) > ext.yAxisMin &&
-                    (point.y as any) <= ext.yAxisMax
+                    isNumber(point.y) &&
```
Comment (pawelfus) [inline ts/Extensions/Annotations/Types/Measure.ts:292]: already checked in `isPointWithinExtremes`

**Review by pawelfus — CHANGES_REQUESTED** [review]
One last thing :)

**Review by DJTechnoo — APPROVED** [review]
Amazing job!

File: ts/Extensions/Annotations/Types/Measure.ts (hunk 5 above)
Comment (kamil-musialowski) [reply ts/Extensions/Annotations/Types/Measure.ts:292]: Yeah, I've tried that but then it complains that `point.y > max` could be null or undefined
image

Comment (pawelfus) [reply ts/Extensions/Annotations/Types/Measure.ts:292]: Oh, I see. Thanks for checking!

**Review by pawelfus — APPROVED** [review]
Thanks!

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
