### PR TITLE
bugfix/20435-points-events-update-regression

### LINKED ISSUE #20435: Point events update does not work.
#### Expected behaviour
Even if the event has been triggered before, using `series.update` with the appropriate options (as in the demo) should update the event.

#### Actual behaviour
Once a function passed to the `series.point.events.mouseOver` option (or other, e.g. `click`, etc.) is called, it cannot be changed or removed by updating it.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/5ywL7zqv/
1. Open console
2. Click the button to add/remove an event; hover over points to see if the event is still working.

#### Product version
Highcharts v11.3.0

### PR DESCRIPTION
**Pull request by hubertkozik**
Fixed regression after fix #20435, updating of existing point event didn't remove the old event.

### CODE REVIEW

File: ts/Core/Series/Point.ts [hunk 1]
```diff
@@ -1319,6 +1319,12 @@ class Point {
                     .indexOf(userEvent) === -1
             )
         ) {
+            // While updating the existing callback event the old one should be
+            // removed
+            if (point.hasImportedEvents) {
+                removeEvent(point, eventType);
+            }
```
Comment (bre1470) [inline ts/Core/Series/Point.ts:1326]: This removes all listeners, while three lines up we are just testing, if the new listener has not been added. It might be better to have somewhere a reference of the outdated listener, to just remove that one and keep the rest of listeners in place. So something like a `splice` operation on `point.hcEvents[eventType]`. But at the same time it reminds of an old discussion about series listeners. Some users like to have the callback replacement while others like to have callback additions.

Comment (hubertkozik) [reply ts/Core/Series/Point.ts]: I've changed the solution a little bit. I would say, that callback additions are not the correct way of dealing with it, even in the topic https://github.com/highcharts/highcharts/issues/20435 users complain about old events, which which be updated/removed.

**Review by bre1470 — APPROVED** [review]
Nice solution. LGTM 👍

File: ts/Core/Series/Point.ts [hunk 2]
```diff
@@ -1319,18 +1319,23 @@ class Point {
                     .indexOf(userEvent) === -1
             )
         ) {
-            addEvent(point, eventType, userEvent);
-            point.hasImportedEvents = true;
+            // While updating the existing callback event the old one should be
+            // removed
+            if (point.importedUserEvent) {
+                point.importedUserEvent();
+            }
```
Comment (TorsteinHonsi) [inline ts/Core/Series/Point.ts:1326]: Terser:

```suggestion
            point.importedUserEvent.?();
```

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks! Except for the tiny suggestion, it's good to go 👍
