### PR TITLE
fix(grid): correct broken credits demo URL in JSDoc

### LINKED ISSUE #24326: Grid API docs demo - wrong URL.
https://github.com/highcharts/highcharts/blob/d327a0d9f2b86539432467a682fe5166b519ca10/ts/Grid/Pro/Credits/CreditsProComposition.ts#L81

Live: https://api.highcharts.com/grid/credits

API demo link 404 - probably it should be (?):
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/grid-pro/e2e/credits-pro

### PR DESCRIPTION
**Pull request by ramanverse**
## Problem

Fixes #24326

The JSDoc comment on the `Options.credits` property in `CreditsProComposition.ts` contains a `@link` pointing to a non-existent demo URL:

```
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/grid-pro/credits
```

This URL returns a 404 error, as shown in the [API docs](https://api.highcharts.com/grid/credits).

## Fix

Updated the URL to point to the correct existing sample:

```
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/grid-pro/e2e/credits-pro
```

## Changes

- **File:** `ts/Grid/Pro/Credits/CreditsProComposition.ts`
- - **Change:** One-line URL fix in a JSDoc `@link` comment

### CODE REVIEW

**Comment by ramanverse** [comment]
@KacperMadej I've pushed a fix for that broken Credits demo link. @sebastianbochan, @karolkolodziej - could one of you take a look? It's a documentation-only change to fix the pathing. Ready for review whenever you're free!

File: ts/Grid/Pro/Credits/CreditsProComposition.ts [hunk 1]
```diff
@@ -78,7 +85,7 @@ declare module '../../Core/Options' {
         /**
          * Options for the credits label.
          *
-         * Try it: {@link https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/grid-pro/credits | Credits options}
+         * Try it: {@link https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/grid-pro/e2e/credits-pro | Credits options}
```
Comment (ddragula) [inline ts/Grid/Pro/Credits/CreditsProComposition.ts]: We treat the samples in the e2e folder as strictly internal. In addition, the sample itself needs a few visual tweaks before it can be published in the documentation (e.g. full dark mode support in jsfiddle), but this is optional for this PR – you can do it, or we’ll take care of it on our end.

```suggestion
         * Try it: {@link https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/grid-pro/basic/credits | Credits options}
```

**Comment by ramanverse** [comment]
@ddragula I've updated the credits demo URL to the basic sample as you suggested, can you review it
