### PR TITLE
bugfix/18025-gridlines-across-panes

### LINKED ISSUE #18025: gridline: clipping issue in stock
#### Actual behaviour
We are currently unable to remove the red line from the gridline options: 
https://api.highcharts.com/highstock/xAxis.gridLineWidth

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/8znmf1ew/

#### Workaround: 
https://jsfiddle.net/BlackLabel/c0swz1mL/

#### Product version
v10.3.1

### PR DESCRIPTION
**Pull request by kamil-musialowski**
Fixed #18025, gridlines were rendered across panes.

### CODE REVIEW

File: ts/Core/Axis/Axis.ts [hunk 1]
```diff
@@ -989,42 +989,69 @@ class Axis {
             return x;
         }
 
-        const evt: Event = {
+        const evt: Partial<Event&Axis.PlotLinePathOptions> = {
```
Comment (pawellysy) [inline ts/Core/Axis/Axis.ts:992]: When I think about it, I think it should be just `Partial<Axis.PlotLinePathOptions>`Since there are no `Event`'s attributes, but your call.

File: ts/Core/Axis/Axis.ts [hunk 2]
```diff
@@ -989,42 +989,69 @@ class Axis {
             return x;
         }
```
Comment (pawellysy) [inline ts/Core/Axis/Axis.ts:990]: Now, when looking at it, the body of `between` function looks a lot like what we implemented. Could you maybe investigate, why didn't it work correctly?

**Review by pawellysy — CHANGES_REQUESTED** [review]
Good job! Few comments

**Review by pawellysy — APPROVED** [review]
Looks good!

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
