### PR TITLE
dash/22684-connector-polling-restarting

### LINKED ISSUE #22684: Connector polling remains active even if connector is unused
### Expected behaviour
Polling should only remain active for connectors currently in use. Once a connector is removed or replaced, polling should be automatically terminated.

### Actual behaviour
I’ve observed that when a JSON connector with polling enabled is assigned to a component, it continues to poll indefinitely—persisting even after the connector is modified via edit mode or the component is deleted. This issue only ceases when the dashboard is closed. In the development environment, it even manifests as an error.

### Live demo with steps to reproduce
[JSFiddle Demo](https://jsfiddle.net/trip57/s3ty7opa/2/)
**Steps to replicate:**
1. Open the Developer Tools in your browser (Chrome: Ctrl + Shift + I).
2. Navigate to the Network tab.
3. Wait at least 10 seconds—you should see a request being sent to the connector's URL.
4. Enable Edit Mode and delete the chart titled "Polling".
5. Wait another 10 seconds—a request will still be sent to the connector's URL.

### Product version
Highcharts JS v12.1.2 (2024-12-21)
Highcharts Dashboards v3.1.0 (2024-12-04)

### Affected browser(s)
All

### PR DESCRIPTION
**Pull request by KamilKubik**
Fixed #22684, connector polling restarting based on assignment.

---

1. `removeEvent(this);` has been added to prevent a missing reference error when (removing/adding) a chart that uses a connector. 
2. The `polling` getter has been changed to avoid the recursion. Originally, the getter was added to prevent external overwriting. That remains. 
3. The `ConnectorTypes` has been pointing to the abstract class instead of the instances created from it, causing the TS error since the `options.dataRefreshRate` is not defined in the `dataConnector` abstract class. I can see a few approaches here, so I'm open to getting your feedback.

### CODE REVIEW

File: ts/Dashboards/Components/Component.ts [hunk 1]
```diff
@@ -838,6 +870,32 @@ abstract class Component {
...
+     * @param connector
+     * Instance of a connector.
+     *
+     * @internal
+     */
+    public removeConnectorAssignment(
+        connector: Component.ConnectorTypes | undefined
+    ): void {
+        const component = this;
+        if (connector && connector.elements.includes(component.element)) {
```
Comment (sebastianbochan) [inline ts/Dashboards/Components/Component.ts:886]: 1. You can use optional `connector?.elements.includes`
2. `connector.elements` appears a few times, consider using `const ` and assign a reference.

File: ts/Dashboards/Components/Component.ts [hunk 2]
```diff
@@ -838,6 +870,32 @@ abstract class Component {
...
+     * Removes the component instance from the provided connector.
+     * Stops the connector polling if the last element is removed.
+     *
+     * @param connector
+     * Instance of a connector.
+     *
+     * @internal
+     */
+    public removeConnectorAssignment(
+        connector: Component.ConnectorTypes | undefined
```
Comment (sebastianbochan) [inline ts/Dashboards/Components/Component.ts:883]: `connector?: Component.ConnectorTypes`

Its optional then and we do not need to use "undefined type"

File: ts/Dashboards/Components/Component.ts [hunk 3]
```diff
@@ -489,6 +490,36 @@ abstract class Component {
...
+     * @param connector
+     * Instance of a connector.
+     *
+     * @internal
+     */
+    public addConnectorAssignment(
+        connector: Component.ConnectorTypes | undefined
+    ): void {
+        const component = this;
+        if (connector && !connector.elements.includes(component.element)) {
```
Comment (sebastianbochan) [inline ts/Dashboards/Components/Component.ts:506]: Similar notes as in `removeConnectorAssignment`

**Review by sebastianbochan — CHANGES_REQUESTED** [review]

File: ts/Dashboards/Components/Component.ts (hunk 1 above)
Comment (KamilKubik) [reply ts/Dashboards/Components/Component.ts:886]: `connector &&` makes sure it's defined inside. When I do it this way, it shows errors on every usage. My point is I should either use the optional chaining or define the connector somewhere anyway. If I then don't follow this suggestion, there's only one usage of `connector.elements` I could use a variable for.

**Review by karolkolodziej — CHANGES_REQUESTED** [review]
Looks good, but please cover it in e2e tests.

**Review by sebastianbochan — APPROVED** [review]

File: test/cypress/dashboards/integration/Components/general.cy.js [hunk 4]
```diff
@@ -38,3 +38,42 @@ describe('Caption', () => {
       .should('be.visible');
   });
 });
+
+describe('Data polling restarting', () => {
+  before(() => {
+    cy.visit('dashboards/data/connector-polling');
```
Comment (karolkolodziej) [inline test/cypress/dashboards/integration/Components/general.cy.js:44]: if this demo is only for the sake of this test, please move it to `dashboards/cypress/...`

**Review by karolkolodziej — APPROVED** [review]

File: test/cypress/dashboards/integration/Components/general.cy.js (hunk 4 above)
Comment (KamilKubik) [reply test/cypress/dashboards/integration/Components/general.cy.js]: Changed, thanks!

**Review by ddragula — APPROVED** [review]
