### PR TITLE
bugfix/23843-animated-coloraxis-marker

### LINKED ISSUE #23843: Animated Markers on Color Axis
#### Expected behaviour
Marker animates to move smoothly along color axis to new values.

#### Actual behaviour
Marker jumps immediately to new value on the color axis.

#### Live demo with steps to reproduce
https://jsfiddle.net/xmranbkj/
Steps:
1. Hover a heatmap data point and observe the marker on the color axis
2. Hover another data point with a different value, and observe that the marker on the color axis jumps rather than having a smooth animation. 

#### Product version
Highcharts v12.1

#### Affected browser(s)
Chrome

### PR DESCRIPTION
**Pull request by sebastianbochan**
Fixed #23843, `colorAxis` marker didn't animate when moving.

### CODE REVIEW

File: ts/Core/Axis/Axis.ts [hunk 1]
```diff
@@ -4607,9 +4607,15 @@ class Axis {
...
-                d: path
-            });
+            graphic.show();
+
+            // Animate the crosshair when it has animation options (e.g. color
+            // axis marker) and has been drawn before
+            graphic.animate(
+                { d: path },
+                options?.animation ?
+                    animObject(options.animation) : { duration: 0 }
```
Comment (TorsteinHonsi) [inline ts/Core/Axis/Axis.ts]: It should be safe to use `animObject` here also when `options?.animation` is falsy, in which case I believe it should return `{ duration: 0 }`. Unless I'm missing something?
```suggestion
                animObject(options?.animation)
```

File: ts/Core/Axis/Axis.ts [hunk 2]
```diff
@@ -4607,9 +4607,15 @@ class Axis {
...
             }
 
-            graphic.show().attr({
-                d: path
-            });
+            graphic.show();
+
+            // Animate the crosshair when it has animation options (e.g. color
+            // axis marker) and has been drawn before
+            graphic.animate(
```
Comment (TorsteinHonsi) [inline ts/Core/Axis/Axis.ts]: We should preserve the chaining for (microscopically) smaller weight.

File: ts/Core/Axis/AxisOptions.ts [hunk 3]
```diff
@@ -199,6 +200,14 @@ export interface AxisCrosshairLabelOptions {
 
 export interface AxisCrosshairOptions {
 
+    /**
+     * Animation for the crosshair as it moves between values. Set to
+     * `false` to disable animation. Used by the color axis marker.
+     *
+     * @product highcharts highstock highmaps
```
Comment (TorsteinHonsi) [inline ts/Core/Axis/AxisOptions.ts:207]:
```suggestion
     * @product highcharts highstock highmaps
     * @since next
```

**Comment by sebastianbochan** [comment]
@TorsteinHonsi 
Applied requested suggestions.

Regarding animation for marker, it is enabled by default. If you need to disable it, you should use the option:

```
 colorAxis: {
        marker: {
            animation: false
        }
},
```
