### PR TITLE
Docs: Fixed doclet of bollinger fillColor and params.

### LINKED ISSUE #16857: PlotBbParamsOptions.standardDeviation missing in highcharts v9.3.2 typings
#### Expected behaviour

No TS compiler error when setting a `standardDeviation` for BollingerBands.

Example:

```ts
      {
        type: 'bb' as const,
        linkedTo: 'candleChart',
        yAxis: 0,
        color: 'grey',
        params: {
          standardDeviation: 2,
          period: 20,
          index: 3,
        },
        dataGrouping: {
          enabled: false,
        },
      }
```

#### Actual behaviour

The `highcharts.d.ts` file of highcharts v9.3.2 doesn't recognize `standardDeviation` anymore. It is simply missing from `interface PlotBbParamsOptions`. This was working fine with highcharts v9.1.2.

**Screenshot:**

image

#### Live demo with steps to reproduce

The JS unit tests actually include a `standardDeviation` setting:

- https://github.com/highcharts/highcharts/blob/v9.3.2/samples/unit-tests/indicator-bb/recalculations/demo.js#L15-L22

#### Product version

- highcharts v9.3.2

#### Affected browser(s)

- TS source code is affected

### PR DESCRIPTION
**Pull request by bre1470**
Fixed #16857, `PlotBbParamsOptions.standardDeviation` missing

### CODE REVIEW

File: ts/Stock/Indicators/BB/BBIndicator.ts [hunk 1]
```diff
@@ -110,12 +110,14 @@ class BBIndicator extends SMAIndicator {
...
-         * @type      {Highcharts.Color}
-         * @since 9.3.2
+         * @type      {Highcharts.ColorType}
+         * @since     9.3.2
          * @apioption plotOptions.bb.fillColor
-         *
          */
 
+        /**
+         * Paramters used in calculation of regression series' points.
```
Comment (TorsteinHonsi) [inline ts/Stock/Indicators/BB/BBIndicator.ts:119]: Typo: Parameters

... of _the_ regression series' points?

File: ts/Stock/Indicators/BB/BBIndicator.ts [hunk 2]
```diff
@@ -151,9 +153,18 @@ class BBIndicator extends SMAIndicator {
          * @extends plotOptions.bb.bottomLine
          */
         topLine: {
+            /**
+             * Styles for a top line.
```
Comment (TorsteinHonsi) [inline ts/Stock/Indicators/BB/BBIndicator.ts:157]: ... _the_ top line?

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
