### PR TITLE
bugfix/21245-boxplot-multiple-series-position

### LINKED ISSUE #21245: Boxplot with two data series is NOT rendered correctly
#### Expected behaviour
Expected to render two boxplots next to each other.

#### Actual behaviour
Boxplots are rendered disjointed frome their min/max parts and one over the other

#### Live demo with steps to reproduce
https://jsfiddle.net/Lzwovy7q/

#### Product version
Last NOT affected version is 11.4.0, present since then

#### Affected browser(s)
Chrome, Firefox, Safary (others not tested)

### PR DESCRIPTION
**Pull request by hubertkozik**
Fixed #21245, points were wrongly positioned for multiple boxplot series.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1207445117851437

### CODE REVIEW

**Review by MarkusBarstad — APPROVED** [review]
Good job 🎉 !

File: ts/Series/BoxPlot/BoxPlotSeries.ts [hunk 1]
```diff
@@ -261,7 +261,11 @@ class BoxPlotSeries extends ColumnSeries {
                 let d: SVGPath;
 
                 // The stem
-                const stemX = crisp(point.plotX || 0, point.stem.strokeWidth());
+                const stemX = crisp(
+                    (point.plotX || 0) + (series.pointXOffset || 0) +
```
Comment (Xillez) [inline ts/Series/BoxPlot/BoxPlotSeries.ts:265]: Is there a reason for why we use "||" instead of "??"?
I'd recommend using ?? instead of || as the nullish coalescing operator (??) is regarded as safer and cannot be mistaken as a boolean or operator.

**Comment by Xillez** [comment]
Sorry for the late review 😅 Looks good to me except a minor question 👍

File: ts/Series/BoxPlot/BoxPlotSeries.ts (hunk 1 above)
Comment (TorsteinHonsi) [reply ts/Series/BoxPlot/BoxPlotSeries.ts:265]: Since `point.plotX` is typed as `number|undefined`, I'd say the `||` operator is safe. We use this pattern a lot throughout the code base, for properties of this type.

**Review by TorsteinHonsi — APPROVED** [review]
Looks good to me 👍
