### PR TITLE
bugfix/13375-plotbands-events-not-working

### LINKED ISSUE #13375: plotBand events not working if it was added with the api addPlotBand()
If the chart is initialized without a plotBand option within the xAxis option, no events are attached if it get's added at a later point.
If there is an existing plotBand option, the event's will be attached, the plotBand option must not include any plotBand, just the option needs to exist.

Problem is that `isNew` is false on second loop without an existing plotBand option.
I checked this with:
`console.log('create plot', isNew, options.id, path);`

before

```
// common for lines and bands
if ((isNew || !svgElem.d) && path && path.length) {
```

If the `plotBand` option **does not** exists, isNew is within the first call `true` and on second `false`
If the `plotBand` option **does** exists, on first and second isNew is `true`

#### Expected behaviour

Events should get attached correctly.

#### Actual behaviour

`if ((isNew || !svgElem.d) && path && path.length) {` is false and the events are not attached.

#### Live demo with steps to reproduce
http://jsfiddle.net/d2k6r1bs/13/

Saved version has the issue, uncomment the plotBand option to get the expected behaviour

#### Product version
Highstock JS v8.0.4 (2020-03-10)

#### Affected browser(s)
All, (Verified in Firefox + Chrome in Win + Linux, IE 11 + Edge (not the chrome version))

### PR DESCRIPTION
**Pull request by Izothep**
Fixed #13375, events were not added to dynamically created plot bands and lines.

### CODE REVIEW

**Comment by Izothep** [comment]
Actually, I want to add one more fix in this PR, I am converting it to draft

File: js/parts/PlotLineOrBand.js [hunk 1]
```diff
@@ -106,7 +106,7 @@ var PlotLineOrBand = /** @class */ (function () {
              * @name Highcharts.PlotLineOrBand#svgElement
              * @type {Highcharts.SVGElement}
              */
-            plotLine.svgElem = svgElem = renderer
+            plotLine.svgElem = svgElem = svgElem || renderer
```
Comment (Izothep) [inline js/parts/PlotLineOrBand.js:109]: ok, its a relict of different solution, additional check might be removed.
