### PR TITLE
bugfix/23946-shadow-inverted-chart

### LINKED ISSUE #23946: Shadow property breaks displaying line series on a bar chart
#### Expected behaviour
When combining a line/spline series with shadow property applied and a bar series, the chart displays line series properly.

#### Actual behaviour
When combining a line/spline series with shadow property applied and a bar series, part of the line isn't shown, only the points are displayed.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/zx14t389/

1. Remove the `shadow` property and the series displays properly. This seems to affect only line/spline, other types of series work fine.
2. The bug happens only on a bar chart. Change the type of a bar series to column and it works fine.
3. Bug seems to be related to window size. When the window is smaller, it displays correctly. See images 
below:
Image

Image

Regression since v11.2

Originally found on [this forum post.](https://www.highcharts.com/forum/viewtopic.php?t=53759)

#### Product version
Highcharts Core

### PR DESCRIPTION
**Pull request by sebastianbochan**
Fixed #23946, bad clipping in an inverted chart if a series had shadow enabled

### CODE REVIEW

File: ts/Series/Line/LineSeries.ts [hunk 1]
```diff
@@ -161,18 +161,25 @@ class LineSeries extends Series {
...
-                            isObject(options.shadow) ? options.shadow : {}
-                        )
-                    );
+                            isInverted ? {} :
+                                { filterUnits: 'userSpaceOnUse' },
+                            options.shadow
+                        ) : (
+                            isInverted ? true :
+                                { filterUnits: 'userSpaceOnUse' }
+                        );
```
Comment (jedrzejruta) [inline ts/Series/Line/LineSeries.ts:178]: How about splitting the `defaultOptions` for the shadow so that it's more readable? It feels cleaner since at the first glance I had to dive deeper in order to understand why the isInverted is checked twice. 


```suggestion
 const defaultShadowOptions =
    isInverted ? {} : { filterUnits: 'userSpaceOnUse' };
                        
const shadowOptions = isObject(options.shadow) ?
    merge(
        defaultShadow,
        options.shadow
    ) :
    isInverted ? true : defaultShadow;
```

File: ts/Series/Line/LineSeries.ts [hunk 2]
```diff
@@ -161,18 +161,24 @@ class LineSeries extends Series {
...
-                graph[verb](attribs)
-                    // Add shadow to normal series as well as zones
-                    .shadow(
-                        options.shadow &&
-                        // If shadow is defined, call function with
-                        // `filterUnits: 'userSpaceOnUse'` to avoid known
-                        // SVG filter bug (#19093)
+                graph[verb](attribs);
+
+                // Add shadow only to the main series (not zones)
```
Comment (TorsteinHonsi) [inline ts/Series/Line/LineSeries.ts:166]: If we don't apply it to zones, we're causing a regression with the zone/shadow combination like this: https://jsfiddle.net/highcharts/j71ebym2/

I tried removing the `!i` condition and the shadows seem to render correctly both for inverted and non-inverted charts? Or did you find a case where it failed?

Comment (sebastianbochan) [reply ts/Series/Line/LineSeries.ts:166]: Thanks!
There are so many regressions everywhere :) Sorry, I was not aware of the particular one.

Anyway, I removed `!i` and it looks good. All my tests passed (including polar chart and chart with 2 points).

Comment (TorsteinHonsi) [reply ts/Series/Line/LineSeries.ts:166]: Great!
