### PR TITLE
bugfix/13811-partialFill-order

### LINKED ISSUE #13811: can't override series partialFill color for a specific point
#### Expected behaviour
PartialFill fill color can be defined as an object in plotOptions, series and data.
When defined for a data point I expect it to override the fill color defined in the series or plotOptions level.

#### Actual behaviour
Fill color defined in plotOptions or series level can't be overriden.

#### Live demo with steps to reproduce
https://jsfiddle.net/alvarezg/0nu2t75p/
Partial fill in top left point should be black.
Partial fill in bottom left point should be red
.
#### Product version
Highcharts 8.1.2

### PR DESCRIPTION
**Pull request by khlieng**
Fixed #13811, `Point.partialFill` didn't override `Series.partialFill`.

### CODE REVIEW

File: samples/unit-tests/series-xrange/xrange/demo.js [hunk 1]
```diff
@@ -477,3 +477,68 @@ QUnit.test('Stacking', assert => {
...
+            dataLabels: {
+                enabled: true
+            }
+        }]
+    });
+
+    assert.strictEqual(
+        chart.series[0].points[0].graphic.partRect.attr('fill'),
+        'black',
+        'Point.partialFill takes priority'
```
Comment (TorsteinHonsi) [inline samples/unit-tests/series-xrange/xrange/demo.js:537]: For the sake of readability, it's good practice to include the word "should" in the message. That way, in five years when the test fails, we don't have to do brain gymnastics to understand what is expected. "Point.partialFill should take priority".

File: samples/unit-tests/series-xrange/xrange/demo.js [hunk 2]
```diff
@@ -477,3 +477,68 @@ QUnit.test('Stacking', assert => {
...
+    );
+    assert.strictEqual(
+        chart.series[0].points[2].graphic.partRect.attr('fill'),
+        'red',
+        'Series.partialFill still works'
```
Comment (TorsteinHonsi) [inline samples/unit-tests/series-xrange/xrange/demo.js:542]: Series.partialFill should still work

File: ts/Series/XRangeSeries.ts [hunk 3]
```diff
@@ -696,7 +696,7 @@ BaseSeries.seriesType<typeof Highcharts.XRangeSeries>('xrange', 'column'
                         }
                         if (isObject(seriesOpts.partialFill)) {
                             pfOptions = merge(
-                                pfOptions, seriesOpts.partialFill
+                                {}, seriesOpts.partialFill, pfOptions
```
Comment (TorsteinHonsi) [inline ts/Series/XRangeSeries.ts:699]: The first empty object is not needed, since merge (by default) returns a new object and assigns it to `pfOptions`.

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
