### PR TITLE
bugfix/21319-resetZoomButton-visile-while-panning

### LINKED ISSUE #21319: When panning, the reset zoom button appears
#### Expected behaviour
When panning, the reset zoom button appears.

#### Actual behaviour
Only when and `ordinal` is disabled. 
The reset zoom button should not be visible when panning.
image

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/n4g37veh/
1. Zoom with scroll
2. Pan

#### Product version
Regression was introduced in version 11.4.0. 
Unable to bisect.

#### Affected browser(s)
All

### PR DESCRIPTION
**Pull request by kamil-musialowski**
Fixed #21319, a regression since v11.4.0, `resetZoomButton` was visible while panning on non-ordinal axes.

### CODE REVIEW

**Review by pawellysy — APPROVED** [review]

**Review by pawelfus — APPROVED** [review]
Thanks!

**Review by bm64 — APPROVED** [review]

**Review by DJTechnoo — APPROVED** [review]
Looks good!

File: ts/Core/Chart/Chart.ts [hunk 1]
```diff
@@ -3865,8 +3865,13 @@ class Chart {
                 );
             } else {
 
-                // Show or hide the Reset zoom button
-                if (displayButton && !this.resetZoomButton) {
+                // Show or hide the Reset zoom button, but not while panning
+                if (
+                    displayButton &&
+                    !this.xAxis[0].isPanning && // #21319
+                    !this.yAxis[0].isPanning && // #21319
```
[the remark this answers is not in the document]
Comment (kamil-musialowski) [reply ts/Core/Chart/Chart.ts]: Oh yes, that's a very good catch - thank you!

File: ts/Core/Chart/Chart.ts [hunk 2]
```diff
@@ -3822,6 +3823,10 @@ class Chart {
                         // operation has finished.
                         axis.isPanning = trigger !== 'zoom';
 
+                        if (axis.isPanning && !isAnyAxisPanning) {
```
Comment (TorsteinHonsi) [inline ts/Core/Chart/Chart.ts:3826]:
```suggestion
                        if (axis.isPanning) {
```
It's sufficient to check for `axis.isPanning` here, right? Doesn't matter if it's already true, it doesn't get any truer.

File: ts/Core/Chart/Chart.ts [hunk 3]
```diff
@@ -3641,7 +3641,8 @@ class Chart {
             { inverted } = this;
 
         let hasZoomed = false,
-            displayButton: boolean|undefined;
+            displayButton: boolean|undefined,
+            isAnyAxisPanning = false;
```
Comment (TorsteinHonsi) [inline ts/Core/Chart/Chart.ts:3645]:
```suggestion
            isAnyAxisPanning: true | undefined;
```
We can chip off a few bytes by not setting it to false to begin with.

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Some micro optimizing change requests for file size

File: ts/Core/Chart/Chart.ts (hunk 2 above)
Comment (kamil-musialowski) [reply ts/Core/Chart/Chart.ts:3826]: Yeah, definitely - my initial thought was "there is no need to assign `true` a few times". But making the file a bit smaller is also a valid reason for that.

**Review by TorsteinHonsi — APPROVED** [review]
