### PR TITLE
bugfix/17545-funnel-data-labels-inside 

### LINKED ISSUE #17545: Funnel/Pyramid Chart - Data Labels appear inside indicator even when inside is set to false
#### Expected behaviour
Setting dataLabels > inside : false should display data labels outside the Indicator on full screen view

#### Actual behaviour
The data labels appear inside Funnel/Pyramid indicator when viewed in 'View in full screen'. This also happens at time on when loading the Indicator itself.

#### Live demo with steps to reproduce
https://jsfiddle.net/obpLf8js/1/
Funnel_Fullscreen_InsideFalse_DataLabelsAppearInside

#### Product version
Highcharts JS v10.1.0 (2022-04-29)

#### Affected browser(s)
Chrome. Edge

Note: This does not happen all the time but sporadically happens. I am not able to tell the pattern as it is very random. Setting  allowOverlap: false resolves this issue but does not display the lower value data labels on load unless mouse hover. The missing data values affect when exported as image/pdf

### PR DESCRIPTION
**Pull request by jakubjanuchta**
Fixed #17545, misplaced funnel/pyramid dataLabels after legend item click when `dataLabels.inside` set to false.

### CODE REVIEW

File: ts/Extensions/OverlappingDataLabels.ts [hunk 1]
```diff
@@ -278,9 +278,11 @@ function hideOrShow(label: SVGElement, chart: Chart): boolean {
                 isLabelAffected = true;
 
                 // Animate or set the opacity
-                label.alignAttr.opacity = newOpacity;
+                const labelAttr = label.dataLabelPosition?.posAttribs ||
+                    label.alignAttr;
+                labelAttr.opacity = newOpacity;
                 label[label.isOld ? 'animate' : 'attr'](
-                    label.alignAttr,
+                    labelAttr,
```
Comment (TorsteinHonsi) [inline ts/Extensions/OverlappingDataLabels.ts:285]: Is a change in the core needed? Do we know why `label.alignAttr` is not updated for the funnel? Is it something specific to the funnel series, or can the same situation appear in a pie series?

**Review by TorsteinHonsi — COMMENTED** [review]
Thanks! In addtion to my inline question, see https://github.com/highcharts/highcharts/tree/master/changelog#writing-content-for-the-changelog, point 8 about using code backticks.

File: ts/Extensions/OverlappingDataLabels.ts (hunk 1 above)
Comment (jakubjanuchta) [reply ts/Extensions/OverlappingDataLabels.ts:285]: Thanks for the backticks suggestions, I changed the PR description. 

Funnel utilizes Pie drawDataLabels only when inside: false. 
https://github.com/highcharts/highcharts/blob/12a5a01b32a09882151b806e86021fe269b71019/ts/Series/Funnel/FunnelSeries.ts#L248-L254
Pie dataLabels are positioned based on `dataLabelPosition.posAttribs` and the `alignAttr` for pie label remains undefined (which means that it's position is never updated in `OverlappingDataLabels`) because alignAttr is only updated by `SVGElement.align` in `alignDataLabel` which is not utilized by pie labels but it is by funnel with `dataLabels.inside` = false and that's why the incorrect position is applied in `OverlappingDataLabels`.
https://github.com/highcharts/highcharts/blob/12a5a01b32a09882151b806e86021fe269b71019/ts/Series/Funnel/FunnelSeries.ts#L216-L226

Comment (jakubjanuchta) [reply ts/Extensions/OverlappingDataLabels.ts:285]: Thanks for the backticks suggestions @TorsteinHonsi , I changed the PR description. 

Funnel utilizes Pie drawDataLabels only when inside: false. 
https://github.com/highcharts/highcharts/blob/12a5a01b32a09882151b806e86021fe269b71019/ts/Series/Funnel/FunnelSeries.ts#L248-L254
Pie dataLabels are positioned based on `dataLabelPosition.posAttribs` and the `alignAttr` for pie label remains undefined (which means that it's position is never updated in `OverlappingDataLabels`) because alignAttr is only updated by `SVGElement.align` in `alignDataLabel` which is not utilized by pie labels but it is by funnel with `dataLabels.inside` = false and that's why the incorrect position is applied in `OverlappingDataLabels`.
https://github.com/highcharts/highcharts/blob/12a5a01b32a09882151b806e86021fe269b71019/ts/Series/Funnel/FunnelSeries.ts#L216-L226

Comment (TorsteinHonsi) [reply ts/Extensions/OverlappingDataLabels.ts:285]: So can we override this somehow from the funnel series module so we don't need to make an exception in the overlapping labels module?

Comment (jakubjanuchta) [reply ts/Extensions/OverlappingDataLabels.ts]: Sure! Although, I haven't found a right place to overwrite the `alignAttr` in the funnel module after `posAttribs` is calculated and before utilizing `hideOrShow` where the position is updated so I had to update it in PieDataLabels.

Comment (TorsteinHonsi) [reply ts/Extensions/OverlappingDataLabels.ts]: I found some inconsistencies and moved the fix to the funnel series (and simplified overlappping labels along the way). Thanks!

**Review by TorsteinHonsi — APPROVED** [review]
