### PR TITLE
bugfix/20954-noData-string

### LINKED ISSUE #20954: Highcharts PIE doesn't display noData string for hidden points
#### Expected behaviour
When user filters out the entire data by removing every series in the legend, the PIE chart should display the configured noData string

#### Actual behaviour
When user filters out the entire data by removing every series in the legend, the PIE chart doesn't display the configured noData string

#### Live demo with steps to reproduce
https://jsfiddle.net/ue2gs83b/3/
Press on every series in the legend to filter that series out.

#### Product version

Latest version

#### Affected browser(s)
Chrome

### PR DESCRIPTION
**Pull request by magdalena-gut**
Fixed #20954, the `noData` label was not visible for pie series with all points hidden.

### CODE REVIEW

File: ts/Series/Pie/PieSeries.ts [hunk 1]
```diff
@@ -274,11 +274,11 @@ class PieSeries extends Series {
 
     /**
      * Define hasData function for non-cartesian series. Returns true if the
-     * series has points at all.
+     * series has at least one visible point (#23235)
      * @private
      */
     public hasData(): boolean {
-        return !!this.dataTable.rowCount;
+        return this.points.some((point): boolean => point.visible !== false);
```
Comment (TorsteinHonsi) [inline ts/Series/Pie/PieSeries.ts]: Given that `point.visible` is [never undefined](https://github.com/highcharts/highcharts/blob/f090a057f64544895ed73ca32df1feb4f61f32e0/ts/Core/Series/Point.ts#L145), it should be sufficient with a boolean test:
```suggestion
        return this.points.some((point): boolean => point.visible);
```

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks! One inline comment.

**Review by TorsteinHonsi — APPROVED** [review]
