### PR TITLE
bugfix/18435-gantt-zoom-tooltip-misplaced

### LINKED ISSUE #18435: Gantt Chart: Tooltip misplaced on navigator zooming
#### Expected behaviour
After zooming in using the navigator, the tooltip position should be placed on the left side of the chart.

#### Actual behaviour
After zooming on a bar, the tooltip is placed outside of the chart
ezgif com-gif-maker

#### Live demo with steps to reproduce

- Zoom in on the navigator
- Hover on the first bar

https://jsfiddle.net/rzhwcug7/

#### Product version
Highcharts v10.3.3 (latest)

#### Affected browser(s)
Tested  version 109.0.5414.119 (arm64)

### PR DESCRIPTION
**Pull request by jakubjanuchta**
Fixed #18435, tooltip was misplaced outside the plot area when zooming in gantt and x-range series.

### CODE REVIEW

File: ts/Core/Axis/Axis.ts [hunk 1]
```diff
@@ -2790,7 +2790,7 @@ class Axis {
             dataMin: axis.dataMin as any,
             dataMax: axis.dataMax as any,
             userMin: axis.userMin,
-            userMax: axis.userMax,
+            userMax: axis.userMax
```
Comment (jakubjanuchta) [inline ts/Core/Axis/Axis.ts:2793]: Fixed lint on master

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
