### PR TITLE
bugfix/19832-CSV-export-performance

### LINKED ISSUE #19832: CSV export performance issue
#### Expected behaviour
The CSV export should be performed almost immediately.

#### Actual behaviour
The CSV export takes approximately 5-10 seconds.

#### Live demo with steps to reproduce
Stackblitz is the only editor, where we can run the newest HC version (11.1.0) and have that amount of data without lagging the whole editor. It probably needs more investigation, and maybe it's not because of the amount but a specific data set.

https://stackblitz.com/edit/js-u8a9rx?file=package.json,chart-options.js,index.js,index.html

#### Product version
Affected from: v10.3.0
Last working: v10.2.1

Bisected to: 426f0660927742380945314cba2494dca66d70b4

### PR DESCRIPTION
**Pull request by bm64**
Fixed #19832, improved CSV export performance.

### CODE REVIEW

**Comment by TorsteinHonsi** [comment]
Thank you @bm64 !
Can you throw in some comments too? This code is quite hard to grasp, and actually some explanatory comments were removed in the PR 😬 

Also, I am curious what your benchmark show? How much of a speed improvement is this?

File: ts/Extensions/ExportData/ExportData.ts [hunk 1]
```diff
@@ -562,26 +544,41 @@ function chartGetDataRows(
...
+                        arr[i] = 0;
+                    }
+
+                    rows[key].pointers = arr;
+                    rows[key].pointers[series.index] = 1;
+                } else {
+                    const modifiedKey = `${key},${rows[key].pointers[series.index]}`,
+                        originalKey = key;
+
+                    if (rows[key].pointers[series.index]) {
```
Comment (pawelfus) [inline ts/Extensions/ExportData/ExportData.ts:561]: It took me a minute to get it. It would be nice to have a comment explaining we check here if it's a duplicate.

File: ts/Extensions/ExportData/ExportData.ts [hunk 2]
```diff
@@ -562,26 +544,41 @@ function chartGetDataRows(
...
                     rows[key] = [];
-                    // Contain the X values from one or more X axes
                     rows[key].xValues = [];
+
+                    const arr = [];
+                    for (let i = 0; i < series.chart.series.length; i++) {
+                        arr[i] = 0;
+                    }
+
+                    rows[key].pointers = arr;
```
Comment (pawelfus) [inline ts/Extensions/ExportData/ExportData.ts:555]: I would add a comment here explaining briefly the solution with pointers

**Review by pawelfus — APPROVED** [review]
Looks good, I don't see any logic errors, good job 👍 

PS: I would add some comments though, so it's easier to maintain in the future

**Comment by bm64** [comment]
@TorsteinHonsi comments added. When it comes to the benchmark, I created a demo with challenging data set for this specific issue, and the export times went from few seconds (~10s in my case) to instant.
Before: https://stackblitz.com/edit/web-platform-thrrjk?file=index.html
After: https://stackblitz.com/edit/web-platform-zju7vz?file=index.html

**Review by TorsteinHonsi — APPROVED** [review]
