### PR TITLE
bugfix/17888-plotLine-label-align

### LINKED ISSUE #17888: PlotLine labels do not appear when using align right with textAlign left
#### Expected behaviour
PlotLine label text is in DOM
PlotLine label appears to the right of the chart

#### Actual behaviour

PlotLine label text is not in DOM
PlotLine label is not appearing anywhere

#### Live demo with steps to reproduce
* Add a y-axis plotline label, with `align: 'right'` and `textAlign: 'left'`
* plotline label does not appear
* will appear if you set `useHTML: true`, or use a different the textAlign value

Demo with a working plotline label, and a missing plotline label
https://jsfiddle.net/br8ag2np/

#### Product version
Highcharts 10.2.1

### PR DESCRIPTION
**Pull request by bm64**
Fixed #17888, plot line labels with `align: 'right'` and `textAlign: 'left'` weren't displayed.

### CODE REVIEW

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks for the PR!

Unfortunately it reintroduces #15777, where the idea was that labels should not extend past their plot area.

There seems to be a conflict of interest here, so what we probably need to do is to introduce an option, `label.clip`, that is false by default to preserve the current functionality. 

Also part of this PR, we should include tests for both cases, including #15777.

File: ts/Core/Axis/PlotLineOrBand/PlotLineOrBand.ts [hunk 1]
```diff
@@ -914,6 +917,15 @@ export default PlotLineOrBand;
  * @apioption  xAxis.plotLines.label.align
  */
 
+/**
+ * Whether to hide labels that are outside the plot area.
+ *
+ * @type      {boolean}
+ * @default   false
+ * @since     next
+ * @apioption xAxis.plotLines.clip
```
Comment (TorsteinHonsi) [inline ts/Core/Axis/PlotLineOrBand/PlotLineOrBand.ts:926]: It is on`xAxis.plotLines.labels.clip`

File: ts/Core/Axis/PlotLineOrBand/PlotLineOrBand.ts [hunk 2]
```diff
@@ -345,13 +346,15 @@ class PlotLineOrBand {
             width: arrayMax(xBounds) - x,
             height: arrayMax(yBounds) - y
         });
-
         if (!label.alignValue || label.alignValue === 'left') {
+            const length = optionsLabel.clip ?
```
Comment (TorsteinHonsi) [inline ts/Core/Axis/PlotLineOrBand/PlotLineOrBand.ts:350]: Better call it `width` because that's what it reflects

File: ts/Core/Axis/PlotLineOrBand/PlotLineOrBand.ts [hunk 3]
```diff
@@ -265,6 +265,7 @@ class PlotLineOrBand {
             // apply defaults
             optionsLabel = merge({
                 align: horiz && isBand && 'center',
+                clip: false,
```
Comment (TorsteinHonsi) [inline ts/Core/Axis/PlotLineOrBand/PlotLineOrBand.ts:268]: Is this necessary? If we leave it out, it will become `undefined` by default which will still work correctly on line 350.

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
