### PR TITLE
bugfix/23338-boosted-halo-hidden

### LINKED ISSUE #23338: With boost enabled, after hiding a series, marker halo effect stops appearing
#### Expected behaviour
When hovering over a data point, the marker halo effect should appear (assuming it's enabled).

#### Actual behaviour
If boost is enabled and active, halo effects will show up as expected. However, if there are multiple series, and you hide one via the legend, the halo effect stops working for the remaining series.

The halo effect starts working again when you un-hide that first hidden series. This could be restoring everything to visibility, but it also happens if you hide everything and then show the first. So, order matters; it's not just a question of whether anything is hidden.

#### Live demo with steps to reproduce
https://jsfiddle.net/zfemvgwc/

Here, there are two series. Halo effects are enabled, and boost is forced active. If you hover over the data initially, the halo effect works.

If you hide either series, the halo effect stops working for the remaining series.

If you then re-enable that series, halo effects return.

Alternatively, if you've hidden one, if you hide the other, then enable the first, halo effects also return.

That is:

- initially working -> hide A -> broken -> show A -> working
- initially working -> hide A -> broken -> hide B -> show A -> working -> hide A -> show B -> still working

#### Product version
Highcharts 12.3.0

#### Affected browser(s)
Confirmed in Chrome and Firefox

### PR DESCRIPTION
**Pull request by MarkusBarstad**
Fixed #23338 , boosted halo was erroneously hidden

Thoughts on the unit test? is it to verbose for this?

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1210823974796477

### CODE REVIEW

File: samples/unit-tests/boost/setvisible/demo.js [hunk 1]
```diff
@@ -72,6 +59,72 @@ QUnit.test('Boosted and not boosted series - visibility', function (assert) {
     );
 });
 
+QUnit.test(
+    'Shared boost marker group stays visible for hovered series, (#23338)',
+    function (assert) {
+        const chart = Highcharts.chart('container', {
+            boost: {
+                enabled: true,
```
Comment (magdalena-gut) [inline samples/unit-tests/boost/setvisible/demo.js]: It’s the default, so it can be removed

File: samples/unit-tests/boost/setvisible/demo.js [hunk 2]
```diff
@@ -72,6 +59,72 @@ QUnit.test('Boosted and not boosted series - visibility', function (assert) {
...
+                allowForce: true
+            },
+            plotOptions: {
+                series: {
+                    boostThreshold: 1,
+                    marker: {
```
Comment (magdalena-gut) [inline samples/unit-tests/boost/setvisible/demo.js]: makrer options are default, so can be removed

**Review by magdalena-gut — CHANGES_REQUESTED** [review]
Works well - just small nits. The test coverage looks good to me as well.

**Review by magdalena-gut — APPROVED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
Thanks, looks good!
