### PR TITLE
bugfix/21299-navigator-postion-incorrect

### LINKED ISSUE #21299: Navigator position is incorrect
#### Expected behaviour
Distance between the axis and navigator should be equal to the value set in config.

#### Actual behaviour
Navigator overlaps the xAxis when margin is set to 0.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/n1rvwet9/

#### Product version
Stock 11.4.3

Broken since 11.0.0, worked fine in 10.3.3
Bisected to https://github.com/highcharts/highcharts/commit/0480dc0c204b25a48a851d93bd12aec3720dc2e0

### PR DESCRIPTION
**Pull request by AndrzejBuleczka**
Fixed https://github.com/highcharts/highcharts/issues/21299, scrollbar and navigator margin settings were incorrect.

### CODE REVIEW

File: ts/Stock/Navigator/Navigator.ts [hunk 1]
```diff
@@ -1503,8 +1503,10 @@ class Navigator {
                 chart.options.scrollbar,
                 { vertical: chart.inverted }
             );
-            if (!isNumber(options.margin) && navigator.navigatorEnabled) {
-                options.margin = chart.inverted ? -3 : 3;
+            if (navigator.navigatorEnabled) {
+                if (!isNumber(options.margin)) {
+                    options.margin = chart.inverted ? -3 : 3;
+                }
```
Comment (kamil-musialowski) [inline ts/Stock/Navigator/Navigator.ts:1509]: Can we do it that way?

```suggestion
            if (navigator.navigatorEnabled && !isNumber(options.margin)) {
                  options.margin = chart.inverted ? -3 : 3;
```

**Review by kamil-musialowski — CHANGES_REQUESTED** [review]
One small comment for start 🤔 

@pawelfus Are we cool with such visual diff?

File: ts/Stock/Navigator/Navigator.ts (hunk 1 above)
Comment (AndrzejBuleczka) [reply ts/Stock/Navigator/Navigator.ts:1509]: pewnie!

**Review by kamil-musialowski — CHANGES_REQUESTED** [review]
Lint error :)

**Comment by kamil-musialowski** [comment]
@AndrzejBuleczka also have a look at the contribution guide https://github.com/highcharts/highcharts/blob/master/CONTRIBUTING.md and change the title to something more descriptive, as it will be visible in the [changelog](https://www.highcharts.com/blog/changelog/) later.

I.e the message in the PR should look like this:
Fixed https://github.com/highcharts/highcharts/issues/21299, scrollbar and navigator margin settings were incorrect.

**Review by kamil-musialowski — CHANGES_REQUESTED** [review]
See comment above

**Review by pawelfus — CHANGES_REQUESTED** [review]
That's a lot of visual changes - we should avoid that, as described in https://github.com/highcharts/highcharts/issues/21299#issuecomment-2382918264

**Comment by AndrzejBuleczka** [comment]
Thanks @pawelfus for the comments, I added tests, and as for the visual changes, I don't see how this can be fixed without it, and am more than open for suggestions in this respect. The core issue was that the scrollbar margin was not counted into spacing calculation for the navigator group, so the fix causes the minimal shift of the whole navigator group.

**Comment by AndrzejBuleczka** [comment]
Setting default margin to 22 does the trick, thanks @pawelfus!

**Review by pawelfus — CHANGES_REQUESTED** [review]
Thanks! How about the margin when the navigator is disabled, but scrollbar enabled? Please take a look at the remainder of the visual differences.

**Comment by AndrzejBuleczka** [comment]
With the kind help of @kamil-musialowski I've spotted one inconsistent bit about standalone scrollbar margin and we fixed it, the remaining visual differences seem to be expected and are caused by the changes introduced.

File: ts/Stock/Navigator/Navigator.ts [hunk 2]
```diff
@@ -1497,13 +1497,13 @@ class Navigator {
 
 
         // Initialize the scrollbar
-        if ((chart.options.scrollbar as any).enabled) {
+        if (chart.options.scrollbar?.enabled) {
```
Comment (kamil-musialowski) [inline ts/Stock/Navigator/Navigator.ts:1500]: You've even managed to find another one - good job! 🎊

**Review by kamil-musialowski — APPROVED** [review]
I think we have it, nice!

File: ts/Stock/Navigator/Navigator.ts (hunk 2 above)
Comment (AndrzejBuleczka) [reply ts/Stock/Navigator/Navigator.ts:1500]: Learning from the best 😄

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
