### PR TITLE
bugfix/23011-toolbar-missing-aria-labels

### LINKED ISSUE #23011: Missing `aria-labels` for Stock Tools buttons
#### Expected behaviour
Descriptive aria-labels are visible by screen readers for each Stock Tools button.

#### Actual behaviour
All buttons are read out as "button" or "clickable button", without any descriptive information or label.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/pu48nwg7/

#### Product version
Since introduction of Stock Tools (v7.0.0+)

Image

### PR DESCRIPTION
**Pull request by DJTechnoo**
Fixed #23011, missing aria labels in stock toolbar.

### CODE REVIEW

File: ts/Stock/StockTools/StockToolbar.ts [hunk 1]
```diff
@@ -31,6 +31,7 @@ import type {
 import U from '../../Core/Utilities.js';
 import AST from '../../Core/Renderer/HTML/AST.js';
 import StockToolsUtilities from './StockToolsUtilities.js';
+import HTMLAttributes from '../../Core/Renderer/HTML/HTMLAttributes';
```
Comment (pawelfus) [inline ts/Stock/StockTools/StockToolbar.ts]: Import type only

File: ts/Stock/StockTools/StockToolbar.ts [hunk 2]
```diff
@@ -537,8 +542,10 @@ class Toolbar {
         // Toolbar
         this.toolbar = toolbar = createElement('ul', {
             className: 'highcharts-stocktools-toolbar ' +
-                    guiOptions.toolbarClassName
-        });
+                    guiOptions.toolbarClassName,
+            role: 'group',
+            ariaLabel: 'Stock chart tools'
```
Comment (pawelfus) [inline ts/Stock/StockTools/StockToolbar.ts]: I think it should be configurable, similar to https://api.highcharts.com/highstock/lang.accessibility.rangeSelector and https://api.highcharts.com/highstock/lang.accessibility.navigator

Comment (pawelfus) [reply ts/Stock/StockTools/StockToolbar.ts]: The same about the other options

**Review by pawelfus — CHANGES_REQUESTED** [review]
Thanks! Minor changes only needed

File: ts/Stock/StockTools/StockToolbar.ts [hunk 3]
```diff
@@ -372,30 +373,36 @@ class Toolbar {
...
         }, void 0, target);
 
         // Single button
         const elementType = (btnOptions.elementType || 'button') as string;
         const mainButton = createElement(elementType, {
-            className: 'highcharts-menu-item-btn'
-        }, void 0, buttonWrapper);
+            className: 'highcharts-menu-item-btn',
+            ariaLabel: btnLabelName,
+            tabindex: 0
```
Comment (jedrzejruta) [inline ts/Stock/StockTools/StockToolbar.ts]: It would be nice to also add here the `aria-expanded: false` attribute.  Then, in the `addSubmenu` function, toggle this attribute on click event (below line 213).

File: ts/Stock/StockTools/StockToolbar.ts
Comment (jedrzejruta) [inline ts/Stock/StockTools/StockToolbar.ts]: Here you could also add the `id` for the `submenuWrapper`.

Comment (jedrzejruta) [inline ts/Stock/StockTools/StockToolbar.ts:209]: And then the `aria-controls` attribute can be set for `submenuArrow` with something like this:
`submenuArrow.setAttribute('aria-controls', submenuWrapper.id);`

Comment (jedrzejruta) [inline ts/Stock/StockTools/StockToolbar.ts:216]: Here, you can toggle the submenu's arrow 'aria-expanded' attribute.

File: ts/Stock/StockTools/StockToolbar.ts [hunk 4]
```diff
@@ -199,18 +200,22 @@ class Toolbar {
...
             allButtons = this.toolbar.childNodes,
+            title = buttonWrapper.title,
             // Create submenu container
             submenuWrapper = this.submenu = createElement('ul', {
-                className: 'highcharts-submenu-wrapper'
-            }, void 0, buttonWrapper);
+                className: 'highcharts-submenu-wrapper',
+                id: 'highcharts-submenu-wrapper-' +
+                    title.toLowerCase().replace(/\s+/g, '-'),
+                role: 'menu'
```
Comment (jedrzejruta) [inline ts/Stock/StockTools/StockToolbar.ts]: After further checking, it seems that adding `role = menu` can be more confusing, as it requires additional  event handling: https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/examples/disclosure-navigation/. I know that this implementation has been based on the workaround, however it turns out that most screen readers should pickup automatically via correct semantics that it's a group of items.

File: ts/Stock/StockTools/StockToolbar.ts [hunk 5]
```diff
@@ -372,30 +380,38 @@ class Toolbar {
...
         }, void 0, target);
 
         // Single button
         const elementType = (btnOptions.elementType || 'button') as string;
         const mainButton = createElement(elementType, {
-            className: 'highcharts-menu-item-btn'
-        }, void 0, buttonWrapper);
+            className: 'highcharts-menu-item-btn',
+            ariaLabel: btnLabelName,
+            tabindex: 0,
```
Comment (jedrzejruta) [inline ts/Stock/StockTools/StockToolbar.ts]: Since we're using a button, we can safely get rid of tabIndex: https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes/tabindex?utm_source=chatgpt.com#accessibility_concerns

File: ts/Stock/StockTools/StockToolbar.ts [hunk 6]
```diff
@@ -372,30 +380,38 @@ class Toolbar {
...
+            role: 'menuitem'
```
Comment (jedrzejruta) [inline ts/Stock/StockTools/StockToolbar.ts]: Similarly as with `role=menu`, it's better to remove it and leave default aria implementation.

File: ts/Stock/StockTools/StockToolbar.ts [hunk 7]
```diff
@@ -537,8 +556,10 @@ class Toolbar {
         // Toolbar
         this.toolbar = toolbar = createElement('ul', {
             className: 'highcharts-stocktools-toolbar ' +
-                    guiOptions.toolbarClassName
-        });
+                    guiOptions.toolbarClassName,
+            role: 'group',
```
Comment (jedrzejruta) [inline ts/Stock/StockTools/StockToolbar.ts]: I'm not certain about this one either. It seems that if I remove it, the screen reader automatically pickups that it's a group of _x_ elements and displays it, whereas with `role=group` set, this information is gone. What do you think?

File: ts/Accessibility/Options/LangOptions.d.ts [hunk 8]
```diff
@@ -18,6 +18,7 @@
  * */
 
 import type { LangOptions } from '../../Core/Options';
+import { LangStockToolsOptions } from '../../Stock/StockTools/StockToolsOptions';
```
Comment (PaulDalek) [inline ts/Accessibility/Options/LangOptions.d.ts]: Should be imported as a type.

File: ts/Stock/StockTools/StockToolbar.ts (hunk 7 above)
Comment (DJTechnoo) [reply ts/Stock/StockTools/StockToolbar.ts]: Note regarding all the changes: Removing all the roles caused some side-effects, such as duplicate readouts (caused by title interference + aria-label).

In order to keep the tooltip on hover and reliable aria readouts, they have been combined and moved one level deeper into the button itself. The reason for this move was to fix backwards tabbing. (The previous menu button  only would read "button"). 

However all of this worked before removing the roles. 🤔

Comment (jedrzejruta) [reply ts/Stock/StockTools/StockToolbar.ts]: That's really strange, thanks for explaining this bit. Seems to work fine now!
