### PR TITLE
bugfix/24097-fixed-dendrogram-demo

### LINKED ISSUE #24097: Labels with SVG are not exported
#### Expected behaviour
Exported image the same as the viewed chart.

#### Actual behaviour
SVG in labels are not exported - missing.

#### Live demo with steps to reproduce
https://www.highcharts.com/demo/highcharts/dendrogram

The lack of bears is visible as:
Image

_Internal note:_
This might be also related to the lack of these SVG in the demo thumbnail.

#### Product version
Highcharts Core v12.5.0

#### Tested browser(s)
Chrome

### PR DESCRIPTION
**Pull request by AndrzejBuleczka**
Fixed #24097, added the missing XML namespace to inline SVGs within HTML data labels to prevent them from being stripped during export.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1213011827479336

### CODE REVIEW

File: samples/highcharts/demo/dendrogram/demo.ts [hunk 1]
```diff
@@ -14,10 +40,51 @@ const treeData = [
...
-    e[0], e[1], e[2], e[3], e[4], // Pass these through as is
-    typeof e[5] === 'string' && document.getElementById(e[5]).innerHTML // icon
-]);
+].map(e => {
+    const iconString = icons[e[5] as keyof typeof icons];
+    let iconURI = '';
+
+    if (iconString) {
+    // 1. Strip invisible line breaks to prevent encoding corruption
+        let styledSVG = iconString.replace(/\r?\n|\r/g, '');
```
Comment (KacperMadej) [inline samples/highcharts/demo/dendrogram/demo.ts]: Firstly, in general, replace once and use that as the initial data to reduce not needed processing. Secondly, this seems to be already done, so this replace should possible to be safely removed (`/\r?\n|\r/.test(iconString)` returns `false` for me for all).

File: samples/highcharts/demo/dendrogram/demo.ts [hunk 2]
```diff
@@ -14,10 +40,51 @@ const treeData = [
...
+        `;
+
+        styledSVG = styledSVG.replace(
+            /<svg([^>]*)>/,
+            `<svg$1 xmlns="http://www.w3.org/2000/svg">${inlineStyles}`
+        );
+
+        // 4. Safely encode to URI
+        iconURI =
+      'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(styledSVG);
```
Comment (KacperMadej) [inline samples/highcharts/demo/dendrogram/demo.ts]: Indentation for this line is wrong. Indent better or move back up and break after `+`.

File: samples/highcharts/demo/dendrogram/demo.ts [hunk 3]
```diff
@@ -1,3 +1,29 @@
...
+};
+
+Highcharts.AST.bypassHTMLFiltering = true;
```
Comment (KacperMadej) [inline samples/highcharts/demo/dendrogram/demo.ts]: `bypassHTMLFiltering` should not be used for demos that do not explicitly demonstrate usage of `bypassHTMLFiltering`.

**Comment by AndrzejBuleczka** [comment]
Hi @KacperMadej , thanks for feedback. I've reverted all the workarounds inside the demo files so it remains clean. I focused entirely on the internal code.
The root cause of the missing SVGs was an XML namespace inheritance issue when `sanitizeSVG` wraps `useHTML` content in a <foreignObject>. I've applied a native regex fix in `Exporting.ts` to inject the SVG namespace, which successfully stops the export server from stripping the labels.
(Note: Since the demo uses external CSS classes like `.icon-dark` within `useHTML`, the exported labels naturally render with fallback solid colors since `inlineStyles()` doesn't deep-parse external stylesheets for foreign objects - but the core issue of the SVGs dropping out completely is now resolved natively).
