### PR TITLE
bugfix/15362-cleaning-indicators-params-docs

### LINKED ISSUE #15362: Stocktools indicator popup - unnecessary params for some indicators
#### Expected behaviour
Remove the `index` and `period` parameter from Stocktools (possibly also from documentation)
for indicators that don't use them.

#### Actual behaviour
For some indicators, there is an option inside the Stocktools indicator popup to add the `index` and `period` parameter.
Where some indicators like for example VBP doesn't need those.

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/stock-tools-gui
https://api.highcharts.com/highstock/series.ad.params

#### Product version
 Highstock JS v9.0.1 (2021-02-15)

#### Affected browser(s)
All

_Inernal note:_
Go through each indicator file, check listed `params` and compare them with Stocktools and documentation (add `excluding`).

### PR DESCRIPTION
**Pull request by raf18seb**
Fixed #15362, corrected API and Stock Tools popup list of indicators' params.

#### Upgrade note
The default value of [linearregression.params.xAxisUnit](https://api.highcharts.com/highstock/plotOptions.linearregression.params.xAxisUnit) has been changed from `undefined` to `null`.

### CODE REVIEW

File: ts/Stock/Indicators/LinearRegression/LinearRegression.ts [hunk 1]
```diff
@@ -108,7 +108,7 @@ class LinearRegressionIndicator extends SMAIndicator {
                  * @type    {number}
                  * @product highstock
                  */
-                xAxisUnit: void 0
+                xAxisUnit: null
```
Comment (pawelfus) [inline ts/Stock/Indicators/LinearRegression/LinearRegression.ts:111]: Please change the doclet to inform users about `null` value above:

```
                 * Default value is the closest distance between two data
                 * points.
```
And change type in doclet: `@type    {number}`


Additionally, add an upgrade note (see 4th point: https://github.com/highcharts/highcharts/tree/master/changelog#writing-content-for-the-changelog )

**Review by pawelfus — CHANGES_REQUESTED** [review]
Looks great! Just one minor thing:

File: ts/Stock/Indicators/Chaikin/ChaikinIndicator.ts [hunk 2]
```diff
@@ -73,9 +73,10 @@ class ChaikinIndicator extends EMAIndicator {
          * Paramters used in calculation of Chaikin Oscillator
          * series points.
          *
-         * @excluding index, period
+         * @excluding index
```
Comment (karolkolodziej) [inline ts/Stock/Indicators/Chaikin/ChaikinIndicator.ts:76]: If we're giving users the ability to change the `period`, we should inform them where this parameter is used.
Based on the `ChainkinIndicator.ts` this value is only used for `AD` calculation.
``` TS
        ADL = AD.prototype.getValues.call(this, series, {
            volumeSeriesID: params.volumeSeriesID,
            period: period
        }) as IndicatorValuesObject<TLinkedSeries>;

```
This information should be included in the API. My suggestion: 
```
Parameter used indirectly for calculating the accumulation/distribution indicator.  
Decides about the number of data points that are taken into account for the indicator calculations.
```

**Review by karolkolodziej — CHANGES_REQUESTED** [review]
Apart from one minor thing, it looks good!

File: ts/Stock/Indicators/Momentum/MomentumIndicator.ts [hunk 3]
```diff
@@ -67,11 +67,8 @@ class MomentumIndicator extends SMAIndicator {
      * @requires     stock/indicators/momentum
      * @optionparent plotOptions.momentum
      */
-    public static defaultOptions: MomentumOptions = merge(SMAIndicator.defaultOptions, {
-        params: {
-            period: 14
-        }
-    } as MomentumOptions);
+    public static defaultOptions: MomentumOptions =
+    merge(SMAIndicator.defaultOptions, {} as MomentumOptions);
```
Comment (pawellysy) [inline ts/Stock/Indicators/Momentum/MomentumIndicator.ts:71]: Is th `merge` function needed here? 
couldn't it be just 
`public static defaultOptions = SMAIndicator.defaultOptions as MomentumOptions`

**Review by pawellysy — CHANGES_REQUESTED** [review]
See comment

File: ts/Stock/Indicators/Momentum/MomentumIndicator.ts (hunk 3 above)
Comment (raf18seb) [reply ts/Stock/Indicators/Momentum/MomentumIndicator.ts:71]: Unfortunately, it generates an error ```code tagged with @optionparent must be an object``` when generating API. I'm leaving it as it is.

Comment (pawelfus) [reply ts/Stock/Indicators/Momentum/MomentumIndicator.ts:71]: FYI @bre1470

Comment (bre1470) [reply ts/Stock/Indicators/Momentum/MomentumIndicator.ts:71]: This is correct, it creates a clone and also follows the pattern for JSDoc.

Comment (raf18seb) [reply ts/Stock/Indicators/Momentum/MomentumIndicator.ts]: Anyway, it's resolved now, because I'm not merging an empty object anymore.

File: ts/Stock/Indicators/LinearRegression/LinearRegression.ts [hunk 4]
```diff
@@ -82,8 +82,8 @@ class LinearRegressionIndicator extends SMAIndicator {
                  * computing the slope and the intercept. This may enchance the
                  * legiblitity of the indicator's values.
                  *
-                 * Default value is the closest distance between two data
-                 * points.
+                 * In `v9.0.2`, the default value has been changed
+                 * from `undefined` to `null`.
```
Comment (pawelfus) [inline ts/Stock/Indicators/LinearRegression/LinearRegression.ts:86]: Please, keep the explanation how default value (null) works :)

**Review by pawelfus — CHANGES_REQUESTED** [review]
Nice! 
Just a minor thing

**Review by karolkolodziej — APPROVED** [review]

**Review by pawelfus — APPROVED** [review]
Nothing to add, thanks! :)

**Review by pawellysy — APPROVED** [review]
Nothing to add 👍

**Review by TorsteinHonsi — APPROVED** [review]
