### PR TITLE
bugfix/23728-axis-breaks-outside-data-range

### LINKED ISSUE #23728: Y-axis breaks don't shift points
#### Expected behaviour
The sections specified in the breaks should be omitted, causing all data points to shift closer together.

#### Actual behaviour
The breaks are applied, but the data points are not shifted closer together as expected.

#### Live demo with steps to reproduce
Bad: https://jsfiddle.net/BlackLabel/u94qrh1b/
Fine: https://jsfiddle.net/BlackLabel/oq62j19m/

#### Product version
Highcharts 12.4.0

#### Affected browser(s)
All

### PR DESCRIPTION
**Pull request by kamil-musialowski**
Fixed #23728, axis breaks were rendered incorrectly when there were no points in them.

### CODE REVIEW

**Review by PaulDalek — APPROVED** [review]
Looks and works well, nice one!

**Review by jedrzejruta — APPROVED** [review]
LGTM!

File: ts/Core/Axis/BrokenAxis.ts [hunk 1]
```diff
@@ -948,21 +935,31 @@ namespace BrokenAxis {
...
 
-                                    while (start - repeat > dataMin) {
+                                    while (
+                                        isNumber(min) &&
+                                        start - repeat > min
+                                    ) {
                                         start -= repeat;
                                     }
-                                    while (start < dataMin) {
+                                    while (isNumber(min) && start < min) {
```
Comment (pawelfus) [inline ts/Core/Axis/BrokenAxis.ts]: This `isNumber()` is already checked above. I've initiated benchmarks again to double-check (some of the results slower by ~7%), but I think we should improve that.

Applies to all `isNumber()`'s in PR.

**Review by pawelfus — CHANGES_REQUESTED** [review]
Looks good, I couldn't break it (tested the remove `threshold`-related code). Adding @KacperMadej - maybe there's something I'm missing still.

File: ts/Core/Axis/BrokenAxis.ts (hunk 1 above)
Comment (kamil-musialowski) [reply ts/Core/Axis/BrokenAxis.ts]: It is checked above, but since the while loop is inside function, it's in a different scope and we get TS error without the double check. 

I also didn't remove `if (isNumber(min) && isNumber(max)) {` on purpose, to not loop through breaks when min or max are not a number.

image

Comment (pawelfus) [reply ts/Core/Axis/BrokenAxis.ts]: Right! min/max are mutable variables (`let`). Could you try narrowing it down to const? Like this:

```ts
                        if (isNumber(min) && isNumber(max)) {
                            const minVal = min,
                                maxVal = max;
                            breaks.forEach(
                                function (brk): void {
                                    start = brk.from;
                                    repeat = brk.repeat || Infinity;

                                    while (
                                        start - repeat > minVal
                                    ) {
                                        start -= repeat;
                                    }
```

Comment (kamil-musialowski) [reply ts/Core/Axis/BrokenAxis.ts]: I've tried that approach before but I wasn't sure if I want to introduce two consts just for this purpose. But if you are fine with it, then we can go with that solution.

Comment (pawelfus) [reply ts/Core/Axis/BrokenAxis.ts]: That is a very good concern (size of the lib vs performance). I personally favor performance, when it comes to a few bytes. If the alternative were hundreds of lines long, I’d rather keep the less performant solution.

**Review by pawelfus — APPROVED** [review]
Thanks!

**Review by DJTechnoo — APPROVED** [review]
Good job! 🎉

**Review by KacperMadej — CHANGES_REQUESTED** [review]
The changes will cause a regression of https://github.com/highcharts/highcharts/issues/13898

In the top demo of that issue - https://jsfiddle.net/a7uwqjpc/19/
Steps:
- scroll the chart to the very bottom
- collapse "Develop"
- collapse "Design"
Now, you should still be seeing 4 rows ("Planning" and its sub-task "Requirements"), but the chart collapses into 2 rows.

There are also other other ways to get that chart to change the height but those stapes seem fastest and simplest.

File: ts/Core/Axis/BrokenAxis.ts [hunk 2]
```diff
@@ -948,21 +935,26 @@ namespace BrokenAxis {
                         }
 
                         // Construct an array holding all breaks in the axis
-                        // for the current data range.
-                        if (isNumber(dataMin) && isNumber(dataMax)) {
+                        // for the current data range. Use min and max instead
+                        // of dataMin and dataMax to ensure that the breaks are
+                        // constructed correctly even if break happens outside
+                        // the data range, #23728.
```
Comment (KacperMadej) [inline ts/Core/Axis/BrokenAxis.ts]: Nitpicking: Isn't the added sentence in opposition to the 1st one? With the changes there's no "current data range" limitation for the breaks.

Comment (KacperMadej) [reply ts/Core/Axis/BrokenAxis.ts]: This is related to what breaks the breaks (or makes the broken axis broken - pick your favourite pun). Your change to `min, max` makes the processed range smaller than data range after zoom. Gantt's treegrid breaks logic requires for the breaks set on the data to be applied even when that break lands outside of the axis `min, max`. I'm guessing the axis range that will work for both should be the biggest set out of `min, max, dataMin, dataMax`, but I haven't tested this, so just a guess.

Comment (KacperMadej) [reply ts/Core/Axis/BrokenAxis.ts]: @kamil-musialowski Tested both ([collapsable gantt](https://jsfiddle.net/a7uwqjpc/19/) and [the relevant](https://jsfiddle.net/BlackLabel/u94qrh1b/)) and seems ok  -https://github.com/highcharts/highcharts/commit/f61757f4e3913b9d629a68182051cbd08cd08f01 .

Comment (kamil-musialowski) [reply ts/Core/Axis/BrokenAxis.ts]: Thank you for checking everything, I have implemented your solution, tested manually and everything seems to be okay!

**Review by KacperMadej — APPROVED** [review]
👍

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
