### PR TITLE
Fixed #24225, allowMutatingData = false and soft update

### LINKED ISSUE #24225: Animated data update fails when allowMutatingData is false
#### Expected behaviour
Smooth, animated updates [like when allowMutatingData is true](https://jsfiddle.net/highcharts/fc2w5Lte/4/)

#### Actual behaviour
The columns jump to the new position. Under the hood, all points are scrapped and new ones built, instead of updating existing points. 

#### Live demo with steps to reproduce
https://jsfiddle.net/highcharts/fc2w5Lte/5/

#### Product version
Probably ever since `allowMutatingData` was introduced

### PR DESCRIPTION
**Pull request by TorsteinHonsi**
Fixed #24225, animated data updates didn't work when `chart.allowMutatingData` was false

### CODE REVIEW

File: ts/Core/Series/Point.ts [hunk 1]
```diff
@@ -628,9 +628,16 @@ class Point {
...
-        point.options = point.options ?
-            extend(point.options, options as any) :
-            options;
+        // If we're updating, extend or merge existing options. If we're not
+        // allowed to mutate, merge new data into existing and return a copy,
+        // because `point.options` is a reference to `options.data[i]`.
+        if (point.options) {
+            point.options = series.chart.options.chart.allowMutatingData ?
+                extend(point.options, options as any) :
+                merge(point.options, options as any);
```
Comment (KamilKubik) [inline ts/Core/Series/Point.ts]: Looks like we can avoid `as any` here.

```suggestion
                extend(point.options, options) :
                merge(point.options, options);
```

Comment (TorsteinHonsi) [reply ts/Core/Series/Point.ts]: Nice!
