### PR TITLE
bugfix/20886-map-drilldown-mouse-tracking

### LINKED ISSUE #20886: Missing `hover` and `click` events after drilling down the map
#### Actual behaviour

Steps to reproduce the issue:
1. A user is able to drill down any country from the map by clicking its data label, e.g **Denmark** on the demo below
2. After drilling down and getting back up to the first level it's no longer possible to hover the country & drill down by clicking the data label. 

#### Live demo with steps to reproduce

https://www.highcharts.com/demo/maps/map-drilldown-preloaded

#### Product version
v11.4.0

#### Affected browser(s)
Chrome v122.0.6261.129

### PR DESCRIPTION
**Pull request by Xillez**
Fixed #20886, data labels mouse event tracking was broken after drill up

~~Fixed #20886, maps: datalabels mouse event tracking broken after drillup~~

---

Asana task: https://app.asana.com/0/1204848917817812/1206886636865116/f

### CODE REVIEW

File: samples/unit-tests/maps/drilldown/demo.js [hunk 1]
```diff
@@ -359,3 +359,84 @@ QUnit.test('Map drilldown animation for GeoJSON maps', async assert => {
...
+
+        setTimeout(() => {
+            chart.drillUp();
+
+            setTimeout(() => {
+                assert.ok(
+                    chart.series[0].dataLabelsGroup
+                        .hasClass('highcharts-tracker'),
+                    'Data label group should have tracking after drillup.'
+                );
```
Comment (hubertkozik) [inline samples/unit-tests/maps/drilldown/demo.js:436]: Do we need an entirely new test (QUnit) for checking only one class on the data labels group? I think we can use the existing test from above and put this `assert` somewhere there.

**Review by hubertkozik — CHANGES_REQUESTED** [review]

File: samples/unit-tests/maps/drilldown/demo.js (hunk 1 above)
Comment (Xillez) [reply samples/unit-tests/maps/drilldown/demo.js:436]: After having fiddled with this for a while I think it's better to have it as a separate test, as the above tests are rather convoluted and have tons of stuff going on at different times (like turning off animations so on).
I have to have the animation on (cause that's when the issue occurs) so that also limits the test's I can modify.

FYI, I test two things here, that tracking has been turned off when it should be (before drillup and before the mapChart has re-rendered) and that tracking has been applied after rendering.

Comment (hubertkozik) [reply samples/unit-tests/maps/drilldown/demo.js]: Ok! Now, after the last commit I can some some commented tests, is this desired or overlooked?

**Comment by Xillez** [comment]
sorry, screwed up the commit, will reset and re-push

**Review by hubertkozik — APPROVED** [review]

File: samples/unit-tests/maps/drilldown/demo.js [hunk 2]
```diff
@@ -359,3 +359,91 @@ QUnit.test('Map drilldown animation for GeoJSON maps', async assert => {
         TestUtilities.lolexUninstall(clock);
     }
 });
+
+QUnit.test(
+    '#20886, Map drilldown datalabel mouse tracking',
+    async assert => {
+        const world = await fetch(
+                'https://code.highcharts.com/mapdata/custom/world-continents.geo.json'
```
Comment (KacperMadej) [inline samples/unit-tests/maps/drilldown/demo.js:367]: Issues with testing .topo.json maps on drill down due to animation should be a separate issue that could be fixed if reported. I am adding this comment to find this in the future if needed.

**Review by KacperMadej — APPROVED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
