### PR TITLE
bugfix/22235-geoheatmap-decimal-issues

### LINKED ISSUE #22235: GeoHeatMap not getting drawn for decimal lat lng
#### Expected behaviour
geoHeapMap should show for decimal lat lng also.

#### Actual behaviour
geoHeapMap only showing for integer lat lng .
#### Live demo with steps to reproduce

https://jsfiddle.net/AnandKumbar1098/r3cywmuj/7/
above the link in which geoheatmap is not getting showed , but if change the lat lng from decimal to integer it works.
please Fix i have a requirement where we need to draw heatmap with decimal lat lng

#### Product version
Latest

#### Affected browser(s)
chrome , edge

### PR DESCRIPTION
**Pull request by MarkusBarstad**
Fixed #22235, decimal lon/lat values were not handled correctly

Note that this doesnt "solve" the users problem by itself, he will still be required to set colsize/rowsize as suggested here: https://github.com/highcharts/highcharts/issues/22235#issuecomment-2616053253

This simply is intended to add the desired behavior as described in the post linked above.

It is still desirable to have a colsize/rowsize that is close to the spacing of the datapoints for this rounding to help things.

I have also attempted to optimize the rendering a bit, unsure if this has been noticably succesful, and might detract from readability.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208864527093775

### CODE REVIEW

File: ts/Series/GeoHeatmap/GeoHeatmapSeries.ts [hunk 1]
```diff
@@ -355,27 +359,58 @@ class GeoHeatmapSeries extends MapSeries {
...
+                            unEvenLat ?
+                                (lat: number): number => (
+                                    Math.round(lat / colsize) * colsize
+                                ) :
+                                (lat: number): number => lat
+                        ),
+                        pointsLen = points.length;
+
+                    if (unEvenLon || unEvenLat) {
+                        error(
```
Comment (goransle) [inline ts/Series/GeoHeatmap/GeoHeatmapSeries.ts:387]: I think maybe we should add a `Highcharts warning:` (or similar) and possibly also the values here. Looks like `error` has a params parameter that prints like this:

image

File: ts/Series/GeoHeatmap/GeoHeatmapSeries.ts [hunk 2]
```diff
@@ -340,12 +341,15 @@ class GeoHeatmapSeries extends MapSeries {
...
             if (canvas && ctx && colorAxis && topLeft && bottomRight) {
-                const dimensions = {
-                    x: topLeft.x,
-                    y: topLeft.y,
-                    width: bottomRight.x - topLeft.x,
-                    height: bottomRight.y - topLeft.y
-                };
+                const
+                    { x, y } = topLeft,
+                    [width, height] = [bottomRight.x - x, bottomRight.y - y],
```
Comment (goransle) [inline ts/Series/GeoHeatmap/GeoHeatmapSeries.ts:346]: This array deconstruction seems a bit unnecessary (now that I look at it again)

File: ts/Series/GeoHeatmap/GeoHeatmapSeries.ts [hunk 3]
```diff
@@ -355,27 +359,65 @@ class GeoHeatmapSeries extends MapSeries {
...
+                    // Needed for tooltip
+                    series.directTouch = false;
+                    series.isDirtyCanvas = true;
 
                     // First pixelData represents the geo coordinates
-                    for (let i = 0; i < points.length; i++) {
+                    for (let i = 0; i < pointsLen; i++) {
                         const p = points[i],
-                            sourceArr = new Uint8ClampedArray(
+                            /* SourceArr = new Uint8ClampedArray(
```
Comment (goransle) [inline ts/Series/GeoHeatmap/GeoHeatmapSeries.ts:407]: This should probably be removed if not used anymore

**Review by goransle — APPROVED** [review]
LGTM 👍

**Review by TorsteinHonsi — APPROVED** [review]
Thanks, looks good!

We won't get full support for interpolation of random locations until we implement it in WebGPU or WebGL.
