### PR TITLE
bugfix/21775-shrinking-chart

### LINKED ISSUE #21775: Chart is shrinking with every re-render.
#### Expected behaviour
Chart should have the same height after rerender.

#### Actual behaviour
Chart is shrinking until it becomes 0.

#### Additional Information

- I am using `highcharts/highstock` with `highcharts-react-official`.
- Shrinking happens whenever the chart is re-rendered due to changes to the `series`, panning, zooming, etc.
- I am passing custom `series`, `xAxis` and `yAxis` to the `navigator`.
- It works as expected if `navigator` is disabled or if the `series` property of the `navigator`  is not assigned.
- It also happens if I pass empty array to the `series` property of the `navigator`.

#### Live demo with steps to reproduce
Screenshot 2024-09-03 at 13 54 38
Screenshot 2024-09-03 at 13 54 46

#### Product version
11.4.8 (It works fine for any version <11.4.8)

#### Affected browser(s)
google, firefox

### PR DESCRIPTION
**Pull request by DJTechnoo**
Fixed #21775, toggling navigator would shrink the chart.

### CODE REVIEW

File: ts/Stock/Navigator/Navigator.ts [hunk 1]
```diff
@@ -868,7 +854,7 @@ class Navigator {
         };
 
         // Add shades and handles mousedown events
```
Comment (pawelfus) [inline ts/Stock/Navigator/Navigator.ts]: Incorrect comment

**Review by pawelfus — CHANGES_REQUESTED** [review]
Looks good! Just a tine thing to fix

File: ts/Stock/Navigator/Navigator.ts [hunk 2]
```diff
@@ -895,6 +882,35 @@ class Navigator {
...
+
+    /**
+     * Set up the mouse and touch events for the shades and handles only.
+     *
+     * @private
+     * @function Highcharts.Navigator#addShadesAndHandelsEvents
+     */
+    public addShadesAndHandlesEvents(): void {
+        this.shadesAndHandlesEventsToUnbind = this.getPartsEvents('mousedown'),
+        this.shadesAndHandlesEventsToUnbind.concat(
```
Comment (PaulDalek) [inline ts/Stock/Navigator/Navigator.ts:893]: Shouldn't this be as follows?

```
this.shadesAndHandlesEventsToUnbind = this.shadesAndHandlesEventsToUnbind.concat(
  this.getPartsEvents('touchstart')
);
```

With the `concat` array is copied, so the `this.shadesAndHandlesEventsToUnbind` won't be modified with the current approach. You can also use `push` instead.

**Review by PaulDalek — CHANGES_REQUESTED** [review]
Great one! Only found one thing.

File: ts/Stock/Navigator/Navigator.ts [hunk 3]
```diff
@@ -525,25 +525,11 @@ class Navigator {
                             ['left', 'right'][index]
                         ).add(navigatorGroup);
 
-                    navigator.addMouseEvents();
+                    // Remove old events:
+                    navigator.removeShadesAndHandlesEvents();
+                    // Re-add the events with new elements:
+                    navigator.addShadesAndHandlesEvents();
                 // If the navigator symbol changed, update its path and name
```
Comment (jedrzejruta) [inline ts/Stock/Navigator/Navigator.ts]: This comment seems to be invalid now, since the code part updating path and name got removed.

**Review by jedrzejruta — APPROVED** [review]
Great work - it must have been really hard to get to the bottom of this issue! 👏 

One minor thing to adjust, other than that nothing to add!

File: ts/Stock/Navigator/Navigator.ts (hunk 2 above)
Comment (DJTechnoo) [reply ts/Stock/Navigator/Navigator.ts:893]: Thanks for the suggestion! I tested this but it breaks plenty of tests, so reverted back

**Review by pawelfus — APPROVED** [review]
This is good, thanks! I love the perf improvements (seen in benchmark)!

**Review by kamil-musialowski — APPROVED** [review]
Nice one! Congrats 👏

File: ts/Stock/Navigator/Navigator.ts [hunk 4]
```diff
@@ -895,6 +879,35 @@ class Navigator {
...
             );
         }
+
+    }
+
+    /**
+     * Set up the mouse and touch events for the shades and handles only.
+     *
+     * @private
+     * @function Highcharts.Navigator#addShadesAndHandelsEvents
```
Comment (jedrzejruta) [inline ts/Stock/Navigator/Navigator.ts]: 👀 
```suggestion
     * @function Highcharts.Navigator#addShadesAndHandlesEvents
```

**Review by jedrzejruta — CHANGES_REQUESTED** [review]
One last thing 👀

File: ts/Stock/Navigator/Navigator.ts (hunk 2 above)
Comment (PaulDalek) [reply ts/Stock/Navigator/Navigator.ts:893]: Hmm, that’s weird. No actions are performed on the concatenated array, so I think this line is doing nothing, or maybe I’m missing something. Either way, it was already there before, so I guess no harm in it :).

**Review by PaulDalek — APPROVED** [review]
Thanks, approved!

**Review by jedrzejruta — APPROVED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
