### PR TITLE
bugfix/20998-axis-left-dataLabels-overflow

### LINKED ISSUE #20998: dataLabels overflow chart, when axis position is changed
#### Expected behaviour
dataLabels should be justified to be inside the plot area, in case of an overflow when axis have a non default position.

#### Live demo with steps to reproduce
Right side: https://jsfiddle.net/highcharts/as6xgo3b/
Left side: https://jsfiddle.net/highcharts/as6xgo3b/1/
Top and left sides: https://jsfiddle.net/highcharts/as6xgo3b/2/

#### Product version
HC 11.4.1

### PR DESCRIPTION
**Pull request by kamil-musialowski**
Fixed #20998, data labels overflowed the plot area when the axis position was different from default.

### CODE REVIEW

File: ts/Core/Series/DataLabel.ts [hunk 1]
```diff
@@ -846,7 +846,9 @@ namespace DataLabel {
         const chart = this.chart,
             align = options.align,
             verticalAlign = options.verticalAlign,
-            padding = dataLabel.box ? 0 : (dataLabel.padding || 0);
+            padding = dataLabel.box ? 0 : (dataLabel.padding || 0),
+            horizontalAxis = this.xAxis?.horiz ? this.xAxis :
+                this.yAxis?.horiz ? this.yAxis : void 0;
```
Comment (TorsteinHonsi) [inline ts/Core/Series/DataLabel.ts:851]:
```suggestion
            horizontalAxis = chart.inverted ? this.yAxis : this.xAxis;
```
Simpler check

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks for the PR!

Please create an issue so that in the future we can see a description and replication of the bug. Here's a demo: https://jsfiddle.net/highcharts/as6xgo3b/

Also, we need to look at the broader picture. We are now fixing the overflow on the right side of the chart. But we need to look at related configs:
* Left side: https://jsfiddle.net/highcharts/as6xgo3b/1/
* Top and left sides: https://jsfiddle.net/highcharts/as6xgo3b/2/ 
* Wider and higher axes seem to be handled correctly: https://jsfiddle.net/highcharts/as6xgo3b/3/

**Review by pawelfus — COMMENTED** [review]
Will that be a big problem to fix also overflow for bottom labels in a non-inverted chart? Like here: https://jsfiddle.net/BlackLabel/bsmxz2n3/3/ (orange labels are misplaced)

**Comment by kamil-musialowski** [comment]
I'll also have a look into that @pawelfus , thanks for reporting 😄

**Comment by kamil-musialowski** [comment]
@pawelfus Fixed 👍

**Comment by TorsteinHonsi** [comment]
Pending approval by @pawelfus
