### PR TITLE
bugfix-24073/histogram-object-array

### LINKED ISSUE #24073: Histogram: regression in 12.4.0+ — object-form points in series.data throw toPrecision error
#### Expected behaviour
•   Histogram series should accept direct data provided as an array of point objects (e.g., [{ y: 1 }, { y: 2 }]), as it did before.
•   No runtime errors should occur when using object-form points.

#### Actual behaviour
•   From v12.4.0, passing histogram data as an array of point objects throws:    
`Uncaught TypeError: can't access property "toPrecision", t is undefined`
•   Array of numbers works, and using a linked base series works. The object-form fails.

#### Live demo with steps to reproduce
•   Working in 12.3.0: https://jsfiddle.net/BlackLabel/Lq1rkbte/
•   Broken in 12.4.0: https://codepen.io/Olli-Vihervuori/pen/YPWQRZQ

Minimal config that breaks in 12.4.0+:
```
{
  "series": [
    {
      "type": "histogram",
      "data": [{ "y": 1 },{ "y": 2 },{ "y": 3 }]
    }
  ]
}
```

#### Product version
Highcharts Core v12.4.0
Last known working: v12.3.0
Bisected to: [a82cb05](https://github.com/highcharts/highcharts/commit/a82cb057a885a3cfd97f4f52f98590430de3e317)

#### Affected browser(s)
all

### PR DESCRIPTION
**Pull request by DJTechnoo**
Fixed #24073, object data in histogram caused error.

### CODE REVIEW

File: samples/unit-tests/series-histogram/histogram/demo.js [hunk 1]
```diff
@@ -1,5 +1,23 @@
...
+                    { y: 2 },
+                    { y: 3 }
+                ]
+            }
+        ]
+    });
+
+    assert.ok(
+        chart.series[0],
+        'Histogram should initialize with object data without baseseries.'
```
Comment (kamil-musialowski) [inline samples/unit-tests/series-histogram/histogram/demo.js]: Could you please add `'#24073'` here?

File: ts/Series/Histogram/HistogramSeries.ts [hunk 2]
```diff
@@ -150,6 +150,14 @@ class HistogramSeries extends ColumnSeries {
     ): void {
         let alteredData;
         if (typeof data !== 'undefined' && data.length > 0) {
+            // Support data array of objects (#24073).
+            data = data.map(function (item: number | { y: number }): number {
+                if (typeof item === 'number') {
+                    return item;
+                }
+                return item.y;
```
Comment (kamil-musialowski) [inline ts/Series/Histogram/HistogramSeries.ts]:
```suggestion
                return isNumber(item) ? item : item.y;
```

**Comment by jedrzejruta** [comment]
> I think you're on a right path, but the fix is not working quite well yet 🤕 See: https://jsfiddle.net/BlackLabel/nsor67d8/ 12.3.0 renders 3 points this branch builds only 2

@kamil-musialowski Actually 🤓

This PR resolves the issue correctly (not rendering bins when data is set as object), however it seems that this might be another regression introduced in v12.4.0, where the number of bins is calculated differently. https://jsfiddle.net/BlackLabel/q1rk4ecx/

File: ts/Series/Histogram/HistogramSeries.ts [hunk 3]
```diff
@@ -150,6 +150,14 @@ class HistogramSeries extends ColumnSeries {
     ): void {
         let alteredData;
         if (typeof data !== 'undefined' && data.length > 0) {
+            // Support data array of objects (#24073).
+            data = data.map(function (item: number | { y: number }): number {
```
Comment (pawelfus) [inline ts/Series/Histogram/HistogramSeries.ts]: Types nitpicking:
Tricky (as always with data points) - item can be `null` or `undefined`. The same for `y`.

File: ts/Series/Histogram/HistogramSeries.ts [hunk 4]
```diff
@@ -150,6 +150,14 @@ class HistogramSeries extends ColumnSeries {
...
+                if (typeof item === 'number') {
+                    return item;
+                }
+                return item.y;
+            });
+
             alteredData = this.derivedData(
                 data.filter(isNumber),
```
Comment (pawelfus) [inline ts/Series/Histogram/HistogramSeries.ts:161]: Info: Now we have two loops: one to iterate and normalize format, then another one here to filter out duplicates. I guess it shouldn't be a performance problem for histogram data, however in general it's better to keep at minimum extra loops.
