### PR TITLE
Bugfix/11493 split tooltip 2

### LINKED ISSUE #7650: Hovered points outside plotting area
#### Expected behaviour
Points which are outside the plotting area should not be visible/hovered.

#### Actual behaviour
See the attached screenshot:
image

#### Live demo with steps to reproduce
http://jsfiddle.net/efujfuat/1/
1. Move the mouse cursor to point {Series 1, x: 2, y: 3} 
-> point {Series 2, x: 2, y: 1} will be visible outside the plotting area.

Removing the chart setting `{ tooltip: {shared: true} }` fixes the problem. But I need this shared tooltip.

Similar issue: #3916

#### Product version
Highcharts: latest version

#### Affected browser(s)
Chrome v63

### LINKED ISSUE #7711: yAxis display out of pane after setExtremes
#### Live demo with steps to reproduce
http://jsfiddle.net/b62tdy3w/

click the button (set yAxis[0]'s extremes)

snipaste_2018-01-23_17-38-56

#### Product version
Highstock 6.0 +

### LINKED ISSUE #11493: Y Axis scaled using set Extremes Is inappropriate
#### Expected behaviour
Hovering on the Chart should display the values of the series in the tooltip that belongs to the View of the chart, in effect

#### Actual behaviour
The tool-tip displays the values that does not belong to the View in effect of the chart

#### Live demo with steps to reproduce

1. Create Multiple Y Axises that are not opposite to each other.
That is, It is being arranged below one after the other.
2. Add one or multiple Series to each of these axises.
3. Let the data points vary from a range of 70 - 100.
4. Scale one of the Axises between 85 - 90
5. Hover over the Chart
6. Observe the tooltips that are being displayed

Observation
The tooltip displays values above 90 for the Axis which has been scaled till 90

Please find the below working fiddle

https://jsfiddle.net/uk1exc89/1/

See the tooltip before and after clicking on the 'Set Scale Range' button

Please find the image below for the outcome

AfterScaling

The toolTip that belongs to the **Title 4** region is being displayed along with **Title 3** region which does not make any sense to the user at all.

#### Product version

Highstock - 7.1.2

#### Affected browser(s)
Only tested out in Google Chrome - ^74.0.x

### PR DESCRIPTION
**Pull request by jon-a-nygaard**
Fixed #7650, hide hover points outside plot area. Fixed #11493, limit split tooltip to yAxis range.

---
# Description
Reverts #11531 due to unwanted side effects. Please see https://github.com/highcharts/highcharts/issues/11493#issuecomment-519074331 and https://github.com/highcharts/highcharts/issues/7711#issuecomment-518251273.
Applies a different solution to fix the related issues.

- Halo gets the same visibility as point.graphic or the stateMarkerGraphic
- stateMarkerGraphic is hidden if `point.isInside === false`
- Split tooltip target and anchorY is limited to (`yAxis.pos < target < yAxis.pos + yAxis.len`). Height of tooltip is also considered for `target`.

# Example(s)
- [Demo of issue #7650](https://jsfiddle.net/jon_a_nygaard/z0o94uwm/)
- [Demo of issue #7650 with fix applied](https://jsfiddle.net/jon_a_nygaard/9bq1jv4k/)
- [Demo of issue #11493](https://jsfiddle.net/jon_a_nygaard/nhudqsfa/)
- [Demo of issue #11493 with fix applied](https://jsfiddle.net/jon_a_nygaard/9weaxh2j/)

# Related issue(s)
Closes #7650
Closes #11493
Closes #7711

### CODE REVIEW

**Comment by jon-a-nygaard** [comment]
IE8 is not happy with something related to visibility, I am currently looking into fixing this.

File: ts/parts/Interaction.ts [hunk 1]
```diff
@@ -1264,6 +1259,9 @@ extend(Point.prototype, /** @lends Highcharts.Point.prototype */ {
                 'class': 'highcharts-halo highcharts-color-' +
                     pick(point.colorIndex, series.colorIndex) +
                     (point.className ? ' ' + point.className : ''),
+                'visibility': (
+                    (point.graphic || stateMarkerGraphic) as any
+                ).visibility,
```
Comment (pawelfus) [inline ts/parts/Interaction.ts]: Would it be better to move this into the condition above? So not rendering halo at all, when point/shared marker is not visible? By the condition above I mean:
https://github.com/highcharts/highcharts/blob/0bb12294b4f4f6c03b4b265488535e0e956b6039/ts/parts/Interaction.ts#L1246

Comment (jon-a-nygaard) [reply ts/parts/Interaction.ts]: Thanks, that is a good point. Will make the necessary change.

It will only be optimal when `(point.graphic || stateMarkerGraphic) as any).visibility` equals `hidden` though. Since `inherit` can be both `'visible'|'hidden'` depending on the parents, it will have to be rendered in this case.

Comment (jon-a-nygaard) [reply ts/parts/Interaction.ts]: @pawelfus Please see latest changes.

Comment (pawelfus) [reply ts/parts/Interaction.ts]: Looks good, thanks!
