### PR TITLE
bugfix/23809-standalone-nav-rangeselector-trigger

### LINKED ISSUE #23809: HighStock: Standalone navigator does not react to range selectors
#### Expected behaviour
Standalone navigator should react to changes in the range selector selections the same as embedded navigator

#### Actual behaviour
Standalone navigator selection does not react to range selector clicks, only normal chart zoom.

#### Live demo with steps to reproduce
https://jsfiddle.net/chrisaurora/pv4Ls1dr/2/

#### Product version

Highcharts Stock latest
#### Affected browser(s)
All

### PR DESCRIPTION
**Pull request by kamil-musialowski**
Fixed #23809, `rangeSelector` events were not working in standalone navigator.

### CODE REVIEW

File: samples/unit-tests/standalone-navigator/general/demo.js [hunk 1]
```diff
@@ -0,0 +1,83 @@
...
+        0,
+        `Standalone navigator should react to range selector input value change,
+        #23809.`
+    );
+
+    // Cleanup after appending multiple containers
+    navigator.destroy();
+    container1.parentNode.removeChild(container1);
+    chart.destroy();
+    container2.parentNode.removeChild(container2);
```
Comment (jedrzejruta) [inline samples/unit-tests/standalone-navigator/general/demo.js:82]: Out of curiosity, is there any special reason to do the cleanup after the assertions?

Comment (kamil-musialowski) [reply samples/unit-tests/standalone-navigator/general/demo.js:82]: TL;DR Good practice for unit-tests 😄 

Normally, you would render a chart in div `container` in one test, and then once render the chart again in another test it destroys the old chart and creates a new one.

However, since we are rendering the charts in child containers, they won't get deleted automatically, so they would stay there forever 😄

Comment (jedrzejruta) [reply samples/unit-tests/standalone-navigator/general/demo.js:82]: Thanks for the robust explanation, makes sense! 🎉

**Review by DJTechnoo — APPROVED** [review]
LGTM 🎉
