### PR TITLE
bugfix/20470-nested-props-exporting-data

### LINKED ISSUE #20470: Using dot notation in `series.keys` results in wrong data exporting
#### Expected behaviour

The data is parsed and exported properly.

#### Actual behaviour

The row with dot notation doesn't have any value shown.

#### Live demo with steps to reproduce

Wait for the data table to appear, this is also related to exporting as CSV and XLS.

[https://jsfiddle.net/BlackLabel/59bnvjLq/](https://jsfiddle.net/BlackLabel/59bnvjLq/)

#### Product version
Since Highcharts v6.1.0

_Internal note:_ It seems that the mock point isn't created properly in the `chartGetDataRows()` when the dot notation is introduced.

### PR DESCRIPTION
**Pull request by jedrzejruta**
Fixed #20470, allow values from nested properties in exported data.

### CODE REVIEW

File: ts/Extensions/ExportData/ExportData.ts [hunk 1]
```diff
@@ -602,7 +602,10 @@ function chartGetDataRows(
 
                 while (j < valueCount) {
                     prop = pointArrayMap[j]; // `y`, `z` etc
-                    val = (mockPoint as any)[prop];
+                    val = series.pointClass.prototype.getNestedProperty.apply(
+                        mockPoint as any,
```
Comment (hubertkozik) [inline ts/Extensions/ExportData/ExportData.ts:606]: I don't like this `as any` - let's remove it 😁

**Review by hubertkozik — CHANGES_REQUESTED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!

**Review by hubertkozik — APPROVED** [review]
