### PR TITLE
bugfix/22981-stock-axis-plotline-misalignment

### LINKED ISSUE #22981: tickWidth align issue in Stock
#### Expected behaviour
After setting tickWidth on yAxis the tick marks are aligned with grid lines.

#### Actual behaviour
After setting tickWidth on yAxis the tick marks are misaligned with grid lines.

Image

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/crtz5g7e/

#### Product version
The issue occurs only in Highcharts Stock since version 11.4.2

### PR DESCRIPTION
**Pull request by jedrzejruta**
Fixed #22981, rounding of y-values for the plot lines with Highcharts Stock resulted in misaligned grid lines.

### CODE REVIEW

File: samples/unit-tests/axis/gridlines/demo.js [hunk 1]
```diff
@@ -127,3 +127,31 @@ QUnit.test('Animation of grid lines and tick marks', function (assert) {
...
+        series: [{
+            data: [1, 2, 3, 4, 5]
+        }]
+    });
+    const ticks = chart.yAxis[0].ticks;
+
+    for (const pos in ticks) {
+        if (Object.hasOwnProperty.call(ticks, pos)) {
+            console.log(ticks[pos].mark.attr('d').split(' ')[2]);
+            console.log(ticks[pos].gridLine.attr('d').split(' ')[2]);
```
Comment (DJTechnoo) [inline samples/unit-tests/axis/gridlines/demo.js:148]: Some leftover consoles

**Review by DJTechnoo — CHANGES_REQUESTED** [review]
Looks good! Just a little bit of clean-up:

**Review by DJTechnoo — APPROVED** [review]
Magnificent!

**Comment by TorsteinHonsi** [comment]
@pawelfus Confirmed. Karma loads the files of [karma-files.json](https://github.com/highcharts/highcharts/blob/master/test/karma-files.json) and run all tests in one batch (split by `--browsercount`).

**Review by kamil-musialowski — APPROVED** [review]
Nice!

**Review by bm64 — APPROVED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
