### PR TITLE
bugfix/11546-parentNodes-missing-after-update

### LINKED ISSUE #11546: PackedBubble: Missing parentNodes after chart.update
#### Expected behaviour
Chart rendered the same way as before `chart.update()` (no missing parentNodes)

#### Actual behaviour
parentNodes vanished

#### Live demo with steps to reproduce
Demo: https://jsfiddle.net/BlackLabel/7ut0aLf8/

#### Product version
v7

FYI @Izothep

### PR DESCRIPTION
**Pull request by Izothep**
Fixed #11546, in packed bubble series parentNodes were missing after chart and series update.

### CODE REVIEW

File: ts/parts-more/PackedBubbleSeries.ts [hunk 1]
```diff
@@ -1113,14 +1113,13 @@ seriesType<Highcharts.PackedBubbleSeriesOptions>(
                 width: (series.parentNodeRadius as any) * 2,
                 height: (series.parentNodeRadius as any) * 2
             }, parentOptions);
-            if (!series.graph) {
+            if (!(series.parentNode as any).graphic) {
                 series.graph = (series.parentNode as any).graphic =
                     chart.renderer.symbol(parentOptions.symbol)
                         .attr(parentAttribs)
```
Comment (pawelfus) [inline ts/parts-more/PackedBubbleSeries.ts]: Is that line necessary? It's done after if-else. Or some of `parentAttribs` are expected **before** adding to DOM?

Comment (Izothep) [reply ts/parts-more/PackedBubbleSeries.ts]: Thanks for the feedback! It was a relict after removing `if-else` from the code, I have already removed unnecessary `attr` in the newest commit.
