### PR TITLE
bugfix/16041-flag-distribute-maxDistance 

### LINKED ISSUE #16041: Flag series is hidden when chart width is fixed when text is long
#### Expected behaviour
Flag series is hidden when chart width is fixed when text is long.

#### Actual behaviour
Flag series should show up, may be with some ellipsis text overflow.

#### Live demo with steps to reproduce
https://jsfiddle.net/07zok3t8/

On commenting out line no 3 in JS code, we can see flag series showing up.

#### Product version
Highstock JS v9.1.2 

#### Affected browser(s)
Chrome

### PR DESCRIPTION
**Pull request by karolkolodziej**
Fixed #16041, long flag labels were not distributed properly which resulted in removing them.

### CODE REVIEW

File: samples/unit-tests/series-flags/general/demo.js [hunk 1]
```diff
@@ -201,4 +201,36 @@ QUnit.test('Scrolling inverted chart with a flag series.', function (assert) {
...
+    const chart = Highcharts.chart('container', {
+        chart: {
+            width: 800
+        },
+        series: [{
+            data: [
+                [1, 10],
+                [6, 60]
+            ],
+            type: 'line'
```
Comment (raf18seb) [inline samples/unit-tests/series-flags/general/demo.js:216]: This is the default, not needed

File: samples/unit-tests/series-flags/general/demo.js [hunk 2]
```diff
@@ -201,4 +201,36 @@ QUnit.test('Scrolling inverted chart with a flag series.', function (assert) {
...
+            }],
+            type: "flags"
+        }]
+    });
+
+    assert.ok(
+        chart.series[1].points[0].graphic.x > 0,
+        'The flag graphic should have a positive x position.'
+    );
+    chart.setSize(400, undefined);
```
Comment (raf18seb) [inline samples/unit-tests/series-flags/general/demo.js:230]: The second argument `undefined` is the default one, not needed here, but it can stay of course.

File: samples/unit-tests/series-flags/general/demo.js [hunk 3]
```diff
@@ -201,4 +201,36 @@ QUnit.test('Scrolling inverted chart with a flag series.', function (assert) {
...
+                [1, 10],
+                [6, 60]
+            ],
+            type: 'line'
+        }, {
+            data: [{
+                x: 5,
+                title: "Very long long text very long long text"
+            }],
+            type: "flags"
```
Comment (raf18seb) [inline samples/unit-tests/series-flags/general/demo.js:222]: Double quote

File: samples/unit-tests/series-flags/general/demo.js [hunk 4]
```diff
@@ -201,4 +201,36 @@ QUnit.test('Scrolling inverted chart with a flag series.', function (assert) {
...
+        series: [{
+            data: [
+                [1, 10],
+                [6, 60]
+            ],
+            type: 'line'
+        }, {
+            data: [{
+                x: 5,
+                title: "Very long long text very long long text"
```
Comment (raf18seb) [inline samples/unit-tests/series-flags/general/demo.js:220]: Double quote

**Review by raf18seb — CHANGES_REQUESTED** [review]

**Review by pawelfus — APPROVED** [review]
Please resolve Rafal's comments, the rest looks good, thanks!

**Review by raf18seb — APPROVED** [review]
Thanks!

**Review by pawellysy — APPROVED** [review]

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
I think 300px is too distant in most situations. See https://jsfiddle.net/highcharts/xLyzbt16/1/ and test it with the PR.

What if we analyze the boxes and look for the widest box? Then we could set the `maxDistance` to something like `Math.min(greatestBoxWidth, 100)`?

**Comment by karolkolodziej** [comment]
Setting `Math.min(greatestBoxWidth, 100)` won't work in this case. 
For smaller flags, numbers are so small that they disappear.

I decided to use `Math.max..` to preserve the previous behaviour and for the longer labels distribute them properly 😄

**Comment by TorsteinHonsi** [comment]
> won't work in this case

Yes of course, `Math.max` was what I meant 🙃
