### PR TITLE
bugfix/24164-ghost-markers-updating-data-a11y

### LINKED ISSUE #24164: Ghost markers when updating series data with accessibility & styled mode & disabled markers
#### Expected behaviour
After updating the series' dataset, no markers are visible when marker.enabled: false.

#### Actual behaviour
After updating the series' dataset with accessibility module on & styled mode on, disabled (ghost) markers are shown. (Related to https://github.com/highcharts/highcharts/issues/23878)

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/ef7uLghy/
Click the `Set Dataset` button.

Image

#### Product version
Highcharts Core v12.5.0

### PR DESCRIPTION
**Pull request by MarkusBarstad**
Fixed #24164, ghost markers appeared when updating a11y series data.

### CODE REVIEW

File: ts/Accessibility/Components/SeriesComponent/ForcedMarkers.ts [hunk 1]
```diff
@@ -305,6 +313,20 @@ namespace ForcedMarkersComposition {
...
+     * @private
+     */
+    function destroyPointMarkerGraphics(series: SeriesComposition): void {
+        if (series.points) {
+            series.points.forEach((point): void => {
+                if (point.graphic) {
+                    point.graphic = point.graphic.destroy();
+                }
+            });
+        }
```
Comment (TorsteinHonsi) [inline ts/Accessibility/Components/SeriesComponent/ForcedMarkers.ts]: A small and non-critical optimization tip - we can use optional chaining instead of a full `if` condition when dealing with array functions.
```suggestion
        series.points?.forEach((point): void => {
            if (point.graphic) {
                point.graphic = point.graphic.destroy();
            }
        });
```
