### PR TITLE
bugfix/23193-all-grid-rows-proper-removal

### LINKED ISSUE #23193: Removing all rows, leaves one empty row
#### Expected behaviour
When removing all of the rows, the `tbody` should be empty.

#### Actual behaviour
When removing all rows, there is one empty row.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/otuaw3fc/

#### Product version
Highcharts Grid v1.1.0 (2025-05-15)

#### Affected browser(s)
All

### PR DESCRIPTION
**Pull request by KamilKubik**
Fixed #23193, not all grid rows were properly removed.

### CODE REVIEW

**Review by karolkolodziej — APPROVED** [review]

**Review by skrulling — APPROVED** [review]

**Review by sebastianbochan — APPROVED** [review]

File: ts/Grid/Core/Table/Actions/RowsVirtualizer.ts [hunk 1]
```diff
@@ -262,6 +262,13 @@ class RowsVirtualizer {
      */
     private renderRows(rowCursor: number): void {
         const { viewport: vp, buffer } = this;
+        const rowCount = vp.dataTable.getRowCount();
+
+        // Stop rendering if there are no rows to render.
+        if (rowCount === 0) {
```
Comment (ddragula) [inline ts/Grid/Core/Table/Actions/RowsVirtualizer.ts]:
```suggestion
        if (rowCount < 1) {
```

**Review by ddragula — APPROVED** [review]
Nice, thanks!
