### PR TITLE
bugfix/22698-range-selector-group-text-attr

### LINKED ISSUE #22698: Wrong `text-align` values set for RangeSelector group on initial load and update of data
#### Expected behaviour
The `text-align` is set correctly, according to the possible values (left, center, right).

#### Actual behaviour
On initial load, the _range-selector-group_ `text-align` attribute is set to undefined, and upon updating the data, on each iteration a NaN value is appended.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/y3n94po1/

#### Product version
Highcharts Stock v12.1.0+

Internal note: Regression introduced in [03f90af](https://github.com/highcharts/highcharts/commits/03f90af2a84e1278e7c915a07dde768b0eb1ffdd)

### PR DESCRIPTION
**Pull request by jedrzejruta**
Fixed #22698, `text-align` attribute incorrectly set for the Range selector group.

The _text-align_ attribute shouldn't be set on the group element at all, since the positioning applies to either buttons or input elements.

### CODE REVIEW

**Review by kamil-musialowski — APPROVED** [review]
Nice!

**Review by pawelfus — APPROVED** [review]
Thanks!

File: ts/Core/Renderer/SVG/SVGElement.ts [hunk 1]
```diff
@@ -454,9 +454,12 @@ class SVGElement implements SVGElementBase {
             y = (alignToBox.y || 0) + (alignOptions.y || 0) +
                 ((alignToBox.height || 0) - (alignOptions.height || 0)) *
                 getAlignFactor(alignOptions.verticalAlign),
-            attribs: SVGAttributes = {
-                'text-align': alignOptions?.align
-            };
+            attribs: SVGAttributes = {};
+
+        // Add text-align attribute only if option is defined, #22698
+        if (defined(alignOptions.align)) {
```
Comment (TorsteinHonsi) [inline ts/Core/Renderer/SVG/SVGElement.ts]: Since `align` is of type [AlignValue](https://github.com/highcharts/highcharts/blob/a1be1023304a10a50bfc69efda5841382bc0dce8/ts/Core/Renderer/AlignObject.d.ts#L17) and can never have legit falsy values like false, 0 or `''`, a truthy check should suffice.

```suggestion
        if (alignOptions.align) {
```

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks!

In addition to the inline comment, there is now also a conflict that should be resolved.

File: ts/Core/Renderer/SVG/SVGElement.ts (hunk 1 above)
Comment (jedrzejruta) [reply ts/Core/Renderer/SVG/SVGElement.ts]: Good catch, indeed it should be sufficient!

**Review by TorsteinHonsi — APPROVED** [review]
