### PR TITLE
bugfix/20327-rangeselector-inactive-button-click 

### LINKED ISSUE #20327: Zooming issues when rangeSelector.selected set to disabled button
#### Expected behaviour
Panning should preserve the current range

#### Actual behaviour
When the `rangeSelector.selected` option is set to a button that is disabled due to the range exceeding the data range, panning the chart will extend the range to the button instead of limiting it to the data range. 

#### Live demo with steps to reproduce
https://jsfiddle.net/highcharts/sm1o95uf/
* Drag the navigator => x-axis range is extended way outside data range

Or
* Zoom in by mousewheel
* Drag the navigator to the right => poof

Interestingly, if we use the navigator handles to zoom instead of the mouse wheel, then it works as intended

#### Product version
11.2

This issue is forked from https://github.com/highcharts/highcharts/issues/19976

### PR DESCRIPTION
**Pull request by kamil-musialowski**
Fixed #20327, `rangeSelector` allowed to set range larger than possible extremes.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1206202876057667

### CODE REVIEW

**Review by bm64 — APPROVED** [review]

**Review by pawellysy — APPROVED** [review]

File: ts/Stock/RangeSelector/RangeSelector.ts [hunk 1]
```diff
@@ -362,6 +362,18 @@ class RangeSelector {
             this.dropdown.selectedIndex = i + 1;
         }
 
+        const resetFixedRange = (): void => {
+            // If rangeSelector.selected is larger than actual range, reset
+            // chart fixed range (#20327)
+            const xAxis = chart.xAxis[0];
+            if (xAxis.dataMax && xAxis.dataMin && rangeOptions._range) {
```
Comment (pawelfus) [inline ts/Stock/RangeSelector/RangeSelector.ts:369]: When checking numbers, be careful with truthy values (`dataMax` or `dataMin` can be 0)

**Review by pawelfus — CHANGES_REQUESTED** [review]
In addition to the comment below:

Did you consider **not** setting `fixedRange` property when the conditions are not met? Instead of setting it + removing it afterward? 

I'm still worried that the current solution in `toFixedRange` can cause leaks - I couldn't come up with any demo though.

Note: Current master branch delivers a bit different behaviour. When selecting a disabled button, we try to fall back to the "All" button, meaning we shouldn't necessarily clear that value, but set it to the correct one.

File: ts/Stock/RangeSelector/RangeSelector.ts (hunk 1 above)
Comment (kamil-musialowski) [reply ts/Stock/RangeSelector/RangeSelector.ts:369]: Rookie mistake, thanks 😬

**Comment by kamil-musialowski** [comment]
@pawelfus Thank you for the review, I did consider not setting it at all, however at the initial chart load, when the `RangeSelector.clickButton()` is fired we don't have any extremes, dataMin/Max, nothing to compare the `fixedRange` with.

To the note: I think it's a good idea, I will change the logic and see if everything works like it should.

**Review by pawelfus — CHANGES_REQUESTED** [review]
As discussed:
- move the function to prototype + rename
- refactor setting fixedRange

**Review by pawelfus — APPROVED** [review]
Thanks!

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
