### PR TITLE
bugfix/13283-hexcolor-treated-as-comment)

### LINKED ISSUE #13283: Hex color format is ignored in data from CSV
#### Expected behaviour
Hex color should work like other formats: http://jsfiddle.net/BlackLabel/6m4e8x0y/4946/

#### Actual behaviour
Hex color is interpreted as `null` value.

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/0gjbn4m6/1/

#### Product version
Highcharts v8.0.4

#### Affected browser(s)
All
___
_Interna note:_
Probably caused by:
https://github.com/highcharts/highcharts/blob/2aef02113d9a157bb621200cb795f3b58a8a1a04/ts/modules/data.src.ts#L1449-L1457

### PR DESCRIPTION
**Pull request by DJTechnoo**
Fixed #13283, an issue with the data module's CSV parser. Hex colors (and any other strings following a hash) were treated as a comment and ignored.

~~Fixed #13283, Hex color ignored as a comment.~~

### CODE REVIEW

**Comment by TorsteinHonsi** [comment]
@cvasseng Arguably we should not support hash-style comment at all. Apparently the CSV spec doesn't mention it. When putting the issue report's CSV in a .csv file and opening it in Numbers, it parses the comments as regular strings. Likewise with https://csvjson.com/. So an alternative solution here would be to remove this altogether:

```js
                // Quoted string
                if (c === '#') {
                    // The rest of the row is a comment
                    push();
                    return;
                }
```

What do you think?

**Comment by DJTechnoo** [comment]
> So an alternative solution here would be to remove this altogether:

I would agree to remove it. Shall I proceed to do so?

**Comment by cvasseng** [comment]
This was initially done more out of convention, there's some (obscure) software that exports CSV with column formatting in comments, and it was low-effort to add, so I just did it. 

I don't see any reason not to remove it, especially if it's causing issues elsewhere.

File: samples/unit-tests/data/csv/demo.js [hunk 1]
```diff
@@ -713,3 +685,27 @@ QUnit.test('Dot date format', function (assert) {
         }
     });
 });
+
+QUnit.test(
+    'Hex values are not treated as comments (#13283).',
+    function (assert) {
+        var chart = Highcharts.chart('container', {
```
Comment (TorsteinHonsi) [inline samples/unit-tests/data/csv/demo.js:692]: Instead of creating a full `Chart` instance, we can test this using the Data module only. See some of the other tests in the same file for how we call `Highcharts.data` and do the assertion in the `parsed` callback.

File: samples/unit-tests/data/csv/demo.js [hunk 2]
```diff
@@ -713,3 +685,27 @@ QUnit.test('Dot date format', function (assert) {
...
+
+                itemDelimiter: ';',
+                seriesMapping: [{
+                    color: 2
+                }]
+            }
+        });
+
+        var actualColor = chart.series[0].data[0].options.color;
+        assert.strictEqual(actualColor, '#F0F', 'Color must be a hex value');
```
Comment (TorsteinHonsi) [inline samples/unit-tests/data/csv/demo.js:709]: Not a big deal, but our general rule of thumb is that assertion descriptions should contain the word "should". We may add a pre-commit rule for it in the future.

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
