### PR TITLE
bugfix/8095-reset-zoom-drilldown

### LINKED ISSUE #8095: Reset zoom button does not show up when performing zooming after drilldown
#### Expected behaviour
Zooming on any drilldown level should result in displaying reset zoom button.
#### Actual behaviour
The reset zoom button does not display when performing zooming on any drilldown level.

#### Live demo with steps to reproduce
http://jsfiddle.net/502k9msp/

1. Perform a drilldown.
2. Zoom anywhere.

### PR DESCRIPTION
**Pull request by karolkolodziej**
Fixed #8095, reset zoom button was not visible after drilldown.

### CODE REVIEW

File: ts/Extensions/Drilldown.ts [hunk 1]
```diff
@@ -1633,3 +1634,59 @@ addEvent(Point, 'afterSetState', function (): void {
...
+            this.drillUpButton.align({
+                x: buttonOptions.position.x,
+                y: buttonOptions.position.y,
+                align: 'right'
+            },
+            false,
+            buttonOptions.relativeTo || 'plotBox'
+            );
+        }
+    }
```
Comment (sebastianbochan) [inline ts/Extensions/Drilldown.ts:1682]: Lines 1668-1681 are exactly the same as 1649-1661. I suggest to extract it and avoid code rendudant.

**Review by sebastianbochan — CHANGES_REQUESTED** [review]

**Review by sebastianbochan — APPROVED** [review]

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
We already have an event handler for `beforeShowResetZoom` on line 1057. Instead of creating a complicated workaround for our own code, we should modify the existing code to do what we want. The current event handler disables the `resetZoomButton` if the `drillUpButton` is present. That's obviously not what we want with this fix, we want to align them side by side instead.

File: ts/Extensions/Drilldown.ts [hunk 2]
```diff
@@ -68,6 +68,7 @@ declare module '../Core/Chart/ChartLike' {
         drilldown?: Highcharts.ChartDrilldownObject;
         drilldownLevels?: Array<Highcharts.DrilldownLevelObject>;
         drillUpButton?: SVGElement;
+        temporaryDrillUpButton?: SVGElement;
```
Comment (TorsteinHonsi) [inline ts/Extensions/Drilldown.ts:71]: This line is obsolete

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
In addition to the inline comments, there is a fail case. With the [OP demo](http://jsfiddle.net/502k9msp/):

1. Perform drilldown by clicking first column
2. Zoom in
3. Click "Back to"
4. Click first column => Crash

File: samples/unit-tests/drilldown/resetzoom/demo.js [hunk 3]
```diff
@@ -155,6 +155,11 @@ QUnit.test('Drilldown and reset zoom', function (assert) {
         'object',
         'We have a drillUp button'
     );
+    assert.strictEqual(
+        typeof chart.resetZoomButton,
+        'object',
+        'Reset zoom button should also be visible.'
+    );
```
Comment (TorsteinHonsi) [inline samples/unit-tests/drilldown/resetzoom/demo.js:163]: In addition to checking for the button's existence, it would probably be a good idea to check that it does not overlap with the drillUp button.

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]

**Comment by karolkolodziej** [comment]
Thanks for pointing that case! I added a piece of code (together with a proper test) covering that example.

**Review by TorsteinHonsi — APPROVED** [review]
