### PR TITLE
bugfix/boost-point-click-differs-from-non-boost

### LINKED ISSUE #22515: Point click event on boost is not working properly.
#### Expected behaviour
Point click event behaves the same with and without the boost, returning the point object on the point marker click.

#### Actual behaviour
Click event works in boost, but it is an even listener on the whole plot area and it returns chart.hoverPoint

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/etywz1p2/

#### Product version
Highcharts Core

Workaround: https://jsfiddle.net/BlackLabel/rwxq8z0d/
#### Affected browser(s)
all

### PR DESCRIPTION
**Pull request by MarkusBarstad**
Fixed #22515, boosted points had different click-events from non-boost

FYI: I have removed `highcharts-tracker` class from `boost.target`. This feels like a radical move, and I'm not totally sure what may break because of this :grimacing:

### CODE REVIEW

**Review by bre1470 — CHANGES_REQUESTED** [review]
This would likely lead to a regression of https://github.com/highcharts/highcharts/commit/1154a304c07a02bdb86daabcaf1dd62de594a59b. Try to fix the click event of boost.

**Comment by MarkusBarstad** [comment]
@bre1470 

Ok, so fixin it from within boost was not as straightforward as I had hoped.

To alter the `click` event I used wrap simply because other boost-stuff does, and I wanted to prevent `firePointEvent` in case it fires when it should not.

This feels a bit hacky, but I am not sure how we should otherwise do it.

Another option is to override `Pointer.onContainerMouseClick` since this is where the erroneous calls to `Point.firePointEvent` comes from, but doing so would introduce more code.

Any ideas? 🤔

**Comment by bre1470** [comment]
Changing a bubble layout to fix a scatter issue seems unrelated, when the jsfiddle does not contain the code. That besides I am not able to reproduce the issue in the ticket.

**Comment by MarkusBarstad** [comment]
Sorry @bre1470 ! 

I messed up with my local git so I didn't even push the fix, and I pushed a wrong file.

Things should be good now.

**Comment by TorsteinHonsi** [comment]
@KacperMadej So the OP issue here is that Boost triggers click events on the closest point, while non-boost requires the click to actually be on the marker?

In that case I think measuring the distance between the click and the point would be the safest bet. It also should rule out issues with the halo and the marker. See https://jsfiddle.net/highcharts/8cmvrzoL/

**Comment by MarkusBarstad** [comment]
@TorsteinHonsi , @KacperMadej 
Do note that the current implementation does not involve removing 'highcharts-tracker' guys, just checking for it!

Its like this (though this could be a worse option than checking the distance, just in case it might be better to simply to a prop lookup and we can trust what the event says):
```
        wrap(
            PointClass.prototype,
            'firePointEvent',
            function (this: typeof PointClass.prototype, proceed): boolean {
                const eType = arguments[1];
                const event = arguments[2];
                if (
                    event &&
                    eType === 'click' &&
                    event
                        ?.target
                        ?.className
                        ?.baseVal
                        ?.includes('highcharts-tracker')
                ) {
                    return false;
                }
                return proceed.apply(this, [].slice.call(arguments, 1));
            }
        );
```

**Comment by MarkusBarstad** [comment]
@TorsteinHonsi Regarding he `distance > 10` should we hardcode this to 10 or is there some dynamic point property we should go for here

**Comment by MarkusBarstad** [comment]
@bre1470 
Alright everything should be good here now! The failing test also fails on master (at least locally here) so i dont think thats related.

File: ts/Extensions/Boost/BoostSeries.ts [hunk 1]
```diff
@@ -235,6 +236,27 @@ function compose<T extends typeof Series>(
...
+            ): boolean | undefined {
+                if (type === 'click' && this.series.boosted) {
+                    const point = e.point,
+                        { xAxis, yAxis } = point.series,
+                        distance = Math.sqrt(
+                            Math.pow(point.plotX + xAxis.pos - e.chartX, 2) +
+                            Math.pow(point.plotY + yAxis.pos - e.chartY, 2)
+                        );
+
+                    if (distance > 10) {
```
Comment (KacperMadej) [inline ts/Extensions/Boost/BoostSeries.ts:254]: How about `>= point.series.options.marker?.radius ?? 10`? For `scatter` it makes sense. Falls back to `10` for e.g. `column`. Not sure if similar check can be done for `bubble` - at a first glance, the point's z-based marker pixel size computation is done only in the boost scope for drawing, not assigned to the point or data.

File: ts/Extensions/Boost/BoostSeries.ts [hunk 2]
```diff
@@ -235,6 +236,27 @@ function compose<T extends typeof Series>(
...
+                this: typeof PointClass.prototype,
+                proceed, type, e
+            ): boolean | undefined {
+                if (type === 'click' && this.series.boosted) {
+                    const point = e.point,
+                        { xAxis, yAxis } = point.series,
+                        distance = Math.sqrt(
+                            Math.pow(point.plotX + xAxis.pos - e.chartX, 2) +
+                            Math.pow(point.plotY + yAxis.pos - e.chartY, 2)
+                        );
```
Comment (KacperMadej) [inline ts/Extensions/Boost/BoostSeries.ts:252]: Some (if not all) points in this function already have `point.dist`. All points found using KD Tree are found through the distance calculation before entering here.

**Review by bre1470 — APPROVED** [review]
I am still not able to reproduce the issue with the latest changes. When I check the console, the event context is always (boost + non-boost) the point of the scatter series and equals to the hoverPoint. The only difference is the amount of properties between a boosted point and a regular point, which has additional properties like graphic for the SVG element and a boolean flag whether it is a negative value.

Besides that the changes look solid, so I will give a green light.

**Review by KacperMadej — APPROVED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
