### PR TITLE
bugfix/23019-broken-null-opacity-on-maps

### LINKED ISSUE #23019: Upgrading from 12.1.2 to 12.2.0 breaks `nullInteraction` on maps
#### Expected behaviour

Setting `nullInteraction: true` on highmaps should allow interaction with `null` values.

#### Actual behaviour

Countries with `null` values now have `opacity: 0` and are not visible anymore.

#### Live demo with steps to reproduce

Broken in 12.2.0: https://jsfiddle.net/vwg6yd9a/

Used to be fine in 12.1.2: https://jsfiddle.net/a85ydkfL/

#### Product version

Highmaps 12.2.0

#### Affected browser(s)

Chrome.

### PR DESCRIPTION
**Pull request by AndrzejBuleczka**
Fixed #23019, a regression in v12.2.0 causing `nullInteraction` to break in maps.

~~Fixed #23019, added check for map series type to get correct opacity with `nullInteraction: true` .~~

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1210196759459796

### CODE REVIEW

**Comment by AndrzejBuleczka** [comment]
Thanks @KacperMadej for great review and very helpful tips!

**Review by KacperMadej — APPROVED** [review]
All good. Thank you!

File: ts/Series/Map/MapSeries.ts [hunk 1]
```diff
@@ -675,6 +675,13 @@ class MapSeries extends ScatterSeries {
             attr.fill = this.options.nullColor;
         }
 
+        // Set opacity: if point is null and nullInteraction is true,
+        // force opacity 1. Otherwise use point/series opacity or default 1
```
Comment (TorsteinHonsi) [inline ts/Series/Map/MapSeries.ts]:
```suggestion
        // Set opacity: if point is null and nullInteraction is true, force
        // opacity 1. Otherwise use point/series opacity or default 1 (#23019)
```

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Nice, thanks! Just a little change request - adding a reference to the offending issue is always helpful to the future developer who wonders why we need this condition.

**Review by TorsteinHonsi — APPROVED** [review]
