### PR TITLE
bugfix/23385-nodes-dataLabels

### LINKED ISSUE #23385: Can't update options for sankey and dependency wheel series
#### Expected behaviour

dynamic update chart or series's options after chart rendered, such as colors, DataLabels and etc

#### Actual behaviour

Can't update colors and dataLabels options 

#### Live demo with steps to reproduce

https://jsfiddle.net/2p08th5g/

### PR DESCRIPTION
**Pull request by kamil-musialowski**
Fixed #23385, `dataLabels` on sankey and dependency wheel nodes were not destroyed after update.

### CODE REVIEW

**Review by pawelfus — CHANGES_REQUESTED** [review]
.

File: ts/Core/Series/Series.ts [hunk 1]
```diff
@@ -4692,6 +4692,16 @@ class Series {
                     }
                 }
             }
+
+            // Also destroy node labels when data labels are disabled. Do not
+            // call resolveColor here to avoid reassigning colorByPoint colors.
+            if (kinds.dataLabel && this.nodes) { // #23385
```
Comment (pawelfus) [inline ts/Core/Series/Series.ts]: I'm not convinced if that belongs here. I would expect NodesComposition to hold `nodes` logic. Is this possible? Using eg `afterUpdate` event?

Comment (kamil-musialowski) [reply ts/Core/Series/Series.ts]: Wow, I didn't even thought about `NodesComposition`. It works!

**Review by pawelfus — APPROVED** [review]
Thanks!

File: ts/Series/NodesComposition.ts [hunk 2]
```diff
@@ -143,9 +150,23 @@ namespace NodesComposition {
...
+        addEvent(SeriesClass, 'afterUpdate', afterUpdate);
+
         return SeriesClass as (T&typeof SeriesComposition);
     }
 
+    /**
+     * Destroy data labels on nodes.
+     * @private
+     */
+    function afterUpdate(this: Series): void {
```
Comment (PaulDalek) [inline ts/Series/NodesComposition.ts:162]: I would go with a slightly modified version:

```
function afterUpdate(this: Series): void {
  if (!this.hasDataLabels?.()) { // #23385
    for (const node of this.nodes || []) {
      node.destroyElements({ dataLabel: 1 });
    }
  }
}
```

But it's your call ;)

**Review by PaulDalek — COMMENTED** [review]
Good job, only one small suggestion from me.

**Review by PaulDalek — APPROVED** [review]

File: ts/Series/NodesComposition.ts (hunk 2 above)
Comment (kamil-musialowski) [reply ts/Series/NodesComposition.ts:162]: Hmm, I think I'm going to stick with my solution, unless there is a good reason to change that 😄

**Review by DJTechnoo — APPROVED** [review]
LGTM! 🎉

**Review by wchmiel — APPROVED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
