### PR TITLE
bugfix/16583-zoomKey-panKey-ignored

### LINKED ISSUE #16583: chart configuration property `zoomKey` is ignored.
#### Expected behaviour
```JavaScript
chart {
  panning: true,
  zoomKey: 'shift',
  zoomType: 'x',
}
```
I expect these properties in a chart configuration to implement panning as the default behavior when a user clicks and drags the chart series.

[workaround suggested that does not work in my case](https://github.com/highcharts/highcharts/issues/12669#issuecomment-569642997)
I cannot ignore `dragStart` events because I want to support panning. 

#### Actual behaviour

The chart will highlight on click and drag.  The chart will zoom.  Panning will be ignored. 

#### Live demo with steps to reproduce
[Here is a jsfiddle demo](https://jsfiddle.net/fqmLjrpk/)

#### Product version
```
/*
 Highcharts JS v9.3.0 (2021-10-21)

 (c) 2009-2021 Torstein Honsi

 License: www.highcharts.com/license
*/
```

#### Affected browser(s)
I was able to reproduce this on my local installation of 
- Chrome `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36`
- Firefox ` Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0 `
- Safari `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15 `

### PR DESCRIPTION
**Pull request by jedrzejruta**
Fixed #16583, `zoomKey` and `panKey` were ignored when set together.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1209822976319025

### CODE REVIEW

File: samples/unit-tests/chart/panning/demo.js [hunk 1]
```diff
@@ -230,6 +230,60 @@ QUnit.test('Zoom and pan key', function (assert) {
...
+
+    chart.zoomOut();
+
+    controller.pan([150, 100], [250, 150]);
+
+    assert.ok(
+        chart.xAxis[0].min === xExtremes.dataMin &&
+        chart.yAxis[0].max === 314,
+        'Chart should not zoom in without zoomKey pressed, #16583.'
+    );
```
Comment (pawelfus) [inline samples/unit-tests/chart/panning/demo.js:258]: Alternative: get extremes before `controller.pan` and compare with the ones after the panning.

File: samples/unit-tests/chart/panning/demo.js [hunk 2]
```diff
@@ -230,6 +230,60 @@ QUnit.test('Zoom and pan key', function (assert) {
...
+
+    controller.pan([150, 100], [250, 150], { altKey: true });
+
+    xExtremes = chart.xAxis[0].getExtremes();
+    yExtremes = chart.yAxis[0].getExtremes();
+
+    assert.ok(
```
Comment (pawelfus) [inline samples/unit-tests/chart/panning/demo.js:262]: Then: Compare new extremes after panning with `{ altKey: true }` vs old extremes snapshot.

File: ts/Core/Pointer.ts [hunk 3]
```diff
@@ -954,6 +957,21 @@ class Pointer {
...
+     *
+     * @internal
+     * @param {Event} e
+     *        A mouse event.
+     * @param {string | undefined} key
+     *        Zoom or pan key.
+     * @return {boolean}
+     *         True if the zoom or pan key is pressed. False otherwise.
+     */
+    private zoomOrPankeyPressed(e: Event, key: string | undefined): boolean {
```
Comment (pawelfus) [inline ts/Core/Pointer.ts]: Key*

However, the function name is misleading. At first I thought half of the zooming functionality will break (because function name suggest a key must be pressed). Then I realized, function will return true also in case, when `key` is not configured.

**Comment by jedrzejruta** [comment]
> Extra question: http://utils.highcharts.local/samples/#test/unit-tests/chart/zoomtype - this demo fails spectacularly (34/103 or 31/101 greens only). Am I the only one?

@pawelfus You're not the only one, funnily enough it also fails on latest master, however when running it locally via console (or CI) it passes without any errors.

File: ts/Core/Pointer.ts [hunk 4]
```diff
@@ -954,6 +957,22 @@ class Pointer {
...
+     * @internal
+     * @param {Event} e
+     *        A mouse event.
+     * @param {string | undefined} key
+     *        Zoom or pan key.
+     * @return {boolean}
+     *         True if the key is undefined
+     *         or if the action key is pressed. False otherwise.
+     */
+    private checkActionKey(e: Event, key: string | undefined): boolean {
```
Comment (TorsteinHonsi) [inline ts/Core/Pointer.ts]: Since this is a simple helper function, called twice from the same file, we can shave off a few bytes by making it a local arrow function. Also the typeof test can be `!defined(key)`.

```ts
const checkActionKey = (e: Event, key: string | undefined): boolean => 
    !defined(key) || (e as any)[`${key}Key`];
```

Comment (jedrzejruta) [reply ts/Core/Pointer.ts]: Thanks, makes sense to use it here!

Comment (TorsteinHonsi) [reply ts/Core/Pointer.ts]: In addition to using `defined` like you did, I think it should be a local arrow function. So not being called ast `this.checkActionKey`, but as `checkActionKey`. The compiler will pack this into a single byte function name, and compile file weight additions will be minimal.

```ts
const checkActionKey = (e: Event, key: string | undefined): boolean => 
    !defined(key) || (e as any)[`${key}Key`];
```

Comment (jedrzejruta) [reply ts/Core/Pointer.ts]: Missed that part - should be good now 🙈
