### PR TITLE
bugfix/15735-remove-indicator

### LINKED ISSUE #15735: Stock Tools: Adding and removing panes misplaces yAxis with `top` predefined
#### Expected behaviour
Correctly positioned first/main yAxis

#### Actual behaviour
yAxis is translated to the top (negative `yAxis.top` value)

#### Live demo with steps to reproduce
[Demo](https://jsfiddle.net/BlackLabel/kam2zwbg/1/)

- initial yAxis has `yAxis.top` defined.
- add 2 indicators with separate yAxes (for example 2x ATR)
- remove the first of them -> yAxis height is calculated incorrectly:

Zrzut ekranu 2021-05-17 o 18 00 00

#### Product version
Highcharts Stock

### PR DESCRIPTION
**Pull request by pawellysy**
Fixed #15735, axes were wrongly calculated when removing an indicator via Stock Tools GUI.

### CODE REVIEW

File: ts/Stock/StockToolsBindings.ts [hunk 1]
```diff
@@ -348,9 +354,12 @@ bindingsUtils.manageIndicators = function (
...
 
             if (indicatorsWithAxes.indexOf(series.type) >= 0) {
-                const removedYAxisHeight = yAxis.options.height;
+                const removedYAxisProps = {
+                    height: yAxis.options.height,
+                    top: yAxis.options.top
+                } as Highcharts.AxisPositionsObject;
                 yAxis.remove(false);
-                navigation.resizeYAxes(removedYAxisHeight as string);
+                navigation.resizeYAxes(removedYAxisProps);
```
Comment (karolkolodziej) [inline ts/Stock/StockToolsBindings.ts:362]: There is something wrong with `AxisPositionsObject` interface declaration if you still need to cast it here like this.

**Review by karolkolodziej — CHANGES_REQUESTED** [review]
- [x] One TS issue to fix

File: ts/Stock/StockToolsBindings.ts [hunk 2]
```diff
@@ -348,9 +354,12 @@ bindingsUtils.manageIndicators = function (
             series.remove(false);
 
             if (indicatorsWithAxes.indexOf(series.type) >= 0) {
-                const removedYAxisHeight = yAxis.options.height;
+                const removedYAxisProps = {
+                    height: yAxis.options.height,
+                    top: yAxis.options.top
+                } as Highcharts.AxisPositionsObject;
```
Comment (karolkolodziej) [inline ts/Stock/StockToolsBindings.ts:360]: There is something wrong with `AxisPositionsObject` interface declaration if you still need to cast it here like this.

**Review by karolkolodziej — CHANGES_REQUESTED** [review]

File: ts/Stock/StockToolsBindings.ts (hunk 2 above)
Comment (karolkolodziej) [reply ts/Stock/StockToolsBindings.ts:360]: Additionally, I think there is no need for adding the `Object` word into that interface's name.

Comment (pawellysy) [reply ts/Stock/StockToolsBindings.ts:360]: As you can see below, the `removedYAxisHeight` was previously casted as well (to string).  Since we can only remove the axis we previously created by GUI, these options are certainly strings, so I decided to cast them here, since this is not an issue.

**Review by raf18seb — APPROVED** [review]
Nice!

**Review by karolkolodziej — APPROVED** [review]

**Comment by TorsteinHonsi** [comment]
Pending approval by @pawelfus

**Review by pawelfus — CHANGES_REQUESTED** [review]
Just some minor changes in doclets, the rest looks great, thanks!

File: samples/highcharts/cypress/custom-indicator-stock-tools-gui/demo.details [hunk 3]
```diff
@@ -0,0 +1,10 @@
+---
+name: Demo which is a base for cypress tests
+skipTest: true
+js_wrap: b
+tags:
+  - Highcharts Stock demo
+categories:
+  - General:
+      priority: 11
```
Comment (pawelfus) [inline samples/highcharts/cypress/custom-indicator-stock-tools-gui/demo.details:9]: No need for tags and categories in the test

**Review by pawelfus — CHANGES_REQUESTED** [review]

**Review by pawelfus — APPROVED** [review]
Thanks!
