### PR TITLE
bugfix/24476-dataTable-wrong-sorting 

### LINKED ISSUE #24476: Chart data table not sorting correctly on header click
#### Expected behaviour
Clicking chart data table headers should sort based on values.

#### Actual behaviour
Sorting does not work as expected.
From @raf18seb: seems like a thousandsSep is breaking it, see https://jsfiddle.net/BlackLabel/qk5ozhvn/

#### Live demo with steps to reproduce
Click Series 1 header to test
https://jsfiddle.net/LB0ge/9L0tnf6g/

#### Product version
Highcharts Core, v12.6.0

#### Affected browser(s)
All (tested on Chrome)

### PR DESCRIPTION
**Pull request by AndrzejBuleczka**
Fixed #24476, improved parsing logic in export table sorting so that it correctly handles language options.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1214059603686531

### CODE REVIEW

File: ts/Extensions/ExportData/ExportData.ts [hunk 1]
```diff
@@ -1614,21 +1614,38 @@ namespace ExportData {
...
+                }
+
+                let normalized = value;
+                if (thousandsSep) {
+                    normalized = normalized.split(thousandsSep).join('');
+                }
+                normalized = normalized.replace(decimalPoint, '.');
+
+                const number = Number(normalized);
+                return isNaN(number) ? null : number;
```
Comment (jedrzejruta) [inline ts/Extensions/ExportData/ExportData.ts]: Instead of doing isNan you could import the isNumber utility function, which has a stricter check for finite numbers too.

**Review by jedrzejruta — CHANGES_REQUESTED** [review]
Very nice! 👏 

How about adding an assertion to the already existing test for `sortable table`? https://github.com/highcharts/highcharts/blob/aae8e928fd0b9d7705d49860b31142ea13e35535/samples/unit-tests/export-data/basics/demo.js#L1345-L1511

**Review by wchmiel — APPROVED** [review]
Look good ;)

File: ts/Extensions/ExportData/ExportData.ts (hunk 1 above)
Comment (AndrzejBuleczka) [reply ts/Extensions/ExportData/ExportData.ts]: good point, done

**Review by jedrzejruta — APPROVED** [review]
Thanks! 🎉

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
All good, except we now have some merge conflict with the other export table PR.

**Review by TorsteinHonsi — APPROVED** [review]
