### PR TITLE
bugfix/20877-ordinal-panning

### LINKED ISSUE #20877: Scrolling chart on mobile devices
Hi. 

There is a problem with the chart working on mobile devices.

The touch does not work correctly.
On PC the mouse wheel zoom works fine.
But on mobile the chart just breaks.

#### Expected behaviour
Correct operation on mobile devices.
Smooth with free movement of bars and zooming

#### Actual behaviour
Сhart crashes when you try to swipe it.
Bars are squeezed together, fall outside the chart window or disappear altogether.

#### Live demo with steps to reproduce
[https://codepen.io/NeBox/pen/GRLpZwr](https://codepen.io/NeBox/pen/GRLpZwr)

#### Product version
Highstock 11.4.0

#### Affected browser(s)
Here are two links to the video

the first one demonstrates how highcharts works
https://drive.google.com/file/d/178-XURIzVi4ZeKZpqqGAQnTmnxc3mLs1/view?usp=sharing

the second one is made on another chart, where the chart works smoothly and beautifully
https://drive.google.com/file/d/1-WRg_z3CUNlVMGjca_61bKrGHanKJXce/view?usp=sharing

### PR DESCRIPTION
**Pull request by pawelfus**
Fixed #20877, panning using one finger on touch devices didn't work correctly with a dispersed dataset.
___
The "after-refactor" fix. On mobile devices, previously we scaled grouped visually and created a mock selection marker. Then on touchend event, we apply new extremes. In the current implementation, we update extremes "live", so OrdinalAxis needs to connect to both `pan` and `touchpan` events. 

Extra change to store `mouseDownX` on touchstart since it's the base for panning in OrdinalAxis to compare with how many units we moved away.

### CODE REVIEW

**Review by pawellysy — APPROVED** [review]

File: samples/unit-tests/axis/extremes/demo.js [hunk 1]
```diff
@@ -651,6 +670,47 @@ QUnit.test('Touch panning falls back to data range (#3104)', function (assert) {
         tickPositionsAfterSlide,
         'Tick positions has changed after touch sliding'
     );
+
+    // Reset user-extremes
+    chart.xAxis[0].setExtremes();
+
+    chart.update({
+        chart: {
+            zoomType: '',
```
Comment (kamil-musialowski) [inline samples/unit-tests/axis/extremes/demo.js:679]:
```suggestion
            zooming: {
               type: ''
            }
```

**Review by kamil-musialowski — CHANGES_REQUESTED** [review]
All good! I would just suggest changing the [deprecated `zoomType`](https://api.highcharts.com/highstock/chart.zoomType) to [`zooming.type`](https://api.highcharts.com/highstock/chart.zooming.type)

**Review by bm64 — APPROVED** [review]

**Review by DJTechnoo — APPROVED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
