### PR TITLE
bugfix/15383-indicator-recalc

### LINKED ISSUE #15383: Indicators recalculate its values wrongly, when you change the type of the main series
#### Expected behaviour
When updating main series, the indicator should recalculate correctly, when you change the type.

#### Actual behaviour
The indicator doesn't take into consideration the new type of the main series. It recalculates assuming that the main series is still the pevious type.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/m1sf506h/

#### Product version
v9.0.1

#### Affected browser(s)
all

### PR DESCRIPTION
**Pull request by khlieng**
Fixed #15383, indicators did not recalculate when updating series type.

### CODE REVIEW

**Review by pawelfus — APPROVED** [review]
Looks good, thanks! 👍

File: ts/Core/Series/Series.ts [hunk 1]
```diff
@@ -6763,6 +6767,9 @@ class Series {
 
         series.init(chart, options);
 
+        if (casting) {
+            series.isDirtyData = true;
+        }
```
Comment (TorsteinHonsi) [inline ts/Core/Series/Series.ts:6772]: Since this bug fix only applies to indicators that need to recalculate the data, I'm concerned that `isDirtyData` is not necessary for other series. I think this is more precise:
```ts
if (casting && series.hasDerivedData) {
    series.isDirtyData = true;
}
```

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]

File: ts/Core/Series/Series.ts (hunk 1 above)
Comment (khlieng) [reply ts/Core/Series/Series.ts:6772]: This wont work since its the indicator that has `hasDerivedData` set, but its not the indicator that changes type and the indicator relies on the series its bound to firing `updatedData`.

Comment (khlieng) [reply ts/Core/Series/Series.ts:6772]: Maybe checking `linkedSeries` could work?

Comment (pawelfus) [reply ts/Core/Series/Series.ts]: Hm.. there's also antoher solution. Instead of marking series after an update with `isDirtyData` flag, technical indicators could listen to `series.update()` events and check if `type` and `data` changed in any way.

But still, it is strange that `isDirtyData` flag was not set when updating the series with `{ type, data }` object. Most of the technical indicators recalculate only on `updatedData` event (Volume By Price is recalculated on `afterSetExtremes`) .  Perhaps the best solution is to check: `casting && dataChange`?

Comment (khlieng) [reply ts/Core/Series/Series.ts]: `isDirtyData` was only set when the series already had points previously and casting clears the points. Checking `casting && dataChange` sounds like it would break the `setData + update({ type })` case.

**Review by TorsteinHonsi — APPROVED** [review]

File: ts/Core/Series/Series.ts [hunk 2]
```diff
@@ -6811,6 +6814,10 @@ class Series {
         series.initialType = initialType;
         chart.linkSeries(); // Links are lost in series.remove (#3028)
 
+        if (casting && series.linkedSeries.length) {
```
Comment (TorsteinHonsi) [inline ts/Core/Series/Series.ts:6817]: Nice! Now we just need a small comment and a reference to the issue.

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
