### PR TITLE
Bugfix/dragging control point annotation

### LINKED ISSUE #20807: Annotations drag and resize
#### Actual behaviour
Annotations don't get proportionally resized when dragging the control point.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/9eLuod1y/
1. Draw an annotation (I'd recommend line or measure), try to resize or drag it.
For this specific case, test with a chart width of 500.

#### Product version
Stock 11.4 (worked fine in 11.2, broken since 11.3)

Bisected to 39d395d28d6b5e5c5e056756ff70a3f1f7203666

### PR DESCRIPTION
**Pull request by pawellysy**
Fixed #20807, annotations didn't get proportionally resized when dragging a control point. Ordinal axis' `getExtendedPositions` didn't take `dataGrouping` options into account.

### CODE REVIEW

**Review by bm64 — APPROVED** [review]

File: samples/unit-tests/stock-tools/stock-annotation-dragging/demo.js [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+            animation: { defer: 0 }
+        }
+    );
+
+
+    const originalPlotX = annotation.points[0].plotX;
+    const testController = new TestController(chart);
+    const diff = 25;
+    const start = chart.plotLeft + originalPlotX;
+    testController.pan([start, 200], [diff + start, 200], void 0, true);
```
Comment (kamil-musialowski) [inline samples/unit-tests/stock-tools/stock-annotation-dragging/demo.js:65]: Unnecessary debugging marker :D

**Review by kamil-musialowski — APPROVED** [review]
Cool! One tiny tiny thing commented.

**Review by pawelfus — APPROVED** [review]
Nice catch!

File: samples/unit-tests/stock-tools/stock-annotation-dragging/demo.js [hunk 2]
```diff
@@ -0,0 +1,72 @@
+QUnit.test('Dragging annotation', function (assert) {
+    const data = [];
+    for (let i = 0; i < 300; i++) {
+        if (i > 100 && i < 200) {
+            continue;
+        }
```
Comment (DJTechnoo) [inline samples/unit-tests/stock-tools/stock-annotation-dragging/demo.js:6]: Would it perhaps make sense to invert the if statement in order to avoid continue?

**Review by DJTechnoo — APPROVED** [review]
Looks good! I have one comment, but I approve

File: samples/unit-tests/stock-tools/stock-annotation-dragging/demo.js (hunk 2 above)
Comment (pawellysy) [reply samples/unit-tests/stock-tools/stock-annotation-dragging/demo.js:6]: Doesn't matter that much, apart from that I usually prefer early return, which this continue kinda is.

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
