### PR TITLE
bugfix/21106-boost-resize-clipping

### LINKED ISSUE #21106: Setting chart size does not work when switching from boost to standard mode
#### Expected behaviour
`setSize` keeps working when switching from boost mode to standard mode.

#### Actual behaviour
When we switch from boost mode to standard mode, `setSize` does not work anymore. A part of the plotted series is invisible.

image

#### Live demo with steps to reproduce
https://jsfiddle.net/w0gL1poh/51/

1. Start in standard mode, play around with the size (increase, decrease, reset), everything works as expected
2. Toggle on boost mode, play around with the size (increase, decrease, reset), everything works as expected
3. Toggle off boost mode, decrease size works as expected, increase size does not work, only part of the series is shown

It seems as if the (initial) size (at the time you disable boost mode) is the max size and you cannot increase width or height beyond this size.

#### Product version
Highcharts v11.4.1

#### Affected browser(s)
Version 124.0.6367.119 (Official Build) (arm64)

### PR DESCRIPTION
**Pull request by Xillez**
Fixed #21106, Series clipped on boost disable and increase chart size

---

Asana task: https://app.asana.com/0/1204848917817812/1207230417580846/f

### CODE REVIEW

**Review by bre1470 — APPROVED** [review]
Nice! Works for me. 👍

File: ts/Extensions/Boost/BoostSeries.ts [hunk 1]
```diff
@@ -726,6 +726,12 @@ function exitBoost(
             boost.clear();
         }
     }
+
+    // #21106, clean up boost clipping on the series groups.
+    const target = (chart.seriesGroup || series.group);
+    if (target) {
+        target.clip();
+    }
```
Comment (TorsteinHonsi) [inline ts/Extensions/Boost/BoostSeries.ts:734]: A little terser:
```suggestion
    (chart.seriesGroup || series.group)?.clip();
```

**Review by hubertkozik — APPROVED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
