### PR TITLE
bugfix/20816-templating-date-format

### LINKED ISSUE #20816: `pointFormat` wrong timezone displayed when used with `#if` or `#unless`
#### Expected behaviour

The tooltip date should be displayed according to given timezone.

#### Actual behaviour
The tooltip date is displayed according to system timezone, disregarding given timezone.

#### Live demo with steps to reproduce
[https://jsfiddle.net/BlackLabel/Lzayofu7/](https://jsfiddle.net/BlackLabel/Lzayofu7/)
Remove the `#if` statement, and the date will be displayed correctly.

#### Product version
Regression introduced in Highcharts v11.1.0

### PR DESCRIPTION
**Pull request by hubertkozik**
Fixed #20816, timezone wasn't respected in Templating in format strings.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1206810963494468

### CODE REVIEW

**Review by KacperMadej — APPROVED** [review]

File: ts/Core/Templating.ts [hunk 1]
```diff
@@ -289,7 +289,7 @@ function format(str = '', ctx: any, chart?: Chart): string {
     }
 
     // Execute
-    matches.forEach((match): void => {
+    matches.forEach(function (match): void {
```
Comment (TorsteinHonsi) [inline ts/Core/Templating.ts:292]: Was this change necessary or just a remaining debugging step? I can't see that we use the function scope in the solution?

**Review by TorsteinHonsi — COMMENTED** [review]
Thanks!

File: ts/Core/Templating.ts (hunk 1 above)
Comment (hubertkozik) [reply ts/Core/Templating.ts]: It's a remain from debugging step, but I left it with `function` word, because I had an issue with wrong `chart` instance, now it works correctly with the arrow function  🤷‍♂️  I reverted it.
