### PR TITLE
bugfix/22516-boost-state-inactive

### LINKED ISSUE #22516: Adding a series with boost enabled breaks markers setting
#### Expected behaviour
With boost module enabled, markers should behave the same if another series (with the same settings) is added as before.

#### Actual behaviour
With boost module enabled, if another series is added, markers setting for hover is not preserved

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/7zxw5smn/
First note how the point markers appear on hover. Add new series with a button below the chart. Note that hover effect is broken for both series now.

#### Product version
Highcharts Core

#### Affected browser(s)
all

### PR DESCRIPTION
**Pull request by KacperMadej**
Fixed #22516, prevented inactive state for series with shared `markerGroup` when hovering a boosted series.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1209142462125420

### CODE REVIEW

**Review by MarkusBarstad — APPROVED** [review]
Works well!

File: ts/Core/Pointer.ts [hunk 1]
```diff
@@ -212,15 +211,24 @@ class Pointer {
             if (series.navigatorSeries) {
                 activeSeries.push(series.navigatorSeries);
             }
+
+            // Include boosed series when they share markerGroup
+            if (series.boosted && series.markerGroup) {
+                activeSeries = activeSeries.concat(
+                    this.chart.series.filter(function (otherSeries): boolean {
+                        return otherSeries.markerGroup === series.markerGroup;
+                    })
```
Comment (TorsteinHonsi) [inline ts/Core/Pointer.ts:220]: Arrow function is terser. Maybe also use `push.apply` instead of concat?
```suggestion
                    this.chart.series.filter((otherSeries): boolean =>
                        otherSeries.markerGroup === series.markerGroup
                    )
```

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks!

**Review by TorsteinHonsi — APPROVED** [review]
