### PR TITLE
bugfix/15359-BubbleLegend-wrong-color-styled-mode

### LINKED ISSUE #15359: BubbleLegend picks wrong color in styled mode
#### Expected behaviour
When setting `colorIndex` to the series, the bubble legend should use it by default.

#### Actual behaviour
It uses the series index instead of `series.colorIndex`.

https://github.com/highcharts/highcharts/blob/d93b70dae1ed19ba762522c9fbbd8135f8819985/ts/Series/Bubble/BubbleLegend.ts#L825

#### Live demo with steps to reproduce
https://jsfiddle.net/highcharts/weLd6hru/

#### Product version
v9.0.1

#### Affected browser(s)
All

### PR DESCRIPTION
**Pull request by DJTechnoo**
Fixed #15359, wrong `BubbleLegend` color in `styledMode`.

### CODE REVIEW

File: samples/unit-tests/bubble-legend/styles/demo.js [hunk 1]
```diff
@@ -65,3 +65,38 @@ QUnit.test('Bubble legend ranges', function (assert) {
         'Bubble legend was properly disabled with the legend'
     );
 });
+
+QUnit.test('Bubble legend styled mode', function (assert) {
+    var chart = Highcharts.chart('container', {
```
Comment (TorsteinHonsi) [inline samples/unit-tests/bubble-legend/styles/demo.js:70]: Long-running pre-commit tests are becoming a problem for us. Instead of creating a new chart for this test, see if you can modify one of the existing bubble-legend tests and add the assertion there.

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
