### PR TITLE
Fixed #6943, could not update axis events

### LINKED ISSUE #6943: Can't update axis events?
#### Expected behavior

Calling xAxis[0].update({ events: { ... } }); should update the event handlers such as afterSetExtremes.

#### Actual behavior

Event handlers don't change. In the demo, the original afterSetExtremes persists after we set `events` via `Axis.update`.

#### Live demo with steps to reproduce

http://jsfiddle.net/by3hryj1/

### PR DESCRIPTION
**Pull request by TorsteinHonsi**
Fixed #6943, could not update axis events that were set by options.

### CODE REVIEW

File: ts/Core/Foundation.ts [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+ * instance. #6943, #10861.
+ */
+const registerEventOptions = (
+    component: Axis|Series
+): void => {
+
+    // A lookup over those events that are added by _options_ (not
+    // programmatically). These are updated through .update()
+    component.eventOptions = component.eventOptions || {};
+
```
Comment (bre1470) [inline ts/Core/Foundation.ts:49]: I was expecting a class structure.
```ts
class Foundation {
  eventOptions: Record<string, Function>;
  protected registerEventOptions(eventOptions: Record<string, Function>): void {…};
}
export default Foundation;
```
```ts
class Axis extends Foundation {
…
    this.registerEventOptions(this.options.events);
…
}
```
```ts
class Series extends Foundation {
…
    this.registerEventOptions(this.options.events);
…
}
```

Comment (TorsteinHonsi) [reply ts/Core/Foundation.ts:49]: Yes, eventually, when we see more patterns... Isn't this okay for a start, since we only have one function to share between the two classes?

Comment (bre1470) [reply ts/Core/Foundation.ts:49]: It is for me. I just fear, that someone else will come along and add to the temporary pattern, and eventually it will become difficult to refactor it as a class.

Comment (bre1470) [reply ts/Core/Foundation.ts:49]: I suggest to wrap it in a static class function.
```ts
class Foundation {
  public static registerEventOptions = (
    component: Axis|Series
  ): void => {…}
}
export default Foundation;
```

**Review by bre1470 — APPROVED** [review]
