### PR TITLE
Fixed #13494, bubble animation failed when redrawing

### LINKED ISSUE #13494: bubble series not visible after second call to addSeries
#### Expected behaviour
`addSeries` is called twice and two series are visible.
image

#### Actual behaviour
Only the second series is visible
image

#### Live demo with steps to reproduce

https://jsfiddle.net/alvarezg/3xdkucny/
(resizing viewport or toggling series visibility in legend seems to fix the issue but initial render is wrong)
#### Product version

Highcharts, Highstock 8.0.3 and newer (works with 8.0.2)

### PR DESCRIPTION
**Pull request by TorsteinHonsi**
Fixed #13494, a regression causing bubble animation to fail when redrawing, like when running `addSeries` in quick succession.

### CODE REVIEW

File: samples/unit-tests/series-bubble/marker/demo.js [hunk 1]
```diff
@@ -108,4 +108,75 @@ QUnit.test('Bubble data points without z-param.(#8608)', function (assert) {
...
+                'First series points should continue animating'
+            );
+            assert.strictEqual(
+                chart.series[1].points[0].graphic.attr('width'),
+                1,
+                'Second series points should be in animation start position'
+            );
+        }, 50);
+
+        setTimeout(() => {
```
Comment (pawelfus) [inline samples/unit-tests/series-bubble/marker/demo.js:167]: Since it's async test, shouldn't we use `done = asert.async()`? See: https://api.qunitjs.com/assert/async

Comment (TorsteinHonsi) [reply samples/unit-tests/series-bubble/marker/demo.js:167]: Actually that's not required when we use lolex, since `setTimeout()` is overridden and made sync.
