### PR TITLE
Fixed pie data label cut off at bottom

### LINKED ISSUE #22100: Pie chart label cut off when container has a particular height and multi-line data-labels are used
#### Expected behaviour
The data label is either be fully visible, or completely hidden.

#### Actual behaviour
There is an intermediate state when the data-label is partially visible and partially hidden (i.e. the label is cut off). 

In the screenshot below I show this intermediate state: the CHC label also has a number and percentage below it, but these are not visible / are cut off.
Screenshot 2024-11-04 at 10 58 21

#### Live demo with steps to reproduce
1. Go to my [JSFiddle](https://jsfiddle.net/yepfdb30/8/)
2. Increase/decrease the height of the container until the bottom data label becomes partially visible (this is around 170-180px)

#### Product version
Highcharts Core 11.4.8

#### Affected browser(s)
All

#### Additional notes
- I discussed this problem with a Highcharts support engineer (Michal) and he agreed that this was a bug although probably not very high urgency, because it only occurs under very specific circumstances
- I found a previous issue https://github.com/highcharts/highcharts/issues/17286 that seemed identical at fist glance, but I actually think in the end that case the problem was caused by a configuration error (rigidly setting the chart size to 100%).

### PR DESCRIPTION
**Pull request by TorsteinHonsi**
Fixed #22100, pie data label was cut off in some cases when rendered at the bottom of the pie. Altered positioning logic by letting labels gravitate towards the sides when there is space available, which also leaves room for the pie to render larger in limited space.

Test case https://jsfiddle.net/highcharts/nt0qa289/ .

### CODE REVIEW

File: ts/Series/Pie/PieDataLabel.ts [hunk 1]
```diff
@@ -388,6 +413,31 @@ namespace ColumnDataLabel {
...
+                            box.size
+                        )
+                            .attr({
+                                stroke: 'silver',
+                                'stroke-width': 1
+                            })
+                            .add();
+                    }
+                });
+                // */
```
Comment (hubertkozik) [inline ts/Series/Pie/PieDataLabel.ts:440]: After uncommenting this block the boxes look a little bit strange to me, but the data labels are placed correctly.
image

**Review by hubertkozik — APPROVED** [review]

File: ts/Series/Pie/PieDataLabel.ts (hunk 1 above)
Comment (TorsteinHonsi) [reply ts/Series/Pie/PieDataLabel.ts:440]: Yes I know... In some cases the boxes are spot on, in other cases like this they are shifted. I haven't found out why that is, but I know something is fishy with the box distribution. Otherwise the CHC label wouldn't fall outside the chart in the first place.
