### PR TITLE
bugfix/13437-navigator-empty-series-error 

### LINKED ISSUE #13437: Highstock- errors in console when adding new series to chart with no data
#### Expected behaviour
Add series without errors

#### Actual behaviour
Errors in console
`Error: <rect> attribute width: Expected length, "NaN".`

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/qa1vyhz9/

#### Product version
Highstock 8.0.4

#### Affected browser(s)
All

### PR DESCRIPTION
**Pull request by Izothep**
Fixed #13437, navigator with empty data caused errors in console.

### CODE REVIEW

File: ts/Core/Navigator.ts [hunk 1]
```diff
@@ -1744,7 +1744,13 @@ class Navigator {
         }
 
         // Update position of navigator shades, outline and handles (#12573)
-        if (navigator.navigatorEnabled) {
+        if (
+            navigator.navigatorEnabled &&
+            navigator.zoomedMin &&
+            navigator.zoomedMax
```
Comment (pawelfus) [inline ts/Core/Navigator.ts:1750]: When dealing with numbers always use `isNumber()` to avoid misinterpreting `zoomedMin` and `zoomedMax` value 0.

Comment (Izothep) [reply ts/Core/Navigator.ts:1750]: oh right, my mistake. Thanks
